/**
 * Generator bank soal gap UKOM Perencana Ahli Muda (100 soal).
 * Jalankan dari folder Latihan UKOM: node scripts/build-gap100.mjs
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_PATH = path.join(__dirname, "parts", "gap100.js");

const LEVELS = ["singkat", "sedang", "panjang", "kasus"];

function q(id, cluster, topic, stem, correct, distractors, explain) {
  const number = Number(id.slice(-2));
  const answer = (number - 1) % 5;
  // Keep every generated item at exactly five options: one key and four distractors.
  const options = distractors.slice(0, 4);
  options.splice(answer, 0, correct);
  return {
    id,
    cluster,
    level: LEVELS[(number - 1) % LEVELS.length],
    source: "gap",
    topic,
    stem,
    options,
    answer,
    explain,
    version: 1
  };
}

const QUESTIONS = [
  // === TEKNIS (26): JFP/kompetensi/Bloom 5, evaluasi 6, ego sektoral/daerah 4, POIC 5, IOOI 3, 5M 2, SMART 1 ===
  q("G-T01", "teknis", "JFP Permen PAN 4/2020", "Seorang analis baru ditempatkan pada unit perencanaan dan diminta menjelaskan kedudukan Jabatan Fungsional Perencana menurut Permen PANRB Nomor 4 Tahun 2020. Penjelasan mana yang paling tepat untuk membedakan tugas perencana dari staf administrasi program?", "Perencana melakukan penyiapan, pengkajian, perumusan, pengendalian, dan evaluasi rencana pembangunan berbasis analisis kebijakan.", ["Perencana terutama bertugas mengarsipkan surat masuk dan membuat notulen rapat pimpinan.", "Perencana hanya menghitung realisasi keuangan program tanpa menilai logika intervensi.", "Perencana berwenang mengganti keputusan kepala daerah tanpa proses perencanaan.", "Perencana bekerja hanya setelah dokumen APBD disahkan."], "Permen PANRB 4/2020 menempatkan perencana sebagai jabatan fungsional yang menjalankan kegiatan perencanaan pembangunan, bukan sekadar administrasi."),
  q("G-T02", "teknis", "Empat kompetensi teknis", "Dalam seleksi Perencana Ahli Muda, peserta diminta menunjukkan empat kompetensi teknis utama. Kombinasi mana yang paling menggambarkan kompetensi teknis perencana pada level ahli muda?", "Mengidentifikasi masalah, menganalisis data, menyusun alternatif kebijakan, serta memantau dan mengevaluasi pelaksanaan rencana.", ["Membuat desain grafis, mengelola perjalanan dinas, menyusun absensi, dan menjaga aset kantor.", "Melakukan audit investigatif, menetapkan sanksi pidana, menagih pajak, dan menyita aset.", "Menerbitkan izin usaha, mengesahkan sertifikat tanah, menguji mutu barang, dan membuat kontrak konstruksi.", "Mengelola protokol pimpinan, dokumentasi foto, persuratan, dan konsumsi rapat."], "Kompetensi teknis perencana berkaitan dengan analisis perencanaan dari masalah sampai evaluasi, sesuai peran JFP dalam siklus pembangunan."),
  q("G-T03", "teknis", "Bloom C2", "Pada sesi ujian, soal meminta peserta membedakan output, outcome, dan impact dalam program penurunan stunting. Level kognitif Bloom yang paling dominan untuk tugas tersebut adalah?", "C2, karena peserta harus memahami konsep dan menjelaskan perbedaan antaristilah.", ["C1, karena peserta hanya menyalin definisi tanpa pemahaman.", "C4, karena peserta wajib memecah model kausal yang kompleks.", "C5, karena peserta diminta menilai kebijakan dengan kriteria normatif.", "C6, karena peserta harus menciptakan program baru dari awal."], "Membedakan dan menjelaskan makna konsep termasuk pemahaman atau C2 dalam taksonomi Bloom."),
  q("G-T04", "teknis", "Bloom C3", "Tim Bappeda menerima data kemiskinan, akses sanitasi, dan angka putus sekolah. Peserta ujian diminta memilih indikator prioritas untuk rancangan program kecamatan berdasarkan kriteria yang sudah diberikan. Level Bloom yang paling tepat adalah?", "C3, karena peserta menerapkan konsep dan kriteria pada data kasus.", ["C1, karena tugas terbatas pada mengingat daftar indikator tanpa memakai data kasus.", "C2, karena tugas terbatas menjelaskan istilah tanpa menerapkan kriteria pada data.", "C5, karena tugas menilai normatif tanpa menerapkan kriteria pada data program.", "C6, karena tugas menuntut penelitian konseptual baru tanpa data kasus."], "C3 menekankan penerapan pengetahuan pada situasi konkret; peserta menggunakan kriteria untuk memilih indikator."),
  q("G-T05", "teknis", "JFP dan kompetensi", "Seorang Perencana Ahli Muda diminta menyusun policy brief untuk isu kemacetan. Agar sesuai peran JFP dan level C3, keluaran terbaik adalah?", "Policy brief yang menerapkan analisis data lalu lintas, akar masalah, opsi intervensi, risiko, dan rekomendasi yang dapat dilaksanakan.", ["Daftar hadir rapat lintas OPD tanpa analisis masalah.", "Salinan berita media sosial tentang keluhan warga.", "Keputusan final rute angkutan tanpa mandat dan tanpa data.", "Poster kampanye tertib lalu lintas tanpa indikator keberhasilan."], "Perencana ahli muda menerapkan analisis untuk menghasilkan rekomendasi kebijakan; ini sesuai kompetensi teknis dan level aplikasi C3."),
  q("G-T06", "teknis", "Evaluasi ex ante", "Sebelum program revitalisasi pasar dimasukkan ke RKPD, tim diminta menilai kelayakan, kebutuhan, risiko sosial, dan konsistensi dengan prioritas daerah. Jenis evaluasi yang digunakan adalah?", "Evaluasi ex ante.", ["Evaluasi ex post.", "Evaluasi terminal setelah aset diserahterimakan.", "Audit kepatuhan tahunan.", "Evaluasi dampak lima tahun setelah program selesai."], "Ex ante dilakukan sebelum intervensi dijalankan untuk menilai relevansi, kelayakan, risiko, dan desain program."),
  q("G-T07", "teknis", "Evaluasi ongoing", "Pada triwulan kedua, pembangunan SPAM baru mencapai 38% sementara target fisik 55%. Perencana diminta memberi rekomendasi korektif tanpa menunggu akhir tahun. Evaluasi yang tepat adalah?", "Evaluasi ongoing atau monitoring evaluatif selama pelaksanaan.", ["Evaluasi ex ante karena program belum selesai sepenuhnya.", "Evaluasi ex post karena masih ada sisa pekerjaan.", "Evaluasi meta karena membandingkan seluruh studi evaluasi.", "Evaluasi normatif yang tidak membutuhkan data realisasi."], "Ongoing evaluation dilakukan saat program berjalan untuk mengidentifikasi deviasi dan memperbaiki pelaksanaan."),
  q("G-T08", "teknis", "Evaluasi ex post", "Dua tahun setelah program pelatihan wirausaha selesai, pemerintah daerah ingin mengetahui apakah pendapatan peserta naik dan usaha bertahan. Pendekatan evaluasi yang paling tepat adalah?", "Evaluasi ex post dengan fokus outcome dan dampak setelah intervensi selesai.", ["Evaluasi ex ante dengan fokus desain awal.", "Monitoring harian kehadiran peserta.", "Reviu administrasi tanda terima honor.", "Penyusunan baseline tanpa membandingkan hasil."], "Ex post menilai hasil dan dampak setelah program selesai sehingga cocok untuk melihat perubahan pendapatan dan keberlanjutan usaha."),
  q("G-T09", "teknis", "Evaluasi desain", "Dalam evaluasi awal program irigasi, tim menemukan indikator hanya mengukur panjang saluran, padahal tujuan program adalah peningkatan produktivitas padi. Rekomendasi terbaik adalah?", "Menyelaraskan indikator output dengan outcome produktivitas agar logika program dapat diuji.", ["Menghapus indikator outcome karena sulit diukur.", "Mengubah tujuan program menjadi panjang saluran saja.", "Menunda evaluasi sampai semua saluran rusak.", "Memakai indikator serapan anggaran sebagai satu-satunya ukuran keberhasilan."], "Evaluasi desain memeriksa konsistensi input-output-outcome; indikator harus mengikuti tujuan substantif program."),
  q("G-T10", "teknis", "Evaluasi proses", "Program penanganan kawasan kumuh memiliki anggaran cukup, tetapi realisasi rendah karena tender terlambat dan koordinasi kelurahan lemah. Fokus evaluasi yang paling relevan adalah?", "Evaluasi proses untuk menilai hambatan pelaksanaan, tata kelola, dan koordinasi.", ["Evaluasi dampak jangka panjang saja.", "Evaluasi kepuasan pimpinan tanpa data proses.", "Evaluasi akademik yang hanya menguji teori urbanisasi.", "Evaluasi harga pasar tanah di sekitar lokasi."], "Masalah utama berada pada pelaksanaan; evaluasi proses menilai apakah kegiatan berjalan sesuai rencana dan apa hambatannya."),
  q("G-T11", "teknis", "Evaluasi hasil", "Setelah program beasiswa daerah berjalan tiga tahun, angka putus sekolah turun tetapi belum jelas apakah penurunan terjadi pada kelompok miskin yang menjadi sasaran. Analisis evaluasi yang paling tepat adalah?", "Membandingkan capaian outcome menurut kelompok sasaran, baseline, dan target untuk menilai efektivitas program.", ["Melaporkan total dana terserap sebagai bukti cukup.", "Menghitung jumlah rapat koordinasi sebagai dampak utama.", "Mengabaikan data kelompok miskin karena semua siswa sama.", "Mengganti sasaran setelah hasil terlihat agar capaian tampak tinggi."], "Evaluasi hasil harus menguji perubahan outcome pada sasaran yang direncanakan, bukan hanya aktivitas atau serapan."),
  q("G-T12", "teknis", "Ego sektoral", "Dinas kesehatan, pendidikan, dan sosial menjalankan program stunting dengan sasaran desa berbeda dan indikator sendiri-sendiri. Akibatnya keluarga prioritas tidak menerima paket layanan lengkap. Masalah tata kelola yang paling tepat disebut?", "Ego sektoral, karena perangkat daerah bekerja dalam silo dan tidak mengintegrasikan sasaran lintas urusan.", ["Ego daerah, karena konflik utama terjadi antara provinsi dan kabupaten.", "Moral hazard penerima manfaat, karena warga sengaja menolak bantuan.", "Inflasi biaya, karena harga barang naik mendadak.", "Kegagalan pasar informasi keuangan."], "Ego sektoral muncul ketika organisasi mempertahankan agenda sektornya sehingga koordinasi program lintas urusan lemah."),
  q("G-T13", "teknis", "Ego daerah", "Dalam proyek transportasi aglomerasi, satu kabupaten menolak menyesuaikan trayek dengan kota tetangga karena khawatir retribusi terminalnya turun. Padahal perjalanan warga melintasi batas administratif. Ini terutama mencerminkan?", "Ego daerah, karena kepentingan fiskal lokal menghambat solusi lintas wilayah.", ["Ego sektoral murni, karena hanya konflik antara dinas dalam daerah yang sama.", "Kegagalan indikator SMART, karena tidak ada satuan waktu.", "Masalah 5M pada metode kerja laboratorium.", "Kelebihan barang publik lokal."], "Ego daerah terjadi saat kepentingan wilayah administratif mengalahkan kebutuhan layanan yang bersifat lintas batas."),
  q("G-T14", "teknis", "Mengatasi ego sektoral", "Gubernur meminta solusi agar program penurunan kemiskinan tidak terpecah antara bantuan sosial, pelatihan, dan akses permodalan. Langkah perencanaan yang paling tepat adalah?", "Membangun sasaran bersama, matriks peran OPD, indikator lintas urusan, dan forum pengendalian berkala.", ["Meminta setiap OPD membuat program baru tanpa berbagi data.", "Menaikkan pagu semua dinas agar tidak ada yang merasa dirugikan.", "Menyerahkan seluruh program kepada satu vendor swasta.", "Menghapus indikator outcome karena sulit dikoordinasikan."], "Koordinasi lintas sektor membutuhkan tujuan bersama, pembagian peran, data terpadu, dan mekanisme pengendalian."),
  q("G-T15", "teknis", "Mengatasi ego daerah", "Kawasan banjir berada di hulu kabupaten A dan hilir kota B. Jika masing-masing daerah hanya membangun drainase lokal, banjir tetap terjadi. Instrumen yang paling tepat untuk mengurangi ego daerah adalah?", "Kerja sama antardaerah berbasis rencana kawasan, pembagian manfaat-biaya, dan indikator bersama.", ["Kompetisi antardaerah untuk menunjukkan siapa yang paling cepat membangun.", "Larangan berbagi data hidrologi karena merupakan aset daerah.", "Pemindahan semua warga hilir tanpa kajian.", "Penundaan program sampai batas administrasi berubah."], "Masalah lintas wilayah perlu kerja sama antardaerah agar biaya, manfaat, dan target dikelola bersama."),
  q("G-T16", "teknis", "POIC Planning", "Dalam siklus POIC, kepala bidang meminta tim menetapkan tujuan, strategi, target, dan kebutuhan sumber daya sebelum program dimulai. Komponen POIC yang sedang dilakukan adalah?", "Planning.", ["Organizing.", "Actuating.", "Controlling.", "Auditing."], "Planning mencakup penentuan tujuan, strategi, target, jadwal, dan sumber daya sebelum pelaksanaan."),
  q("G-T17", "teknis", "POIC Organizing", "Setelah rencana disetujui, Bappeda membagi peran antara bidang infrastruktur, ekonomi, dan sosial, menetapkan alur koordinasi, serta menunjuk penanggung jawab data. Ini adalah komponen POIC berupa?", "Organizing.", ["Planning.", "Actuating.", "Controlling.", "Forecasting.", "Budget cutting."], "Organizing mengatur struktur, pembagian tugas, mekanisme koordinasi, dan tanggung jawab pelaksana."),
  q("G-T18", "teknis", "POIC Actuating", "Dokumen rencana sudah selesai dan tim mulai menjalankan musrenbang tematik, verifikasi usulan, dan asistensi perangkat daerah sesuai jadwal. Dalam POIC, kegiatan ini termasuk?", "Actuating.", ["Planning.", "Organizing.", "Controlling.", "Evaluating ex post.", "Legislating."], "Actuating adalah pelaksanaan kegiatan sesuai rencana dan pembagian peran yang telah ditetapkan."),
  q("G-T19", "teknis", "POIC Controlling", "Pada bulan keenam, pimpinan membandingkan capaian output dengan target, menemukan deviasi, lalu meminta tindakan korektif. Komponen POIC yang paling tepat adalah?", "Controlling.", ["Planning.", "Organizing.", "Actuating.", "Brainstorming.", "Procurement."], "Controlling mengukur kemajuan, membandingkan dengan target, dan mengarahkan koreksi ketika ada deviasi."),
  q("G-T20", "teknis", "POIC terpadu", "Rencana pengembangan kawasan wisata gagal karena tim hanya membuat dokumen, tetapi tidak membagi peran, tidak melaksanakan agenda, dan tidak mengendalikan deviasi. Pelajaran POIC yang paling tepat adalah?", "Keempat fungsi planning, organizing, actuating, dan controlling harus berjalan sebagai satu siklus manajemen.", ["Planning saja cukup jika dokumen rencana sangat rinci.", "Controlling hanya dilakukan oleh auditor eksternal setelah semua selesai.", "Organizing tidak perlu jika anggaran sudah tersedia.", "Actuating dapat dimulai tanpa tujuan dan indikator."], "POIC adalah rangkaian fungsi manajemen yang saling terkait, bukan daftar kegiatan yang dapat dipilih sebagian saja."),
  q("G-T21", "teknis", "Input-output-outcome-impact", "Program sanitasi membangun 500 sambungan rumah, lalu diare balita menurun dan kualitas hidup warga membaik. Urutan konsep yang benar adalah?", "Input membiayai kegiatan, output berupa sambungan rumah, outcome berupa perubahan perilaku/kesehatan, impact berupa kualitas hidup jangka panjang.", ["Output adalah dana, input adalah penurunan diare, outcome adalah rapat, impact adalah SPJ.", "Input dan impact sama-sama jumlah sambungan rumah.", "Outcome hanya berarti jumlah kegiatan sosialisasi.", "Impact selalu dapat diukur pada hari pekerjaan selesai."], "Kerangka input-output-outcome-impact membedakan sumber daya, produk langsung, perubahan antara, dan dampak jangka panjang."),
  q("G-T22", "teknis", "Outcome vs output", "Dinas melaporkan keberhasilan program literasi hanya dari 40 pelatihan guru. Perencana meminta indikator tambahan berupa kenaikan kemampuan membaca siswa kelas awal. Mengapa permintaan ini tepat?", "Jumlah pelatihan adalah output, sedangkan kemampuan membaca siswa menunjukkan outcome yang lebih dekat dengan tujuan program.", ["Pelatihan guru selalu impact jangka panjang.", "Kemampuan membaca siswa hanyalah input program.", "Outcome tidak boleh digunakan dalam dokumen perencanaan.", "Output dan outcome selalu identik jika kegiatan selesai.", "Indikator hasil harus selalu berupa serapan anggaran."], "Output adalah produk langsung kegiatan; outcome adalah perubahan yang dialami penerima manfaat atau sistem layanan."),
  q("G-T23", "teknis", "Impact", "Lima tahun setelah pembangunan jalan produksi, biaya logistik petani turun dan pusat pertumbuhan baru muncul. Ukuran ini lebih tepat disebut impact karena?", "Menggambarkan perubahan jangka panjang yang lebih luas daripada output fisik jalan.", ["Menggambarkan jumlah kontrak pekerjaan.", "Mengukur kehadiran pekerja lapangan.", "Menghitung volume aspal yang dipasang.", "Menunjukkan jumlah rapat koordinasi.", "Mencatat nilai uang muka kontraktor."], "Impact menilai efek jangka panjang dan lebih luas yang timbul dari outcome program."),
  q("G-T24", "teknis", "5M input", "Saat menilai kesiapan program digitalisasi layanan desa, perencana memeriksa ketersediaan SDM operator, anggaran, perangkat komputer, prosedur kerja, dan data awal. Ini mencerminkan kerangka input?", "5M: man, money, material/machine, method, dan market/information sesuai kebutuhan program.", ["SMART: specific, measurable, achievable, relevant, time-bound.", "POIC: planning, organizing, actuating, controlling.", "SWOT: strength, weakness, opportunity, threat.", "PESTEL: politik, ekonomi, sosial, teknologi, lingkungan, hukum."], "5M membantu memeriksa kesiapan input seperti manusia, dana, sarana, metode, dan informasi/pasar."),
  q("G-T25", "teknis", "5M gap", "Program layanan mobil perpustakaan sering batal karena kendaraan rusak, sopir terbatas, dan SOP peminjaman belum jelas. Analisis gap input 5M yang paling tepat adalah?", "Kelemahan terjadi pada machine/material, man, dan method sehingga perbaikan input harus diarahkan ke tiga aspek itu.", ["Masalah hanya pada impact karena minat baca belum naik.", "Masalah hanya pada market karena buku belum populer.", "Tidak ada gap input selama anggaran sudah terserap.", "Masalah berada pada SMART karena target punya batas waktu.", "Masalah hanya pada ego daerah."], "Kerangka 5M mengurai sumber masalah input: sarana, SDM, metode, dana, dan informasi/pasar."),
  q("G-T26", "teknis", "SMART", "Indikator 'meningkatkan kualitas layanan publik secepatnya' dinilai lemah. Rumusan SMART terbaik adalah?", "Persentase permohonan izin usaha yang selesai maksimal 3 hari kerja meningkat dari 62% menjadi 85% pada akhir 2026.", ["Layanan publik harus lebih baik dan cepat.", "Semua pegawai harus bekerja keras demi masyarakat.", "Masyarakat merasa puas kapan pun memungkinkan.", "Perizinan akan dibuat modern sesuai arahan pimpinan.", "Kualitas pelayanan menjadi prioritas utama daerah."], "SMART menuntut indikator spesifik, terukur, dapat dicapai, relevan, dan memiliki batas waktu."),

  // === EKONOMI (29): kegagalan pasar 8, barang 6, Chenery-Syrquin 4, Klassen 4, paradigma 3, kegagalan pemerintah 2, floor/ceiling 2 ===
  q("G-E01", "ekonomi", "Eksternalitas negatif", "Kawasan industri meningkatkan output daerah, tetapi limbah cair menurunkan kualitas air sungai dan biaya kesehatan warga. Bentuk kegagalan pasar dan intervensi yang paling tepat adalah?", "Eksternalitas negatif; pemerintah dapat menetapkan baku mutu, pajak/pungutan polusi, dan pengawasan lingkungan.", ["Monopoli alamiah; pemerintah harus membiarkan harga bebas sepenuhnya.", "Barang publik murni; solusinya membagi sungai menjadi hak milik pribadi.", "Asimetri informasi; solusinya hanya iklan layanan masyarakat.", "Tragedy of the commons; solusinya menghapus semua kegiatan ekonomi."], "Eksternalitas negatif terjadi saat biaya sosial tidak masuk ke harga pasar; regulasi dan instrumen ekonomi menginternalisasi biaya tersebut."),
  q("G-E02", "ekonomi", "Eksternalitas positif", "Program imunisasi menghasilkan manfaat bagi anak yang divaksin dan juga menurunkan risiko penularan pada masyarakat. Mengapa subsidi atau penyediaan publik dapat dibenarkan?", "Ada eksternalitas positif sehingga manfaat sosial lebih besar daripada manfaat privat yang diperhitungkan keluarga.", ["Ada monopoli alamiah yang membuat vaksin tidak dapat diproduksi.", "Ada price ceiling yang selalu menimbulkan surplus.", "Ada barang private murni sehingga negara tidak boleh terlibat.", "Ada kegagalan pemerintah yang pasti lebih besar dari pasar."], "Eksternalitas positif sering menyebabkan konsumsi pasar terlalu rendah; subsidi atau layanan publik dapat menaikkan konsumsi ke tingkat sosial yang lebih baik."),
  q("G-E03", "ekonomi", "Barang publik", "Penerangan jalan lingkungan membuat semua warga di ruas tersebut terbantu dan sulit mengecualikan pengguna tertentu. Ini menunjukkan alasan intervensi pemerintah karena?", "Barang publik atau mendekati publik memiliki non-rivalry dan sulit dieksklusi sehingga pasar cenderung kurang menyediakan.", ["Barang private umumnya disediakan pasar tanpa subsidi penuh pemerintah.", "Common resource rentan overuse meski sulit dikecualikan.", "Club goods tidak membutuhkan biaya operasional.", "Monopoli alamiah justru sering memerlukan regulasi tarif dan mutu layanan."], "Barang publik sulit dibiayai murni melalui pasar karena masalah free rider."),
  q("G-E04", "ekonomi", "Asimetri informasi", "Petani membeli benih unggul dari pedagang, tetapi tidak dapat menilai mutu benih sebelum panen. Banyak benih palsu beredar dan merusak kepercayaan pasar. Kegagalan pasar ini terutama berupa?", "Asimetri informasi; pemerintah dapat memperkuat sertifikasi, label, pengujian mutu, dan pengawasan.", ["Eksternalitas positif; pemerintah sebaiknya membayar semua pembeli benih.", "Barang publik; benih tidak rival dan tidak eksklusif.", "Price floor; harga selalu di bawah keseimbangan.", "Tragedy of the commons; benih digunakan bersama tanpa kepemilikan."], "Asimetri informasi terjadi ketika penjual dan pembeli tidak memiliki informasi mutu yang seimbang; sertifikasi mengurangi adverse selection."),
  q("G-E05", "ekonomi", "Monopoli alamiah", "Distribusi air minum perpipaan di kota kecil membutuhkan jaringan mahal sehingga satu operator lebih efisien daripada banyak jaringan paralel. Risiko utamanya adalah tarif tinggi dan mutu rendah. Intervensi yang tepat?", "Regulasi tarif dan standar layanan atau penyediaan BUMD karena karakter monopoli alamiah.", ["Membiarkan operator menaikkan tarif tanpa batas.", "Melarang seluruh investasi jaringan air.", "Mewajibkan lima jaringan pipa bersaing di jalan yang sama.", "Mengganti tarif air dengan harga lelang harian tanpa standar mutu."], "Monopoli alamiah muncul karena skala ekonomi besar; regulasi diperlukan agar efisiensi tidak berubah menjadi eksploitasi konsumen."),
  q("G-E06", "ekonomi", "Kegagalan koordinasi", "Investor pengolahan kakao menunggu kepastian pasokan petani, sementara petani enggan menanam kakao karena belum ada pembeli industri. Kebuntuan ini disebut?", "Kegagalan koordinasi; pemerintah dapat memfasilitasi kemitraan, informasi pasar, dan infrastruktur pendukung.", ["Eksternalitas negatif murni; solusinya pajak polusi.", "Barang publik murni; solusinya lampu jalan.", "Price ceiling; solusinya menaikkan harga maksimum.", "Kegagalan pemerintah; solusinya menghentikan semua fasilitasi."], "Kegagalan koordinasi terjadi saat keputusan saling bergantung membuat pasar tidak mencapai investasi yang bermanfaat."),
  q("G-E07", "ekonomi", "Intervensi pemerintah", "Pasar perumahan murah gagal menyediakan hunian layak untuk pekerja berpendapatan rendah karena daya beli rendah, informasi lahan terbatas, dan risiko pengembang tinggi. Paket intervensi yang paling seimbang adalah?", "Subsidi tepat sasaran, penyediaan prasarana dasar, informasi lahan, dan regulasi mutu minimum.", ["Menetapkan semua rumah gratis tanpa sumber pendanaan.", "Membiarkan pasar sepenuhnya karena hunian bukan urusan publik.", "Melarang pembangunan rumah komersial di seluruh kota.", "Menaikkan pajak bahan bangunan tanpa kompensasi."], "Intervensi pemerintah perlu menjawab sumber kegagalan pasar tanpa mengabaikan keberlanjutan fiskal dan mutu layanan."),
  q("G-E08", "ekonomi", "Government intervention trade-off", "Pemerintah daerah ingin mengatasi harga cabai yang sangat fluktuatif. Pilihan yang paling masuk akal untuk mengurangi kegagalan pasar tanpa mendistorsi terlalu besar adalah?", "Memperbaiki informasi harga, logistik, cadangan terbatas, dan kemitraan pemasaran petani.", ["Menetapkan satu harga tetap sepanjang tahun tanpa melihat pasokan.", "Mewajibkan petani menjual hanya ke satu pembeli.", "Melarang perdagangan antardaerah agar harga lokal tidak berubah.", "Menghapus data harga karena menimbulkan kepanikan."], "Intervensi yang baik memperbaiki informasi, logistik, dan koordinasi sehingga volatilitas turun dengan distorsi minimal."),
  q("G-E09", "ekonomi", "Barang private", "Roti yang dibeli seseorang tidak dapat dikonsumsi orang lain dan penjual dapat mengecualikan pembeli yang tidak membayar. Dalam klasifikasi ekonomi publik, roti adalah?", "Barang private.", ["Barang publik murni.", "Barang club.", "Common-pool resource.", "Merit good non-rival."], "Barang private bersifat rival dan eksklusif, sehingga pasar umumnya dapat menyediakannya."),
  q("G-E10", "ekonomi", "Barang publik", "Sistem peringatan dini tsunami memberi informasi kepada seluruh warga pesisir dan sulit mengecualikan orang yang tidak membayar. Kategori yang paling tepat adalah?", "Barang publik atau layanan publik dengan manfaat non-rival dan sulit dieksklusi.", ["Barang private karena hanya satu orang dapat mendengar sirene.", "Barang club karena pengguna selalu dibatasi anggota.", "Common-pool resource karena pemakaian satu orang mengurangi sirene orang lain.", "Tragedy of the commons karena overuse sumber bersama tanpa aturan."], "Peringatan dini memiliki karakter non-rival dan non-excludable sehingga membutuhkan pembiayaan kolektif."),
  q("G-E11", "ekonomi", "Barang club", "Jalan tol tidak macet pada jam normal dan pengguna dapat dikecualikan melalui gerbang pembayaran. Secara ekonomi, fasilitas ini mendekati?", "Barang club.", ["Barang private murni seperti makanan sekali konsumsi.", "Barang publik murni yang tidak dapat dipungut biaya.", "Common-pool resource yang selalu bebas akses.", "Eksternalitas negatif tanpa manfaat langsung."], "Club goods eksklusif tetapi relatif non-rival sampai kapasitas mulai padat."),
  q("G-E12", "ekonomi", "Common goods", "Danau tangkap ikan yang terbuka untuk banyak nelayan membuat tangkapan satu nelayan mengurangi stok untuk nelayan lain. Ini termasuk?", "Common-pool resource atau barang bersama.", ["Barang publik murni.", "Barang private karena ikan di danau tidak pernah berkurang.", "Barang club karena akses selalu terbatas anggota.", "Barang merit yang tidak perlu aturan."], "Common-pool resource sulit dieksklusi tetapi rival dalam konsumsi, sehingga rentan overuse."),
  q("G-E13", "ekonomi", "Tragedy of the commons", "Jika setiap peternak menambah sapi di padang penggembalaan bersama tanpa aturan, rumput habis dan semua rugi. Konsep yang paling tepat adalah?", "Tragedy of the commons.", ["Adverse selection pada asuransi.", "Price ceiling yang menciptakan surplus.", "Barang club dengan kapasitas kosong.", "Monopoli alamiah jaringan listrik."], "Tragedy of the commons terjadi ketika akses bersama dan insentif individual menyebabkan eksploitasi berlebihan."),
  q("G-E14", "ekonomi", "Mengelola common goods", "Untuk mencegah overfishing di perairan lokal, kebijakan yang paling tepat adalah?", "Kuota tangkap, musim larangan, pengawasan komunitas, dan hak akses yang jelas.", ["Membebaskan alat tangkap apa pun agar produksi naik cepat.", "Menghapus data stok ikan karena memicu konflik.", "Memberi subsidi bahan bakar tanpa batas.", "Menaikkan harga eceran ikan dengan price ceiling."], "Common goods perlu aturan akses, batas pemanfaatan, dan pengawasan agar stok tidak terkuras."),
  q("G-E15", "ekonomi", "Chenery-Syrquin akumulasi", "Menurut pola transformasi Chenery-Syrquin, kenaikan pendapatan per kapita biasanya disertai perubahan struktur. Faktor awal yang mendorong kapasitas produksi jangka panjang adalah?", "Akumulasi modal fisik dan manusia melalui investasi, pendidikan, dan kesehatan.", ["Penurunan semua tabungan rumah tangga.", "Penghapusan seluruh perdagangan antardaerah.", "Peningkatan konsumsi mewah tanpa investasi.", "Pengurangan keterampilan tenaga kerja."], "Chenery-Syrquin menekankan akumulasi sebagai pendorong transformasi produktif dan perubahan struktur ekonomi."),
  q("G-E16", "ekonomi", "Chenery-Syrquin alokasi", "Daerah yang tumbuh mulai menggeser tenaga kerja dari pertanian subsisten ke industri dan jasa produktif. Dalam kerangka Chenery-Syrquin, ini terutama terkait?", "Perubahan alokasi sumber daya antar sektor.", ["Kegagalan pemerintah dalam regulasi tarif.", "Price ceiling komoditas pangan.", "Barang publik non-rival.", "Asimetri informasi pada kredit mikro."], "Transformasi struktural mencakup realokasi tenaga kerja dan modal dari sektor berproduktivitas rendah ke lebih tinggi."),
  q("G-E17", "ekonomi", "Chenery-Syrquin demografi", "Kota menengah tumbuh cepat karena migrasi desa-kota, perubahan komposisi usia kerja, dan meningkatnya partisipasi angkatan kerja perempuan. Faktor Chenery-Syrquin yang relevan adalah?", "Transisi demografi dan urbanisasi sebagai bagian dari perubahan struktur pembangunan.", ["Monopoli alamiah.", "Barang club.", "Kebijakan harga dasar.", "Audit kepatuhan belanja."], "Pola Chenery-Syrquin mencakup perubahan demografi, urbanisasi, dan struktur tenaga kerja selama pembangunan."),
  q("G-E18", "ekonomi", "Chenery-Syrquin perdagangan", "Provinsi pesisir tumbuh setelah ekspor manufaktur meningkat dan impor mesin mendorong produktivitas. Dalam faktor transformasi Chenery-Syrquin, hal ini paling dekat dengan?", "Perubahan perdagangan, permintaan, dan keterbukaan ekonomi.", ["Tragedy of the commons.", "Kegagalan koordinasi antarnelayan.", "Price floor upah minimum.", "Barang publik lokal."], "Transformasi struktural dipengaruhi oleh komposisi permintaan, perdagangan, teknologi, dan integrasi pasar."),
  q("G-E19", "ekonomi", "Klassen maju cepat", "Kabupaten A memiliki laju pertumbuhan ekonomi dan PDRB per kapita di atas rata-rata provinsi. Dalam tipologi Klassen, daerah ini masuk kategori?", "Daerah maju dan tumbuh cepat.", ["Daerah maju tetapi tertekan.", "Daerah berkembang cepat.", "Daerah relatif tertinggal.", "Daerah tanpa klasifikasi."], "Tipologi Klassen memakai dua sumbu: pertumbuhan dan pendapatan per kapita relatif terhadap rata-rata wilayah acuan."),
  q("G-E20", "ekonomi", "Klassen maju tertekan", "Kabupaten B memiliki PDRB per kapita tinggi karena basis tambang lama, tetapi pertumbuhan ekonominya di bawah rata-rata provinsi. Kategori Klassen yang tepat adalah?", "Daerah maju tetapi tertekan.", ["Daerah maju dan tumbuh cepat.", "Daerah berkembang cepat.", "Daerah relatif tertinggal.", "Daerah baru tanpa aktivitas ekonomi."], "Pendapatan tinggi namun pertumbuhan rendah menunjukkan daerah maju tetapi tertekan."),
  q("G-E21", "ekonomi", "Klassen berkembang cepat", "Kabupaten C memiliki PDRB per kapita masih rendah, tetapi pertumbuhannya lebih tinggi dari rata-rata provinsi selama lima tahun. Dalam matriks Klassen, daerah ini termasuk?", "Daerah berkembang cepat.", ["Daerah maju dan tumbuh cepat.", "Daerah maju tetapi tertekan.", "Daerah relatif tertinggal.", "Daerah jenuh investasi."], "Pertumbuhan tinggi namun pendapatan per kapita rendah menunjukkan potensi mengejar ketertinggalan."),
  q("G-E22", "ekonomi", "Klassen tertinggal", "Kabupaten D memiliki pertumbuhan ekonomi dan PDRB per kapita sama-sama di bawah rata-rata provinsi. Prioritas strategi yang paling tepat adalah?", "Daerah relatif tertinggal; perlu penguatan layanan dasar, konektivitas, produktivitas lokal, dan investasi yang sesuai potensi.", ["Daerah maju cepat sehingga cukup menjaga status quo.", "Daerah maju tertekan sehingga cukup mengelola sektor lama.", "Daerah berkembang cepat sehingga tidak perlu dukungan dasar.", "Daerah tanpa masalah pembangunan."], "Kuadran tertinggal menandakan kinerja relatif rendah pada dua indikator sehingga intervensi dasar dan produktivitas diperlukan."),
  q("G-E23", "ekonomi", "Capabilities", "Dalam pendekatan capability, keberhasilan pembangunan tidak cukup diukur dari PDRB. Indikator yang paling sesuai adalah?", "Perluasan kemampuan warga untuk hidup sehat, berpendidikan, berpartisipasi, dan memilih kehidupan yang bernilai.", ["Kenaikan output industri meski akses pendidikan memburuk.", "Jumlah proyek fisik tanpa melihat penerima manfaat.", "Besarnya belanja aparatur sebagai ukuran kesejahteraan.", "Jumlah izin investasi tanpa kualitas pekerjaan."], "Pendekatan capabilities menekankan perluasan kebebasan substantif dan kemampuan manusia, bukan hanya pendapatan."),
  q("G-E24", "ekonomi", "Todaro", "Todaro menekankan pembangunan sebagai proses multidimensi. Pernyataan yang paling sesuai adalah?", "Pembangunan mencakup kenaikan taraf hidup, harga diri, kebebasan memilih, serta perubahan struktur ekonomi dan kelembagaan.", ["Pembangunan identik dengan pertumbuhan PDRB tanpa memperhatikan distribusi.", "Pembangunan cukup berarti pembangunan gedung pemerintah.", "Pembangunan hanya terjadi jika sektor pertanian dihapus seluruhnya.", "Pembangunan tidak membutuhkan perubahan institusi."], "Todaro melihat pembangunan sebagai proses multidimensi: ekonomi, sosial, kelembagaan, dan peningkatan pilihan hidup."),
  q("G-E25", "ekonomi", "Stiglitz", "Dalam rapat, seorang perencana mengingatkan bahwa liberalisasi pasar tanpa institusi, informasi, dan perlindungan kelompok rentan dapat memperlebar ketimpangan. Pandangan ini sejalan dengan?", "Stiglitz, yang menekankan informasi tidak sempurna, peran institusi, dan kualitas intervensi negara.", ["Pandangan bahwa pasar selalu sempurna.", "Doktrin bahwa pemerintah tidak pernah boleh mengoreksi pasar.", "Konsep price floor sebagai satu-satunya alat pembangunan.", "Tipologi Klassen kuadran maju cepat."], "Stiglitz banyak menyoroti asimetri informasi, kegagalan pasar, dan pentingnya institusi serta kebijakan publik yang baik."),
  q("G-E26", "ekonomi", "Kegagalan pemerintah", "Subsidi pupuk dirancang untuk petani kecil, tetapi sebagian besar dinikmati petani besar karena data penerima buruk dan pengawasan lemah. Ini menunjukkan?", "Kegagalan pemerintah akibat targeting error, informasi lemah, dan rent seeking.", ["Eksternalitas positif yang selalu berhasil.", "Barang publik murni yang tidak bisa disalahgunakan.", "Monopoli alamiah yang efisien.", "Tragedy of the commons tanpa peran negara."], "Government failure muncul ketika intervensi publik tidak mencapai tujuan karena desain, informasi, insentif, atau tata kelola buruk."),
  q("G-E27", "ekonomi", "Kegagalan pemerintah regulasi", "Pemerintah menetapkan izin usaha sangat rumit untuk melindungi konsumen, tetapi prosesnya menciptakan biaya tinggi dan peluang pungli. Evaluasi terbaik adalah?", "Regulasi mengalami kegagalan pemerintah karena biaya transaksi dan rent seeking melebihi manfaat perlindungan.", ["Regulasi pasti efektif karena dibuat pemerintah.", "Masalah ini murni kegagalan pasar tanpa unsur birokrasi.", "Semua izin harus ditambah agar pungli turun.", "Tidak perlu mengukur biaya dan manfaat regulasi."], "Intervensi dapat gagal jika desain regulasi membuka rente, memperlambat layanan, dan tidak proporsional terhadap risikonya."),
  q("G-E28", "ekonomi", "Price floor", "Pemerintah menetapkan harga dasar gabah di atas harga keseimbangan untuk melindungi petani. Dampak yang perlu diantisipasi adalah?", "Surplus pasokan jika pembelian atau penyerapan tidak disiapkan.", ["Kekurangan pasokan karena harga terlalu rendah.", "Permintaan selalu meningkat tanpa batas.", "Harga pasar pasti sama dengan nol.", "Tidak ada dampak pada insentif produksi."], "Price floor di atas keseimbangan dapat menciptakan surplus karena produsen ingin menjual lebih banyak daripada yang diminta pasar."),
  q("G-E29", "ekonomi", "Price ceiling", "Saat harga sewa rumah melonjak, pemerintah menetapkan harga maksimum di bawah keseimbangan. Risiko utama dari price ceiling tersebut adalah?", "Kekurangan pasokan, penurunan mutu, dan pasar informal jika tidak disertai kebijakan pelengkap.", ["Surplus unit sewa karena harga terlalu tinggi.", "Produsen otomatis membangun lebih banyak rumah.", "Tidak ada perubahan perilaku pemilik rumah.", "Semua penyewa pasti mendapat rumah lebih baik."], "Price ceiling di bawah keseimbangan dapat menekan harga tetapi menyebabkan excess demand dan distorsi kualitas/pasokan."),

  // === SOSIAL (25): SIPD 6, stakeholder 6, pendampingan/fasilitasi 4, Chambers 3, gender/difabel 4, MBG/kebijakan sosial 2 ===
  q("G-S01", "sosial", "Permen 900 SIPD indikator kerja", "Dalam SIPD, sebuah OPD mengisi indikator 'jumlah rapat koordinasi kemiskinan' untuk menilai pelaksanaan kegiatan. Indikator tersebut paling tepat disebut?", "Indikator kerja karena mengukur aktivitas atau keluaran kerja yang dilakukan.", ["Indikator kinerja utama outcome karena langsung mengukur penurunan kemiskinan.", "Indikator impact jangka panjang.", "Indikator makro nasional.", "Indikator gender responsif otomatis."], "Indikator kerja cenderung mengukur aktivitas/output proses, berbeda dari indikator kinerja yang menunjukkan hasil atau capaian tujuan."),
  q("G-S02", "sosial", "Permen 900 SIPD indikator kinerja", "OPD ingin menilai apakah program perlindungan anak berhasil. Indikator yang paling mencerminkan kinerja adalah?", "Persentase kasus kekerasan anak yang tertangani sesuai standar layanan dalam 30 hari.", ["Jumlah rapat tim perlindungan anak.", "Jumlah spanduk kampanye yang dicetak.", "Jumlah perjalanan dinas petugas.", "Jumlah halaman laporan kegiatan."], "Indikator kinerja harus menggambarkan capaian layanan atau hasil, bukan hanya aktivitas administratif."),
  q("G-S03", "sosial", "SIPD output vs outcome", "Program pelatihan kerja melaporkan 500 peserta hadir. Kepala daerah meminta indikator yang lebih menggambarkan manfaat program. Pilihan terbaik adalah?", "Persentase lulusan pelatihan yang bekerja atau berusaha dalam enam bulan.", ["Jumlah kursi yang disiapkan panitia.", "Jumlah sertifikat yang dicetak tanpa verifikasi kerja.", "Jumlah konsumsi peserta.", "Jumlah surat undangan yang dikirim."], "Output peserta hadir belum menunjukkan manfaat; outcome ketenagakerjaan lebih tepat menilai kinerja program."),
  q("G-S04", "sosial", "SIPD kualitas indikator", "Indikator 'masyarakat semakin sejahtera' ditolak karena terlalu umum. Rumusan yang lebih baik untuk SIPD adalah?", "Persentase rumah tangga miskin ekstrem yang keluar dari status miskin ekstrem pada akhir 2026.", ["Kesejahteraan meningkat semaksimal mungkin.", "Masyarakat merasa lebih baik.", "Bantuan sosial dibagikan dengan niat baik.", "Semua kegiatan berjalan lancar."], "Indikator SIPD perlu jelas, terukur, dan dapat ditelusuri terhadap target serta sasaran."),
  q("G-S05", "sosial", "SIPD konsistensi", "Dalam Renja, kegiatan posyandu memakai indikator bayi ditimbang, tetapi sasaran program adalah penurunan stunting. Tindakan perencana yang tepat adalah?", "Menambahkan indikator kinerja yang menghubungkan layanan posyandu dengan prevalensi atau risiko stunting sasaran.", ["Menghapus sasaran stunting karena sulit dicapai.", "Mengganti semua indikator menjadi serapan anggaran.", "Mencatat jumlah rapat kader sebagai indikator akhir.", "Mengabaikan konsistensi karena SIPD hanya aplikasi."], "Konsistensi indikator kerja dan kinerja penting agar aktivitas dapat ditautkan ke sasaran pembangunan."),
  q("G-S06", "sosial", "SIPD evaluasi kinerja", "Saat evaluasi SIPD, realisasi kegiatan tinggi tetapi outcome sosial rendah. Pertanyaan evaluatif paling penting adalah?", "Apakah output kegiatan benar-benar menjangkau kelompok sasaran dan cukup kuat untuk mengubah outcome?", ["Apakah semua foto kegiatan sudah diunggah.", "Apakah jumlah rapat bisa ditambah agar serapan naik.", "Apakah indikator outcome perlu dihapus dari dokumen.", "Apakah laporan dibuat lebih panjang."], "Evaluasi kinerja harus menguji hubungan aktivitas-output-outcome dan ketepatan sasaran, bukan hanya kelengkapan administrasi."),
  q("G-S07", "sosial", "Stakeholder power-interest tinggi-tinggi", "Dalam revitalisasi pasar, asosiasi pedagang memiliki pengaruh besar dan kepentingan tinggi karena lapaknya terdampak langsung. Strategi engagement yang tepat dalam power-interest matrix adalah?", "Kelola secara dekat melalui konsultasi intensif, negosiasi, dan pelibatan dalam keputusan kunci.", ["Cukup diberi informasi umum setahun sekali.", "Diabaikan karena terlalu kritis.", "Dipuaskan minimal tanpa komunikasi.", "Hanya dipantau dari jauh."], "Stakeholder high power-high interest harus dikelola dekat karena dapat menentukan keberhasilan dan terdampak besar."),
  q("G-S08", "sosial", "Stakeholder high power low interest", "Sebuah kantor vertikal memiliki kewenangan persetujuan teknis tinggi, tetapi minatnya terhadap program kampung tematik rendah. Dalam matriks power-interest, strategi yang tepat adalah?", "Keep satisfied: penuhi kebutuhan informasi strategis dan libatkan pada keputusan yang memerlukan kewenangannya.", ["Manage closely seperti kelompok terdampak langsung setiap hari.", "Abaikan sepenuhnya karena minat rendah.", "Serahkan seluruh program kepadanya.", "Mobilisasi protes agar minat naik."], "High power-low interest perlu dijaga kepuasannya agar tidak menjadi penghambat, tanpa membebani komunikasi berlebihan."),
  q("G-S09", "sosial", "Stakeholder low power high interest", "Kelompok remaja difabel sangat berkepentingan pada desain taman inklusif, tetapi pengaruh formalnya rendah. Strategi yang paling tepat adalah?", "Keep informed dan berdayakan kanal partisipasinya agar kebutuhan spesifik masuk desain.", ["Abaikan karena tidak memiliki kewenangan anggaran.", "Beri keputusan final tanpa konsultasi.", "Cukup kirim laporan teknis setelah taman selesai.", "Minta mereka membiayai seluruh perubahan desain."], "Low power-high interest perlu diberi informasi dan ruang aspirasi; dalam isu inklusi, pemberdayaan penting agar suara rentan tidak hilang."),
  q("G-S10", "sosial", "Stakeholder low-low", "Dalam program peningkatan drainase kecil, kelompok pengunjung sesekali pasar memiliki pengaruh dan kepentingan rendah. Strategi matriks yang proporsional adalah?", "Monitor dengan komunikasi minimum sambil tetap membuka kanal keluhan.", ["Kelola harian seperti pengambil keputusan utama.", "Berikan veto atas desain teknis.", "Rahasiakan seluruh informasi publik.", "Jadikan satu-satunya penerima manfaat."], "Low power-low interest cukup dipantau, tetapi prinsip pelayanan publik tetap menyediakan informasi dan kanal masukan."),
  q("G-S11", "sosial", "Pemetaan stakeholder", "Konflik lahan untuk sekolah baru melibatkan pemilik tanah, warga sekitar, dinas pendidikan, DPRD, dan calon siswa. Langkah awal pemetaan stakeholder yang paling tepat adalah?", "Mengidentifikasi kepentingan, tingkat pengaruh, posisi dukungan, dan risiko konflik setiap aktor.", ["Langsung memilih aktor yang paling setuju saja.", "Menghapus aktor yang menolak dari daftar.", "Menganggap semua stakeholder memiliki pengaruh sama.", "Menunda pemetaan sampai konflik membesar."], "Power-interest matrix dimulai dari identifikasi aktor, kepentingan, pengaruh, posisi, dan strategi komunikasi."),
  q("G-S12", "sosial", "Strategi stakeholder", "Proyek relokasi warga bantaran sungai ditolak karena warga merasa hanya diberi sosialisasi satu arah. Perbaikan strategi stakeholder terbaik adalah?", "Meningkatkan pelibatan warga terdampak melalui dialog, opsi kompensasi, jadwal transisi, dan mekanisme keluhan.", ["Mempercepat penggusuran agar konflik cepat selesai.", "Mengurangi informasi supaya warga tidak bertanya.", "Melibatkan hanya kontraktor pelaksana.", "Menganggap penolakan sebagai bukti warga tidak rasional."], "Stakeholder terdampak langsung biasanya high interest; engagement harus dialogis dan menyediakan mekanisme penyelesaian keberatan."),
  q("G-S13", "sosial", "Pendampingan", "Kelompok usaha perempuan sudah berjalan, tetapi pembukuan, akses izin, dan negosiasi pasar masih lemah. Peran petugas paling tepat adalah?", "Pendampingan berkelanjutan untuk memperkuat kapasitas kelompok sampai mampu menjalankan fungsi sendiri.", ["Fasilitasi satu kali lalu seluruh masalah dianggap selesai.", "Mengambil alih seluruh usaha kelompok secara permanen.", "Hanya memberi ceramah tanpa praktik.", "Membubarkan kelompok agar tidak bergantung."], "Pendampingan menekankan proses berkelanjutan, penguatan kapasitas, dan kemandirian kelompok sasaran."),
  q("G-S14", "sosial", "Fasilitasi", "Dalam musyawarah desa, warga memiliki berbagai usulan dan perlu proses diskusi agar mencapai prioritas bersama. Peran fasilitator yang tepat adalah?", "Memandu proses dialog netral, memastikan partisipasi, dan membantu kelompok menyepakati keputusan.", ["Menentukan semua keputusan sesuai preferensi pribadi fasilitator.", "Membaca materi tanpa memberi ruang diskusi.", "Menyuruh peserta mengikuti usulan tokoh terkuat.", "Mengganti forum warga dengan rapat tertutup pejabat."], "Fasilitasi berfokus pada proses, netralitas, partisipasi, dan kesepakatan kelompok."),
  q("G-S15", "sosial", "Pendampingan vs fasilitasi", "Program pemberdayaan desa membutuhkan pelatihan administrasi BUMDes selama enam bulan dan forum musyawarah untuk memilih unit usaha. Pembedaan peran yang tepat adalah?", "Pendampingan untuk penguatan kapasitas BUMDes, fasilitasi untuk memandu musyawarah pemilihan unit usaha.", ["Fasilitasi berarti menggantikan pengurus BUMDes selama enam bulan.", "Pendampingan hanya berarti memimpin rapat satu kali.", "Keduanya sama sehingga tidak perlu dibedakan.", "Pendampingan selalu netral tanpa memberi arahan teknis."], "Pendampingan lebih intensif dan berkelanjutan; fasilitasi memandu proses kelompok agar keputusan lahir secara partisipatif."),
  q("G-S16", "sosial", "Etika pendampingan", "Pendamping sosial menemukan kelompok dampingan selalu menunggu keputusan pendamping sebelum bertindak. Koreksi yang tepat adalah?", "Mengurangi ketergantungan dengan transfer keterampilan, coaching, dan keputusan bertahap oleh kelompok.", ["Terus mengambil keputusan agar program cepat selesai.", "Menghentikan seluruh kegiatan tanpa transisi.", "Mengganti anggota yang bertanya terlalu banyak.", "Membuat laporan berhasil meski kapasitas tidak berubah."], "Pendampingan yang baik memperkuat agency dan kemandirian, bukan menciptakan ketergantungan baru."),
  q("G-S17", "sosial", "Chambers kemiskinan", "Menurut Chambers, kemiskinan tidak hanya rendah pendapatan. Rumah tangga miskin juga rentan sakit, tidak berdaya menghadapi aparat, terisolasi, dan lemah secara fisik. Kerangka ini dikenal sebagai?", "Lima deprivasi Chambers: poverty, physical weakness, isolation, vulnerability, dan powerlessness.", ["Lima kekuatan Porter.", "Lima M input produksi.", "Lima pilar SMART.", "Lima kuadran Klassen."], "Chambers menjelaskan jebakan deprivasi yang saling menguatkan, bukan hanya kekurangan uang."),
  q("G-S18", "sosial", "Chambers vulnerability", "Keluarga nelayan tidak selalu miskin pada musim panen ikan, tetapi mudah jatuh miskin saat cuaca ekstrem, sakit, atau alat rusak. Dalam Chambers, kondisi ini terutama disebut?", "Vulnerability atau kerentanan terhadap guncangan.", ["Isolation karena lokasi selalu terpencil.", "Powerlessness karena tidak ada hak politik sama sekali.", "Physical weakness karena semua anggota pasti sakit.", "Market failure monopoli."], "Vulnerability menggambarkan risiko jatuh atau makin miskin ketika menghadapi shock ekonomi, kesehatan, atau lingkungan."),
  q("G-S19", "sosial", "Chambers powerlessness", "Warga miskin kota enggan melapor pungutan liar karena takut kehilangan akses bantuan dan tidak paham prosedur pengaduan. Dalam kerangka Chambers, ini terutama menunjukkan?", "Powerlessness karena warga tidak memiliki daya tawar dan akses efektif terhadap keputusan.", ["Physical weakness karena kekurangan gizi.", "Barang publik karena laporan tidak rival.", "Price floor karena harga bantuan tinggi.", "Klassen maju tertekan."], "Powerlessness adalah ketidakberdayaan dalam relasi sosial dan kelembagaan sehingga hak sulit diperjuangkan."),
  q("G-S20", "sosial", "Gender responsive planning", "Program pelatihan digital hanya dilaksanakan malam hari di lokasi jauh. Data menunjukkan banyak perempuan tidak hadir karena beban pengasuhan dan keamanan transportasi. Perbaikan paling responsif gender adalah?", "Menyesuaikan waktu/lokasi, menyediakan dukungan pengasuhan atau transportasi aman, dan memantau partisipasi serta hasil menurut jenis kelamin.", ["Menyimpulkan perempuan tidak berminat teknologi.", "Menghapus peserta perempuan agar target kelulusan naik.", "Menambah materi teknis tanpa mengubah hambatan akses.", "Mengadakan pelatihan hanya untuk peserta yang bisa datang malam."], "Perencanaan responsif gender mengidentifikasi hambatan akses, partisipasi, kontrol, dan manfaat yang berbeda antara kelompok."),
  q("G-S21", "sosial", "Inklusi difabel", "Gedung layanan baru memiliki loket tinggi, tidak ada jalur kursi roda, dan formulir hanya cetak kecil. Rekomendasi inklusi difabel terbaik adalah?", "Menerapkan desain universal, akomodasi layak, informasi aksesibel, dan pelibatan penyandang disabilitas dalam uji layanan.", ["Membuat loket khusus di lantai dua tanpa lift.", "Meminta difabel membawa pendamping pribadi saja.", "Menunda layanan sampai semua warga tidak membutuhkan bantuan.", "Mengganti layanan tatap muka dengan pengumuman lisan saja."], "Inklusi difabel membutuhkan aksesibilitas fisik, informasi, komunikasi, dan akomodasi layak sesuai prinsip desain universal."),
  q("G-S22", "sosial", "Data inklusi", "Bappeda ingin memastikan bantuan sosial tidak bias terhadap perempuan kepala keluarga dan penyandang disabilitas. Data minimum yang perlu diminta adalah?", "Data terpilah menurut jenis kelamin, usia, disabilitas, status rumah tangga, lokasi, dan tingkat kerentanan.", ["Total penerima saja agar sederhana.", "Foto kegiatan tanpa identitas kelompok.", "Rata-rata kabupaten tanpa kelompok rentan.", "Jumlah rapat verifikasi."], "Data terpilah membantu menemukan kesenjangan akses dan memastikan kelompok rentan terjangkau."),
  q("G-S23", "sosial", "GEDSI", "Dalam pembangunan taman kota, anak, lansia, perempuan, dan difabel memiliki kebutuhan keamanan serta akses berbeda. Prinsip GEDSI yang paling tepat adalah?", "Melibatkan kelompok beragam sejak perencanaan dan memastikan manfaat, keamanan, serta akses setara.", ["Menggunakan standar rata-rata orang dewasa laki-laki sebagai satu-satunya acuan.", "Menganggap desain netral pasti cocok untuk semua.", "Menghapus konsultasi karena memperlambat proyek.", "Membatasi taman hanya untuk kelompok yang paling mampu membayar."], "GEDSI menekankan gender equality, disability, and social inclusion agar desain dan layanan tidak mengecualikan kelompok tertentu."),
  q("G-S24", "sosial", "MBG targeting", "Dalam program Makan Bergizi Gratis di daerah terpencil, sekolah mudah dijangkau mendapat pasokan rutin, sedangkan sekolah kecil di pulau terpencil sering terlambat. Risiko kebijakan sosial yang harus dikoreksi adalah?", "Ketimpangan akses layanan; perlu desain logistik afirmatif untuk wilayah sulit dan pemantauan mutu gizi.", ["Keberhasilan penuh karena rata-rata kabupaten sudah tinggi.", "Masalah private goods sehingga pemerintah tidak boleh terlibat.", "Price floor beras yang otomatis menyelesaikan distribusi.", "Tidak perlu evaluasi karena program bersifat nasional."], "Kebijakan sosial perlu memperhatikan equity; rata-rata capaian dapat menyembunyikan kelompok atau wilayah yang tertinggal."),
  q("G-S25", "sosial", "Kebijakan sosial kasus", "Bantuan tunai untuk lansia miskin meningkatkan konsumsi, tetapi sebagian penerima kesulitan mencairkan bantuan karena rekening pasif dan jarak bank jauh. Rekomendasi terbaik adalah?", "Memperbaiki kanal pencairan, verifikasi rekening, layanan jemput bola, dan mekanisme pengaduan untuk lansia rentan.", ["Menghentikan bantuan karena semua kendala berasal dari penerima.", "Mengganti semua bantuan dengan rapat sosialisasi.", "Mengabaikan biaya transportasi karena bukan indikator keuangan.", "Menaikkan target realisasi tanpa memperbaiki akses."], "Efektivitas kebijakan sosial ditentukan bukan hanya nominal bantuan, tetapi juga akses, administrasi, dan perlindungan kelompok rentan."),

  // === SPASIAL (20): PBG/SLF PP21 5, SIG/QGIS 4, LVC 3, asas perencanaan 4, institutional capability 2, IKN/PSN 2 ===
  q("G-P01", "spasial", "PBG", "Pengembang ingin membangun ruko di zona perdagangan RDTR. Sebelum konstruksi, ia harus memastikan kesesuaian tata ruang dan persyaratan teknis bangunan. Perizinan bangunan yang relevan adalah?", "PBG, yaitu Persetujuan Bangunan Gedung yang diberikan sebelum pembangunan sesuai fungsi dan standar teknis.", ["SLF yang hanya diterbitkan sebelum desain dibuat.", "IMB baru tanpa mengacu sistem PBG.", "Sertifikat tanah tidak menggantikan PBG atau kesesuaian tata ruang.", "Izin lingkungan tidak menggantikan persyaratan teknis bangunan dan KKPR."], "PBG menggantikan IMB sebagai persetujuan sebelum membangun dengan basis fungsi, standar teknis, dan kesesuaian tata ruang."),
  q("G-P02", "spasial", "SLF", "Sebuah gedung pelayanan publik selesai dibangun dan akan digunakan. Pemerintah perlu memastikan bangunan laik fungsi dari aspek keselamatan, kesehatan, kenyamanan, dan kemudahan. Dokumen yang dibutuhkan adalah?", "SLF atau Sertifikat Laik Fungsi.", ["PBG baru untuk memulai desain.", "KKPR untuk mengganti sertifikat tanah.", "AMDAL sebagai bukti semua struktur aman.", "SPPT PBB sebagai izin operasional gedung."], "SLF diterbitkan setelah bangunan memenuhi persyaratan laik fungsi untuk digunakan."),
  q("G-P03", "spasial", "PP 21/2021 tata ruang", "Dalam sistem perizinan berbasis tata ruang, investor mengajukan kegiatan di lokasi yang belum memiliki RDTR digital. Langkah yang harus diperiksa perencana adalah?", "Kesesuaian Kegiatan Pemanfaatan Ruang berdasarkan RTRW, rencana rinci bila ada, dan ketentuan PP 21/2021.", ["Menerbitkan izin otomatis karena belum ada RDTR.", "Mengabaikan RTRW selama investasi bernilai besar.", "Meminta investor menentukan sendiri zonasi.", "Mengganti proses tata ruang dengan rekomendasi informal."], "PP 21/2021 mengatur penyelenggaraan penataan ruang dan KKPR sebagai instrumen kesesuaian pemanfaatan ruang."),
  q("G-P04", "spasial", "PBG-SLF hubungan", "Bangunan pasar rakyat telah memiliki PBG, tetapi selama konstruksi terjadi perubahan struktur. Sebelum digunakan, apa yang paling tepat dilakukan?", "Memeriksa kesesuaian pelaksanaan dengan PBG dan persyaratan teknis sebelum penerbitan SLF.", ["Langsung digunakan karena PBG sudah cukup untuk seluruh umur bangunan.", "Menghapus kebutuhan SLF agar pedagang cepat masuk.", "Mengganti PBG dengan surat keterangan lurah.", "Menerbitkan SLF tanpa pemeriksaan teknis."], "PBG mengatur persetujuan membangun; SLF memastikan bangunan yang selesai benar-benar laik fungsi."),
  q("G-P05", "spasial", "PBG inklusif", "Gedung kantor pemerintah mengajukan PBG tetapi desainnya belum menyediakan ramp, toilet aksesibel, dan jalur evakuasi difabel. Catatan perencana terbaik adalah?", "Persyaratan kemudahan dan aksesibilitas harus dipenuhi sebelum PBG disetujui.", ["Aksesibilitas cukup ditambahkan setelah gedung ramai.", "Difabel dapat dilayani di luar gedung saja.", "PBG hanya memeriksa warna fasad.", "SLF tidak terkait keselamatan dan kemudahan."], "Standar teknis bangunan gedung mencakup keselamatan, kesehatan, kenyamanan, dan kemudahan termasuk aksesibilitas."),
  q("G-P06", "spasial", "SIG peta tematik", "Bappeda ingin membuat peta tematik kemiskinan per desa di QGIS. Data tabular berisi kode desa dan angka kemiskinan, sedangkan layer batas desa memiliki kode wilayah. Langkah kunci adalah?", "Melakukan join data tabular ke layer batas desa menggunakan kode wilayah yang konsisten.", ["Menggambar ulang semua batas desa secara manual.", "Mengubah angka kemiskinan menjadi foto.", "Menghapus kode wilayah agar label lebih pendek.", "Menyimpan tabel tanpa sistem koordinat."], "Peta tematik membutuhkan penggabungan atribut statistik dengan geometri wilayah melalui kunci yang sama."),
  q("G-P07", "spasial", "SIG klasifikasi", "Peta choropleth pengangguran kecamatan terlihat menyesatkan karena satu kelas memuat hampir semua kecamatan. Perbaikan QGIS yang tepat adalah?", "Memilih metode klasifikasi yang sesuai seperti quantile, natural breaks, atau interval yang diuji terhadap sebaran data.", ["Mengubah warna acak tanpa melihat data.", "Menghapus legenda agar tidak dipertanyakan.", "Menggunakan satu kelas untuk semua kecamatan.", "Mengubah proyeksi menjadi tabel Excel."], "Klasifikasi memengaruhi interpretasi peta tematik; metode harus sesuai distribusi data dan tujuan analisis."),
  q("G-P08", "spasial", "SIG CRS", "Layer jalan dan batas administrasi tidak bertumpuk di QGIS meskipun lokasinya sama. Penyebab teknis yang paling mungkin dan perlu dicek adalah?", "Perbedaan atau kesalahan Coordinate Reference System (CRS).", ["Jumlah kolom atribut terlalu banyak.", "Warna simbol jalan terlalu gelap.", "Nama file terlalu panjang.", "Legenda belum dicetak."], "CRS yang salah atau tidak terdefinisi membuat layer tidak sejajar secara spasial."),
  q("G-P09", "spasial", "SIG layout", "Peta prioritas sanitasi akan dipakai dalam musrenbang. Elemen layout yang minimal harus ada agar peta dapat dibaca dan dipertanggungjawabkan adalah?", "Judul, legenda, skala, arah utara, sumber data, tahun data, dan inset/lokasi bila perlu.", ["Hanya warna menarik tanpa sumber data.", "Logo besar tanpa legenda.", "Foto kegiatan sebagai pengganti skala.", "Tabel anggaran tanpa geometri."], "Layout peta tematik harus menyampaikan makna simbol, skala, orientasi, lokasi, dan sumber data."),
  q("G-P10", "spasial", "Land value capture", "Pembangunan stasiun baru menaikkan nilai tanah di sekitarnya. Pemerintah ingin mengambil sebagian kenaikan nilai untuk membiayai trotoar dan drainase kawasan. Instrumen ini dikenal sebagai?", "Land value capture.", ["Price ceiling perumahan.", "Common-pool resource.", "Stakeholder mapping.", "Evaluasi ex ante."], "Land value capture menangkap sebagian kenaikan nilai lahan akibat investasi publik atau perubahan regulasi untuk membiayai kepentingan publik."),
  q("G-P11", "spasial", "LVC instrumen", "Kota akan membangun koridor BRT dan mempertimbangkan kontribusi pengembang di area yang mendapat tambahan koefisien lantai bangunan. Pilihan instrumen LVC yang relevan adalah?", "Betterment levy, development charge, kontribusi pengembang, atau penjualan hak pengembangan tambahan.", ["Subsidi konsumsi BBM tanpa target.", "Penghapusan seluruh pajak properti.", "Larangan semua pembangunan di koridor.", "Bantuan tunai tanpa hubungan dengan kenaikan nilai lahan."], "Instrumen LVC mengaitkan manfaat kenaikan nilai lahan dengan kontribusi untuk infrastruktur atau layanan kawasan."),
  q("G-P12", "spasial", "LVC risiko", "Penerapan LVC di kawasan transit ditolak warga karena khawatir gentrifikasi dan penggusuran. Mitigasi kebijakan yang paling tepat adalah?", "Mengombinasikan LVC dengan hunian terjangkau, perlindungan penyewa, partisipasi warga, dan transparansi penggunaan dana.", ["Mengabaikan warga karena nilai tanah naik.", "Menaikkan pungutan tanpa kajian kemampuan bayar.", "Menghapus transportasi publik agar harga tanah tidak naik.", "Membatasi informasi penggunaan dana."], "LVC perlu desain sosial agar kenaikan nilai lahan tidak hanya menguntungkan pemilik modal dan tidak mendorong eksklusi."),
  q("G-P13", "spasial", "Asas keterpaduan", "Rencana kawasan pesisir memisahkan program pelabuhan, permukiman, mangrove, dan pariwisata tanpa analisis hubungan ruang. Asas perencanaan yang paling dilanggar adalah?", "Keterpaduan antar sektor, wilayah, dan pemangku kepentingan.", ["Kerahasiaan mutlak.", "Profit maksimum investor.", "Sentralisasi semua keputusan teknis.", "Penghapusan partisipasi."], "Asas keterpaduan menuntut rencana ruang menghubungkan sektor, wilayah, lingkungan, dan aktor."),
  q("G-P14", "spasial", "Asas keberlanjutan", "Kawasan resapan diubah menjadi perumahan tanpa memperhitungkan banjir dan daya dukung air. Asas perencanaan yang terutama diabaikan adalah?", "Keberlanjutan dan keserasian lingkungan.", ["Kompetisi harga tanah.", "Kerahasiaan data publik.", "Penyederhanaan administrasi saja.", "Eksklusivitas layanan."], "Perencanaan ruang harus menjaga daya dukung, daya tampung, dan keberlanjutan lingkungan."),
  q("G-P15", "spasial", "Asas partisipatif", "RDTR disusun cepat tetapi warga baru mengetahui zonasi setelah ditetapkan dan banyak usaha kecil terdampak. Kekurangan proses yang paling jelas adalah?", "Minimnya partisipasi masyarakat dan transparansi informasi rencana.", ["Terlalu banyak data spasial.", "Terlalu jelasnya legenda peta.", "Kelebihan koordinasi lintas OPD.", "Terlalu kuatnya evaluasi ex post."], "Asas partisipatif mengharuskan masyarakat diberi ruang informasi dan masukan dalam perencanaan."),
  q("G-P16", "spasial", "Asas kepastian hukum", "Investor dan warga bingung karena peta zonasi, peraturan zonasi, dan izin pemanfaatan ruang saling berbeda. Asas yang paling perlu diperkuat adalah?", "Kepastian hukum melalui konsistensi dokumen rencana, aturan zonasi, dan perizinan.", ["Ketertutupan dokumen agar tidak diperdebatkan.", "Kebebasan setiap petugas menafsirkan zonasi.", "Penghapusan standar peta.", "Prioritas lisan dibanding dokumen resmi."], "Kepastian hukum membutuhkan dokumen tata ruang yang konsisten, dapat diakses, dan menjadi dasar perizinan."),
  q("G-P17", "spasial", "Institutional capability", "Kabupaten memiliki peta rawan bencana bagus, tetapi tidak ada unit yang mampu memperbarui data, anggaran GIS minim, dan koordinasi BPBD-Bappeda lemah. Isu utamanya adalah?", "Institutional capability: kapasitas organisasi, SDM, anggaran, proses, dan koordinasi untuk menjalankan fungsi spasial.", ["Kualitas legenda peta semata.", "Price floor lahan.", "Barang private.", "Evaluasi impact rumah tangga."], "Kapabilitas institusional menentukan apakah data dan rencana dapat dipelihara, digunakan, dan dikoordinasikan."),
  q("G-P18", "spasial", "Institutional capability improvement", "Untuk memperkuat kemampuan daerah mengelola RDTR digital, langkah paling tepat adalah?", "Membangun SOP pemutakhiran data, pelatihan GIS, tata kelola berbagi data, anggaran rutin, dan mandat koordinasi.", ["Membeli software mahal tanpa operator.", "Menugaskan satu staf tanpa SOP dan anggaran.", "Menyimpan data di komputer pribadi tanpa backup.", "Menghapus metadata agar file ringan."], "Kapabilitas institusional membutuhkan orang, proses, teknologi, pendanaan, dan mandat yang jelas."),
  q("G-P19", "spasial", "IKN", "Pembangunan IKN memicu pertumbuhan wilayah sekitar. Perencana daerah penyangga harus mengantisipasi tekanan permukiman, transportasi, air, dan lingkungan. Pendekatan terbaik adalah?", "Menyelaraskan RTRW/RDTR daerah penyangga dengan rencana IKN, daya dukung lingkungan, konektivitas, dan perlindungan masyarakat lokal.", ["Menunggu seluruh dampak terjadi sebelum membuat rencana.", "Mengabaikan IKN karena berada di wilayah administrasi berbeda.", "Mengubah semua lahan menjadi komersial tanpa kajian.", "Melarang seluruh mobilitas penduduk."], "IKN berdampak lintas wilayah sehingga daerah penyangga perlu integrasi tata ruang, layanan, lingkungan, dan sosial."),
  q("G-P20", "spasial", "PSN", "Sebuah Proyek Strategis Nasional melewati beberapa kabupaten dan membutuhkan sinkronisasi RTRW, pengadaan tanah, serta mitigasi sosial. Peran perencana daerah yang paling tepat adalah?", "Memastikan kesesuaian rencana tata ruang, integrasi program daerah, mitigasi dampak, dan koordinasi lintas kewenangan.", ["Menerbitkan semua izin tanpa memeriksa tata ruang karena status PSN.", "Menolak semua koordinasi karena PSN hanya urusan pusat.", "Menghapus konsultasi publik agar proyek cepat.", "Mengabaikan dampak lokal selama target nasional tercapai."], "PSN tetap membutuhkan sinkronisasi spasial dan sosial; status strategis tidak menghapus prinsip tata ruang, koordinasi, dan mitigasi dampak.")
];

function esc(value) {
  return JSON.stringify(value);
}

function serializeBank(name, bank) {
  let output = `// Bank soal gap UKOM Perencana Ahli Muda - dihasilkan build-gap100.mjs\n`;
  output += `// Jangan edit manual; jalankan: node scripts/build-gap100.mjs\n`;
  output += `const ${name} = [\n`;
  bank.forEach((item, index) => {
    output += "  {\n";
    output += `    id: ${esc(item.id)},\n`;
    output += `    cluster: ${esc(item.cluster)},\n`;
    output += `    level: ${esc(item.level)},\n`;
    output += `    source: ${esc(item.source)},\n`;
    output += `    stem: ${esc(item.stem)},\n`;
    output += "    options: [\n";
    item.options.forEach((option) => {
      output += `      ${esc(option)},\n`;
    });
    output += "    ],\n";
    output += `    answer: ${item.answer},\n`;
    output += `    explain: ${esc(item.explain)},\n`;
    output += `    version: ${item.version}\n`;
    output += `  }${index < bank.length - 1 ? "," : ""}\n`;
  });
  output += "];\n";
  return output;
}

function countBy(items, key) {
  return items.reduce((acc, item) => {
    acc[item[key]] = (acc[item[key]] || 0) + 1;
    return acc;
  }, {});
}

function validateBank(bank) {
  const expectedClusters = { teknis: 26, ekonomi: 29, sosial: 25, spasial: 20 };
  const clusterCounts = countBy(bank, "cluster");
  const ids = new Set();
  const stems = new Set();

  if (bank.length !== 100) throw new Error(`Expected 100 questions, got ${bank.length}`);

  for (const [cluster, expected] of Object.entries(expectedClusters)) {
    if (clusterCounts[cluster] !== expected) {
      throw new Error(`Expected ${expected} ${cluster} questions, got ${clusterCounts[cluster] || 0}`);
    }
  }

  for (const item of bank) {
    if (ids.has(item.id)) throw new Error(`Duplicate id: ${item.id}`);
    if (stems.has(item.stem)) throw new Error(`Duplicate stem: ${item.stem}`);
    if (!["teknis", "ekonomi", "sosial", "spasial"].includes(item.cluster)) throw new Error(`Invalid cluster: ${item.id}`);
    if (!LEVELS.includes(item.level)) throw new Error(`Invalid level: ${item.id}`);
    if (item.source !== "gap") throw new Error(`Invalid source: ${item.id}`);
    if (!Array.isArray(item.options) || item.options.length !== 5) throw new Error(`Invalid options length: ${item.id}`);
    if (!Number.isInteger(item.answer) || item.answer < 0 || item.answer > 4) throw new Error(`Invalid answer: ${item.id}`);
    if (new Set(item.options).size !== 5) throw new Error(`Duplicate option in: ${item.id}`);
    if (!item.options[item.answer]) throw new Error(`Answer points to empty option: ${item.id}`);
    if (!item.explain || item.version !== 1) throw new Error(`Invalid metadata: ${item.id}`);
    ids.add(item.id);
    stems.add(item.stem);
  }

  return clusterCounts;
}

const counts = validateBank(QUESTIONS);
fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
fs.writeFileSync(OUT_PATH, serializeBank("BANK_GAP", QUESTIONS), "utf8");

console.log(`OK: ${OUT_PATH}`);
console.log(`total: ${QUESTIONS.length}`);
console.log(`teknis: ${counts.teknis} | ekonomi: ${counts.ekonomi} | sosial: ${counts.sosial} | spasial: ${counts.spasial}`);
