// Generator bank soal gap UKOM Perencana Ahli Muda batch 2 (100 soal).
// Jalankan dari folder Latihan UKOM: node scripts/build-gap200.mjs
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_PATH = path.join(__dirname, "parts", "gap200.js");
const GAP100_PATH = path.join(__dirname, "parts", "gap100.js");

const LEVELS = ["singkat", "sedang", "panjang", "kasus"];
const EXPECTED_CLUSTERS = { teknis: 26, ekonomi: 29, sosial: 25, spasial: 20 };

function q(id, cluster, level, topic, stem, options, answer, explain) {
  return { id, cluster, level, source: "gap2", topic, stem, options, answer, explain, version: 1 };
}

/** Acak posisi jawaban benar agar tidak terkonsentrasi di opsi A */
function rebalanceAnswers(bank) {
  const pattern = [];
  for (let i = 0; i < 100; i++) pattern.push(i % 5);
  for (let i = pattern.length - 1; i > 0; i--) {
    const j = (i * 17 + 13) % (i + 1);
    [pattern[i], pattern[j]] = [pattern[j], pattern[i]];
  }
  return bank.map((item, idx) => {
    const correctText = item.options[item.answer];
    const others = item.options.filter((_, i) => i !== item.answer);
    const target = pattern[idx];
    const opts = [...others];
    opts.splice(target, 0, correctText);
    return { ...item, options: opts, answer: target };
  });
}

const QUESTIONS = [
  // === TEKNIS (26) ===
  q("G2-T01", "teknis", "kasus", "Permen PPN 3/2011 vs 4/2020", "Seorang pejabat menilai kinerja Perencana Ahli Muda dengan daftar angka kredit lama, sementara unit kepegawaian meminta penyesuaian ke Permen PANRB 4/2020. Sikap analitis yang paling tepat adalah?", ["Tetap memakai seluruh rincian lama tanpa memetakan substansi ke ketentuan terbaru.", "Membandingkan substansi peran perencana dan memakai ketentuan terbaru untuk penilaian jabatan, sambil memastikan transisi administrasi tidak merugikan pegawai.", "Menghapus bukti kerja lama tanpa kajian transisi administrasi.", "Mengubah jabatan perencana menjadi staf umum agar tidak perlu angka kredit.", "Menyerahkan penilaian hanya pada preferensi atasan langsung tanpa pedoman."], 1, "Permen PPN 3/2011 dapat menjadi konteks historis, tetapi penilaian jabatan harus mengikuti kerangka terbaru yang berlaku dan dikelola secara tertib."),
  q("G2-T02", "teknis", "panjang", "Permen PPN 3/2011 vs 4/2020", "Dalam rapat, peserta menyamakan tugas perencana menurut Permen PPN 3/2011 dengan uraian jabatan Permen PANRB 4/2020 tanpa melihat perubahan nomenklatur dan sistem pembinaan. Risiko utama dari cara baca tersebut adalah?", ["Terjadi salah tafsir peran, bukti kerja, dan pembinaan karier karena regulasi lama dan baru dipakai tanpa pemetaan substansi.", "Semua regulasi otomatis batal sehingga tidak perlu pedoman jabatan.", "Perencana hanya boleh mengerjakan kegiatan fisik lapangan.", "Dokumen perencanaan tidak lagi membutuhkan analisis data.", "Penilaian kinerja cukup memakai jumlah halaman laporan."], 0, "Regulasi lama dan baru perlu dibaca secara kontekstual agar substansi tugas, pembinaan, dan bukti kinerja tidak tertukar."),
  q("G2-T03", "teknis", "kasus", "Empat kompetensi applied", "Bappeda meminta Perencana Ahli Muda menguji usulan jalan desa yang populer, tetapi data menunjukkan manfaat ekonomi rendah dan risiko banjir tinggi. Kompetensi teknis yang paling tampak jika ia menyusun alternatif lokasi, membandingkan biaya-manfaat, dan memberi rekomendasi berbasis bukti adalah?", ["Kompetensi protokoler karena mampu mengatur urutan acara musrenbang.", "Kompetensi pengarsipan karena menyimpan dokumen usulan.", "Kompetensi analisis kebijakan dan penyusunan rekomendasi perencanaan.", "Kompetensi pengadaan karena menentukan pemenang kontraktor.", "Kompetensi kehumasan karena menjawab keluhan media sosial."], 2, "Kasus ini menuntut analisis masalah, alternatif, dan rekomendasi, bukan sekadar administrasi atau komunikasi."),
  q("G2-T04", "teknis", "kasus", "Empat kompetensi applied", "Saat indikator kemiskinan daerah memburuk, seorang perencana menggabungkan data DTKS, Podes, dan APBD lalu menemukan bahwa desa terpencil tidak menerima paket layanan lengkap. Tindakan berikutnya yang paling sesuai kompetensi ahli muda adalah?", ["Langsung menyalahkan desa tanpa memeriksa desain program.", "Menyusun analisis kesenjangan sasaran dan rekomendasi integrasi program lintas OPD.", "Menghapus indikator kemiskinan agar capaian terlihat stabil.", "Membuat spanduk motivasi sebagai satu-satunya intervensi.", "Menunda kajian sampai semua data sempurna."], 1, "Perencana ahli muda menggunakan data untuk mengidentifikasi masalah dan merumuskan rekomendasi yang dapat ditindaklanjuti."),
  q("G2-T05", "teknis", "sedang", "Bloom C4/C5 edge", "Peserta ujian diminta memecah rantai sebab-akibat program irigasi, menemukan indikator yang tidak logis, lalu menunjukkan bagian desain yang harus diperbaiki. Level Bloom yang paling dominan adalah?", ["C2, karena hanya memahami definisi irigasi.", "C3, karena sekadar menerapkan rumus volume air.", "C6, karena harus menciptakan teori baru.", "C4, karena menganalisis struktur masalah dan hubungan antarbagian.", "C1, karena hanya mengingat istilah output."], 3, "Memecah struktur logika dan menguji hubungan antarbagian adalah analisis atau C4."),
  q("G2-T06", "teknis", "panjang", "Bloom C4/C5 edge", "Dalam soal lain, peserta diberi dua opsi kebijakan transportasi dengan data biaya, emisi, akses warga miskin, dan risiko fiskal. Ia diminta memilih opsi terbaik dengan kriteria tertimbang. Level Bloom yang paling tepat adalah?", ["C5, karena peserta mengevaluasi dan membuat penilaian berdasarkan kriteria.", "C1, karena tugas terbatas menghafal istilah tanpa evaluasi opsi.", "C2, karena tugas terbatas menjelaskan konsep tanpa memilih opsi terbaik.", "C3, karena tugas menerapkan prosedur tanpa menilai kriteria kebijakan.", "C4, karena tidak ada unsur penilaian pilihan terbaik."], 0, "Memilih opsi terbaik dengan kriteria dan justifikasi merupakan evaluasi atau C5."),
  q("G2-T07", "teknis", "kasus", "PP 39/2023 evaluasi", "Tim pengendalian menemukan program prioritas nasional di daerah tidak mencapai target antara dan ada perbedaan data realisasi antar-OPD. Sesuai semangat evaluasi pembangunan dalam PP 39/2023, langkah paling tepat adalah?", ["Mencatat deviasi sebagai masalah administrasi kecil saja.", "Menggunakan evaluasi untuk menilai capaian, hambatan, dan tindak lanjut perbaikan secara terukur.", "Menunggu akhir RPJMN tanpa koreksi tahunan.", "Menghapus target yang tidak tercapai dari laporan.", "Mengganti semua indikator dengan serapan anggaran."], 1, "Evaluasi pembangunan dipakai untuk mengukur capaian, menjelaskan deviasi, dan mendorong perbaikan pelaksanaan."),
  q("G2-T08", "teknis", "sedang", "PP 39/2023 evaluasi", "Dalam evaluasi semester, perangkat daerah hanya melaporkan foto kegiatan dan SPJ. Informasi minimum yang masih kurang untuk menilai kinerja program adalah?", ["Nama pejabat yang membuka acara.", "Jumlah konsumsi rapat koordinasi.", "Capaian output dan outcome terhadap target, masalah pelaksanaan, serta rencana tindak lanjut.", "Daftar undangan yang tidak hadir.", "Warna desain banner kegiatan."], 2, "Evaluasi memerlukan data capaian terhadap target dan penjelasan deviasi, bukan sekadar bukti aktivitas."),
  q("G2-T09", "teknis", "kasus", "Musrenbang tahapan", "Dalam tahapan musrenbang, kelurahan mengusulkan banyak kegiatan, tetapi sebagian tidak sesuai prioritas RKPD dan kewenangan daerah. Peran perencana yang paling tepat sebelum forum kabupaten adalah?", ["Menerima seluruh usulan agar tidak ada warga kecewa.", "Menghapus semua usulan masyarakat karena mengganggu program OPD.", "Memverifikasi kesesuaian usulan dengan masalah, kewenangan, prioritas, pagu indikatif, dan data teknis.", "Menyerahkan keputusan ke kontraktor pembangunan.", "Mengubah usulan menjadi belanja pegawai agar mudah diserap."], 2, "Usulan musrenbang perlu disaring secara teknokratis dan partisipatif agar selaras dengan kewenangan serta prioritas."),
  q("G2-T10", "teknis", "panjang", "Musrenbang tahapan", "Pada forum perangkat daerah, dua OPD mengklaim kegiatan pemberdayaan UMKM yang sama. Agar musrenbang tidak menjadi daftar belanja ganda, keluaran yang harus dihasilkan adalah?", ["Daftar semua usulan tanpa penanggung jawab.", "Matriks kesepakatan program, lokasi, sasaran, indikator, penanggung jawab, dan sumber pendanaan.", "Notulen singkat tanpa keputusan.", "Surat larangan usulan baru dari masyarakat.", "Poster prioritas daerah."], 1, "Forum perangkat daerah harus menajamkan program dan membagi peran agar tidak terjadi duplikasi kegiatan."),
  q("G2-T11", "teknis", "kasus", "RKP sinkronisasi", "Pemerintah daerah menyusun RKPD dengan prioritas pengentasan kemiskinan, tetapi RKP tahun berjalan menekankan stunting, ketahanan pangan, dan produktivitas. Sinkronisasi yang paling tepat adalah?", ["Menyalin semua program pusat tanpa melihat masalah daerah.", "Menolak prioritas nasional karena RKPD sepenuhnya otonom.", "Mencari irisan sasaran, indikator, lokasi prioritas, dan dukungan pendanaan agar prioritas nasional dan daerah saling menguatkan.", "Menghapus program kemiskinan dari daerah.", "Menyusun RKPD setelah APBD selesai."], 2, "Sinkronisasi RKP-RKPD bukan sekadar menyalin, tetapi menyelaraskan prioritas nasional dengan kebutuhan dan kewenangan daerah."),
  q("G2-T12", "teknis", "sedang", "RKP sinkronisasi", "Jika kegiatan daerah tidak tercantum sebagai prioritas nasional tetapi langsung menjawab masalah mendesak daerah, bagaimana perencana sebaiknya menempatkannya dalam RKPD?", ["Tetap dapat diusulkan jika berbasis data, sesuai kewenangan, mendukung sasaran daerah, dan tidak bertentangan dengan prioritas nasional.", "Wajib dihapus karena semua kegiatan harus identik dengan RKP.", "Dimasukkan tanpa indikator agar fleksibel.", "Dipindahkan ke belanja tidak terduga tanpa kajian.", "Disembunyikan dari forum publik."], 0, "Otonomi daerah tetap memberi ruang prioritas lokal, selama konsisten dengan kerangka pembangunan dan bukti kebutuhan."),
  q("G2-T13", "teknis", "kasus", "Ego dalam revisi RKPD", "Saat revisi RKPD, beberapa OPD meminta tambahan kegiatan sendiri-sendiri dengan alasan arahan pimpinan, tetapi tidak menunjukkan perubahan asumsi makro atau kebutuhan mendesak. Ini menunjukkan risiko apa?", ["Ego sektoral yang memanfaatkan revisi untuk memasukkan agenda OPD tanpa dasar perubahan kebijakan yang jelas.", "Peningkatan akuntabilitas karena semua OPD bebas menambah kegiatan.", "Kegagalan pasar barang publik murni.", "Evaluasi ex post yang terlalu ketat.", "Kelebihan kapasitas fiskal daerah."], 0, "Revisi RKPD harus berbasis perubahan asumsi atau kebutuhan prioritas, bukan sekadar kanal tambahan agenda sektoral."),
  q("G2-T14", "teknis", "panjang", "Ego dalam revisi RKPD", "Kabupaten hulu menolak memasukkan kegiatan konservasi daerah aliran sungai dalam perubahan RKPD karena manfaat banjir lebih terasa di kota hilir. Instrumen perencanaan yang paling relevan untuk mengurangi ego daerah adalah?", ["Menunda kegiatan sampai kota hilir membayar seluruh biaya tanpa kesepakatan.", "Menyusun kerja sama antardaerah dengan pembagian manfaat-biaya, indikator lintas wilayah, dan dukungan provinsi.", "Mengubah batas administrasi secara sepihak.", "Menghapus data banjir lintas wilayah.", "Membiarkan setiap daerah menyusun program drainase lokal saja."], 1, "Masalah eksternalitas lintas wilayah membutuhkan koordinasi dan pembagian manfaat-biaya antardaerah."),
  q("G2-T15", "teknis", "kasus", "POIC failure cases", "Program satu data daerah gagal karena rencana sudah ada, tetapi tidak ada pembagian steward data, jadwal pemutakhiran, atau forum penyelesaian perbedaan angka. Fungsi POIC yang paling lemah adalah?", ["Planning karena tujuan belum pernah ditulis sama sekali.", "Organizing karena peran, struktur koordinasi, dan tanggung jawab data tidak dibentuk.", "Actuating karena kegiatan lapangan terlalu banyak.", "Controlling karena target selalu melampaui realisasi.", "Budgeting karena semua anggaran habis."], 1, "Kegagalan membagi peran dan alur kerja menunjukkan masalah organizing."),
  q("G2-T16", "teknis", "sedang", "POIC failure cases", "Sebuah program padat karya memiliki tim lengkap dan SOP, tetapi kepala bidang tidak pernah menggerakkan pelaksana, jadwal sosialisasi mundur, dan kelompok sasaran tidak dihubungi. Fungsi POIC yang paling bermasalah adalah?", ["Actuating, karena pelaksanaan dan penggerakan sumber daya tidak berjalan.", "Planning, karena tidak ada dokumen sama sekali.", "Organizing, karena struktur pasti tidak ada.", "Controlling, karena evaluasi akhir terlalu rinci.", "Forecasting, karena harga bahan berubah."], 0, "Actuating berkaitan dengan menggerakkan orang dan melaksanakan kegiatan sesuai rencana."),
  q("G2-T17", "teknis", "panjang", "POIC failure cases", "Pada akhir triwulan, realisasi fisik irigasi turun jauh dari target, tetapi manajer program hanya menunggu laporan akhir tahun. Fungsi POIC yang gagal diterapkan adalah?", ["Planning karena target terlalu jelas.", "Organizing karena semua staf punya tugas.", "Actuating karena kontrak sudah berjalan.", "Controlling karena deviasi tidak dipantau dan tidak ada koreksi tepat waktu.", "Staffing karena pegawai terlalu banyak."], 3, "Controlling menuntut pemantauan deviasi dan tindakan korektif saat program berjalan."),
  q("G2-T18", "teknis", "kasus", "Logframe", "Dalam logframe program sanitasi, kegiatan pembangunan septic tank komunal sudah selesai, tetapi perilaku buang air besar sembarangan belum berubah. Bagian logika yang perlu diuji terutama adalah?", ["Apakah input kas daerah cukup untuk membayar honor rapat.", "Apakah output fisik cukup terhubung dengan outcome perubahan perilaku melalui edukasi, operasi, dan pemeliharaan.", "Apakah judul program sudah panjang.", "Apakah semua foto kegiatan berwarna.", "Apakah jumlah halaman laporan meningkat."], 1, "Logframe menguji hubungan kegiatan-output-outcome serta asumsi yang diperlukan agar hasil terjadi."),
  q("G2-T19", "teknis", "panjang", "Logframe", "Sebuah logframe mencantumkan tujuan 'petani sejahtera', output 'pelatihan 20 kali', indikator outcome 'jumlah peserta hadir', dan asumsi 'cuaca baik'. Kelemahan paling substantif adalah?", ["Indikator outcome masih berupa output kehadiran sehingga belum mengukur perubahan kapasitas atau pendapatan petani.", "Asumsi cuaca selalu tidak relevan untuk pertanian.", "Pelatihan tidak boleh menjadi kegiatan program.", "Tujuan petani sejahtera terlalu sempit untuk daerah.", "Logframe tidak boleh memuat asumsi."], 0, "Indikator outcome harus menggambarkan perubahan pada sasaran, bukan hanya aktivitas atau kehadiran."),
  q("G2-T20", "teknis", "kasus", "5M market", "Program olahan ikan memiliki mesin, pelatih, modal, dan SOP produksi, tetapi produk menumpuk karena kemasan tidak sesuai selera pembeli dan kanal pemasaran lemah. Dalam 5M, gap utama berada pada?", ["Man karena jumlah pegawai pemerintah kurang.", "Money karena semua masalah selalu anggaran.", "Machine karena mesin pasti rusak.", "Market karena kebutuhan pembeli, akses pasar, dan informasi permintaan belum dipenuhi.", "Method karena tidak ada prosedur produksi sama sekali."], 3, "Aspek market menilai permintaan, pelanggan, saluran pemasaran, dan informasi pasar."),
  q("G2-T21", "teknis", "sedang", "5M market", "Ketika menganalisis kesiapan sentra kopi, perencana menemukan petani punya lahan dan alat, tetapi tidak tahu standar mutu roaster dan jadwal permintaan. Rekomendasi 5M yang paling tepat adalah?", ["Memperbaiki aspek market melalui riset pembeli, kontrak pemasaran, standardisasi mutu, dan informasi harga.", "Membeli gedung kantor baru untuk sekretariat.", "Mengurangi pelatihan mutu karena pasar tidak penting.", "Mengganti semua varietas tanpa uji coba.", "Menghapus indikator penjualan."], 0, "Kesenjangan utama adalah hubungan dengan pasar dan standar permintaan, sehingga intervensi harus menutup gap market."),
  q("G2-T22", "teknis", "panjang", "SMART kecuali", "Indikator 'jumlah UMKM naik dari 1.000 menjadi 1.200 pada 2026 melalui pendampingan legalitas' sudah spesifik, terukur, relevan, dan berbatas waktu. Unsur SMART yang masih perlu diuji paling kuat adalah?", ["Specific, karena angka dan sasaran belum ada.", "Measurable, karena tidak ada satuan.", "Achievable, karena perlu dibandingkan dengan baseline, kapasitas pendamping, dan tren usaha.", "Time-bound, karena tahun tidak disebutkan.", "Relevant, karena UMKM tidak terkait ekonomi daerah."], 2, "Achievable harus diuji terhadap kapasitas, tren, dan sumber daya, meski unsur lain sudah tampak."),
  q("G2-T23", "teknis", "kasus", "SMART kecuali", "Manakah rumusan yang paling jelas BUKAN indikator SMART untuk program pengurangan sampah?", ["Persentase sampah terpilah di sumber naik dari 18% menjadi 40% pada akhir 2026.", "Volume sampah ke TPA turun 15% dalam dua tahun di tiga kecamatan prioritas.", "Jumlah bank sampah aktif meningkat dari 35 menjadi 60 unit pada 2025.", "Persentase rumah tangga yang mendapat layanan angkut sampah naik menjadi 90% pada 2026.", "Masyarakat semakin sadar kebersihan secepat mungkin."], 4, "Rumusan tersebut tidak spesifik, tidak terukur, dan tidak memiliki batas waktu yang jelas."),
  q("G2-T24", "teknis", "panjang", "PP 39/2023 evaluasi", "Dalam evaluasi program prioritas, capaian output tinggi tetapi outcome tidak bergerak. Pertanyaan evaluatif yang paling tajam adalah?", ["Apakah kegiatan menghasilkan output yang tepat, menjangkau sasaran yang benar, dan cukup kuat untuk memengaruhi outcome.", "Apakah laporan memiliki banyak lampiran foto.", "Apakah semua pegawai sudah menandatangani daftar hadir.", "Apakah nama program terdengar menarik.", "Apakah serapan anggaran bisa menjadi satu-satunya indikator."], 0, "Evaluasi kinerja perlu menguji rantai output-outcome dan ketepatan sasaran."),
  q("G2-T25", "teknis", "kasus", "Musrenbang tahapan", "Hasil musrenbang kecamatan memuat usulan jalan usaha tani di kawasan yang menurut RTRW masuk zona lindung. Respons perencana yang paling tepat adalah?", ["Meloloskan usulan karena didukung banyak peserta.", "Menolak tanpa memberi penjelasan teknis.", "Meminta penyesuaian lokasi atau desain berdasarkan tata ruang, fungsi lindung, dan alternatif kebutuhan akses.", "Mengubah peta tata ruang di notulen musrenbang.", "Menyerahkan langsung ke kontraktor."], 2, "Musrenbang tetap harus konsisten dengan tata ruang dan mencari alternatif yang menjawab kebutuhan tanpa melanggar fungsi lindung."),
  q("G2-T26", "teknis", "sedang", "Bloom C4/C5 edge", "Sebuah soal meminta peserta mengurutkan penyebab rendahnya capaian program dari yang paling berpengaruh berdasarkan bukti, lalu mempertahankan argumennya. Level Bloom yang paling mendekati adalah?", ["C1 karena peserta hanya menyebut istilah.", "C2 karena hanya menerjemahkan data.", "C3 karena memakai rumus baku.", "C5 karena ada penilaian prioritas berbasis kriteria dan argumen.", "C6 karena tugas menciptakan model baru tanpa menilai opsi yang ada."], 3, "Menilai prioritas penyebab dengan bukti dan argumen berada pada evaluasi atau C5."),

  // === EKONOMI (29) ===
  q("G2-E01", "ekonomi", "kasus", "Kegagalan pasar mixed cases", "Pasar kredit UMKM macet karena bank sulit membedakan usaha layak dan berisiko, sementara pelaku usaha tidak punya agunan. Kegagalan pasar yang paling dominan adalah?", ["Eksternalitas negatif dari polusi pabrik.", "Barang publik murni karena kredit tidak rival.", "Asimetri informasi dan adverse selection dalam pembiayaan.", "Price floor yang menciptakan surplus kredit.", "Monopoli alamiah jaringan listrik."], 2, "Pemberi kredit tidak memiliki informasi risiko yang seimbang sehingga pasar dapat menolak peminjam layak."),
  q("G2-E02", "ekonomi", "panjang", "Kegagalan pasar mixed cases", "Pemerintah ingin mengembangkan kawasan industri halal, tetapi investor menunggu kepastian pemasok, pemasok menunggu pembeli, dan lembaga sertifikasi belum siap. Ini terutama menggambarkan?", ["Kegagalan koordinasi yang dapat diatasi dengan fasilitasi rantai nilai, standar, dan informasi pasar.", "Barang private murni sehingga pemerintah tidak boleh terlibat.", "Price ceiling yang menyebabkan surplus barang.", "Giffen good karena permintaan naik saat harga naik.", "Phillips curve jangka pendek."], 0, "Keputusan para pelaku saling bergantung sehingga pasar tidak bergerak tanpa koordinasi awal."),
  q("G2-E03", "ekonomi", "kasus", "Kegagalan pasar mixed cases", "Di kawasan wisata, pelaku usaha membuang sampah ke pantai karena biaya pembersihan ditanggung masyarakat dan pemerintah. Intervensi yang paling tepat adalah?", ["Subsidi sampah tanpa kewajiban perubahan perilaku.", "Standar pengelolaan limbah, retribusi atau denda berbasis pencemar, dan pengawasan kolektif.", "Menghapus seluruh usaha wisata.", "Menetapkan harga maksimum kamar hotel.", "Mencetak brosur tanpa penegakan aturan."], 1, "Biaya sosial tidak masuk ke keputusan usaha, sehingga perlu internalisasi eksternalitas negatif."),
  q("G2-E04", "ekonomi", "sedang", "Merit goods", "Pendidikan dasar sering dikategorikan sebagai merit good. Alasan kebijakan publik yang paling tepat adalah?", ["Manfaat sosial pendidikan lebih besar dari manfaat privat dan masyarakat dapat mengonsumsi terlalu sedikit jika dibiarkan murni pasar.", "Pendidikan selalu non-rival dan mustahil mengecualikan siswa.", "Pendidikan hanya bermanfaat untuk sekolah swasta.", "Pendidikan adalah barang inferior yang harus dibatasi.", "Pendidikan tidak memiliki dampak lintas generasi."], 0, "Merit good layak didorong negara karena manfaat sosial dan jangka panjangnya sering kurang dihargai individu."),
  q("G2-E05", "ekonomi", "kasus", "Merit goods", "Vaksinasi anak di daerah terpencil rendah karena keluarga meremehkan risiko penyakit dan biaya perjalanan tinggi. Kebijakan merit good yang paling tepat adalah?", ["Menunggu permintaan pasar naik sendiri.", "Menyediakan layanan jemput bola, subsidi biaya akses, edukasi risiko, dan pencatatan sasaran.", "Menjual vaksin hanya kepada keluarga mampu.", "Menurunkan standar keamanan vaksin.", "Menghapus kampanye karena pilihan individu mutlak."], 1, "Untuk merit good, pemerintah dapat mengatasi under-consumption melalui penyediaan, subsidi, dan informasi."),
  q("G2-E06", "ekonomi", "panjang", "Giffen/normal", "Ketika harga beras kualitas rendah naik, rumah tangga sangat miskin justru membeli lebih banyak beras itu dan mengurangi lauk karena pendapatan riil turun. Ini contoh kemungkinan?", ["Barang normal karena pendapatan naik.", "Barang mewah karena elastisitas pendapatan tinggi.", "Barang Giffen pada kondisi sangat khusus.", "Barang publik karena dikonsumsi banyak orang.", "Barang club karena bisa dipungut tarif."], 2, "Barang Giffen dapat menunjukkan permintaan naik saat harga naik karena efek pendapatan mengalahkan efek substitusi."),
  q("G2-E07", "ekonomi", "sedang", "Giffen/normal", "Jika pendapatan keluarga naik dan konsumsi telur, susu, serta transportasi lebih nyaman ikut naik, barang tersebut paling mungkin disebut?", ["Barang inferior.", "Barang normal.", "Barang Giffen.", "Barang publik murni.", "Common-pool resource."], 1, "Barang normal dikonsumsi lebih banyak ketika pendapatan meningkat."),
  q("G2-E08", "ekonomi", "kasus", "DLQ", "Analisis Dynamic Location Quotient menunjukkan sektor pengolahan makanan memiliki DLQ lebih dari 1 meski LQ saat ini masih di bawah 1. Interpretasi paling hati-hati adalah?", ["Sektor belum basis saat ini, tetapi punya kecenderungan tumbuh lebih cepat dan berpotensi menjadi basis.", "Sektor pasti sudah basis dan tidak perlu dukungan.", "Sektor harus ditutup karena DLQ lebih dari 1.", "Sektor hanya cocok untuk belanja aparatur.", "DLQ tidak terkait dinamika pertumbuhan sektor."], 0, "DLQ memberi sinyal dinamika perubahan relatif, bukan hanya posisi basis saat ini."),
  q("G2-E09", "ekonomi", "panjang", "DLQ", "Jika sektor perikanan memiliki LQ tinggi tetapi DLQ di bawah 1 selama beberapa tahun, rekomendasi perencana yang paling tepat adalah?", ["Menganggap sektor pasti tumbuh cepat selamanya.", "Mewaspadai pelemahan daya saing relatif dan menguji faktor produktivitas, pasar, serta keberlanjutan stok.", "Menghapus seluruh program perikanan tanpa analisis.", "Menjadikan DLQ sebagai indikator kemiskinan rumah tangga.", "Mengabaikan tren karena LQ cukup satu kali."], 1, "LQ tinggi menunjukkan basis saat ini, tetapi DLQ rendah memberi peringatan dinamika relatif melemah."),
  q("G2-E10", "ekonomi", "sedang", "Shift-share intro", "Dalam shift-share, pertumbuhan sektor daerah dipisah menjadi pengaruh pertumbuhan wilayah acuan, struktur industri, dan daya saing lokal. Kegunaan utamanya adalah?", ["Menentukan warna peta administrasi.", "Membedakan apakah pertumbuhan sektor karena tren umum, komposisi sektor, atau keunggulan kompetitif daerah.", "Menghitung angka kemiskinan individu.", "Menetapkan harga maksimum pasar.", "Mengukur kepuasan layanan publik."], 1, "Shift-share membantu mengurai sumber pertumbuhan sektor secara relatif."),
  q("G2-E11", "ekonomi", "kasus", "Shift-share intro", "Sektor akomodasi daerah tumbuh tinggi, tetapi provinsi secara umum juga mengalami boom pariwisata. Analisis shift-share diperlukan agar perencana tidak keliru menyimpulkan bahwa?", ["Seluruh pertumbuhan sektor otomatis dianggap unggulan lokal tanpa analisis komponen.", "Pertumbuhan pariwisata tidak terkait tren provinsi sama sekali.", "Data sektoral tidak bisa dibandingkan.", "Pertumbuhan tinggi selalu berarti ketimpangan turun.", "Akomodasi adalah barang publik."], 0, "Shift-share memisahkan efek tren umum dari keunggulan lokal."),
  q("G2-E12", "ekonomi", "panjang", "ICOR interpret", "Sebuah daerah memiliki ICOR meningkat dari 4 menjadi 7, sementara pertumbuhan ekonomi melambat. Interpretasi kebijakan yang paling masuk akal adalah?", ["Investasi makin efisien karena butuh lebih banyak modal untuk pertumbuhan yang sama.", "Efisiensi investasi menurun sehingga perlu menilai kualitas proyek, waktu konstruksi, dan hambatan produktivitas.", "ICOR tidak pernah terkait produktivitas modal.", "Pertumbuhan pasti akan melonjak tanpa perbaikan.", "Belanja modal harus dihentikan permanen."], 1, "ICOR lebih tinggi biasanya menunjukkan kebutuhan investasi lebih besar untuk menghasilkan tambahan output yang sama."),
  q("G2-E13", "ekonomi", "sedang", "ICOR interpret", "Jika ICOR rendah tetapi layanan dasar belum membaik, kehati-hatian analitis yang diperlukan adalah?", ["Langsung menyimpulkan semua investasi sudah inklusif.", "Memeriksa apakah pertumbuhan terkonsentrasi pada sektor tertentu dan tidak otomatis meningkatkan kesejahteraan luas.", "Mengabaikan indikator sosial karena ICOR cukup.", "Menurunkan seluruh pajak tanpa kajian.", "Menghapus belanja kesehatan."], 1, "Efisiensi modal secara agregat tidak selalu berarti manfaat pembangunan terdistribusi merata."),
  q("G2-E14", "ekonomi", "kasus", "Gini policy", "Rasio Gini daerah naik meski PDRB tumbuh karena pekerjaan baru terkonsentrasi pada tenaga berpendidikan tinggi. Paket kebijakan yang paling sesuai adalah?", ["Meningkatkan akses pendidikan dan pelatihan, perlindungan sosial adaptif, serta dukungan UMKM produktif.", "Menaikkan PDRB saja tanpa melihat distribusi.", "Menghapus data ketimpangan agar investasi masuk.", "Membatasi sekolah hanya untuk kelompok kaya.", "Menetapkan semua harga sama di seluruh pasar."], 0, "Ketimpangan membutuhkan intervensi pada akses kemampuan, kesempatan kerja, dan perlindungan kelompok rentan."),
  q("G2-E15", "ekonomi", "panjang", "Gini policy", "Dua kecamatan memiliki kemiskinan sama, tetapi kecamatan A memiliki Gini jauh lebih tinggi. Implikasi perencanaan yang paling tepat adalah?", ["A cukup diberi program rata-rata tanpa targeting.", "A membutuhkan analisis distribusi manfaat dan desain program yang menjangkau kelompok terbawah, bukan hanya menaikkan rata-rata pendapatan.", "Gini tinggi berarti semua orang miskin sama rata.", "Kecamatan B harus dihapus dari prioritas.", "Ketimpangan tidak relevan untuk kebijakan daerah."], 1, "Gini membantu melihat sebaran pendapatan sehingga program perlu menarget kelompok yang tertinggal."),
  q("G2-E16", "ekonomi", "kasus", "Phillips policy tradeoff", "Inflasi pangan naik tajam, tetapi pengangguran terbuka juga tinggi. Dilema kebijakan yang paling sesuai dengan trade-off Phillips jangka pendek adalah?", ["Menekan inflasi terlalu agresif dapat memperlambat kegiatan ekonomi, tetapi membiarkan inflasi tinggi merusak daya beli.", "Inflasi dan pengangguran selalu turun bersamaan tanpa biaya.", "Pemerintah daerah dapat mencetak uang sendiri untuk semua masalah.", "Pengangguran tidak dipengaruhi kondisi permintaan.", "Harga pangan tidak terkait kesejahteraan."], 0, "Dalam jangka pendek terdapat dilema antara stabilisasi harga dan aktivitas ekonomi, meski tidak mekanis dalam semua situasi."),
  q("G2-E17", "ekonomi", "sedang", "Phillips policy tradeoff", "Respons daerah yang paling proporsional saat inflasi cabai tinggi karena pasokan terganggu adalah?", ["Memperbaiki distribusi, operasi pasar terbatas, informasi harga, dan dukungan produksi tanpa mematikan insentif petani.", "Membekukan semua harga selamanya.", "Melarang petani menjual ke luar daerah tanpa kajian.", "Menghapus survei harga.", "Menurunkan upah semua pekerja."], 0, "Inflasi pasokan lebih tepat direspons dengan perbaikan distribusi dan pasokan, bukan kontrol harga ekstrem."),
  q("G2-E18", "ekonomi", "panjang", "Chenery applied", "Daerah agraris mulai mengalami kenaikan produktivitas pertanian, tumbuhnya agroindustri, urbanisasi kota kecil, dan peningkatan pendidikan tenaga kerja. Dalam kerangka Chenery, gejala ini terutama menunjukkan?", ["Transformasi struktural melalui akumulasi, realokasi sumber daya, dan perubahan permintaan.", "Kegagalan pemerintah karena semua perubahan dilarang.", "Price ceiling pasar tenaga kerja.", "Barang publik murni tanpa rivalitas.", "Tragedy of the commons."], 0, "Chenery menekankan pola transformasi seiring pembangunan: akumulasi, realokasi, urbanisasi, dan perubahan struktur permintaan."),
  q("G2-E19", "ekonomi", "kasus", "Chenery applied", "Jika industrialisasi daerah terjadi tanpa peningkatan keterampilan lokal, banyak tenaga kerja hanya masuk pekerjaan informal rendah upah. Pelajaran Chenery yang relevan adalah?", ["Transformasi sektor perlu diikuti akumulasi modal manusia agar perubahan struktur menghasilkan produktivitas dan kesejahteraan.", "Pendidikan tidak berhubungan dengan industrialisasi.", "Pekerja informal harus segera dipindah ke sektor formal tanpa transisi.", "PDRB saja dianggap cukup tanpa indikator kesejahteraan tenaga kerja.", "Urbanisasi selalu harus dihentikan."], 0, "Akumulasi modal manusia penting agar transformasi struktural tidak meninggalkan tenaga kerja lokal."),
  q("G2-E20", "ekonomi", "sedang", "Klassen policy", "Daerah maju tetapi tertekan dalam tipologi Klassen paling membutuhkan strategi apa?", ["Menjaga sektor lama sambil melakukan diversifikasi, inovasi, dan peningkatan produktivitas agar pertumbuhan pulih.", "Fokus hanya pada bantuan darurat karena semua indikator rendah.", "Mengabaikan sektor basis karena pendapatan tinggi.", "Menghapus investasi baru.", "Menurunkan kualitas layanan dasar."], 0, "Daerah maju tertekan memiliki pendapatan relatif tinggi tetapi pertumbuhan rendah, sehingga perlu pembaruan mesin pertumbuhan."),
  q("G2-E21", "ekonomi", "kasus", "Klassen policy", "Kabupaten dengan pertumbuhan tinggi tetapi PDRB per kapita masih rendah sebaiknya tidak hanya mengejar proyek besar, tetapi juga?", ["Mengunci semua lahan untuk spekulasi.", "Memperkuat kualitas pekerjaan, konektivitas, SDM, dan linkage lokal agar pertumbuhan mengejar pendapatan warga.", "Mengurangi data sektoral agar cepat mengambil keputusan.", "Menolak investasi karena statusnya belum maju.", "Menaikkan harga kebutuhan pokok."], 1, "Daerah berkembang cepat perlu memastikan pertumbuhan berujung pada peningkatan pendapatan dan produktivitas lokal."),
  q("G2-E22", "ekonomi", "panjang", "Government failure corruption", "Bantuan alat pertanian diberikan melalui kontraktor yang dipilih karena kedekatan politik. Alat tidak sesuai kebutuhan petani dan harga jauh di atas pasar. Ini contoh?", ["Government failure akibat korupsi, rent seeking, dan desain pengadaan yang tidak berbasis kebutuhan.", "Eksternalitas positif yang berhasil.", "Barang publik murni karena alat dipakai individu.", "Giffen good karena harga naik.", "Kegagalan koordinasi tanpa unsur tata kelola."], 0, "Korupsi dan rente dapat membuat intervensi pemerintah lebih mahal dan tidak efektif."),
  q("G2-E23", "ekonomi", "kasus", "Government failure corruption", "Regulasi pasar tradisional dibuat untuk melindungi pedagang kecil, tetapi oknum menarik biaya informal untuk mendapatkan kios. Evaluasi kebijakan yang paling tepat adalah?", ["Regulasi perlu diaudit karena tujuan perlindungan berubah menjadi rente dan eksklusi akses.", "Biaya informal selalu meningkatkan efisiensi.", "Pedagang kecil tidak boleh dilibatkan.", "Semua pasar harus ditutup.", "Masalah tersebut murni akibat permintaan konsumen."], 0, "Kebijakan publik dapat gagal ketika implementasi membuka pungli dan menghambat kelompok sasaran."),
  q("G2-E24", "ekonomi", "sedang", "Floor/ceiling combined", "Pemerintah menetapkan harga dasar gabah dan harga eceran tertinggi beras secara bersamaan. Risiko desain yang harus diantisipasi adalah?", ["Selisih insentif produsen dan harga konsumen dapat menekan margin, menciptakan kekurangan, atau membutuhkan subsidi dan stok penyangga.", "Kombinasi kebijakan harga dianggap bebas distorsi tanpa subsidi atau stok.", "Harga dasar selalu menurunkan produksi.", "Harga maksimum selalu menciptakan surplus konsumen tanpa kelangkaan.", "Tidak perlu data pasokan."], 0, "Kombinasi floor dan ceiling perlu dukungan stok, subsidi, dan logistik agar tidak menimbulkan distorsi baru."),
  q("G2-E25", "ekonomi", "panjang", "Floor/ceiling combined", "Jika upah minimum ditetapkan naik tajam saat produktivitas UMKM stagnan, sementara harga produk UMKM dibatasi agar inflasi rendah, dampak yang mungkin muncul adalah?", ["Tekanan biaya pada usaha kecil, pengurangan jam kerja, atau pasar informal jika tidak ada dukungan produktivitas.", "UMKM dianggap pasti menyerap tenaga kerja meski margin tertekan.", "Tidak ada perubahan insentif usaha.", "Produktivitas pasti naik tanpa pelatihan.", "Harga produk selalu bebas naik."], 0, "Price floor pada upah dan pembatasan harga produk dapat menekan margin usaha bila produktivitas tidak meningkat."),
  q("G2-E26", "ekonomi", "kasus", "Kegagalan pasar mixed cases", "Sebuah aplikasi transportasi menjadi satu-satunya penghubung desa wisata dengan pasar setelah pesaing keluar. Tarif naik dan pengemudi sulit berpindah platform. Kegagalan pasar yang perlu diperhatikan adalah?", ["Monopoli atau kekuatan pasar platform yang membutuhkan pengawasan persaingan dan perlindungan pengguna.", "Barang publik murni.", "Eksternalitas positif vaksin.", "DLQ lebih dari satu.", "Price floor gabah."], 0, "Kekuatan pasar dapat menaikkan harga dan menurunkan kesejahteraan ketika pilihan pengguna terbatas."),
  q("G2-E27", "ekonomi", "sedang", "Merit goods", "Mengapa pemerintah tidak cukup hanya memberi brosur tentang gizi untuk mengatasi anemia remaja putri?", ["Karena anemia tidak berhubungan dengan kebijakan publik.", "Karena semua remaja pasti sudah punya informasi sempurna.", "Karena brosur selalu lebih mahal dari layanan.", "Karena gizi adalah common-pool resource.", "Karena informasi penting, tetapi konsumsi tablet tambah darah, akses layanan, norma sosial, dan pemantauan sekolah juga memengaruhi konsumsi merit good."], 4, "Merit good sering membutuhkan kombinasi informasi, penyediaan, akses, dan pemantauan."),
  q("G2-E28", "ekonomi", "kasus", "ICOR interpret", "Investasi jalan kawasan industri besar telah selesai, tetapi pabrik belum masuk karena listrik dan kepastian lahan belum siap. Dampaknya terhadap ICOR jangka pendek kemungkinan?", ["ICOR dapat memburuk karena investasi belum segera menghasilkan tambahan output.", "ICOR pasti turun tajam karena jalan selalu langsung produktif.", "ICOR tidak bisa dihitung untuk investasi fisik.", "ICOR hanya mengukur kemiskinan.", "ICOR membaik jika serapan anggaran tinggi."], 0, "Output tertunda membuat tambahan modal belum menghasilkan pertumbuhan yang sepadan."),
  q("G2-E29", "ekonomi", "panjang", "Gini policy", "Program bantuan modal UMKM ternyata lebih banyak diterima pelaku usaha yang sudah kuat karena mampu memenuhi syarat administrasi. Dampak terhadap ketimpangan dan koreksi yang tepat adalah?", ["Dapat memperlebar ketimpangan; perlu penyederhanaan akses, pendampingan kelompok rentan, dan targeting berbasis data.", "Program UMKM dianggap otomatis meratakan distribusi pendapatan.", "Seleksi administratif dianggap netral tanpa verifikasi penerima rentan.", "Hanya perlu menaikkan bunga pinjaman.", "Menghapus semua pelaporan penerima."], 0, "Program ekonomi inklusif harus memeriksa siapa yang benar-benar mampu mengakses manfaat."),

  // === SOSIAL (25) ===
  q("G2-S01", "sosial", "kasus", "SIPD Renja-RKPD", "Renja OPD mengusulkan kegiatan pelatihan 1.000 pemuda, tetapi RKPD menargetkan penurunan pengangguran muda di tiga kecamatan industri. Konsistensi SIPD yang perlu diperbaiki adalah?", ["Mengaitkan kegiatan Renja dengan sasaran RKPD, lokasi prioritas, indikator hasil kerja, dan target penerima manfaat.", "Menghapus target RKPD agar kegiatan OPD bebas.", "Mengisi semua kolom dengan narasi umum.", "Mengganti indikator menjadi jumlah rapat internal.", "Menyamakan semua kecamatan tanpa data."], 0, "Renja harus menurunkan prioritas RKPD ke kegiatan, lokasi, sasaran, dan indikator yang konsisten."),
  q("G2-S02", "sosial", "panjang", "SIPD Renja-RKPD", "Dalam SIPD, satu kegiatan Renja punya indikator output 'jumlah paket bantuan', tetapi tidak terhubung dengan indikator RKPD tentang keluarga miskin yang keluar dari kemiskinan ekstrem. Tindakan perencana adalah?", ["Menambahkan atau memperjelas indikator kinerja yang menjembatani bantuan dengan perubahan kondisi keluarga sasaran.", "Menghapus indikator RKPD karena sulit.", "Menilai cukup dari jumlah paket saja.", "Memecah kegiatan agar lebih banyak nama program.", "Mengubah sasaran menjadi seluruh penduduk."], 0, "Konsistensi indikator diperlukan agar output kegiatan dapat ditelusuri terhadap outcome RKPD."),
  q("G2-S03", "sosial", "sedang", "IKU daerah", "IKU kepala daerah sebaiknya dipilih dari indikator yang?", ["Mewakili tujuan strategis, dapat diukur berkala, relevan dengan kewenangan, dan memengaruhi akuntabilitas kinerja utama.", "Paling mudah dinaikkan dengan menambah rapat.", "Hanya mengukur jumlah surat masuk.", "Tidak perlu baseline dan target.", "Tidak diketahui perangkat daerah mana pun."], 0, "IKU harus menunjukkan keberhasilan strategis, bukan sekadar aktivitas administratif."),
  q("G2-S04", "sosial", "kasus", "IKU daerah", "Jika visi daerah adalah kota inklusif, indikator mana yang paling layak menjadi IKU dibanding sekadar output?", ["Jumlah seminar inklusi yang dilakukan.", "Persentase fasilitas publik utama yang memenuhi standar aksesibilitas dan layanan inklusif.", "Jumlah spanduk kampanye kota inklusif.", "Jumlah undangan rapat lintas OPD.", "Jumlah dokumen paparan kepala dinas."], 1, "IKU perlu menangkap perubahan layanan strategis yang dirasakan publik."),
  q("G2-S05", "sosial", "panjang", "Stakeholder conflict", "Rencana relokasi pasar ditolak pedagang lama, didukung pengembang, dan didorong pemda karena alasan kemacetan. Langkah awal manajemen konflik yang paling tepat adalah?", ["Memetakan kepentingan, pengaruh, kerugian, manfaat, dan opsi kompensasi tiap aktor sebelum mengambil keputusan final.", "Mengabaikan pedagang karena tidak punya kewenangan formal.", "Mengikuti pengembang karena punya modal terbesar.", "Menyembunyikan desain sampai konstruksi dimulai.", "Mengganti seluruh pedagang dengan penyewa baru."], 0, "Konflik stakeholder perlu dipahami melalui posisi, kepentingan, pengaruh, dan dampak sebelum negosiasi."),
  q("G2-S06", "sosial", "kasus", "Stakeholder conflict", "Dalam pembangunan tempat pengolahan sampah, warga sekitar menolak karena khawatir bau, sementara kota membutuhkan fasilitas. Strategi engagement yang paling tepat adalah?", ["Dialog risiko-manfaat, desain mitigasi bau, kunjungan pembanding, kompensasi proporsional, dan mekanisme keluhan.", "Memaksa persetujuan karena fasilitas penting.", "Memberi informasi hanya setelah proyek selesai.", "Menghapus kajian lingkungan agar cepat.", "Memindahkan masalah ke kecamatan lain tanpa konsultasi."], 0, "Fasilitas yang berpotensi menimbulkan dampak perlu komunikasi risiko dan mitigasi yang kredibel."),
  q("G2-S07", "sosial", "sedang", "PRA transect", "Dalam PRA, tim berjalan bersama warga melintasi dusun dari hulu ke hilir sambil mencatat sumber air, lahan rawan longsor, permukiman, dan fasilitas umum. Alat yang digunakan adalah?", ["Transect walk.", "Focus group statistik nasional.", "Delphi ahli tertutup.", "Regresi time series.", "Audit keuangan."], 0, "Transect walk memetakan kondisi ruang bersama masyarakat melalui penelusuran lapangan."),
  q("G2-S08", "sosial", "kasus", "PRA transect", "Hasil transect menunjukkan wilayah atas punya mata air rusak, tengah kekurangan drainase, dan bawah sering banjir. Cara memakai temuan PRA yang paling tepat adalah?", ["Menghubungkan masalah ruang dengan prioritas intervensi berbeda menurut zona dan kesepakatan warga.", "Merata-ratakan semua masalah menjadi satu kegiatan umum.", "Mengabaikan catatan warga karena bukan survei mahal.", "Memakai hasil hanya sebagai foto dokumentasi.", "Menentukan prioritas berdasarkan lokasi rumah tokoh."], 0, "Temuan transect berguna untuk menyesuaikan intervensi dengan karakter zona dan pengalaman warga."),
  q("G2-S09", "sosial", "panjang", "RRA vs PRA timing", "Tim hanya punya tiga hari untuk memperoleh gambaran awal kemiskinan desa sebelum studi mendalam bulan depan. Pendekatan yang lebih sesuai adalah?", ["RRA, karena cepat dan eksploratif untuk pemahaman awal dengan triangulasi terbatas.", "PRA penuh yang selalu membutuhkan keputusan warga final saat itu juga.", "Sensus lengkap semua rumah tangga.", "Eksperimen acak multi-tahun.", "Audit investigatif pengadaan."], 0, "RRA lebih cepat untuk appraisal awal; PRA lebih menekankan partisipasi dan proses pemberdayaan."),
  q("G2-S10", "sosial", "kasus", "RRA vs PRA timing", "Jika tujuan utama adalah membangun rencana aksi desa yang dimiliki warga dan memunculkan kelompok pelaksana lokal, pendekatan yang lebih tepat adalah?", ["RRA singkat oleh konsultan tanpa forum warga.", "PRA karena proses partisipatifnya membantu analisis bersama, prioritas, dan kepemilikan rencana.", "Survei online tertutup untuk pejabat.", "Desk study dokumen pusat saja.", "Wawancara satu tokoh sebagai wakil semua kelompok."], 1, "PRA dirancang untuk pembelajaran dan perencanaan bersama masyarakat, bukan hanya ekstraksi informasi cepat."),
  q("G2-S11", "sosial", "panjang", "Chambers applied", "Program bantuan rumah gagal menjangkau keluarga paling miskin karena mereka tinggal terpencil, tidak paham prosedur, dan takut berurusan dengan aparat. Kerangka Chambers membantu karena menyoroti?", ["Isolasi dan powerlessness yang menghambat rumah tangga miskin mengakses program.", "Hanya jumlah uang tunai sebagai satu-satunya dimensi kemiskinan.", "Bahwa kemiskinan tidak terkait relasi sosial.", "Bahwa warga miskin memiliki akses informasi dan prosedur yang setara.", "Bahwa prosedur administrasi selalu netral."], 0, "Chambers melihat kemiskinan sebagai deprivasi multidimensi yang saling mengunci."),
  q("G2-S12", "sosial", "kasus", "Chambers applied", "Keluarga lansia miskin tidak mampu ikut pelatihan kerja karena sakit kronis, merawat cucu, dan tidak punya transportasi. Desain program yang paling sesuai dengan perspektif Chambers adalah?", ["Mengganti pelatihan umum dengan dukungan layanan sosial, kesehatan, transportasi, dan bantuan yang sesuai kerentanan.", "Mewajibkan hadir atau bantuan dicabut.", "Menganggap mereka tidak mau berubah.", "Menambah materi kewirausahaan tanpa bantuan akses.", "Memindahkan lokasi lebih jauh."], 0, "Kerentanan dan kelemahan fisik harus dijawab dengan desain layanan yang sesuai kondisi nyata."),
  q("G2-S13", "sosial", "sedang", "Social capital case", "Desa dengan gotong royong kuat berhasil merawat jaringan air minum tanpa biaya besar karena ada norma saling percaya dan sanksi sosial. Ini menunjukkan peran?", ["Modal sosial dalam menurunkan biaya koordinasi dan menjaga aksi kolektif.", "Price ceiling air minum.", "Barang Giffen.", "Monopoli alamiah tanpa regulasi.", "ICOR rendah."], 0, "Kepercayaan, norma, dan jaringan dapat memperkuat kerja kolektif masyarakat."),
  q("G2-S14", "sosial", "kasus", "Social capital case", "Program koperasi desa gagal karena elite lokal menguasai keputusan dan anggota miskin takut menyampaikan keberatan. Pelajaran tentang modal sosial yang tepat adalah?", ["Modal sosial bonding yang kuat bisa eksklusif; perlu transparansi, akuntabilitas, dan jembatan ke kelompok rentan.", "Semua modal sosial selalu baik tanpa risiko.", "Koperasi tidak membutuhkan aturan formal.", "Anggota miskin sebaiknya tidak dilibatkan.", "Kepercayaan cukup menggantikan laporan keuangan."], 0, "Modal sosial dapat memperkuat atau mengecualikan, tergantung distribusi kuasa dan akuntabilitas."),
  q("G2-S15", "sosial", "panjang", "Gender budget", "Analisis anggaran menunjukkan program transportasi sekolah tidak mempertimbangkan siswi yang pulang sore melewati rute rawan kekerasan. Respons penganggaran responsif gender adalah?", ["Menambahkan analisis kebutuhan keamanan, alokasi rute atau armada aman, penerangan, pengawasan, dan indikator manfaat terpilah gender.", "Menyatakan transportasi netral sehingga tidak perlu data gender.", "Menghapus siswi dari sasaran.", "Mengganti semua kegiatan dengan seminar umum.", "Menunda sampai ada kasus besar."], 0, "Gender budget menghubungkan alokasi anggaran dengan kebutuhan, akses, kontrol, dan manfaat berbeda antar kelompok."),
  q("G2-S16", "sosial", "kasus", "Gender budget", "Sebuah OPD mengklaim anggarannya responsif gender karena peserta perempuan 50%, tetapi jadwal pelatihan membuat ibu pekerja informal sulit menyelesaikan kelas. Audit sederhana yang tepat adalah?", ["Menilai tidak hanya jumlah peserta, tetapi hambatan akses, kelulusan, manfaat ekonomi, dan beban pengasuhan.", "Menerima klaim karena proporsi awal cukup.", "Menghapus data kelulusan.", "Membatasi peserta hanya yang tidak punya anak.", "Memindahkan jadwal makin malam."], 0, "Responsif gender tidak berhenti pada kuota peserta; manfaat dan hambatan riil perlu diuji."),
  q("G2-S17", "sosial", "sedang", "Difabel UU", "Dalam layanan publik, prinsip akomodasi yang layak bagi penyandang disabilitas berarti?", ["Penyesuaian yang perlu dan sesuai agar difabel dapat menikmati hak dan layanan secara setara tanpa beban tidak proporsional.", "Bantuan sukarela jika petugas sedang sempat.", "Pemisahan layanan difabel dari semua layanan umum.", "Kewajiban difabel membawa pendamping pribadi.", "Pengurangan standar keselamatan."], 0, "Akomodasi layak adalah kewajiban untuk memastikan akses setara sesuai kebutuhan."),
  q("G2-S18", "sosial", "kasus", "Difabel UU", "Aplikasi pengaduan bansos hanya memakai captcha visual dan tidak kompatibel dengan pembaca layar. Rekomendasi inklusi difabel yang tepat adalah?", ["Menyediakan alternatif aksesibel, kompatibilitas screen reader, kanal bantuan, dan uji pengguna difabel.", "Meminta difabel datang langsung saja.", "Menutup kanal pengaduan daring.", "Menganggap masalah selesai karena aplikasi modern.", "Membatasi pengaduan hanya jam kerja kantor pusat."], 0, "Aksesibilitas digital bagian dari layanan publik inklusif."),
  q("G2-S19", "sosial", "panjang", "MBG logistics", "Program Makan Bergizi Gratis di kepulauan menghadapi biaya dingin tinggi, jadwal kapal tidak pasti, dan risiko mutu makanan turun. Desain logistik yang paling tepat adalah?", ["Dapur atau titik produksi lokal, menu berbasis pangan setempat, standar mutu, rute distribusi adaptif, dan monitoring keamanan pangan.", "Satu dapur pusat jauh untuk semua pulau tanpa cadangan.", "Mengirim menu yang sama tanpa melihat transportasi.", "Menghapus standar gizi agar mudah.", "Mencatat keterlambatan sebagai hal biasa."], 0, "Wilayah kepulauan butuh desain logistik afirmatif yang menjaga mutu, gizi, dan ketepatan waktu."),
  q("G2-S20", "sosial", "kasus", "MBG logistics", "Di wilayah pegunungan, pasokan bahan segar untuk MBG sering terputus saat hujan. Strategi yang paling menjaga keberlanjutan program adalah?", ["Mengembangkan pemasok lokal, stok penyangga aman, menu musiman, dan rencana kontinjensi distribusi.", "Menghentikan program setiap musim hujan.", "Memaksa satu pemasok kota tanpa cadangan.", "Mengganti semua menu dengan makanan instan tanpa standar.", "Tidak mencatat gangguan pasokan."], 0, "Keberlanjutan layanan gizi membutuhkan cadangan, fleksibilitas menu, dan pemasok lokal."),
  q("G2-S21", "sosial", "panjang", "Evaluasi program sosial", "Evaluasi bantuan tunai menunjukkan realisasi 98%, tetapi penerima lansia banyak membayar biaya transportasi besar untuk mencairkan bantuan. Ukuran efektivitas yang perlu ditambahkan adalah?", ["Biaya akses, ketepatan sasaran, ketepatan waktu, dan manfaat bersih yang diterima kelompok rentan.", "Jumlah spanduk pencairan.", "Jumlah pejabat yang hadir.", "Panjang laporan bank.", "Jumlah loket tanpa melihat jarak."], 0, "Program sosial efektif jika manfaat bersih diterima sasaran, bukan hanya tersalurkan secara administratif."),
  q("G2-S22", "sosial", "kasus", "Evaluasi program sosial", "Program pelatihan kerja melaporkan peserta puas, tetapi hanya sedikit yang bekerja setelah enam bulan. Desain evaluasi yang lebih kuat adalah?", ["Tracer study outcome kerja, pembandingan dengan kebutuhan pasar, dan analisis hambatan penempatan.", "Menambah survei kepuasan saat konsumsi dibagikan.", "Menganggap sertifikat sebagai dampak akhir.", "Menghapus indikator pekerjaan.", "Mengukur jumlah foto kelas."], 0, "Evaluasi program sosial perlu menilai outcome nyata setelah intervensi, bukan hanya kepuasan segera."),
  q("G2-S23", "sosial", "sedang", "Stakeholder conflict", "Kelompok adat menolak proyek wisata karena situs sakral tidak dipetakan dalam dokumen awal. Prinsip sosial yang harus dipulihkan adalah?", ["Pengakuan hak dan pengetahuan lokal melalui konsultasi bermakna, pemetaan partisipatif, dan perlindungan situs.", "Mempercepat konstruksi agar penolakan berhenti.", "Menghapus kelompok adat dari daftar stakeholder.", "Mengganti situs sakral dengan spot foto.", "Membatasi informasi peta."], 0, "Konflik sosial sering muncul ketika hak, identitas, dan pengetahuan lokal tidak diakui."),
  q("G2-S24", "sosial", "kasus", "SIPD Renja-RKPD", "Dalam SIPD, indikator Renja 'jumlah keluarga didampingi' naik, tetapi RKPD menargetkan penurunan kekerasan terhadap perempuan. Perbaikan indikator yang paling tepat adalah?", ["Menambahkan indikator kualitas layanan seperti persentase korban mendapat layanan terpadu sesuai standar dan kasus berulang menurun.", "Mengganti semua indikator dengan jumlah rapat.", "Menghapus target korban karena sensitif.", "Mengukur jumlah poster kampanye saja.", "Menilai keberhasilan dari total honor pendamping."], 0, "Output pendampingan perlu ditautkan dengan kualitas layanan dan perubahan risiko kekerasan."),
  q("G2-S25", "sosial", "panjang", "IKU daerah", "Daerah menetapkan IKU 'semua warga bahagia' tanpa metode ukur. Koreksi yang paling tepat adalah?", ["Membiarkan karena visi harus selalu abstrak.", "Menghapus semua IKU agar fleksibel.", "Mengukur dari jumlah pidato kepala daerah.", "Menggunakan komentar media sosial saja tanpa metode.", "Mengubahnya menjadi indikator terukur seperti indeks kepuasan layanan, prevalensi kemiskinan, atau indikator kesejahteraan yang punya baseline, target, dan sumber data."], 4, "IKU harus operasional, punya sumber data, baseline, target, dan relevansi strategis."),

  // === SPASIAL (20) ===
  q("G2-P01", "spasial", "kasus", "KKPR vs izin lain", "Investor sudah memiliki NIB, tetapi lokasi gudang berada dekat kawasan lindung dan belum jelas kesesuaian ruangnya. Dokumen yang harus dipastikan sebelum izin teknis lain berjalan adalah?", ["KKPR atau konfirmasi/persetujuan kesesuaian kegiatan pemanfaatan ruang sesuai ketentuan tata ruang.", "SLF karena bangunan belum dibangun.", "SPPT PBB sebagai pengganti tata ruang.", "Surat domisili RT sebagai izin utama.", "Sertifikat merek dagang."], 0, "KKPR memastikan kegiatan sesuai rencana tata ruang sebelum perizinan teknis lanjutan."),
  q("G2-P02", "spasial", "panjang", "KKPR vs izin lain", "Sebuah pabrik memiliki PBG, tetapi kemudian diketahui kegiatan industrinya tidak sesuai zonasi RDTR. Pelajaran tata ruang yang paling tepat adalah?", ["PBG tidak menggantikan KKPR; kesesuaian kegiatan pemanfaatan ruang harus jelas sebelum persetujuan bangunan.", "PBG dianggap mengesampingkan ketentuan zonasi RDTR.", "RDTR hanya hiasan peta.", "KKPR hanya diperlukan setelah bangunan digunakan.", "Zonasi dapat diubah oleh kontraktor."], 0, "Persetujuan bangunan dan kesesuaian ruang adalah instrumen berbeda yang harus saling konsisten."),
  q("G2-P03", "spasial", "sedang", "RDTR skala", "RDTR membutuhkan skala peta lebih rinci daripada RTRW karena digunakan untuk?", ["Mengatur zonasi dan ketentuan pemanfaatan ruang yang menjadi dasar operasional perizinan.", "Mengganti seluruh sertifikat tanah.", "Menghapus partisipasi publik.", "Menentukan harga semua properti.", "Mengukur inflasi daerah."], 0, "RDTR adalah rencana rinci yang menerjemahkan arahan RTRW ke aturan zonasi operasional."),
  q("G2-P04", "spasial", "kasus", "RDTR skala", "Jika batas zona perdagangan dan permukiman di RDTR terlalu kasar, risiko utama dalam pelayanan perizinan adalah?", ["Ketidakpastian lokasi kegiatan, sengketa interpretasi zonasi, dan keputusan KKPR yang tidak konsisten.", "Semua izin otomatis lebih cepat dan akurat.", "Tidak ada hubungan antara skala peta dan perizinan.", "Harga tanah pasti turun sama rata.", "Peta tidak perlu metadata."], 0, "Skala dan ketelitian RDTR memengaruhi kepastian zonasi dan keputusan pemanfaatan ruang."),
  q("G2-P05", "spasial", "panjang", "LP2B", "Kabupaten ingin mengubah sawah irigasi produktif menjadi kawasan pergudangan karena akses tol baru. Kajian LP2B paling penting untuk memastikan?", ["Perlindungan lahan pangan berkelanjutan, dampak terhadap produksi pangan, dan alternatif lokasi non-produktif.", "Peningkatan reklame gudang.", "Jumlah parkir truk saja.", "Warna bangunan gudang.", "Penghapusan data petani."], 0, "LP2B melindungi lahan pangan strategis agar alih fungsi tidak merusak ketahanan pangan."),
  q("G2-P06", "spasial", "kasus", "LP2B", "Petani setuju menjual sawah LP2B karena harga tinggi, tetapi desa bergantung pada irigasi dan produksi padi lokal. Respons perencana yang paling tepat adalah?", ["Menilai status LP2B, dampak ketahanan pangan, kompensasi atau penggantian lahan, serta kesesuaian tata ruang sebelum perubahan.", "Menerima transaksi sebagai urusan privat sepenuhnya.", "Menghapus peta LP2B agar investasi masuk.", "Memindahkan irigasi tanpa kajian.", "Mengabaikan petani penggarap."], 0, "Alih fungsi LP2B memiliki konsekuensi publik sehingga perlu pengendalian sesuai aturan dan kajian dampak."),
  q("G2-P07", "spasial", "sedang", "RTH breakdown 20+10", "Ketentuan umum RTH kota 30% sering dijelaskan sebagai komposisi?", ["20% RTH publik dan 10% RTH privat.", "30% seluruhnya parkir privat.", "10% publik dan 20% jalan tol.", "15% industri dan 15% permukiman.", "30% hanya taman kantor pemerintah."], 0, "RTH kota umumnya diarahkan minimal 30%, terdiri dari 20% publik dan 10% privat."),
  q("G2-P08", "spasial", "kasus", "RTH breakdown 20+10", "Kota melaporkan RTH 30%, tetapi 24% berasal dari halaman privat kompleks tertutup dan hanya 6% taman publik. Catatan evaluasi yang tepat adalah?", ["Komposisi belum memenuhi kebutuhan RTH publik; akses warga dan fungsi ekologis publik perlu diperkuat.", "Target dianggap tercapai hanya karena angka agregat 30%.", "RTH privat dianggap setara fungsi taman publik terbuka.", "RTH tidak terkait akses masyarakat.", "Semua halaman privat harus dihitung sebagai jalan."], 0, "Proporsi publik penting karena RTH juga berfungsi sebagai ruang ekologis dan sosial yang dapat diakses masyarakat."),
  q("G2-P09", "spasial", "panjang", "SIG buffer analysis", "Bappeda ingin mengetahui sekolah yang berada dalam radius 500 meter dari jalan arteri rawan kecelakaan. Analisis SIG yang tepat adalah?", ["Membuat buffer 500 meter dari jalan arteri lalu melakukan intersect atau select by location terhadap titik sekolah.", "Mengubah warna titik sekolah secara manual.", "Menghapus layer jalan agar peta bersih.", "Menghitung rata-rata nilai ujian.", "Membuat legenda tanpa koordinat."], 0, "Buffer dan overlay lokasi digunakan untuk menemukan objek dalam jarak tertentu dari fitur spasial."),
  q("G2-P10", "spasial", "kasus", "SIG buffer analysis", "Analisis buffer puskesmas 2 km menunjukkan cakupan tinggi, tetapi warga di pulau kecil tetap sulit mengakses layanan karena harus menyeberang laut. Kelemahan analisis yang perlu dicatat adalah?", ["Buffer Euclidean tidak selalu mencerminkan waktu tempuh, moda transportasi, hambatan alam, dan jaringan layanan.", "Buffer jarak lurus dianggap lebih andal daripada analisis akses lapangan.", "Pulau kecil harus dihapus dari peta.", "Cakupan spasial tinggi dianggap menutup masalah akses layanan.", "SIG tidak boleh memakai data transportasi."], 0, "Jarak lurus perlu dilengkapi analisis jaringan dan konteks geografis."),
  q("G2-P11", "spasial", "sedang", "Citra satelit", "Untuk memantau perubahan tutupan lahan hutan menjadi kebun, data yang paling relevan adalah?", ["Citra satelit multitemporal yang diklasifikasi dan diverifikasi dengan data lapangan.", "Daftar hadir rapat desa.", "Foto gedung kantor.", "Tabel inflasi bulanan saja.", "Surat undangan musrenbang."], 0, "Citra satelit multitemporal membantu mendeteksi perubahan spasial dari waktu ke waktu."),
  q("G2-P12", "spasial", "kasus", "Citra satelit", "Hasil klasifikasi citra menunjukkan sawah berkurang, tetapi awan menutup sebagian wilayah saat perekaman. Sikap teknis yang tepat adalah?", ["Melakukan masking awan, memakai citra tanggal lain atau sensor lain, dan validasi lapangan sebelum menyimpulkan.", "Menganggap semua area awan sebagai sawah hilang.", "Menghapus wilayah berawan dari kabupaten.", "Menerbitkan angka final tanpa catatan kualitas.", "Mengganti citra dengan opini warga saja."], 0, "Kualitas citra dan gangguan awan harus ditangani agar interpretasi perubahan lahan tidak bias."),
  q("G2-P13", "spasial", "panjang", "LVC betterment levy", "Pembangunan MRT menaikkan nilai lahan koridor secara besar. Pemerintah mempertimbangkan pungutan atas kenaikan manfaat untuk membiayai akses pejalan kaki. Instrumen yang paling sesuai adalah?", ["Betterment levy sebagai bentuk land value capture atas kenaikan nilai akibat investasi publik.", "Price ceiling sewa rumah.", "Subsidi BBM umum.", "Bantuan sosial tunai.", "Kuota tangkap ikan."], 0, "Betterment levy menangkap sebagian kenaikan nilai lahan yang timbul dari investasi publik."),
  q("G2-P14", "spasial", "kasus", "LVC betterment levy", "Agar betterment levy tidak dianggap tidak adil, prinsip desain yang penting adalah?", ["Dasar perhitungan transparan, hubungan jelas dengan manfaat, kemampuan bayar, perlindungan warga rentan, dan penggunaan dana yang akuntabel.", "Tarif rahasia agar tidak diprotes.", "Pungutan sama untuk semua wilayah meski manfaat berbeda.", "Dana boleh dipakai tanpa laporan.", "Penyewa miskin menanggung seluruh pungutan."], 0, "LVC membutuhkan legitimasi, keadilan, dan transparansi agar tidak membebani pihak yang tidak menikmati manfaat sepadan."),
  q("G2-P15", "spasial", "sedang", "Asas keadilan", "Dalam tata ruang, asas keadilan menuntut agar?", ["Manfaat dan beban pemanfaatan ruang dibagi secara proporsional, termasuk perlindungan kelompok rentan dan wilayah terdampak.", "Kawasan bernilai tinggi hanya untuk pemilik modal.", "Informasi zonasi disimpan untuk pejabat.", "Semua daerah menerima proyek identik tanpa kebutuhan.", "Dampak negatif dipindahkan ke warga miskin."], 0, "Keadilan ruang memperhatikan distribusi manfaat, risiko, akses, dan perlindungan hak."),
  q("G2-P16", "spasial", "kasus", "Asas keadilan", "Kawasan tempat tinggal MBR terdampak perluasan jalan, sementara manfaat kenaikan nilai lahan lebih banyak dinikmati pemilik properti besar. Koreksi perencanaan yang sesuai asas keadilan adalah?", ["Menyediakan kompensasi layak, hunian pengganti terjangkau, perlindungan mata pencaharian, dan pembagian manfaat kawasan.", "Menggusur cepat karena proyek strategis.", "Mengabaikan penyewa karena bukan pemilik lahan.", "Menaikkan nilai tanah tanpa program sosial.", "Membatasi informasi desain jalan."], 0, "Asas keadilan menuntut perlindungan terhadap pihak yang menanggung beban pembangunan."),
  q("G2-P17", "spasial", "panjang", "Institutional SOP", "Daerah memiliki RDTR digital, tetapi setiap dinas memakai versi peta berbeda dan pembaruan tidak terdokumentasi. Solusi institusional paling tepat adalah?", ["SOP pemutakhiran data, wali data spasial, metadata, repositori bersama, dan mekanisme persetujuan versi.", "Membiarkan setiap dinas menyimpan file sendiri.", "Menghapus metadata agar cepat dibuka.", "Mengandalkan pesan pribadi untuk berbagi peta.", "Mencetak peta sekali untuk semua waktu."], 0, "Tata kelola data spasial membutuhkan SOP, peran, metadata, dan kontrol versi."),
  q("G2-P18", "spasial", "kasus", "IKN penyangga", "Daerah penyangga IKN mengalami lonjakan permintaan perumahan pekerja dan spekulasi lahan. Respons tata ruang yang paling tepat adalah?", ["Menyiapkan RDTR kawasan tumbuh, pengendalian alih fungsi, perumahan terjangkau, konektivitas, dan perlindungan masyarakat lokal.", "Membiarkan pasar lahan bergerak tanpa rencana.", "Mengubah semua hutan menjadi komersial.", "Menolak seluruh pendatang tanpa dasar hukum.", "Menunda perencanaan sampai harga stabil sendiri."], 0, "Daerah penyangga perlu mengelola tekanan ruang, hunian, lingkungan, dan sosial secara antisipatif."),
  q("G2-P19", "spasial", "panjang", "PSN mitigasi sosial", "PSN bendungan membutuhkan pengadaan tanah dan relokasi beberapa dusun. Agar mitigasi sosial tidak sekadar formalitas, perencana daerah harus memastikan?", ["Data warga terdampak lengkap, konsultasi bermakna, pemulihan mata pencaharian, kompensasi layak, dan mekanisme keluhan berjalan.", "Relokasi dilakukan dulu baru pendataan.", "Konsultasi cukup lewat poster.", "Pekerjaan fisik tidak perlu mempertimbangkan warga.", "Keluhan warga ditutup agar proyek cepat."], 0, "PSN tetap memerlukan mitigasi sosial yang melindungi hak dan penghidupan warga terdampak."),
  q("G2-P20", "spasial", "kasus", "Mitigasi banjir dan Delphi", "Kota pesisir sulit memilih strategi banjir karena data historis terbatas, penurunan tanah cepat, dan ahli berbeda pendapat. Kombinasi pendekatan yang paling tepat adalah?", ["Menunggu banjir besar berikutnya sebelum bertindak.", "Memilih proyek terbesar tanpa skenario.", "Menghapus masukan ahli karena tidak sama.", "Mengandalkan satu angka curah hujan lama.", "Menggunakan pemodelan skenario banjir, peta risiko, konsultasi ahli Delphi untuk asumsi kunci, dan prioritas adaptasi bertahap."], 4, "Ketidakpastian tinggi dapat ditangani dengan skenario, peta risiko, dan konsensus ahli terstruktur seperti Delphi.")
];

function esc(value) {
  return JSON.stringify(value);
}

function serializeBank(name, bank) {
  let output = `// Bank soal gap UKOM Perencana Ahli Muda batch 2 - dihasilkan build-gap200.mjs\n`;
  output += `// Jangan edit manual; jalankan: node scripts/build-gap200.mjs\n`;
  output += `const ${name} = [\n`;
  bank.forEach((item, index) => {
    output += "  {\n";
    output += `    id: ${esc(item.id)},\n`;
    output += `    cluster: ${esc(item.cluster)},\n`;
    output += `    level: ${esc(item.level)},\n`;
    output += `    source: ${esc(item.source)},\n`;
    output += `    topic: ${esc(item.topic)},\n`;
    output += `    stem: ${esc(item.stem)},\n`;
    output += "    options: [\n";
    item.options.forEach((option) => {
      output += `      ${esc(option)},\n`;
    });
    output += "    ],\n";
    output += `    answer: ${item.answer},\n`;
    output += `    explain: ${esc(item.explain)},\n`;
    output += `    version: ${item.version}\n`;
    output += `  }${index < bank.length - 1 ? "," : ""}\n`;
  });
  output += "];\n";
  return output;
}

function countBy(items, key) {
  return items.reduce((acc, item) => {
    acc[item[key]] = (acc[item[key]] || 0) + 1;
    return acc;
  }, {});
}

function readBatch1Stems() {
  if (!fs.existsSync(GAP100_PATH)) return new Set();
  const text = fs.readFileSync(GAP100_PATH, "utf8");
  const stems = new Set();
  const pattern = /stem:\s*("(?:(?:\\.)|[^"\\])*")/g;
  let match;
  while ((match = pattern.exec(text))) {
    stems.add(JSON.parse(match[1]));
  }
  return stems;
}

function validateIdSequence(bank, cluster, prefix, expected) {
  const actual = bank.filter((item) => item.cluster === cluster).map((item) => item.id);
  for (let i = 1; i <= expected; i += 1) {
    const id = `${prefix}${String(i).padStart(2, "0")}`;
    if (!actual.includes(id)) throw new Error(`Missing id: ${id}`);
  }
}

function validateBank(bank) {
  const clusterCounts = countBy(bank, "cluster");
  const answerCounts = countBy(bank, "answer");
  const ids = new Set();
  const stems = new Set();
  const batch1Stems = readBatch1Stems();

  if (bank.length !== 100) throw new Error(`Expected 100 questions, got ${bank.length}`);

  for (const [cluster, expected] of Object.entries(EXPECTED_CLUSTERS)) {
    if (clusterCounts[cluster] !== expected) {
      throw new Error(`Expected ${expected} ${cluster} questions, got ${clusterCounts[cluster] || 0}`);
    }
  }

  validateIdSequence(bank, "teknis", "G2-T", EXPECTED_CLUSTERS.teknis);
  validateIdSequence(bank, "ekonomi", "G2-E", EXPECTED_CLUSTERS.ekonomi);
  validateIdSequence(bank, "sosial", "G2-S", EXPECTED_CLUSTERS.sosial);
  validateIdSequence(bank, "spasial", "G2-P", EXPECTED_CLUSTERS.spasial);

  for (const item of bank) {
    if (ids.has(item.id)) throw new Error(`Duplicate id: ${item.id}`);
    if (stems.has(item.stem)) throw new Error(`Duplicate stem in batch 2: ${item.stem}`);
    if (batch1Stems.has(item.stem)) throw new Error(`Duplicate stem from batch 1: ${item.id}`);
    if (!Object.hasOwn(EXPECTED_CLUSTERS, item.cluster)) throw new Error(`Invalid cluster: ${item.id}`);
    if (!LEVELS.includes(item.level)) throw new Error(`Invalid level: ${item.id}`);
    if (item.source !== "gap2") throw new Error(`Invalid source: ${item.id}`);
    if (!item.topic || !item.stem || !item.explain || item.version !== 1) throw new Error(`Invalid metadata: ${item.id}`);
    if (!Array.isArray(item.options) || item.options.length !== 5) throw new Error(`Invalid options length: ${item.id}`);
    if (new Set(item.options).size !== 5) throw new Error(`Duplicate option in: ${item.id}`);
    if (!Number.isInteger(item.answer) || item.answer < 0 || item.answer > 4) throw new Error(`Invalid answer: ${item.id}`);
    if (typeof item.options[item.answer] !== "string" || item.options[item.answer].length === 0) {
      throw new Error(`Answer points to empty option: ${item.id}`);
    }
    ids.add(item.id);
    stems.add(item.stem);
  }

  for (let answer = 0; answer <= 4; answer += 1) {
    if (!answerCounts[answer]) throw new Error(`Answer index ${answer} is unused`);
  }

  return { clusterCounts, answerCounts };
}

const BALANCED = rebalanceAnswers(QUESTIONS);
const { clusterCounts, answerCounts } = validateBank(BALANCED);
fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
fs.writeFileSync(OUT_PATH, serializeBank("BANK_GAP2", BALANCED), "utf8");

console.log(`OK: ${OUT_PATH}`);
console.log(`total: ${QUESTIONS.length}`);
console.log(`teknis: ${clusterCounts.teknis} | ekonomi: ${clusterCounts.ekonomi} | sosial: ${clusterCounts.sosial} | spasial: ${clusterCounts.spasial}`);
console.log(`answer index counts: 0=${answerCounts[0]} | 1=${answerCounts[1]} | 2=${answerCounts[2]} | 3=${answerCounts[3]} | 4=${answerCounts[4]}`);
