// Bank soal gap UKOM Perencana Ahli Muda - dihasilkan build-gap100.mjs
// Jangan edit manual; jalankan: node scripts/build-gap100.mjs
const BANK_GAP = [
  {
    id: "G-T01",
    cluster: "teknis",
    level: "singkat",
    source: "gap",
    stem: "Seorang analis baru ditempatkan pada unit perencanaan dan diminta menjelaskan kedudukan Jabatan Fungsional Perencana menurut Permen PANRB Nomor 4 Tahun 2020. Penjelasan mana yang paling tepat untuk membedakan tugas perencana dari staf administrasi program?",
    options: [
      "Perencana melakukan penyiapan, pengkajian, perumusan, pengendalian, dan evaluasi rencana pembangunan berbasis analisis kebijakan.",
      "Perencana terutama bertugas mengarsipkan surat masuk dan membuat notulen rapat pimpinan.",
      "Perencana hanya menghitung realisasi keuangan program tanpa menilai logika intervensi.",
      "Perencana berwenang mengganti keputusan kepala daerah tanpa proses perencanaan.",
      "Perencana bekerja hanya setelah dokumen APBD disahkan.",
    ],
    answer: 0,
    explain: "Permen PANRB 4/2020 menempatkan perencana sebagai jabatan fungsional yang menjalankan kegiatan perencanaan pembangunan, bukan sekadar administrasi.",
    version: 1
  },
  {
    id: "G-T02",
    cluster: "teknis",
    level: "sedang",
    source: "gap",
    stem: "Dalam seleksi Perencana Ahli Muda, peserta diminta menunjukkan empat kompetensi teknis utama. Kombinasi mana yang paling menggambarkan kompetensi teknis perencana pada level ahli muda?",
    options: [
      "Membuat desain grafis, mengelola perjalanan dinas, menyusun absensi, dan menjaga aset kantor.",
      "Mengidentifikasi masalah, menganalisis data, menyusun alternatif kebijakan, serta memantau dan mengevaluasi pelaksanaan rencana.",
      "Melakukan audit investigatif, menetapkan sanksi pidana, menagih pajak, dan menyita aset.",
      "Menerbitkan izin usaha, mengesahkan sertifikat tanah, menguji mutu barang, dan membuat kontrak konstruksi.",
      "Mengelola protokol pimpinan, dokumentasi foto, persuratan, dan konsumsi rapat.",
    ],
    answer: 1,
    explain: "Kompetensi teknis perencana berkaitan dengan analisis perencanaan dari masalah sampai evaluasi, sesuai peran JFP dalam siklus pembangunan.",
    version: 1
  },
  {
    id: "G-T03",
    cluster: "teknis",
    level: "panjang",
    source: "gap",
    stem: "Pada sesi ujian, soal meminta peserta membedakan output, outcome, dan impact dalam program penurunan stunting. Level kognitif Bloom yang paling dominan untuk tugas tersebut adalah?",
    options: [
      "C1, karena peserta hanya menyalin definisi tanpa pemahaman.",
      "C4, karena peserta wajib memecah model kausal yang kompleks.",
      "C2, karena peserta harus memahami konsep dan menjelaskan perbedaan antaristilah.",
      "C5, karena peserta diminta menilai kebijakan dengan kriteria normatif.",
      "C6, karena peserta harus menciptakan program baru dari awal.",
    ],
    answer: 2,
    explain: "Membedakan dan menjelaskan makna konsep termasuk pemahaman atau C2 dalam taksonomi Bloom.",
    version: 1
  },
  {
    id: "G-T04",
    cluster: "teknis",
    level: "kasus",
    source: "gap",
    stem: "Tim Bappeda menerima data kemiskinan, akses sanitasi, dan angka putus sekolah. Peserta ujian diminta memilih indikator prioritas untuk rancangan program kecamatan berdasarkan kriteria yang sudah diberikan. Level Bloom yang paling tepat adalah?",
    options: [
      "C1, karena tugas terbatas pada mengingat daftar indikator tanpa memakai data kasus.",
      "C2, karena tugas terbatas menjelaskan istilah tanpa menerapkan kriteria pada data.",
      "C5, karena tugas menilai normatif tanpa menerapkan kriteria pada data program.",
      "C3, karena peserta menerapkan konsep dan kriteria pada data kasus.",
      "C6, karena tugas menuntut penelitian konseptual baru tanpa data kasus.",
    ],
    answer: 3,
    explain: "C3 menekankan penerapan pengetahuan pada situasi konkret; peserta menggunakan kriteria untuk memilih indikator.",
    version: 1
  },
  {
    id: "G-T05",
    cluster: "teknis",
    level: "singkat",
    source: "gap",
    stem: "Seorang Perencana Ahli Muda diminta menyusun policy brief untuk isu kemacetan. Agar sesuai peran JFP dan level C3, keluaran terbaik adalah?",
    options: [
      "Daftar hadir rapat lintas OPD tanpa analisis masalah.",
      "Salinan berita media sosial tentang keluhan warga.",
      "Keputusan final rute angkutan tanpa mandat dan tanpa data.",
      "Poster kampanye tertib lalu lintas tanpa indikator keberhasilan.",
      "Policy brief yang menerapkan analisis data lalu lintas, akar masalah, opsi intervensi, risiko, dan rekomendasi yang dapat dilaksanakan.",
    ],
    answer: 4,
    explain: "Perencana ahli muda menerapkan analisis untuk menghasilkan rekomendasi kebijakan; ini sesuai kompetensi teknis dan level aplikasi C3.",
    version: 1
  },
  {
    id: "G-T06",
    cluster: "teknis",
    level: "sedang",
    source: "gap",
    stem: "Sebelum program revitalisasi pasar dimasukkan ke RKPD, tim diminta menilai kelayakan, kebutuhan, risiko sosial, dan konsistensi dengan prioritas daerah. Jenis evaluasi yang digunakan adalah?",
    options: [
      "Evaluasi ex ante.",
      "Evaluasi ex post.",
      "Evaluasi terminal setelah aset diserahterimakan.",
      "Audit kepatuhan tahunan.",
      "Evaluasi dampak lima tahun setelah program selesai.",
    ],
    answer: 0,
    explain: "Ex ante dilakukan sebelum intervensi dijalankan untuk menilai relevansi, kelayakan, risiko, dan desain program.",
    version: 1
  },
  {
    id: "G-T07",
    cluster: "teknis",
    level: "panjang",
    source: "gap",
    stem: "Pada triwulan kedua, pembangunan SPAM baru mencapai 38% sementara target fisik 55%. Perencana diminta memberi rekomendasi korektif tanpa menunggu akhir tahun. Evaluasi yang tepat adalah?",
    options: [
      "Evaluasi ex ante karena program belum selesai sepenuhnya.",
      "Evaluasi ongoing atau monitoring evaluatif selama pelaksanaan.",
      "Evaluasi ex post karena masih ada sisa pekerjaan.",
      "Evaluasi meta karena membandingkan seluruh studi evaluasi.",
      "Evaluasi normatif yang tidak membutuhkan data realisasi.",
    ],
    answer: 1,
    explain: "Ongoing evaluation dilakukan saat program berjalan untuk mengidentifikasi deviasi dan memperbaiki pelaksanaan.",
    version: 1
  },
  {
    id: "G-T08",
    cluster: "teknis",
    level: "kasus",
    source: "gap",
    stem: "Dua tahun setelah program pelatihan wirausaha selesai, pemerintah daerah ingin mengetahui apakah pendapatan peserta naik dan usaha bertahan. Pendekatan evaluasi yang paling tepat adalah?",
    options: [
      "Evaluasi ex ante dengan fokus desain awal.",
      "Monitoring harian kehadiran peserta.",
      "Evaluasi ex post dengan fokus outcome dan dampak setelah intervensi selesai.",
      "Reviu administrasi tanda terima honor.",
      "Penyusunan baseline tanpa membandingkan hasil.",
    ],
    answer: 2,
    explain: "Ex post menilai hasil dan dampak setelah program selesai sehingga cocok untuk melihat perubahan pendapatan dan keberlanjutan usaha.",
    version: 1
  },
  {
    id: "G-T09",
    cluster: "teknis",
    level: "singkat",
    source: "gap",
    stem: "Dalam evaluasi awal program irigasi, tim menemukan indikator hanya mengukur panjang saluran, padahal tujuan program adalah peningkatan produktivitas padi. Rekomendasi terbaik adalah?",
    options: [
      "Menghapus indikator outcome karena sulit diukur.",
      "Mengubah tujuan program menjadi panjang saluran saja.",
      "Menunda evaluasi sampai semua saluran rusak.",
      "Menyelaraskan indikator output dengan outcome produktivitas agar logika program dapat diuji.",
      "Memakai indikator serapan anggaran sebagai satu-satunya ukuran keberhasilan.",
    ],
    answer: 3,
    explain: "Evaluasi desain memeriksa konsistensi input-output-outcome; indikator harus mengikuti tujuan substantif program.",
    version: 1
  },
  {
    id: "G-T10",
    cluster: "teknis",
    level: "sedang",
    source: "gap",
    stem: "Program penanganan kawasan kumuh memiliki anggaran cukup, tetapi realisasi rendah karena tender terlambat dan koordinasi kelurahan lemah. Fokus evaluasi yang paling relevan adalah?",
    options: [
      "Evaluasi dampak jangka panjang saja.",
      "Evaluasi kepuasan pimpinan tanpa data proses.",
      "Evaluasi akademik yang hanya menguji teori urbanisasi.",
      "Evaluasi harga pasar tanah di sekitar lokasi.",
      "Evaluasi proses untuk menilai hambatan pelaksanaan, tata kelola, dan koordinasi.",
    ],
    answer: 4,
    explain: "Masalah utama berada pada pelaksanaan; evaluasi proses menilai apakah kegiatan berjalan sesuai rencana dan apa hambatannya.",
    version: 1
  },
  {
    id: "G-T11",
    cluster: "teknis",
    level: "panjang",
    source: "gap",
    stem: "Setelah program beasiswa daerah berjalan tiga tahun, angka putus sekolah turun tetapi belum jelas apakah penurunan terjadi pada kelompok miskin yang menjadi sasaran. Analisis evaluasi yang paling tepat adalah?",
    options: [
      "Membandingkan capaian outcome menurut kelompok sasaran, baseline, dan target untuk menilai efektivitas program.",
      "Melaporkan total dana terserap sebagai bukti cukup.",
      "Menghitung jumlah rapat koordinasi sebagai dampak utama.",
      "Mengabaikan data kelompok miskin karena semua siswa sama.",
      "Mengganti sasaran setelah hasil terlihat agar capaian tampak tinggi.",
    ],
    answer: 0,
    explain: "Evaluasi hasil harus menguji perubahan outcome pada sasaran yang direncanakan, bukan hanya aktivitas atau serapan.",
    version: 1
  },
  {
    id: "G-T12",
    cluster: "teknis",
    level: "kasus",
    source: "gap",
    stem: "Dinas kesehatan, pendidikan, dan sosial menjalankan program stunting dengan sasaran desa berbeda dan indikator sendiri-sendiri. Akibatnya keluarga prioritas tidak menerima paket layanan lengkap. Masalah tata kelola yang paling tepat disebut?",
    options: [
      "Ego daerah, karena konflik utama terjadi antara provinsi dan kabupaten.",
      "Ego sektoral, karena perangkat daerah bekerja dalam silo dan tidak mengintegrasikan sasaran lintas urusan.",
      "Moral hazard penerima manfaat, karena warga sengaja menolak bantuan.",
      "Inflasi biaya, karena harga barang naik mendadak.",
      "Kegagalan pasar informasi keuangan.",
    ],
    answer: 1,
    explain: "Ego sektoral muncul ketika organisasi mempertahankan agenda sektornya sehingga koordinasi program lintas urusan lemah.",
    version: 1
  },
  {
    id: "G-T13",
    cluster: "teknis",
    level: "singkat",
    source: "gap",
    stem: "Dalam proyek transportasi aglomerasi, satu kabupaten menolak menyesuaikan trayek dengan kota tetangga karena khawatir retribusi terminalnya turun. Padahal perjalanan warga melintasi batas administratif. Ini terutama mencerminkan?",
    options: [
      "Ego sektoral murni, karena hanya konflik antara dinas dalam daerah yang sama.",
      "Kegagalan indikator SMART, karena tidak ada satuan waktu.",
      "Ego daerah, karena kepentingan fiskal lokal menghambat solusi lintas wilayah.",
      "Masalah 5M pada metode kerja laboratorium.",
      "Kelebihan barang publik lokal.",
    ],
    answer: 2,
    explain: "Ego daerah terjadi saat kepentingan wilayah administratif mengalahkan kebutuhan layanan yang bersifat lintas batas.",
    version: 1
  },
  {
    id: "G-T14",
    cluster: "teknis",
    level: "sedang",
    source: "gap",
    stem: "Gubernur meminta solusi agar program penurunan kemiskinan tidak terpecah antara bantuan sosial, pelatihan, dan akses permodalan. Langkah perencanaan yang paling tepat adalah?",
    options: [
      "Meminta setiap OPD membuat program baru tanpa berbagi data.",
      "Menaikkan pagu semua dinas agar tidak ada yang merasa dirugikan.",
      "Menyerahkan seluruh program kepada satu vendor swasta.",
      "Membangun sasaran bersama, matriks peran OPD, indikator lintas urusan, dan forum pengendalian berkala.",
      "Menghapus indikator outcome karena sulit dikoordinasikan.",
    ],
    answer: 3,
    explain: "Koordinasi lintas sektor membutuhkan tujuan bersama, pembagian peran, data terpadu, dan mekanisme pengendalian.",
    version: 1
  },
  {
    id: "G-T15",
    cluster: "teknis",
    level: "panjang",
    source: "gap",
    stem: "Kawasan banjir berada di hulu kabupaten A dan hilir kota B. Jika masing-masing daerah hanya membangun drainase lokal, banjir tetap terjadi. Instrumen yang paling tepat untuk mengurangi ego daerah adalah?",
    options: [
      "Kompetisi antardaerah untuk menunjukkan siapa yang paling cepat membangun.",
      "Larangan berbagi data hidrologi karena merupakan aset daerah.",
      "Pemindahan semua warga hilir tanpa kajian.",
      "Penundaan program sampai batas administrasi berubah.",
      "Kerja sama antardaerah berbasis rencana kawasan, pembagian manfaat-biaya, dan indikator bersama.",
    ],
    answer: 4,
    explain: "Masalah lintas wilayah perlu kerja sama antardaerah agar biaya, manfaat, dan target dikelola bersama.",
    version: 1
  },
  {
    id: "G-T16",
    cluster: "teknis",
    level: "kasus",
    source: "gap",
    stem: "Dalam siklus POIC, kepala bidang meminta tim menetapkan tujuan, strategi, target, dan kebutuhan sumber daya sebelum program dimulai. Komponen POIC yang sedang dilakukan adalah?",
    options: [
      "Planning.",
      "Organizing.",
      "Actuating.",
      "Controlling.",
      "Auditing.",
    ],
    answer: 0,
    explain: "Planning mencakup penentuan tujuan, strategi, target, jadwal, dan sumber daya sebelum pelaksanaan.",
    version: 1
  },
  {
    id: "G-T17",
    cluster: "teknis",
    level: "singkat",
    source: "gap",
    stem: "Setelah rencana disetujui, Bappeda membagi peran antara bidang infrastruktur, ekonomi, dan sosial, menetapkan alur koordinasi, serta menunjuk penanggung jawab data. Ini adalah komponen POIC berupa?",
    options: [
      "Planning.",
      "Organizing.",
      "Actuating.",
      "Controlling.",
      "Forecasting.",
    ],
    answer: 1,
    explain: "Organizing mengatur struktur, pembagian tugas, mekanisme koordinasi, dan tanggung jawab pelaksana.",
    version: 1
  },
  {
    id: "G-T18",
    cluster: "teknis",
    level: "sedang",
    source: "gap",
    stem: "Dokumen rencana sudah selesai dan tim mulai menjalankan musrenbang tematik, verifikasi usulan, dan asistensi perangkat daerah sesuai jadwal. Dalam POIC, kegiatan ini termasuk?",
    options: [
      "Planning.",
      "Organizing.",
      "Actuating.",
      "Controlling.",
      "Evaluating ex post.",
    ],
    answer: 2,
    explain: "Actuating adalah pelaksanaan kegiatan sesuai rencana dan pembagian peran yang telah ditetapkan.",
    version: 1
  },
  {
    id: "G-T19",
    cluster: "teknis",
    level: "panjang",
    source: "gap",
    stem: "Pada bulan keenam, pimpinan membandingkan capaian output dengan target, menemukan deviasi, lalu meminta tindakan korektif. Komponen POIC yang paling tepat adalah?",
    options: [
      "Planning.",
      "Organizing.",
      "Actuating.",
      "Controlling.",
      "Brainstorming.",
    ],
    answer: 3,
    explain: "Controlling mengukur kemajuan, membandingkan dengan target, dan mengarahkan koreksi ketika ada deviasi.",
    version: 1
  },
  {
    id: "G-T20",
    cluster: "teknis",
    level: "kasus",
    source: "gap",
    stem: "Rencana pengembangan kawasan wisata gagal karena tim hanya membuat dokumen, tetapi tidak membagi peran, tidak melaksanakan agenda, dan tidak mengendalikan deviasi. Pelajaran POIC yang paling tepat adalah?",
    options: [
      "Planning saja cukup jika dokumen rencana sangat rinci.",
      "Controlling hanya dilakukan oleh auditor eksternal setelah semua selesai.",
      "Organizing tidak perlu jika anggaran sudah tersedia.",
      "Actuating dapat dimulai tanpa tujuan dan indikator.",
      "Keempat fungsi planning, organizing, actuating, dan controlling harus berjalan sebagai satu siklus manajemen.",
    ],
    answer: 4,
    explain: "POIC adalah rangkaian fungsi manajemen yang saling terkait, bukan daftar kegiatan yang dapat dipilih sebagian saja.",
    version: 1
  },
  {
    id: "G-T21",
    cluster: "teknis",
    level: "singkat",
    source: "gap",
    stem: "Program sanitasi membangun 500 sambungan rumah, lalu diare balita menurun dan kualitas hidup warga membaik. Urutan konsep yang benar adalah?",
    options: [
      "Input membiayai kegiatan, output berupa sambungan rumah, outcome berupa perubahan perilaku/kesehatan, impact berupa kualitas hidup jangka panjang.",
      "Output adalah dana, input adalah penurunan diare, outcome adalah rapat, impact adalah SPJ.",
      "Input dan impact sama-sama jumlah sambungan rumah.",
      "Outcome hanya berarti jumlah kegiatan sosialisasi.",
      "Impact selalu dapat diukur pada hari pekerjaan selesai.",
    ],
    answer: 0,
    explain: "Kerangka input-output-outcome-impact membedakan sumber daya, produk langsung, perubahan antara, dan dampak jangka panjang.",
    version: 1
  },
  {
    id: "G-T22",
    cluster: "teknis",
    level: "sedang",
    source: "gap",
    stem: "Dinas melaporkan keberhasilan program literasi hanya dari 40 pelatihan guru. Perencana meminta indikator tambahan berupa kenaikan kemampuan membaca siswa kelas awal. Mengapa permintaan ini tepat?",
    options: [
      "Pelatihan guru cenderung berdampak jangka panjang tanpa ukuran siswa.",
      "Jumlah pelatihan adalah output, sedangkan kemampuan membaca siswa menunjukkan outcome yang lebih dekat dengan tujuan program.",
      "Kemampuan membaca siswa dianggap input program, bukan hasil.",
      "Outcome tidak boleh digunakan dalam dokumen perencanaan.",
      "Output dan outcome dianggap identik jika kegiatan selesai.",
    ],
    answer: 1,
    explain: "Output adalah produk langsung kegiatan; outcome adalah perubahan yang dialami penerima manfaat atau sistem layanan.",
    version: 1
  },
  {
    id: "G-T23",
    cluster: "teknis",
    level: "panjang",
    source: "gap",
    stem: "Lima tahun setelah pembangunan jalan produksi, biaya logistik petani turun dan pusat pertumbuhan baru muncul. Ukuran ini lebih tepat disebut impact karena?",
    options: [
      "Menggambarkan jumlah kontrak pekerjaan.",
      "Mengukur kehadiran pekerja lapangan.",
      "Menggambarkan perubahan jangka panjang yang lebih luas daripada output fisik jalan.",
      "Menghitung volume aspal yang dipasang.",
      "Menunjukkan jumlah rapat koordinasi.",
    ],
    answer: 2,
    explain: "Impact menilai efek jangka panjang dan lebih luas yang timbul dari outcome program.",
    version: 1
  },
  {
    id: "G-T24",
    cluster: "teknis",
    level: "kasus",
    source: "gap",
    stem: "Saat menilai kesiapan program digitalisasi layanan desa, perencana memeriksa ketersediaan SDM operator, anggaran, perangkat komputer, prosedur kerja, dan data awal. Ini mencerminkan kerangka input?",
    options: [
      "SMART: specific, measurable, achievable, relevant, time-bound.",
      "POIC: planning, organizing, actuating, controlling.",
      "SWOT: strength, weakness, opportunity, threat.",
      "5M: man, money, material/machine, method, dan market/information sesuai kebutuhan program.",
      "PESTEL: politik, ekonomi, sosial, teknologi, lingkungan, hukum.",
    ],
    answer: 3,
    explain: "5M membantu memeriksa kesiapan input seperti manusia, dana, sarana, metode, dan informasi/pasar.",
    version: 1
  },
  {
    id: "G-T25",
    cluster: "teknis",
    level: "singkat",
    source: "gap",
    stem: "Program layanan mobil perpustakaan sering batal karena kendaraan rusak, sopir terbatas, dan SOP peminjaman belum jelas. Analisis gap input 5M yang paling tepat adalah?",
    options: [
      "Masalah hanya pada impact karena minat baca belum naik.",
      "Masalah hanya pada market karena buku belum populer.",
      "Tidak ada gap input selama anggaran sudah terserap.",
      "Masalah berada pada SMART karena target punya batas waktu.",
      "Kelemahan terjadi pada machine/material, man, dan method sehingga perbaikan input harus diarahkan ke tiga aspek itu.",
    ],
    answer: 4,
    explain: "Kerangka 5M mengurai sumber masalah input: sarana, SDM, metode, dana, dan informasi/pasar.",
    version: 1
  },
  {
    id: "G-T26",
    cluster: "teknis",
    level: "sedang",
    source: "gap",
    stem: "Indikator 'meningkatkan kualitas layanan publik secepatnya' dinilai lemah. Rumusan SMART terbaik adalah?",
    options: [
      "Persentase permohonan izin usaha yang selesai maksimal 3 hari kerja meningkat dari 62% menjadi 85% pada akhir 2026.",
      "Layanan publik harus lebih baik dan cepat.",
      "Semua pegawai harus bekerja keras demi masyarakat.",
      "Masyarakat merasa puas kapan pun memungkinkan.",
      "Perizinan akan dibuat modern sesuai arahan pimpinan.",
    ],
    answer: 0,
    explain: "SMART menuntut indikator spesifik, terukur, dapat dicapai, relevan, dan memiliki batas waktu.",
    version: 1
  },
  {
    id: "G-E01",
    cluster: "ekonomi",
    level: "singkat",
    source: "gap",
    stem: "Kawasan industri meningkatkan output daerah, tetapi limbah cair menurunkan kualitas air sungai dan biaya kesehatan warga. Bentuk kegagalan pasar dan intervensi yang paling tepat adalah?",
    options: [
      "Eksternalitas negatif; pemerintah dapat menetapkan baku mutu, pajak/pungutan polusi, dan pengawasan lingkungan.",
      "Monopoli alamiah; pemerintah harus membiarkan harga bebas sepenuhnya.",
      "Barang publik murni; solusinya membagi sungai menjadi hak milik pribadi.",
      "Asimetri informasi; solusinya hanya iklan layanan masyarakat.",
      "Tragedy of the commons; solusinya menghapus semua kegiatan ekonomi.",
    ],
    answer: 0,
    explain: "Eksternalitas negatif terjadi saat biaya sosial tidak masuk ke harga pasar; regulasi dan instrumen ekonomi menginternalisasi biaya tersebut.",
    version: 1
  },
  {
    id: "G-E02",
    cluster: "ekonomi",
    level: "sedang",
    source: "gap",
    stem: "Program imunisasi menghasilkan manfaat bagi anak yang divaksin dan juga menurunkan risiko penularan pada masyarakat. Mengapa subsidi atau penyediaan publik dapat dibenarkan?",
    options: [
      "Ada monopoli alamiah yang membuat vaksin tidak dapat diproduksi.",
      "Ada eksternalitas positif sehingga manfaat sosial lebih besar daripada manfaat privat yang diperhitungkan keluarga.",
      "Ada price ceiling yang selalu menimbulkan surplus.",
      "Ada barang private murni sehingga negara tidak boleh terlibat.",
      "Ada kegagalan pemerintah yang pasti lebih besar dari pasar.",
    ],
    answer: 1,
    explain: "Eksternalitas positif sering menyebabkan konsumsi pasar terlalu rendah; subsidi atau layanan publik dapat menaikkan konsumsi ke tingkat sosial yang lebih baik.",
    version: 1
  },
  {
    id: "G-E03",
    cluster: "ekonomi",
    level: "panjang",
    source: "gap",
    stem: "Penerangan jalan lingkungan membuat semua warga di ruas tersebut terbantu dan sulit mengecualikan pengguna tertentu. Ini menunjukkan alasan intervensi pemerintah karena?",
    options: [
      "Barang private umumnya disediakan pasar tanpa subsidi penuh pemerintah.",
      "Common resource rentan overuse meski sulit dikecualikan.",
      "Barang publik atau mendekati publik memiliki non-rivalry dan sulit dieksklusi sehingga pasar cenderung kurang menyediakan.",
      "Club goods tidak membutuhkan biaya operasional.",
      "Monopoli alamiah justru sering memerlukan regulasi tarif dan mutu layanan.",
    ],
    answer: 2,
    explain: "Barang publik sulit dibiayai murni melalui pasar karena masalah free rider.",
    version: 1
  },
  {
    id: "G-E04",
    cluster: "ekonomi",
    level: "kasus",
    source: "gap",
    stem: "Petani membeli benih unggul dari pedagang, tetapi tidak dapat menilai mutu benih sebelum panen. Banyak benih palsu beredar dan merusak kepercayaan pasar. Kegagalan pasar ini terutama berupa?",
    options: [
      "Eksternalitas positif; pemerintah sebaiknya membayar semua pembeli benih.",
      "Barang publik; benih tidak rival dan tidak eksklusif.",
      "Price floor; harga selalu di bawah keseimbangan.",
      "Asimetri informasi; pemerintah dapat memperkuat sertifikasi, label, pengujian mutu, dan pengawasan.",
      "Tragedy of the commons; benih digunakan bersama tanpa kepemilikan.",
    ],
    answer: 3,
    explain: "Asimetri informasi terjadi ketika penjual dan pembeli tidak memiliki informasi mutu yang seimbang; sertifikasi mengurangi adverse selection.",
    version: 1
  },
  {
    id: "G-E05",
    cluster: "ekonomi",
    level: "singkat",
    source: "gap",
    stem: "Distribusi air minum perpipaan di kota kecil membutuhkan jaringan mahal sehingga satu operator lebih efisien daripada banyak jaringan paralel. Risiko utamanya adalah tarif tinggi dan mutu rendah. Intervensi yang tepat?",
    options: [
      "Membiarkan operator menaikkan tarif tanpa batas.",
      "Melarang seluruh investasi jaringan air.",
      "Mewajibkan lima jaringan pipa bersaing di jalan yang sama.",
      "Mengganti tarif air dengan harga lelang harian tanpa standar mutu.",
      "Regulasi tarif dan standar layanan atau penyediaan BUMD karena karakter monopoli alamiah.",
    ],
    answer: 4,
    explain: "Monopoli alamiah muncul karena skala ekonomi besar; regulasi diperlukan agar efisiensi tidak berubah menjadi eksploitasi konsumen.",
    version: 1
  },
  {
    id: "G-E06",
    cluster: "ekonomi",
    level: "sedang",
    source: "gap",
    stem: "Investor pengolahan kakao menunggu kepastian pasokan petani, sementara petani enggan menanam kakao karena belum ada pembeli industri. Kebuntuan ini disebut?",
    options: [
      "Kegagalan koordinasi; pemerintah dapat memfasilitasi kemitraan, informasi pasar, dan infrastruktur pendukung.",
      "Eksternalitas negatif murni; solusinya pajak polusi.",
      "Barang publik murni; solusinya lampu jalan.",
      "Price ceiling; solusinya menaikkan harga maksimum.",
      "Kegagalan pemerintah; solusinya menghentikan semua fasilitasi.",
    ],
    answer: 0,
    explain: "Kegagalan koordinasi terjadi saat keputusan saling bergantung membuat pasar tidak mencapai investasi yang bermanfaat.",
    version: 1
  },
  {
    id: "G-E07",
    cluster: "ekonomi",
    level: "panjang",
    source: "gap",
    stem: "Pasar perumahan murah gagal menyediakan hunian layak untuk pekerja berpendapatan rendah karena daya beli rendah, informasi lahan terbatas, dan risiko pengembang tinggi. Paket intervensi yang paling seimbang adalah?",
    options: [
      "Menetapkan semua rumah gratis tanpa sumber pendanaan.",
      "Subsidi tepat sasaran, penyediaan prasarana dasar, informasi lahan, dan regulasi mutu minimum.",
      "Membiarkan pasar sepenuhnya karena hunian bukan urusan publik.",
      "Melarang pembangunan rumah komersial di seluruh kota.",
      "Menaikkan pajak bahan bangunan tanpa kompensasi.",
    ],
    answer: 1,
    explain: "Intervensi pemerintah perlu menjawab sumber kegagalan pasar tanpa mengabaikan keberlanjutan fiskal dan mutu layanan.",
    version: 1
  },
  {
    id: "G-E08",
    cluster: "ekonomi",
    level: "kasus",
    source: "gap",
    stem: "Pemerintah daerah ingin mengatasi harga cabai yang sangat fluktuatif. Pilihan yang paling masuk akal untuk mengurangi kegagalan pasar tanpa mendistorsi terlalu besar adalah?",
    options: [
      "Menetapkan satu harga tetap sepanjang tahun tanpa melihat pasokan.",
      "Mewajibkan petani menjual hanya ke satu pembeli.",
      "Memperbaiki informasi harga, logistik, cadangan terbatas, dan kemitraan pemasaran petani.",
      "Melarang perdagangan antardaerah agar harga lokal tidak berubah.",
      "Menghapus data harga karena menimbulkan kepanikan.",
    ],
    answer: 2,
    explain: "Intervensi yang baik memperbaiki informasi, logistik, dan koordinasi sehingga volatilitas turun dengan distorsi minimal.",
    version: 1
  },
  {
    id: "G-E09",
    cluster: "ekonomi",
    level: "singkat",
    source: "gap",
    stem: "Roti yang dibeli seseorang tidak dapat dikonsumsi orang lain dan penjual dapat mengecualikan pembeli yang tidak membayar. Dalam klasifikasi ekonomi publik, roti adalah?",
    options: [
      "Barang publik murni.",
      "Barang club.",
      "Common-pool resource.",
      "Barang private.",
      "Merit good non-rival.",
    ],
    answer: 3,
    explain: "Barang private bersifat rival dan eksklusif, sehingga pasar umumnya dapat menyediakannya.",
    version: 1
  },
  {
    id: "G-E10",
    cluster: "ekonomi",
    level: "sedang",
    source: "gap",
    stem: "Sistem peringatan dini tsunami memberi informasi kepada seluruh warga pesisir dan sulit mengecualikan orang yang tidak membayar. Kategori yang paling tepat adalah?",
    options: [
      "Barang private karena hanya satu orang dapat mendengar sirene.",
      "Barang club karena pengguna selalu dibatasi anggota.",
      "Common-pool resource karena pemakaian satu orang mengurangi sirene orang lain.",
      "Tragedy of the commons karena overuse sumber bersama tanpa aturan.",
      "Barang publik atau layanan publik dengan manfaat non-rival dan sulit dieksklusi.",
    ],
    answer: 4,
    explain: "Peringatan dini memiliki karakter non-rival dan non-excludable sehingga membutuhkan pembiayaan kolektif.",
    version: 1
  },
  {
    id: "G-E11",
    cluster: "ekonomi",
    level: "panjang",
    source: "gap",
    stem: "Jalan tol tidak macet pada jam normal dan pengguna dapat dikecualikan melalui gerbang pembayaran. Secara ekonomi, fasilitas ini mendekati?",
    options: [
      "Barang club.",
      "Barang private murni seperti makanan sekali konsumsi.",
      "Barang publik murni yang tidak dapat dipungut biaya.",
      "Common-pool resource yang selalu bebas akses.",
      "Eksternalitas negatif tanpa manfaat langsung.",
    ],
    answer: 0,
    explain: "Club goods eksklusif tetapi relatif non-rival sampai kapasitas mulai padat.",
    version: 1
  },
  {
    id: "G-E12",
    cluster: "ekonomi",
    level: "kasus",
    source: "gap",
    stem: "Danau tangkap ikan yang terbuka untuk banyak nelayan membuat tangkapan satu nelayan mengurangi stok untuk nelayan lain. Ini termasuk?",
    options: [
      "Barang publik murni.",
      "Common-pool resource atau barang bersama.",
      "Barang private karena ikan di danau tidak pernah berkurang.",
      "Barang club karena akses selalu terbatas anggota.",
      "Barang merit yang tidak perlu aturan.",
    ],
    answer: 1,
    explain: "Common-pool resource sulit dieksklusi tetapi rival dalam konsumsi, sehingga rentan overuse.",
    version: 1
  },
  {
    id: "G-E13",
    cluster: "ekonomi",
    level: "singkat",
    source: "gap",
    stem: "Jika setiap peternak menambah sapi di padang penggembalaan bersama tanpa aturan, rumput habis dan semua rugi. Konsep yang paling tepat adalah?",
    options: [
      "Adverse selection pada asuransi.",
      "Price ceiling yang menciptakan surplus.",
      "Tragedy of the commons.",
      "Barang club dengan kapasitas kosong.",
      "Monopoli alamiah jaringan listrik.",
    ],
    answer: 2,
    explain: "Tragedy of the commons terjadi ketika akses bersama dan insentif individual menyebabkan eksploitasi berlebihan.",
    version: 1
  },
  {
    id: "G-E14",
    cluster: "ekonomi",
    level: "sedang",
    source: "gap",
    stem: "Untuk mencegah overfishing di perairan lokal, kebijakan yang paling tepat adalah?",
    options: [
      "Membebaskan alat tangkap apa pun agar produksi naik cepat.",
      "Menghapus data stok ikan karena memicu konflik.",
      "Memberi subsidi bahan bakar tanpa batas.",
      "Kuota tangkap, musim larangan, pengawasan komunitas, dan hak akses yang jelas.",
      "Menaikkan harga eceran ikan dengan price ceiling.",
    ],
    answer: 3,
    explain: "Common goods perlu aturan akses, batas pemanfaatan, dan pengawasan agar stok tidak terkuras.",
    version: 1
  },
  {
    id: "G-E15",
    cluster: "ekonomi",
    level: "panjang",
    source: "gap",
    stem: "Menurut pola transformasi Chenery-Syrquin, kenaikan pendapatan per kapita biasanya disertai perubahan struktur. Faktor awal yang mendorong kapasitas produksi jangka panjang adalah?",
    options: [
      "Penurunan semua tabungan rumah tangga.",
      "Penghapusan seluruh perdagangan antardaerah.",
      "Peningkatan konsumsi mewah tanpa investasi.",
      "Pengurangan keterampilan tenaga kerja.",
      "Akumulasi modal fisik dan manusia melalui investasi, pendidikan, dan kesehatan.",
    ],
    answer: 4,
    explain: "Chenery-Syrquin menekankan akumulasi sebagai pendorong transformasi produktif dan perubahan struktur ekonomi.",
    version: 1
  },
  {
    id: "G-E16",
    cluster: "ekonomi",
    level: "kasus",
    source: "gap",
    stem: "Daerah yang tumbuh mulai menggeser tenaga kerja dari pertanian subsisten ke industri dan jasa produktif. Dalam kerangka Chenery-Syrquin, ini terutama terkait?",
    options: [
      "Perubahan alokasi sumber daya antar sektor.",
      "Kegagalan pemerintah dalam regulasi tarif.",
      "Price ceiling komoditas pangan.",
      "Barang publik non-rival.",
      "Asimetri informasi pada kredit mikro.",
    ],
    answer: 0,
    explain: "Transformasi struktural mencakup realokasi tenaga kerja dan modal dari sektor berproduktivitas rendah ke lebih tinggi.",
    version: 1
  },
  {
    id: "G-E17",
    cluster: "ekonomi",
    level: "singkat",
    source: "gap",
    stem: "Kota menengah tumbuh cepat karena migrasi desa-kota, perubahan komposisi usia kerja, dan meningkatnya partisipasi angkatan kerja perempuan. Faktor Chenery-Syrquin yang relevan adalah?",
    options: [
      "Monopoli alamiah.",
      "Transisi demografi dan urbanisasi sebagai bagian dari perubahan struktur pembangunan.",
      "Barang club.",
      "Kebijakan harga dasar.",
      "Audit kepatuhan belanja.",
    ],
    answer: 1,
    explain: "Pola Chenery-Syrquin mencakup perubahan demografi, urbanisasi, dan struktur tenaga kerja selama pembangunan.",
    version: 1
  },
  {
    id: "G-E18",
    cluster: "ekonomi",
    level: "sedang",
    source: "gap",
    stem: "Provinsi pesisir tumbuh setelah ekspor manufaktur meningkat dan impor mesin mendorong produktivitas. Dalam faktor transformasi Chenery-Syrquin, hal ini paling dekat dengan?",
    options: [
      "Tragedy of the commons.",
      "Kegagalan koordinasi antarnelayan.",
      "Perubahan perdagangan, permintaan, dan keterbukaan ekonomi.",
      "Price floor upah minimum.",
      "Barang publik lokal.",
    ],
    answer: 2,
    explain: "Transformasi struktural dipengaruhi oleh komposisi permintaan, perdagangan, teknologi, dan integrasi pasar.",
    version: 1
  },
  {
    id: "G-E19",
    cluster: "ekonomi",
    level: "panjang",
    source: "gap",
    stem: "Kabupaten A memiliki laju pertumbuhan ekonomi dan PDRB per kapita di atas rata-rata provinsi. Dalam tipologi Klassen, daerah ini masuk kategori?",
    options: [
      "Daerah maju tetapi tertekan.",
      "Daerah berkembang cepat.",
      "Daerah relatif tertinggal.",
      "Daerah maju dan tumbuh cepat.",
      "Daerah tanpa klasifikasi.",
    ],
    answer: 3,
    explain: "Tipologi Klassen memakai dua sumbu: pertumbuhan dan pendapatan per kapita relatif terhadap rata-rata wilayah acuan.",
    version: 1
  },
  {
    id: "G-E20",
    cluster: "ekonomi",
    level: "kasus",
    source: "gap",
    stem: "Kabupaten B memiliki PDRB per kapita tinggi karena basis tambang lama, tetapi pertumbuhan ekonominya di bawah rata-rata provinsi. Kategori Klassen yang tepat adalah?",
    options: [
      "Daerah maju dan tumbuh cepat.",
      "Daerah berkembang cepat.",
      "Daerah relatif tertinggal.",
      "Daerah baru tanpa aktivitas ekonomi.",
      "Daerah maju tetapi tertekan.",
    ],
    answer: 4,
    explain: "Pendapatan tinggi namun pertumbuhan rendah menunjukkan daerah maju tetapi tertekan.",
    version: 1
  },
  {
    id: "G-E21",
    cluster: "ekonomi",
    level: "singkat",
    source: "gap",
    stem: "Kabupaten C memiliki PDRB per kapita masih rendah, tetapi pertumbuhannya lebih tinggi dari rata-rata provinsi selama lima tahun. Dalam matriks Klassen, daerah ini termasuk?",
    options: [
      "Daerah berkembang cepat.",
      "Daerah maju dan tumbuh cepat.",
      "Daerah maju tetapi tertekan.",
      "Daerah relatif tertinggal.",
      "Daerah jenuh investasi.",
    ],
    answer: 0,
    explain: "Pertumbuhan tinggi namun pendapatan per kapita rendah menunjukkan potensi mengejar ketertinggalan.",
    version: 1
  },
  {
    id: "G-E22",
    cluster: "ekonomi",
    level: "sedang",
    source: "gap",
    stem: "Kabupaten D memiliki pertumbuhan ekonomi dan PDRB per kapita sama-sama di bawah rata-rata provinsi. Prioritas strategi yang paling tepat adalah?",
    options: [
      "Daerah maju cepat sehingga cukup menjaga status quo.",
      "Daerah relatif tertinggal; perlu penguatan layanan dasar, konektivitas, produktivitas lokal, dan investasi yang sesuai potensi.",
      "Daerah maju tertekan sehingga cukup mengelola sektor lama.",
      "Daerah berkembang cepat sehingga tidak perlu dukungan dasar.",
      "Daerah tanpa masalah pembangunan.",
    ],
    answer: 1,
    explain: "Kuadran tertinggal menandakan kinerja relatif rendah pada dua indikator sehingga intervensi dasar dan produktivitas diperlukan.",
    version: 1
  },
  {
    id: "G-E23",
    cluster: "ekonomi",
    level: "panjang",
    source: "gap",
    stem: "Dalam pendekatan capability, keberhasilan pembangunan tidak cukup diukur dari PDRB. Indikator yang paling sesuai adalah?",
    options: [
      "Kenaikan output industri meski akses pendidikan memburuk.",
      "Jumlah proyek fisik tanpa melihat penerima manfaat.",
      "Perluasan kemampuan warga untuk hidup sehat, berpendidikan, berpartisipasi, dan memilih kehidupan yang bernilai.",
      "Besarnya belanja aparatur sebagai ukuran kesejahteraan.",
      "Jumlah izin investasi tanpa kualitas pekerjaan.",
    ],
    answer: 2,
    explain: "Pendekatan capabilities menekankan perluasan kebebasan substantif dan kemampuan manusia, bukan hanya pendapatan.",
    version: 1
  },
  {
    id: "G-E24",
    cluster: "ekonomi",
    level: "kasus",
    source: "gap",
    stem: "Todaro menekankan pembangunan sebagai proses multidimensi. Pernyataan yang paling sesuai adalah?",
    options: [
      "Pembangunan identik dengan pertumbuhan PDRB tanpa memperhatikan distribusi.",
      "Pembangunan cukup berarti pembangunan gedung pemerintah.",
      "Pembangunan hanya terjadi jika sektor pertanian dihapus seluruhnya.",
      "Pembangunan mencakup kenaikan taraf hidup, harga diri, kebebasan memilih, serta perubahan struktur ekonomi dan kelembagaan.",
      "Pembangunan tidak membutuhkan perubahan institusi.",
    ],
    answer: 3,
    explain: "Todaro melihat pembangunan sebagai proses multidimensi: ekonomi, sosial, kelembagaan, dan peningkatan pilihan hidup.",
    version: 1
  },
  {
    id: "G-E25",
    cluster: "ekonomi",
    level: "singkat",
    source: "gap",
    stem: "Dalam rapat, seorang perencana mengingatkan bahwa liberalisasi pasar tanpa institusi, informasi, dan perlindungan kelompok rentan dapat memperlebar ketimpangan. Pandangan ini sejalan dengan?",
    options: [
      "Pandangan bahwa pasar selalu sempurna.",
      "Doktrin bahwa pemerintah tidak pernah boleh mengoreksi pasar.",
      "Konsep price floor sebagai satu-satunya alat pembangunan.",
      "Tipologi Klassen kuadran maju cepat.",
      "Stiglitz, yang menekankan informasi tidak sempurna, peran institusi, dan kualitas intervensi negara.",
    ],
    answer: 4,
    explain: "Stiglitz banyak menyoroti asimetri informasi, kegagalan pasar, dan pentingnya institusi serta kebijakan publik yang baik.",
    version: 1
  },
  {
    id: "G-E26",
    cluster: "ekonomi",
    level: "sedang",
    source: "gap",
    stem: "Subsidi pupuk dirancang untuk petani kecil, tetapi sebagian besar dinikmati petani besar karena data penerima buruk dan pengawasan lemah. Ini menunjukkan?",
    options: [
      "Kegagalan pemerintah akibat targeting error, informasi lemah, dan rent seeking.",
      "Eksternalitas positif yang selalu berhasil.",
      "Barang publik murni yang tidak bisa disalahgunakan.",
      "Monopoli alamiah yang efisien.",
      "Tragedy of the commons tanpa peran negara.",
    ],
    answer: 0,
    explain: "Government failure muncul ketika intervensi publik tidak mencapai tujuan karena desain, informasi, insentif, atau tata kelola buruk.",
    version: 1
  },
  {
    id: "G-E27",
    cluster: "ekonomi",
    level: "panjang",
    source: "gap",
    stem: "Pemerintah menetapkan izin usaha sangat rumit untuk melindungi konsumen, tetapi prosesnya menciptakan biaya tinggi dan peluang pungli. Evaluasi terbaik adalah?",
    options: [
      "Regulasi pasti efektif karena dibuat pemerintah.",
      "Regulasi mengalami kegagalan pemerintah karena biaya transaksi dan rent seeking melebihi manfaat perlindungan.",
      "Masalah ini murni kegagalan pasar tanpa unsur birokrasi.",
      "Semua izin harus ditambah agar pungli turun.",
      "Tidak perlu mengukur biaya dan manfaat regulasi.",
    ],
    answer: 1,
    explain: "Intervensi dapat gagal jika desain regulasi membuka rente, memperlambat layanan, dan tidak proporsional terhadap risikonya.",
    version: 1
  },
  {
    id: "G-E28",
    cluster: "ekonomi",
    level: "kasus",
    source: "gap",
    stem: "Pemerintah menetapkan harga dasar gabah di atas harga keseimbangan untuk melindungi petani. Dampak yang perlu diantisipasi adalah?",
    options: [
      "Kekurangan pasokan karena harga terlalu rendah.",
      "Permintaan selalu meningkat tanpa batas.",
      "Surplus pasokan jika pembelian atau penyerapan tidak disiapkan.",
      "Harga pasar pasti sama dengan nol.",
      "Tidak ada dampak pada insentif produksi.",
    ],
    answer: 2,
    explain: "Price floor di atas keseimbangan dapat menciptakan surplus karena produsen ingin menjual lebih banyak daripada yang diminta pasar.",
    version: 1
  },
  {
    id: "G-E29",
    cluster: "ekonomi",
    level: "singkat",
    source: "gap",
    stem: "Saat harga sewa rumah melonjak, pemerintah menetapkan harga maksimum di bawah keseimbangan. Risiko utama dari price ceiling tersebut adalah?",
    options: [
      "Surplus unit sewa karena harga terlalu tinggi.",
      "Produsen otomatis membangun lebih banyak rumah.",
      "Tidak ada perubahan perilaku pemilik rumah.",
      "Kekurangan pasokan, penurunan mutu, dan pasar informal jika tidak disertai kebijakan pelengkap.",
      "Semua penyewa pasti mendapat rumah lebih baik.",
    ],
    answer: 3,
    explain: "Price ceiling di bawah keseimbangan dapat menekan harga tetapi menyebabkan excess demand dan distorsi kualitas/pasokan.",
    version: 1
  },
  {
    id: "G-S01",
    cluster: "sosial",
    level: "singkat",
    source: "gap",
    stem: "Dalam SIPD, sebuah OPD mengisi indikator 'jumlah rapat koordinasi kemiskinan' untuk menilai pelaksanaan kegiatan. Indikator tersebut paling tepat disebut?",
    options: [
      "Indikator kerja karena mengukur aktivitas atau keluaran kerja yang dilakukan.",
      "Indikator kinerja utama outcome karena langsung mengukur penurunan kemiskinan.",
      "Indikator impact jangka panjang.",
      "Indikator makro nasional.",
      "Indikator gender responsif otomatis.",
    ],
    answer: 0,
    explain: "Indikator kerja cenderung mengukur aktivitas/output proses, berbeda dari indikator kinerja yang menunjukkan hasil atau capaian tujuan.",
    version: 1
  },
  {
    id: "G-S02",
    cluster: "sosial",
    level: "sedang",
    source: "gap",
    stem: "OPD ingin menilai apakah program perlindungan anak berhasil. Indikator yang paling mencerminkan kinerja adalah?",
    options: [
      "Jumlah rapat tim perlindungan anak.",
      "Persentase kasus kekerasan anak yang tertangani sesuai standar layanan dalam 30 hari.",
      "Jumlah spanduk kampanye yang dicetak.",
      "Jumlah perjalanan dinas petugas.",
      "Jumlah halaman laporan kegiatan.",
    ],
    answer: 1,
    explain: "Indikator kinerja harus menggambarkan capaian layanan atau hasil, bukan hanya aktivitas administratif.",
    version: 1
  },
  {
    id: "G-S03",
    cluster: "sosial",
    level: "panjang",
    source: "gap",
    stem: "Program pelatihan kerja melaporkan 500 peserta hadir. Kepala daerah meminta indikator yang lebih menggambarkan manfaat program. Pilihan terbaik adalah?",
    options: [
      "Jumlah kursi yang disiapkan panitia.",
      "Jumlah sertifikat yang dicetak tanpa verifikasi kerja.",
      "Persentase lulusan pelatihan yang bekerja atau berusaha dalam enam bulan.",
      "Jumlah konsumsi peserta.",
      "Jumlah surat undangan yang dikirim.",
    ],
    answer: 2,
    explain: "Output peserta hadir belum menunjukkan manfaat; outcome ketenagakerjaan lebih tepat menilai kinerja program.",
    version: 1
  },
  {
    id: "G-S04",
    cluster: "sosial",
    level: "kasus",
    source: "gap",
    stem: "Indikator 'masyarakat semakin sejahtera' ditolak karena terlalu umum. Rumusan yang lebih baik untuk SIPD adalah?",
    options: [
      "Kesejahteraan meningkat semaksimal mungkin.",
      "Masyarakat merasa lebih baik.",
      "Bantuan sosial dibagikan dengan niat baik.",
      "Persentase rumah tangga miskin ekstrem yang keluar dari status miskin ekstrem pada akhir 2026.",
      "Semua kegiatan berjalan lancar.",
    ],
    answer: 3,
    explain: "Indikator SIPD perlu jelas, terukur, dan dapat ditelusuri terhadap target serta sasaran.",
    version: 1
  },
  {
    id: "G-S05",
    cluster: "sosial",
    level: "singkat",
    source: "gap",
    stem: "Dalam Renja, kegiatan posyandu memakai indikator bayi ditimbang, tetapi sasaran program adalah penurunan stunting. Tindakan perencana yang tepat adalah?",
    options: [
      "Menghapus sasaran stunting karena sulit dicapai.",
      "Mengganti semua indikator menjadi serapan anggaran.",
      "Mencatat jumlah rapat kader sebagai indikator akhir.",
      "Mengabaikan konsistensi karena SIPD hanya aplikasi.",
      "Menambahkan indikator kinerja yang menghubungkan layanan posyandu dengan prevalensi atau risiko stunting sasaran.",
    ],
    answer: 4,
    explain: "Konsistensi indikator kerja dan kinerja penting agar aktivitas dapat ditautkan ke sasaran pembangunan.",
    version: 1
  },
  {
    id: "G-S06",
    cluster: "sosial",
    level: "sedang",
    source: "gap",
    stem: "Saat evaluasi SIPD, realisasi kegiatan tinggi tetapi outcome sosial rendah. Pertanyaan evaluatif paling penting adalah?",
    options: [
      "Apakah output kegiatan benar-benar menjangkau kelompok sasaran dan cukup kuat untuk mengubah outcome?",
      "Apakah semua foto kegiatan sudah diunggah.",
      "Apakah jumlah rapat bisa ditambah agar serapan naik.",
      "Apakah indikator outcome perlu dihapus dari dokumen.",
      "Apakah laporan dibuat lebih panjang.",
    ],
    answer: 0,
    explain: "Evaluasi kinerja harus menguji hubungan aktivitas-output-outcome dan ketepatan sasaran, bukan hanya kelengkapan administrasi.",
    version: 1
  },
  {
    id: "G-S07",
    cluster: "sosial",
    level: "panjang",
    source: "gap",
    stem: "Dalam revitalisasi pasar, asosiasi pedagang memiliki pengaruh besar dan kepentingan tinggi karena lapaknya terdampak langsung. Strategi engagement yang tepat dalam power-interest matrix adalah?",
    options: [
      "Cukup diberi informasi umum setahun sekali.",
      "Kelola secara dekat melalui konsultasi intensif, negosiasi, dan pelibatan dalam keputusan kunci.",
      "Diabaikan karena terlalu kritis.",
      "Dipuaskan minimal tanpa komunikasi.",
      "Hanya dipantau dari jauh.",
    ],
    answer: 1,
    explain: "Stakeholder high power-high interest harus dikelola dekat karena dapat menentukan keberhasilan dan terdampak besar.",
    version: 1
  },
  {
    id: "G-S08",
    cluster: "sosial",
    level: "kasus",
    source: "gap",
    stem: "Sebuah kantor vertikal memiliki kewenangan persetujuan teknis tinggi, tetapi minatnya terhadap program kampung tematik rendah. Dalam matriks power-interest, strategi yang tepat adalah?",
    options: [
      "Manage closely seperti kelompok terdampak langsung setiap hari.",
      "Abaikan sepenuhnya karena minat rendah.",
      "Keep satisfied: penuhi kebutuhan informasi strategis dan libatkan pada keputusan yang memerlukan kewenangannya.",
      "Serahkan seluruh program kepadanya.",
      "Mobilisasi protes agar minat naik.",
    ],
    answer: 2,
    explain: "High power-low interest perlu dijaga kepuasannya agar tidak menjadi penghambat, tanpa membebani komunikasi berlebihan.",
    version: 1
  },
  {
    id: "G-S09",
    cluster: "sosial",
    level: "singkat",
    source: "gap",
    stem: "Kelompok remaja difabel sangat berkepentingan pada desain taman inklusif, tetapi pengaruh formalnya rendah. Strategi yang paling tepat adalah?",
    options: [
      "Abaikan karena tidak memiliki kewenangan anggaran.",
      "Beri keputusan final tanpa konsultasi.",
      "Cukup kirim laporan teknis setelah taman selesai.",
      "Keep informed dan berdayakan kanal partisipasinya agar kebutuhan spesifik masuk desain.",
      "Minta mereka membiayai seluruh perubahan desain.",
    ],
    answer: 3,
    explain: "Low power-high interest perlu diberi informasi dan ruang aspirasi; dalam isu inklusi, pemberdayaan penting agar suara rentan tidak hilang.",
    version: 1
  },
  {
    id: "G-S10",
    cluster: "sosial",
    level: "sedang",
    source: "gap",
    stem: "Dalam program peningkatan drainase kecil, kelompok pengunjung sesekali pasar memiliki pengaruh dan kepentingan rendah. Strategi matriks yang proporsional adalah?",
    options: [
      "Kelola harian seperti pengambil keputusan utama.",
      "Berikan veto atas desain teknis.",
      "Rahasiakan seluruh informasi publik.",
      "Jadikan satu-satunya penerima manfaat.",
      "Monitor dengan komunikasi minimum sambil tetap membuka kanal keluhan.",
    ],
    answer: 4,
    explain: "Low power-low interest cukup dipantau, tetapi prinsip pelayanan publik tetap menyediakan informasi dan kanal masukan.",
    version: 1
  },
  {
    id: "G-S11",
    cluster: "sosial",
    level: "panjang",
    source: "gap",
    stem: "Konflik lahan untuk sekolah baru melibatkan pemilik tanah, warga sekitar, dinas pendidikan, DPRD, dan calon siswa. Langkah awal pemetaan stakeholder yang paling tepat adalah?",
    options: [
      "Mengidentifikasi kepentingan, tingkat pengaruh, posisi dukungan, dan risiko konflik setiap aktor.",
      "Langsung memilih aktor yang paling setuju saja.",
      "Menghapus aktor yang menolak dari daftar.",
      "Menganggap semua stakeholder memiliki pengaruh sama.",
      "Menunda pemetaan sampai konflik membesar.",
    ],
    answer: 0,
    explain: "Power-interest matrix dimulai dari identifikasi aktor, kepentingan, pengaruh, posisi, dan strategi komunikasi.",
    version: 1
  },
  {
    id: "G-S12",
    cluster: "sosial",
    level: "kasus",
    source: "gap",
    stem: "Proyek relokasi warga bantaran sungai ditolak karena warga merasa hanya diberi sosialisasi satu arah. Perbaikan strategi stakeholder terbaik adalah?",
    options: [
      "Mempercepat penggusuran agar konflik cepat selesai.",
      "Meningkatkan pelibatan warga terdampak melalui dialog, opsi kompensasi, jadwal transisi, dan mekanisme keluhan.",
      "Mengurangi informasi supaya warga tidak bertanya.",
      "Melibatkan hanya kontraktor pelaksana.",
      "Menganggap penolakan sebagai bukti warga tidak rasional.",
    ],
    answer: 1,
    explain: "Stakeholder terdampak langsung biasanya high interest; engagement harus dialogis dan menyediakan mekanisme penyelesaian keberatan.",
    version: 1
  },
  {
    id: "G-S13",
    cluster: "sosial",
    level: "singkat",
    source: "gap",
    stem: "Kelompok usaha perempuan sudah berjalan, tetapi pembukuan, akses izin, dan negosiasi pasar masih lemah. Peran petugas paling tepat adalah?",
    options: [
      "Fasilitasi satu kali lalu seluruh masalah dianggap selesai.",
      "Mengambil alih seluruh usaha kelompok secara permanen.",
      "Pendampingan berkelanjutan untuk memperkuat kapasitas kelompok sampai mampu menjalankan fungsi sendiri.",
      "Hanya memberi ceramah tanpa praktik.",
      "Membubarkan kelompok agar tidak bergantung.",
    ],
    answer: 2,
    explain: "Pendampingan menekankan proses berkelanjutan, penguatan kapasitas, dan kemandirian kelompok sasaran.",
    version: 1
  },
  {
    id: "G-S14",
    cluster: "sosial",
    level: "sedang",
    source: "gap",
    stem: "Dalam musyawarah desa, warga memiliki berbagai usulan dan perlu proses diskusi agar mencapai prioritas bersama. Peran fasilitator yang tepat adalah?",
    options: [
      "Menentukan semua keputusan sesuai preferensi pribadi fasilitator.",
      "Membaca materi tanpa memberi ruang diskusi.",
      "Menyuruh peserta mengikuti usulan tokoh terkuat.",
      "Memandu proses dialog netral, memastikan partisipasi, dan membantu kelompok menyepakati keputusan.",
      "Mengganti forum warga dengan rapat tertutup pejabat.",
    ],
    answer: 3,
    explain: "Fasilitasi berfokus pada proses, netralitas, partisipasi, dan kesepakatan kelompok.",
    version: 1
  },
  {
    id: "G-S15",
    cluster: "sosial",
    level: "panjang",
    source: "gap",
    stem: "Program pemberdayaan desa membutuhkan pelatihan administrasi BUMDes selama enam bulan dan forum musyawarah untuk memilih unit usaha. Pembedaan peran yang tepat adalah?",
    options: [
      "Fasilitasi berarti menggantikan pengurus BUMDes selama enam bulan.",
      "Pendampingan hanya berarti memimpin rapat satu kali.",
      "Keduanya sama sehingga tidak perlu dibedakan.",
      "Pendampingan selalu netral tanpa memberi arahan teknis.",
      "Pendampingan untuk penguatan kapasitas BUMDes, fasilitasi untuk memandu musyawarah pemilihan unit usaha.",
    ],
    answer: 4,
    explain: "Pendampingan lebih intensif dan berkelanjutan; fasilitasi memandu proses kelompok agar keputusan lahir secara partisipatif.",
    version: 1
  },
  {
    id: "G-S16",
    cluster: "sosial",
    level: "kasus",
    source: "gap",
    stem: "Pendamping sosial menemukan kelompok dampingan selalu menunggu keputusan pendamping sebelum bertindak. Koreksi yang tepat adalah?",
    options: [
      "Mengurangi ketergantungan dengan transfer keterampilan, coaching, dan keputusan bertahap oleh kelompok.",
      "Terus mengambil keputusan agar program cepat selesai.",
      "Menghentikan seluruh kegiatan tanpa transisi.",
      "Mengganti anggota yang bertanya terlalu banyak.",
      "Membuat laporan berhasil meski kapasitas tidak berubah.",
    ],
    answer: 0,
    explain: "Pendampingan yang baik memperkuat agency dan kemandirian, bukan menciptakan ketergantungan baru.",
    version: 1
  },
  {
    id: "G-S17",
    cluster: "sosial",
    level: "singkat",
    source: "gap",
    stem: "Menurut Chambers, kemiskinan tidak hanya rendah pendapatan. Rumah tangga miskin juga rentan sakit, tidak berdaya menghadapi aparat, terisolasi, dan lemah secara fisik. Kerangka ini dikenal sebagai?",
    options: [
      "Lima kekuatan Porter.",
      "Lima deprivasi Chambers: poverty, physical weakness, isolation, vulnerability, dan powerlessness.",
      "Lima M input produksi.",
      "Lima pilar SMART.",
      "Lima kuadran Klassen.",
    ],
    answer: 1,
    explain: "Chambers menjelaskan jebakan deprivasi yang saling menguatkan, bukan hanya kekurangan uang.",
    version: 1
  },
  {
    id: "G-S18",
    cluster: "sosial",
    level: "sedang",
    source: "gap",
    stem: "Keluarga nelayan tidak selalu miskin pada musim panen ikan, tetapi mudah jatuh miskin saat cuaca ekstrem, sakit, atau alat rusak. Dalam Chambers, kondisi ini terutama disebut?",
    options: [
      "Isolation karena lokasi selalu terpencil.",
      "Powerlessness karena tidak ada hak politik sama sekali.",
      "Vulnerability atau kerentanan terhadap guncangan.",
      "Physical weakness karena semua anggota pasti sakit.",
      "Market failure monopoli.",
    ],
    answer: 2,
    explain: "Vulnerability menggambarkan risiko jatuh atau makin miskin ketika menghadapi shock ekonomi, kesehatan, atau lingkungan.",
    version: 1
  },
  {
    id: "G-S19",
    cluster: "sosial",
    level: "panjang",
    source: "gap",
    stem: "Warga miskin kota enggan melapor pungutan liar karena takut kehilangan akses bantuan dan tidak paham prosedur pengaduan. Dalam kerangka Chambers, ini terutama menunjukkan?",
    options: [
      "Physical weakness karena kekurangan gizi.",
      "Barang publik karena laporan tidak rival.",
      "Price floor karena harga bantuan tinggi.",
      "Powerlessness karena warga tidak memiliki daya tawar dan akses efektif terhadap keputusan.",
      "Klassen maju tertekan.",
    ],
    answer: 3,
    explain: "Powerlessness adalah ketidakberdayaan dalam relasi sosial dan kelembagaan sehingga hak sulit diperjuangkan.",
    version: 1
  },
  {
    id: "G-S20",
    cluster: "sosial",
    level: "kasus",
    source: "gap",
    stem: "Program pelatihan digital hanya dilaksanakan malam hari di lokasi jauh. Data menunjukkan banyak perempuan tidak hadir karena beban pengasuhan dan keamanan transportasi. Perbaikan paling responsif gender adalah?",
    options: [
      "Menyimpulkan perempuan tidak berminat teknologi.",
      "Menghapus peserta perempuan agar target kelulusan naik.",
      "Menambah materi teknis tanpa mengubah hambatan akses.",
      "Mengadakan pelatihan hanya untuk peserta yang bisa datang malam.",
      "Menyesuaikan waktu/lokasi, menyediakan dukungan pengasuhan atau transportasi aman, dan memantau partisipasi serta hasil menurut jenis kelamin.",
    ],
    answer: 4,
    explain: "Perencanaan responsif gender mengidentifikasi hambatan akses, partisipasi, kontrol, dan manfaat yang berbeda antara kelompok.",
    version: 1
  },
  {
    id: "G-S21",
    cluster: "sosial",
    level: "singkat",
    source: "gap",
    stem: "Gedung layanan baru memiliki loket tinggi, tidak ada jalur kursi roda, dan formulir hanya cetak kecil. Rekomendasi inklusi difabel terbaik adalah?",
    options: [
      "Menerapkan desain universal, akomodasi layak, informasi aksesibel, dan pelibatan penyandang disabilitas dalam uji layanan.",
      "Membuat loket khusus di lantai dua tanpa lift.",
      "Meminta difabel membawa pendamping pribadi saja.",
      "Menunda layanan sampai semua warga tidak membutuhkan bantuan.",
      "Mengganti layanan tatap muka dengan pengumuman lisan saja.",
    ],
    answer: 0,
    explain: "Inklusi difabel membutuhkan aksesibilitas fisik, informasi, komunikasi, dan akomodasi layak sesuai prinsip desain universal.",
    version: 1
  },
  {
    id: "G-S22",
    cluster: "sosial",
    level: "sedang",
    source: "gap",
    stem: "Bappeda ingin memastikan bantuan sosial tidak bias terhadap perempuan kepala keluarga dan penyandang disabilitas. Data minimum yang perlu diminta adalah?",
    options: [
      "Total penerima saja agar sederhana.",
      "Data terpilah menurut jenis kelamin, usia, disabilitas, status rumah tangga, lokasi, dan tingkat kerentanan.",
      "Foto kegiatan tanpa identitas kelompok.",
      "Rata-rata kabupaten tanpa kelompok rentan.",
      "Jumlah rapat verifikasi.",
    ],
    answer: 1,
    explain: "Data terpilah membantu menemukan kesenjangan akses dan memastikan kelompok rentan terjangkau.",
    version: 1
  },
  {
    id: "G-S23",
    cluster: "sosial",
    level: "panjang",
    source: "gap",
    stem: "Dalam pembangunan taman kota, anak, lansia, perempuan, dan difabel memiliki kebutuhan keamanan serta akses berbeda. Prinsip GEDSI yang paling tepat adalah?",
    options: [
      "Menggunakan standar rata-rata orang dewasa laki-laki sebagai satu-satunya acuan.",
      "Menganggap desain netral pasti cocok untuk semua.",
      "Melibatkan kelompok beragam sejak perencanaan dan memastikan manfaat, keamanan, serta akses setara.",
      "Menghapus konsultasi karena memperlambat proyek.",
      "Membatasi taman hanya untuk kelompok yang paling mampu membayar.",
    ],
    answer: 2,
    explain: "GEDSI menekankan gender equality, disability, and social inclusion agar desain dan layanan tidak mengecualikan kelompok tertentu.",
    version: 1
  },
  {
    id: "G-S24",
    cluster: "sosial",
    level: "kasus",
    source: "gap",
    stem: "Dalam program Makan Bergizi Gratis di daerah terpencil, sekolah mudah dijangkau mendapat pasokan rutin, sedangkan sekolah kecil di pulau terpencil sering terlambat. Risiko kebijakan sosial yang harus dikoreksi adalah?",
    options: [
      "Keberhasilan penuh karena rata-rata kabupaten sudah tinggi.",
      "Masalah private goods sehingga pemerintah tidak boleh terlibat.",
      "Price floor beras yang otomatis menyelesaikan distribusi.",
      "Ketimpangan akses layanan; perlu desain logistik afirmatif untuk wilayah sulit dan pemantauan mutu gizi.",
      "Tidak perlu evaluasi karena program bersifat nasional.",
    ],
    answer: 3,
    explain: "Kebijakan sosial perlu memperhatikan equity; rata-rata capaian dapat menyembunyikan kelompok atau wilayah yang tertinggal.",
    version: 1
  },
  {
    id: "G-S25",
    cluster: "sosial",
    level: "singkat",
    source: "gap",
    stem: "Bantuan tunai untuk lansia miskin meningkatkan konsumsi, tetapi sebagian penerima kesulitan mencairkan bantuan karena rekening pasif dan jarak bank jauh. Rekomendasi terbaik adalah?",
    options: [
      "Menghentikan bantuan karena semua kendala berasal dari penerima.",
      "Mengganti semua bantuan dengan rapat sosialisasi.",
      "Mengabaikan biaya transportasi karena bukan indikator keuangan.",
      "Menaikkan target realisasi tanpa memperbaiki akses.",
      "Memperbaiki kanal pencairan, verifikasi rekening, layanan jemput bola, dan mekanisme pengaduan untuk lansia rentan.",
    ],
    answer: 4,
    explain: "Efektivitas kebijakan sosial ditentukan bukan hanya nominal bantuan, tetapi juga akses, administrasi, dan perlindungan kelompok rentan.",
    version: 1
  },
  {
    id: "G-P01",
    cluster: "spasial",
    level: "singkat",
    source: "gap",
    stem: "Pengembang ingin membangun ruko di zona perdagangan RDTR. Sebelum konstruksi, ia harus memastikan kesesuaian tata ruang dan persyaratan teknis bangunan. Perizinan bangunan yang relevan adalah?",
    options: [
      "PBG, yaitu Persetujuan Bangunan Gedung yang diberikan sebelum pembangunan sesuai fungsi dan standar teknis.",
      "SLF yang hanya diterbitkan sebelum desain dibuat.",
      "IMB baru tanpa mengacu sistem PBG.",
      "Sertifikat tanah tidak menggantikan PBG atau kesesuaian tata ruang.",
      "Izin lingkungan tidak menggantikan persyaratan teknis bangunan dan KKPR.",
    ],
    answer: 0,
    explain: "PBG menggantikan IMB sebagai persetujuan sebelum membangun dengan basis fungsi, standar teknis, dan kesesuaian tata ruang.",
    version: 1
  },
  {
    id: "G-P02",
    cluster: "spasial",
    level: "sedang",
    source: "gap",
    stem: "Sebuah gedung pelayanan publik selesai dibangun dan akan digunakan. Pemerintah perlu memastikan bangunan laik fungsi dari aspek keselamatan, kesehatan, kenyamanan, dan kemudahan. Dokumen yang dibutuhkan adalah?",
    options: [
      "PBG baru untuk memulai desain.",
      "SLF atau Sertifikat Laik Fungsi.",
      "KKPR untuk mengganti sertifikat tanah.",
      "AMDAL sebagai bukti semua struktur aman.",
      "SPPT PBB sebagai izin operasional gedung.",
    ],
    answer: 1,
    explain: "SLF diterbitkan setelah bangunan memenuhi persyaratan laik fungsi untuk digunakan.",
    version: 1
  },
  {
    id: "G-P03",
    cluster: "spasial",
    level: "panjang",
    source: "gap",
    stem: "Dalam sistem perizinan berbasis tata ruang, investor mengajukan kegiatan di lokasi yang belum memiliki RDTR digital. Langkah yang harus diperiksa perencana adalah?",
    options: [
      "Menerbitkan izin otomatis karena belum ada RDTR.",
      "Mengabaikan RTRW selama investasi bernilai besar.",
      "Kesesuaian Kegiatan Pemanfaatan Ruang berdasarkan RTRW, rencana rinci bila ada, dan ketentuan PP 21/2021.",
      "Meminta investor menentukan sendiri zonasi.",
      "Mengganti proses tata ruang dengan rekomendasi informal.",
    ],
    answer: 2,
    explain: "PP 21/2021 mengatur penyelenggaraan penataan ruang dan KKPR sebagai instrumen kesesuaian pemanfaatan ruang.",
    version: 1
  },
  {
    id: "G-P04",
    cluster: "spasial",
    level: "kasus",
    source: "gap",
    stem: "Bangunan pasar rakyat telah memiliki PBG, tetapi selama konstruksi terjadi perubahan struktur. Sebelum digunakan, apa yang paling tepat dilakukan?",
    options: [
      "Langsung digunakan karena PBG sudah cukup untuk seluruh umur bangunan.",
      "Menghapus kebutuhan SLF agar pedagang cepat masuk.",
      "Mengganti PBG dengan surat keterangan lurah.",
      "Memeriksa kesesuaian pelaksanaan dengan PBG dan persyaratan teknis sebelum penerbitan SLF.",
      "Menerbitkan SLF tanpa pemeriksaan teknis.",
    ],
    answer: 3,
    explain: "PBG mengatur persetujuan membangun; SLF memastikan bangunan yang selesai benar-benar laik fungsi.",
    version: 1
  },
  {
    id: "G-P05",
    cluster: "spasial",
    level: "singkat",
    source: "gap",
    stem: "Gedung kantor pemerintah mengajukan PBG tetapi desainnya belum menyediakan ramp, toilet aksesibel, dan jalur evakuasi difabel. Catatan perencana terbaik adalah?",
    options: [
      "Aksesibilitas cukup ditambahkan setelah gedung ramai.",
      "Difabel dapat dilayani di luar gedung saja.",
      "PBG hanya memeriksa warna fasad.",
      "SLF tidak terkait keselamatan dan kemudahan.",
      "Persyaratan kemudahan dan aksesibilitas harus dipenuhi sebelum PBG disetujui.",
    ],
    answer: 4,
    explain: "Standar teknis bangunan gedung mencakup keselamatan, kesehatan, kenyamanan, dan kemudahan termasuk aksesibilitas.",
    version: 1
  },
  {
    id: "G-P06",
    cluster: "spasial",
    level: "sedang",
    source: "gap",
    stem: "Bappeda ingin membuat peta tematik kemiskinan per desa di QGIS. Data tabular berisi kode desa dan angka kemiskinan, sedangkan layer batas desa memiliki kode wilayah. Langkah kunci adalah?",
    options: [
      "Melakukan join data tabular ke layer batas desa menggunakan kode wilayah yang konsisten.",
      "Menggambar ulang semua batas desa secara manual.",
      "Mengubah angka kemiskinan menjadi foto.",
      "Menghapus kode wilayah agar label lebih pendek.",
      "Menyimpan tabel tanpa sistem koordinat.",
    ],
    answer: 0,
    explain: "Peta tematik membutuhkan penggabungan atribut statistik dengan geometri wilayah melalui kunci yang sama.",
    version: 1
  },
  {
    id: "G-P07",
    cluster: "spasial",
    level: "panjang",
    source: "gap",
    stem: "Peta choropleth pengangguran kecamatan terlihat menyesatkan karena satu kelas memuat hampir semua kecamatan. Perbaikan QGIS yang tepat adalah?",
    options: [
      "Mengubah warna acak tanpa melihat data.",
      "Memilih metode klasifikasi yang sesuai seperti quantile, natural breaks, atau interval yang diuji terhadap sebaran data.",
      "Menghapus legenda agar tidak dipertanyakan.",
      "Menggunakan satu kelas untuk semua kecamatan.",
      "Mengubah proyeksi menjadi tabel Excel.",
    ],
    answer: 1,
    explain: "Klasifikasi memengaruhi interpretasi peta tematik; metode harus sesuai distribusi data dan tujuan analisis.",
    version: 1
  },
  {
    id: "G-P08",
    cluster: "spasial",
    level: "kasus",
    source: "gap",
    stem: "Layer jalan dan batas administrasi tidak bertumpuk di QGIS meskipun lokasinya sama. Penyebab teknis yang paling mungkin dan perlu dicek adalah?",
    options: [
      "Jumlah kolom atribut terlalu banyak.",
      "Warna simbol jalan terlalu gelap.",
      "Perbedaan atau kesalahan Coordinate Reference System (CRS).",
      "Nama file terlalu panjang.",
      "Legenda belum dicetak.",
    ],
    answer: 2,
    explain: "CRS yang salah atau tidak terdefinisi membuat layer tidak sejajar secara spasial.",
    version: 1
  },
  {
    id: "G-P09",
    cluster: "spasial",
    level: "singkat",
    source: "gap",
    stem: "Peta prioritas sanitasi akan dipakai dalam musrenbang. Elemen layout yang minimal harus ada agar peta dapat dibaca dan dipertanggungjawabkan adalah?",
    options: [
      "Hanya warna menarik tanpa sumber data.",
      "Logo besar tanpa legenda.",
      "Foto kegiatan sebagai pengganti skala.",
      "Judul, legenda, skala, arah utara, sumber data, tahun data, dan inset/lokasi bila perlu.",
      "Tabel anggaran tanpa geometri.",
    ],
    answer: 3,
    explain: "Layout peta tematik harus menyampaikan makna simbol, skala, orientasi, lokasi, dan sumber data.",
    version: 1
  },
  {
    id: "G-P10",
    cluster: "spasial",
    level: "sedang",
    source: "gap",
    stem: "Pembangunan stasiun baru menaikkan nilai tanah di sekitarnya. Pemerintah ingin mengambil sebagian kenaikan nilai untuk membiayai trotoar dan drainase kawasan. Instrumen ini dikenal sebagai?",
    options: [
      "Price ceiling perumahan.",
      "Common-pool resource.",
      "Stakeholder mapping.",
      "Evaluasi ex ante.",
      "Land value capture.",
    ],
    answer: 4,
    explain: "Land value capture menangkap sebagian kenaikan nilai lahan akibat investasi publik atau perubahan regulasi untuk membiayai kepentingan publik.",
    version: 1
  },
  {
    id: "G-P11",
    cluster: "spasial",
    level: "panjang",
    source: "gap",
    stem: "Kota akan membangun koridor BRT dan mempertimbangkan kontribusi pengembang di area yang mendapat tambahan koefisien lantai bangunan. Pilihan instrumen LVC yang relevan adalah?",
    options: [
      "Betterment levy, development charge, kontribusi pengembang, atau penjualan hak pengembangan tambahan.",
      "Subsidi konsumsi BBM tanpa target.",
      "Penghapusan seluruh pajak properti.",
      "Larangan semua pembangunan di koridor.",
      "Bantuan tunai tanpa hubungan dengan kenaikan nilai lahan.",
    ],
    answer: 0,
    explain: "Instrumen LVC mengaitkan manfaat kenaikan nilai lahan dengan kontribusi untuk infrastruktur atau layanan kawasan.",
    version: 1
  },
  {
    id: "G-P12",
    cluster: "spasial",
    level: "kasus",
    source: "gap",
    stem: "Penerapan LVC di kawasan transit ditolak warga karena khawatir gentrifikasi dan penggusuran. Mitigasi kebijakan yang paling tepat adalah?",
    options: [
      "Mengabaikan warga karena nilai tanah naik.",
      "Mengombinasikan LVC dengan hunian terjangkau, perlindungan penyewa, partisipasi warga, dan transparansi penggunaan dana.",
      "Menaikkan pungutan tanpa kajian kemampuan bayar.",
      "Menghapus transportasi publik agar harga tanah tidak naik.",
      "Membatasi informasi penggunaan dana.",
    ],
    answer: 1,
    explain: "LVC perlu desain sosial agar kenaikan nilai lahan tidak hanya menguntungkan pemilik modal dan tidak mendorong eksklusi.",
    version: 1
  },
  {
    id: "G-P13",
    cluster: "spasial",
    level: "singkat",
    source: "gap",
    stem: "Rencana kawasan pesisir memisahkan program pelabuhan, permukiman, mangrove, dan pariwisata tanpa analisis hubungan ruang. Asas perencanaan yang paling dilanggar adalah?",
    options: [
      "Kerahasiaan mutlak.",
      "Profit maksimum investor.",
      "Keterpaduan antar sektor, wilayah, dan pemangku kepentingan.",
      "Sentralisasi semua keputusan teknis.",
      "Penghapusan partisipasi.",
    ],
    answer: 2,
    explain: "Asas keterpaduan menuntut rencana ruang menghubungkan sektor, wilayah, lingkungan, dan aktor.",
    version: 1
  },
  {
    id: "G-P14",
    cluster: "spasial",
    level: "sedang",
    source: "gap",
    stem: "Kawasan resapan diubah menjadi perumahan tanpa memperhitungkan banjir dan daya dukung air. Asas perencanaan yang terutama diabaikan adalah?",
    options: [
      "Kompetisi harga tanah.",
      "Kerahasiaan data publik.",
      "Penyederhanaan administrasi saja.",
      "Keberlanjutan dan keserasian lingkungan.",
      "Eksklusivitas layanan.",
    ],
    answer: 3,
    explain: "Perencanaan ruang harus menjaga daya dukung, daya tampung, dan keberlanjutan lingkungan.",
    version: 1
  },
  {
    id: "G-P15",
    cluster: "spasial",
    level: "panjang",
    source: "gap",
    stem: "RDTR disusun cepat tetapi warga baru mengetahui zonasi setelah ditetapkan dan banyak usaha kecil terdampak. Kekurangan proses yang paling jelas adalah?",
    options: [
      "Terlalu banyak data spasial.",
      "Terlalu jelasnya legenda peta.",
      "Kelebihan koordinasi lintas OPD.",
      "Terlalu kuatnya evaluasi ex post.",
      "Minimnya partisipasi masyarakat dan transparansi informasi rencana.",
    ],
    answer: 4,
    explain: "Asas partisipatif mengharuskan masyarakat diberi ruang informasi dan masukan dalam perencanaan.",
    version: 1
  },
  {
    id: "G-P16",
    cluster: "spasial",
    level: "kasus",
    source: "gap",
    stem: "Investor dan warga bingung karena peta zonasi, peraturan zonasi, dan izin pemanfaatan ruang saling berbeda. Asas yang paling perlu diperkuat adalah?",
    options: [
      "Kepastian hukum melalui konsistensi dokumen rencana, aturan zonasi, dan perizinan.",
      "Ketertutupan dokumen agar tidak diperdebatkan.",
      "Kebebasan setiap petugas menafsirkan zonasi.",
      "Penghapusan standar peta.",
      "Prioritas lisan dibanding dokumen resmi.",
    ],
    answer: 0,
    explain: "Kepastian hukum membutuhkan dokumen tata ruang yang konsisten, dapat diakses, dan menjadi dasar perizinan.",
    version: 1
  },
  {
    id: "G-P17",
    cluster: "spasial",
    level: "singkat",
    source: "gap",
    stem: "Kabupaten memiliki peta rawan bencana bagus, tetapi tidak ada unit yang mampu memperbarui data, anggaran GIS minim, dan koordinasi BPBD-Bappeda lemah. Isu utamanya adalah?",
    options: [
      "Kualitas legenda peta semata.",
      "Institutional capability: kapasitas organisasi, SDM, anggaran, proses, dan koordinasi untuk menjalankan fungsi spasial.",
      "Price floor lahan.",
      "Barang private.",
      "Evaluasi impact rumah tangga.",
    ],
    answer: 1,
    explain: "Kapabilitas institusional menentukan apakah data dan rencana dapat dipelihara, digunakan, dan dikoordinasikan.",
    version: 1
  },
  {
    id: "G-P18",
    cluster: "spasial",
    level: "sedang",
    source: "gap",
    stem: "Untuk memperkuat kemampuan daerah mengelola RDTR digital, langkah paling tepat adalah?",
    options: [
      "Membeli software mahal tanpa operator.",
      "Menugaskan satu staf tanpa SOP dan anggaran.",
      "Membangun SOP pemutakhiran data, pelatihan GIS, tata kelola berbagi data, anggaran rutin, dan mandat koordinasi.",
      "Menyimpan data di komputer pribadi tanpa backup.",
      "Menghapus metadata agar file ringan.",
    ],
    answer: 2,
    explain: "Kapabilitas institusional membutuhkan orang, proses, teknologi, pendanaan, dan mandat yang jelas.",
    version: 1
  },
  {
    id: "G-P19",
    cluster: "spasial",
    level: "panjang",
    source: "gap",
    stem: "Pembangunan IKN memicu pertumbuhan wilayah sekitar. Perencana daerah penyangga harus mengantisipasi tekanan permukiman, transportasi, air, dan lingkungan. Pendekatan terbaik adalah?",
    options: [
      "Menunggu seluruh dampak terjadi sebelum membuat rencana.",
      "Mengabaikan IKN karena berada di wilayah administrasi berbeda.",
      "Mengubah semua lahan menjadi komersial tanpa kajian.",
      "Menyelaraskan RTRW/RDTR daerah penyangga dengan rencana IKN, daya dukung lingkungan, konektivitas, dan perlindungan masyarakat lokal.",
      "Melarang seluruh mobilitas penduduk.",
    ],
    answer: 3,
    explain: "IKN berdampak lintas wilayah sehingga daerah penyangga perlu integrasi tata ruang, layanan, lingkungan, dan sosial.",
    version: 1
  },
  {
    id: "G-P20",
    cluster: "spasial",
    level: "kasus",
    source: "gap",
    stem: "Sebuah Proyek Strategis Nasional melewati beberapa kabupaten dan membutuhkan sinkronisasi RTRW, pengadaan tanah, serta mitigasi sosial. Peran perencana daerah yang paling tepat adalah?",
    options: [
      "Menerbitkan semua izin tanpa memeriksa tata ruang karena status PSN.",
      "Menolak semua koordinasi karena PSN hanya urusan pusat.",
      "Menghapus konsultasi publik agar proyek cepat.",
      "Mengabaikan dampak lokal selama target nasional tercapai.",
      "Memastikan kesesuaian rencana tata ruang, integrasi program daerah, mitigasi dampak, dan koordinasi lintas kewenangan.",
    ],
    answer: 4,
    explain: "PSN tetap membutuhkan sinkronisasi spasial dan sosial; status strategis tidak menghapus prinsip tata ruang, koordinasi, dan mitigasi dampak.",
    version: 1
  }
];
