// Bank soal gap UKOM Perencana Ahli Muda batch 3 - dihasilkan build-gap300.mjs
// Jangan edit manual; jalankan: node scripts/build-gap300.mjs
const BANK_GAP3 = [
  {
    id: "G3-T01",
    cluster: "teknis",
    level: "panjang",
    source: "gap3",
    topic: "PP 17/2017 dan PP 39/2006",
    stem: "Dalam penyusunan RKP dan rencana kerja K/L, PP 17/2017 menekankan sinkronisasi perencanaan dan penganggaran, sementara PP 39/2006 menuntut pengendalian serta evaluasi pelaksanaan. Praktik yang paling tepat untuk menghubungkan keduanya adalah?",
    options: [
      "Memisahkan dokumen anggaran dari rencana agar setiap unit bebas menyesuaikan kegiatan.",
      "Mengganti evaluasi kinerja dengan daftar serapan anggaran triwulanan.",
      "Menunggu akhir periode sebelum memeriksa keterkaitan rencana dan anggaran.",
      "Mengukur sinkronisasi dari kesamaan judul program dalam dokumen.",
      "Menyusun matriks yang menautkan prioritas, kegiatan, output, alokasi, target antara, realisasi, dan tindak lanjut koreksi.",
    ],
    answer: 4,
    explain: "Sinkronisasi perlu terlihat dari rantai prioritas sampai evaluasi, bukan berhenti pada kesamaan nomenklatur atau serapan.",
    version: 1
  },
  {
    id: "G3-T02",
    cluster: "teknis",
    level: "kasus",
    source: "gap3",
    topic: "Renstra PBD",
    stem: "OPD menyusun Renstra Program Berbasis Data, tetapi indikatornya masih berupa daftar kegiatan tahunan. Koreksi paling penting agar Renstra benar-benar berorientasi hasil adalah?",
    options: [
      "Memperbanyak narasi visi agar dokumen terlihat komprehensif.",
      "Menyamakan semua target dengan realisasi tahun sebelumnya.",
      "Memindahkan seluruh indikator ke lampiran tanpa baseline.",
      "Menurunkan sasaran strategis ke indikator outcome, baseline, target tahunan, sumber data, dan penanggung jawab data.",
      "Menghapus indikator yang sulit dicapai agar laporan lebih ringan.",
    ],
    answer: 3,
    explain: "Renstra berbasis data membutuhkan ukuran hasil yang punya baseline, target, sumber data, dan akuntabilitas pemutakhiran.",
    version: 1
  },
  {
    id: "G3-T03",
    cluster: "teknis",
    level: "sedang",
    source: "gap3",
    topic: "Indikator antara",
    stem: "Program penurunan stunting menargetkan prevalensi turun dalam tiga tahun. Indikator antara yang paling berguna untuk pengendalian tahunan adalah?",
    options: [
      "Jumlah spanduk kampanye gizi yang dipasang di kantor kecamatan.",
      "Jumlah rapat koordinasi lintas perangkat daerah selama satu tahun.",
      "Persentase balita berisiko yang mendapat paket lengkap layanan gizi, kesehatan, sanitasi, dan pendampingan keluarga.",
      "Panjang laporan pelaksanaan kegiatan konvergensi stunting.",
      "Jumlah foto kegiatan posyandu dalam laporan bulanan.",
    ],
    answer: 2,
    explain: "Indikator antara menjembatani output kegiatan dengan outcome akhir sehingga dapat dipakai mengoreksi pelaksanaan lebih dini.",
    version: 1
  },
  {
    id: "G3-T04",
    cluster: "teknis",
    level: "panjang",
    source: "gap3",
    topic: "Evaluasi impact",
    stem: "Evaluasi program pelatihan digital UMKM menunjukkan peserta puas dan sertifikat terbit, tetapi penjualan belum jelas berubah. Desain evaluasi impact yang lebih kuat adalah?",
    options: [
      "Membandingkan perubahan penjualan peserta dengan kelompok pembanding yang serupa, memakai baseline dan follow-up setelah periode yang cukup.",
      "Menambah survei kepuasan pada hari penutupan pelatihan.",
      "Menganggap jumlah sertifikat sebagai dampak akhir program.",
      "Mengukur keberhasilan dari total materi presentasi yang dibagikan.",
      "Memilih testimoni peserta yang paling menarik untuk laporan.",
    ],
    answer: 0,
    explain: "Evaluasi impact perlu mengisolasi perubahan yang dapat dikaitkan dengan intervensi, bukan sekadar output atau kepuasan segera.",
    version: 1
  },
  {
    id: "G3-T05",
    cluster: "teknis",
    level: "kasus",
    source: "gap3",
    topic: "Triple bottom line",
    stem: "Rencana kawasan wisata mangrove menjanjikan PAD tinggi, tetapi berisiko mengurangi fungsi ekologis dan akses nelayan kecil. Analisis triple bottom line menuntut perencana untuk?",
    options: [
      "Memprioritaskan pendapatan daerah meski manfaat sosial dan lingkungan belum terukur.",
      "Menilai kelayakan ekonomi, dampak sosial pada nelayan, dan daya dukung ekologi sebelum menentukan desain investasi.",
      "Menolak semua kegiatan wisata tanpa melihat desain pengelolaan.",
      "Mengubah kawasan menjadi parkir agar penerimaan retribusi cepat naik.",
      "Mengukur keberhasilan dari jumlah pengunjung pada hari pertama pembukaan.",
    ],
    answer: 1,
    explain: "Triple bottom line menimbang profit, people, dan planet secara bersama agar keputusan tidak bias pada satu dimensi.",
    version: 1
  },
  {
    id: "G3-T06",
    cluster: "teknis",
    level: "sedang",
    source: "gap3",
    topic: "Efisiensi vs efektivitas",
    stem: "Dua program beasiswa menghabiskan anggaran sama. Program A menyalurkan dana lebih cepat, sedangkan Program B lebih banyak membuat siswa miskin bertahan sampai lulus. Pernyataan evaluatif yang paling tepat adalah?",
    options: [
      "Program A pasti lebih baik karena kecepatan penyaluran adalah tujuan akhir.",
      "Program B tidak relevan karena outcome pendidikan tidak perlu diukur.",
      "Program A tampak lebih efisien secara proses, tetapi Program B lebih efektif terhadap tujuan pendidikan.",
      "Kedua program tidak dapat dibandingkan karena anggarannya sama.",
      "Efisiensi dan efektivitas selalu memberi kesimpulan identik.",
    ],
    answer: 2,
    explain: "Efisiensi melihat penggunaan sumber daya atau proses, sedangkan efektivitas melihat pencapaian tujuan.",
    version: 1
  },
  {
    id: "G3-T07",
    cluster: "teknis",
    level: "kasus",
    source: "gap3",
    topic: "Musrenbang hasil",
    stem: "Hasil musrenbang kecamatan berisi 120 usulan, tetapi tidak memuat prioritas, indikator, lokasi rinci, atau kesepakatan OPD pengampu. Keluaran yang perlu diperbaiki adalah?",
    options: [
      "Daftar hadir peserta dengan tanda tangan lengkap saja.",
      "Dokumentasi foto forum dari berbagai sudut ruangan.",
      "Narasi sambutan camat sebagai bukti partisipasi.",
      "Berita acara dan matriks prioritas yang memuat masalah, lokasi, sasaran, indikator, pagu indikatif, OPD pengampu, dan status usulan.",
      "Daftar usulan mentah tanpa pembobotan.",
    ],
    answer: 3,
    explain: "Musrenbang harus menghasilkan kesepakatan yang dapat ditelusuri ke perencanaan, bukan sekadar daftar aspirasi.",
    version: 1
  },
  {
    id: "G3-T08",
    cluster: "teknis",
    level: "panjang",
    source: "gap3",
    topic: "RAN dan RKPD",
    stem: "Rencana aksi nasional penurunan emisi meminta daerah memperkuat transportasi rendah karbon, sementara RKPD daerah fokus kemacetan dan kualitas udara. Harmonisasi yang paling tepat adalah?",
    options: [
      "Menyalin semua kegiatan pusat tanpa menilai masalah transportasi daerah.",
      "Menolak rencana aksi nasional karena RKPD bersifat daerah.",
      "Memisahkan program emisi dan kemacetan agar tidak saling memengaruhi.",
      "Mengganti indikator lingkungan dengan jumlah rapat koordinasi.",
      "Memilih kegiatan yang menjawab kedua agenda, seperti angkutan umum, manajemen parkir, jalur pejalan kaki, indikator emisi, dan target kemacetan.",
    ],
    answer: 4,
    explain: "Harmonisasi mencari irisan sasaran, indikator, dan intervensi agar prioritas nasional serta daerah saling menguatkan.",
    version: 1
  },
  {
    id: "G3-T09",
    cluster: "teknis",
    level: "sedang",
    source: "gap3",
    topic: "Partisipatif vs teknokratik",
    stem: "Perencanaan partisipatif dan teknokratik sering dianggap bertentangan. Cara memadukannya secara sehat adalah?",
    options: [
      "Memakai data teknis untuk menguji kelayakan usulan warga, lalu menjelaskan alasan prioritas dan alternatif dalam forum terbuka.",
      "Menerima seluruh aspirasi warga tanpa verifikasi data dan kewenangan.",
      "Menyerahkan semua keputusan kepada model statistik tanpa konsultasi publik.",
      "Menghapus forum warga karena pakar sudah memiliki data.",
      "Menyusun daftar proyek berdasarkan urutan kedatangan proposal.",
    ],
    answer: 0,
    explain: "Partisipasi memberi legitimasi dan pengetahuan lokal, sedangkan teknokrasi menjaga kelayakan, data, dan konsistensi kebijakan.",
    version: 1
  },
  {
    id: "G3-T10",
    cluster: "teknis",
    level: "kasus",
    source: "gap3",
    topic: "PP 17/2017 sinkronisasi",
    stem: "K/L mengusulkan kegiatan prioritas baru setelah pagu indikatif disepakati, tetapi tidak menunjukkan perubahan sasaran nasional atau evidence gap. Sesuai prinsip sinkronisasi PP 17/2017, sikap perencana adalah?",
    options: [
      "Memasukkan usulan karena setiap unit berhak menambah kegiatan kapan pun.",
      "Meminta justifikasi berbasis prioritas, output, lokasi, kebutuhan anggaran, dan konsekuensi terhadap kegiatan lain sebelum memasukkan usulan.",
      "Menghapus seluruh kegiatan lama agar kegiatan baru mendapat ruang.",
      "Menunda penyusunan rencana sampai semua usulan sektoral berhenti.",
      "Menilai usulan cukup dari kesesuaian nama kegiatan dengan arahan pimpinan.",
    ],
    answer: 1,
    explain: "Perubahan usulan harus tetap terhubung dengan prioritas, output, dan konsekuensi anggaran.",
    version: 1
  },
  {
    id: "G3-T11",
    cluster: "teknis",
    level: "panjang",
    source: "gap3",
    topic: "Indikator antara",
    stem: "Dalam program reformasi birokrasi, target akhir adalah kepuasan layanan meningkat. Manakah indikator antara yang paling tajam untuk memantau perubahan sebelum survei akhir tahun?",
    options: [
      "Jumlah pegawai yang mengikuti apel pagi setiap minggu.",
      "Jumlah halaman dokumen SOP yang dicetak ulang.",
      "Persentase layanan prioritas yang memenuhi standar waktu, kanal pengaduan aktif, dan penyelesaian keluhan sesuai SLA.",
      "Jumlah banner budaya kerja di ruang pelayanan.",
      "Jumlah rapat internal tanpa catatan keputusan.",
    ],
    answer: 2,
    explain: "Indikator antara harus menangkap perubahan proses layanan yang logis menuju kepuasan pengguna.",
    version: 1
  },
  {
    id: "G3-T12",
    cluster: "teknis",
    level: "kasus",
    source: "gap3",
    topic: "Evaluasi impact",
    stem: "Program subsidi alat tangkap ramah lingkungan diklaim berhasil karena alat dibagikan seluruhnya. Namun nelayan kembali memakai alat lama setelah tiga bulan. Pertanyaan impact yang perlu dijawab adalah?",
    options: [
      "Apakah semua kuitansi pengadaan tersusun sesuai nomor urut.",
      "Apakah warna alat tangkap sesuai desain katalog.",
      "Apakah acara penyerahan bantuan dihadiri pejabat lengkap.",
      "Apakah subsidi mengubah perilaku penangkapan dan pendapatan nelayan secara berkelanjutan dibanding kondisi sebelum program.",
      "Apakah jumlah paket sama dengan rencana belanja.",
    ],
    answer: 3,
    explain: "Impact menilai perubahan perilaku dan kesejahteraan sasaran, bukan berhenti pada distribusi bantuan.",
    version: 1
  },
  {
    id: "G3-T13",
    cluster: "teknis",
    level: "sedang",
    source: "gap3",
    topic: "Efisiensi vs efektivitas",
    stem: "Sebuah intervensi sanitasi memakai biaya per sambungan rumah lebih rendah daripada daerah pembanding, tetapi banyak sambungan tidak dipakai warga. Kesimpulan paling tepat adalah?",
    options: [
      "Program berhasil penuh karena biaya satuan rendah.",
      "Penggunaan warga tidak relevan dalam evaluasi sanitasi.",
      "Biaya rendah membuktikan outcome kesehatan tercapai.",
      "Sambungan tidak terpakai cukup dicatat sebagai variasi administrasi.",
      "Efisiensi biaya perlu diakui, tetapi efektivitas rendah jika layanan tidak digunakan dan perilaku sanitasi tidak berubah.",
    ],
    answer: 4,
    explain: "Biaya satuan rendah tidak cukup jika output tidak dimanfaatkan dan outcome tidak bergerak.",
    version: 1
  },
  {
    id: "G3-E01",
    cluster: "ekonomi",
    level: "kasus",
    source: "gap3",
    topic: "DLQ interpretasi",
    stem: "Sektor ekonomi kreatif memiliki LQ di bawah 1, tetapi DLQ konsisten di atas 1 selama tiga tahun. Implikasi perencanaan yang paling hati-hati adalah?",
    options: [
      "Sektor belum menjadi basis, tetapi momentum pertumbuhannya layak diuji melalui dukungan talenta, pasar, dan infrastruktur digital.",
      "Sektor pasti sudah basis sehingga tidak perlu analisis lanjutan.",
      "Sektor harus dikeluarkan dari perencanaan karena LQ rendah.",
      "DLQ membuktikan ketimpangan pendapatan sudah turun.",
      "DLQ tidak dapat memberi informasi dinamika sektor.",
    ],
    answer: 0,
    explain: "DLQ di atas 1 memberi sinyal pertumbuhan relatif lebih cepat, bukan status basis saat ini.",
    version: 1
  },
  {
    id: "G3-E02",
    cluster: "ekonomi",
    level: "panjang",
    source: "gap3",
    topic: "Shift-share komponen",
    stem: "Analisis shift-share menunjukkan sektor logistik daerah tumbuh terutama karena komponen pertumbuhan nasional, sedangkan komponen daya saing lokal negatif. Rekomendasi yang paling tepat adalah?",
    options: [
      "Mengklaim pertumbuhan sepenuhnya akibat keunggulan lokal.",
      "Menguji hambatan lokal seperti biaya bongkar muat, konektivitas, perizinan, dan kualitas SDM karena daerah belum menangkap keunggulan sendiri.",
      "Menghentikan semua investasi logistik karena tren nasional positif.",
      "Mengabaikan komponen daya saing karena shift-share hanya menghitung inflasi.",
      "Mengganti sektor logistik dengan bantuan sosial dalam tabel PDRB.",
    ],
    answer: 1,
    explain: "Komponen daya saing negatif menunjukkan kinerja lokal tertinggal dari tren yang lebih luas.",
    version: 1
  },
  {
    id: "G3-E03",
    cluster: "ekonomi",
    level: "sedang",
    source: "gap3",
    topic: "ICOR angka",
    stem: "Jika tambahan investasi Rp8 triliun menghasilkan tambahan output Rp2 triliun, nilai ICOR sederhana adalah?",
    options: [
      "0,25 karena output dibagi investasi.",
      "2 karena investasi dikurangi output.",
      "4, karena ICOR adalah tambahan investasi dibagi tambahan output.",
      "6 karena investasi dan output dijumlahkan lalu dibagi dua.",
      "10 karena investasi dan output harus dijumlahkan.",
    ],
    answer: 2,
    explain: "ICOR sederhana dihitung sebagai delta modal atau investasi dibagi delta output.",
    version: 1
  },
  {
    id: "G3-E04",
    cluster: "ekonomi",
    level: "kasus",
    source: "gap3",
    topic: "Gini redistribusi",
    stem: "Gini daerah meningkat setelah kawasan industri tumbuh karena pekerja lokal berpendidikan rendah tidak masuk rantai nilai utama. Kebijakan redistribusi yang paling produktif adalah?",
    options: [
      "Menaikkan PDRB tanpa melihat siapa yang menikmati manfaat.",
      "Menghapus pengukuran Gini agar citra investasi membaik.",
      "Membatasi pendidikan vokasi untuk pekerja luar daerah.",
      "Pelatihan terarah, beasiswa vokasi, dukungan UMKM pemasok, dan perlindungan sosial untuk kelompok tertinggal.",
      "Menyamaratakan bantuan tanpa memeriksa kelompok terbawah.",
    ],
    answer: 3,
    explain: "Redistribusi produktif memperluas akses kemampuan dan manfaat pertumbuhan bagi kelompok yang tertinggal.",
    version: 1
  },
  {
    id: "G3-E05",
    cluster: "ekonomi",
    level: "sedang",
    source: "gap3",
    topic: "Merit goods",
    stem: "Imunisasi dan pendidikan dasar disebut merit goods terutama karena?",
    options: [
      "Keduanya tidak pernah memerlukan biaya produksi.",
      "Keduanya dapat dikonsumsi tanpa kapasitas layanan.",
      "Keduanya tidak memberi manfaat kepada orang lain.",
      "Keduanya harus disediakan eksklusif oleh pasar.",
      "Manfaat sosialnya besar dan masyarakat dapat mengonsumsi terlalu sedikit jika akses, informasi, atau kemampuan bayar terbatas.",
    ],
    answer: 4,
    explain: "Merit goods sering didorong pemerintah karena manfaat sosialnya kurang diperhitungkan oleh keputusan individu.",
    version: 1
  },
  {
    id: "G3-E06",
    cluster: "ekonomi",
    level: "kasus",
    source: "gap3",
    topic: "Normal vs inferior goods",
    stem: "Ketika pendapatan rumah tangga naik, konsumsi mi instan murah menurun dan konsumsi protein segar meningkat. Interpretasi yang paling tepat adalah?",
    options: [
      "Mi instan murah dalam kasus ini berperilaku sebagai barang inferior, sedangkan protein segar cenderung barang normal.",
      "Keduanya pasti barang publik karena dikonsumsi banyak orang.",
      "Protein segar adalah barang inferior karena lebih mahal.",
      "Mi instan murah pasti barang Giffen dalam semua kondisi.",
      "Perubahan pendapatan tidak dapat memengaruhi pola konsumsi.",
    ],
    answer: 0,
    explain: "Barang inferior dikonsumsi lebih sedikit saat pendapatan naik, sedangkan barang normal naik seiring pendapatan.",
    version: 1
  },
  {
    id: "G3-E07",
    cluster: "ekonomi",
    level: "sedang",
    source: "gap3",
    topic: "Multiplier sederhana",
    stem: "Jika pemerintah daerah membelanjakan Rp100 miliar untuk proyek padat karya dan marginal propensity to consume lokal 0,8, multiplier Keynesian sederhana adalah?",
    options: [
      "0,2, sehingga dampak pasti turun menjadi Rp20 miliar.",
      "5, sehingga potensi dampak pendapatan bruto dapat mencapai Rp500 miliar sebelum kebocoran lain diperhitungkan.",
      "1,25, karena multiplier adalah 1 dikali MPC.",
      "8, karena MPC dikalikan 10.",
      "100, karena belanja awal menjadi multiplier.",
    ],
    answer: 1,
    explain: "Multiplier sederhana adalah 1/(1-MPC), sehingga 1/(1-0,8)=5.",
    version: 1
  },
  {
    id: "G3-E08",
    cluster: "ekonomi",
    level: "panjang",
    source: "gap3",
    topic: "Economic base export",
    stem: "Dalam teori economic base, mengapa ekspor komoditas olahan ke luar daerah dapat mendorong pertumbuhan lokal?",
    options: [
      "Ekspor membuat uang keluar sehingga kegiatan lokal pasti turun.",
      "Sektor basis adalah sektor yang melayani warga setempat saja.",
      "Pendapatan dari luar daerah masuk, meningkatkan permintaan lokal, dan memicu kegiatan non-basis melalui belanja turunan.",
      "Pertumbuhan lokal hanya ditentukan oleh jumlah kantor pemerintah.",
      "Ekspor tidak terkait pendapatan karena barang berpindah lokasi.",
    ],
    answer: 2,
    explain: "Sektor basis membawa permintaan eksternal yang menjadi penggerak pendapatan dan multiplier lokal.",
    version: 1
  },
  {
    id: "G3-E09",
    cluster: "ekonomi",
    level: "kasus",
    source: "gap3",
    topic: "Phillips dan fiskal",
    stem: "Pengangguran naik karena permintaan melemah, sementara inflasi inti rendah. Dalam kerangka Phillips jangka pendek, respons fiskal daerah yang paling masuk akal adalah?",
    options: [
      "Memotong seluruh belanja produktif agar pengangguran turun sendiri.",
      "Menaikkan pajak konsumsi tajam saat daya beli lemah.",
      "Membiarkan proyek tertunda walau pekerja banyak menganggur.",
      "Belanja publik terarah dan padat karya yang menjaga daya beli tanpa mendorong tekanan harga berlebihan.",
      "Mendorong permintaan pada sektor pasokan terbatas tanpa mitigasi inflasi.",
    ],
    answer: 3,
    explain: "Saat inflasi rendah dan pengangguran tinggi, stimulus fiskal terarah dapat membantu permintaan dan pekerjaan dengan tetap memperhatikan risiko harga.",
    version: 1
  },
  {
    id: "G3-E10",
    cluster: "ekonomi",
    level: "sedang",
    source: "gap3",
    topic: "Oligopoli",
    stem: "Pasar semen daerah dikuasai tiga distributor besar yang saling memantau harga dan enggan menurunkan margin. Risiko utama struktur oligopoli tersebut adalah?",
    options: [
      "Harga pasti turun ke biaya marjinal seperti persaingan sempurna.",
      "Konsumen selalu memperoleh pilihan tidak terbatas.",
      "Distributor kecil otomatis menguasai pasar.",
      "Struktur pasar tidak memengaruhi harga.",
      "Harga dapat tetap tinggi karena interdependensi strategi dan hambatan masuk bagi pesaing baru.",
    ],
    answer: 4,
    explain: "Oligopoli membuat keputusan harga saling bergantung dan dapat mengurangi tekanan persaingan.",
    version: 1
  },
  {
    id: "G3-E11",
    cluster: "ekonomi",
    level: "kasus",
    source: "gap3",
    topic: "DLQ interpretasi",
    stem: "Sektor pertanian memiliki LQ tinggi, tetapi DLQ turun di bawah 1 karena produktivitas stagnan dan tenaga kerja muda keluar. Pesan kebijakan yang paling tepat adalah?",
    options: [
      "Basis saat ini perlu diremajakan melalui produktivitas, hilirisasi, dan regenerasi agar tidak melemah secara relatif.",
      "Sektor pasti aman karena LQ tinggi pada satu tahun pengamatan.",
      "DLQ rendah berarti sektor tidak pernah menyumbang ekonomi daerah.",
      "LQ tinggi membuat inovasi tidak diperlukan.",
      "Perencana cukup menaikkan target tanpa intervensi.",
    ],
    answer: 0,
    explain: "LQ menggambarkan posisi saat ini, sedangkan DLQ memberi peringatan tentang arah dinamika relatif.",
    version: 1
  },
  {
    id: "G3-E12",
    cluster: "ekonomi",
    level: "panjang",
    source: "gap3",
    topic: "Shift-share komponen",
    stem: "Komponen bauran industri dalam shift-share sektor farmasi daerah positif, tetapi komponen kompetitif lokal negatif. Interpretasi yang paling tepat adalah?",
    options: [
      "Sektor farmasi pasti tidak memiliki pasar nasional.",
      "Sektor berada pada industri yang tumbuh cepat secara acuan, tetapi kinerja lokal kalah dibanding daerah lain dalam industri yang sama.",
      "Komponen positif berarti semua aspek lokal sudah unggul.",
      "Komponen kompetitif tidak berguna untuk strategi daerah.",
      "Pertumbuhan farmasi hanya dipengaruhi jumlah penduduk miskin.",
    ],
    answer: 1,
    explain: "Bauran industri positif menunjukkan sektor acuan sedang menarik, sementara komponen kompetitif negatif menunjukkan masalah lokal.",
    version: 1
  },
  {
    id: "G3-E13",
    cluster: "ekonomi",
    level: "kasus",
    source: "gap3",
    topic: "ICOR angka",
    stem: "ICOR daerah turun dari 6 menjadi 4, tetapi investasi terkonsentrasi pada tambang padat modal dengan serapan kerja rendah. Kehati-hatian analitis yang tepat adalah?",
    options: [
      "ICOR turun membuktikan semua warga mendapat pekerjaan layak.",
      "Analisis sosial tidak diperlukan jika rasio makro membaik.",
      "Efisiensi output membaik secara agregat, namun dampak inklusi kerja dan keberlanjutan lingkungan tetap perlu diuji.",
      "ICOR rendah berarti investasi bebas risiko lingkungan.",
      "Serapan kerja tidak berkaitan dengan kualitas pertumbuhan.",
    ],
    answer: 2,
    explain: "ICOR agregat perlu dibaca bersama indikator distribusi manfaat, pekerjaan, dan keberlanjutan.",
    version: 1
  },
  {
    id: "G3-E14",
    cluster: "ekonomi",
    level: "sedang",
    source: "gap3",
    topic: "Merit goods",
    stem: "Mengapa subsidi transportasi pelajar miskin dapat dibaca sebagai kebijakan merit good?",
    options: [
      "Karena transportasi pelajar tidak membutuhkan kendaraan dan pengemudi.",
      "Karena semua perjalanan adalah barang publik murni.",
      "Karena subsidi membuat pendidikan tidak lagi memiliki manfaat privat.",
      "Karena membantu konsumsi layanan pendidikan yang manfaat sosialnya besar dan sering terkendala biaya akses.",
      "Karena pelajar miskin tidak perlu memilih sekolah.",
    ],
    answer: 3,
    explain: "Subsidi akses dapat mencegah under-consumption pendidikan akibat biaya perjalanan.",
    version: 1
  },
  {
    id: "G3-E15",
    cluster: "ekonomi",
    level: "panjang",
    source: "gap3",
    topic: "Oligopoli",
    stem: "Empat perusahaan penggilingan padi besar membeli gabah dari banyak petani kecil. Jika mereka memiliki kekuatan tawar tinggi, kebijakan daerah yang paling proporsional adalah?",
    options: [
      "Membiarkan asimetri tawar karena petani pasti mendapat harga adil.",
      "Melarang semua penggilingan besar beroperasi tanpa analisis pasokan.",
      "Menetapkan satu harga tetap sepanjang tahun tanpa melihat kualitas gabah.",
      "Menghapus data harga agar pasar tidak bereaksi.",
      "Memperkuat informasi harga, koperasi petani, akses gudang, pembiayaan, dan pengawasan persaingan tanpa menetapkan harga sembarangan.",
    ],
    answer: 4,
    explain: "Kekuatan pasar pembeli dapat ditekan melalui transparansi, kelembagaan petani, dan pengawasan yang proporsional.",
    version: 1
  },
  {
    id: "G3-S01",
    cluster: "sosial",
    level: "sedang",
    source: "gap3",
    topic: "Transect walk",
    stem: "Dalam transect walk, tim menemukan area permukiman bawah sering tergenang karena saluran tertutup sampah dan elevasi rendah. Keluaran PRA yang paling berguna adalah?",
    options: [
      "Sketsa lintasan, titik masalah, penyebab lokal, kelompok terdampak, dan prioritas tindakan yang disepakati warga.",
      "Daftar belanja alat kebersihan tanpa lokasi masalah.",
      "Foto kegiatan tanpa catatan ruang dan aktor.",
      "Kesimpulan tunggal dari fasilitator tanpa validasi warga.",
      "Peta administrasi kabupaten tanpa detail dusun.",
    ],
    answer: 0,
    explain: "Transect walk menghubungkan pengamatan ruang dengan pengetahuan warga dan prioritas tindakan.",
    version: 1
  },
  {
    id: "G3-S02",
    cluster: "sosial",
    level: "kasus",
    source: "gap3",
    topic: "Social mapping",
    stem: "Program rumah layak huni gagal menjangkau janda lansia karena ia tidak dekat dengan pengurus RT dan tidak tercatat sebagai penerima. Social mapping seharusnya membantu dengan cara?",
    options: [
      "Mengambil data dari tokoh dominan sebagai sumber tunggal.",
      "Memetakan jaringan kuasa, kelompok rentan, akses informasi, dan warga yang tidak terlihat dalam daftar formal.",
      "Mengabaikan relasi sosial karena bantuan rumah bersifat teknis.",
      "Mengurutkan penerima berdasarkan kedekatan dengan panitia.",
      "Menghapus warga yang tidak hadir dalam rapat malam.",
    ],
    answer: 1,
    explain: "Social mapping membantu melihat struktur sosial, akses, dan eksklusi yang tidak tampak dalam data administratif.",
    version: 1
  },
  {
    id: "G3-S03",
    cluster: "sosial",
    level: "sedang",
    source: "gap3",
    topic: "IPM komponen",
    stem: "Komponen utama IPM yang digunakan untuk membaca kualitas pembangunan manusia adalah?",
    options: [
      "Jumlah kantor pemerintahan, luas jalan, dan nilai investasi.",
      "Produksi beras, PAD, dan jumlah pasar modern.",
      "Umur panjang dan hidup sehat, pengetahuan, serta standar hidup layak.",
      "Jumlah rapat OPD, dokumen perencanaan, dan serapan anggaran.",
      "Kepadatan penduduk, luas wilayah, dan jumlah desa.",
    ],
    answer: 2,
    explain: "IPM menggabungkan dimensi kesehatan, pendidikan, dan standar hidup layak.",
    version: 1
  },
  {
    id: "G3-S04",
    cluster: "sosial",
    level: "panjang",
    source: "gap3",
    topic: "Kemiskinan ekstrem",
    stem: "Daerah ingin menurunkan kemiskinan ekstrem, tetapi bantuan tersebar ke rumah tangga miskin umum tanpa memprioritaskan desil terbawah. Perbaikan strategi yang paling tepat adalah?",
    options: [
      "Membagi bantuan sama rata ke semua penduduk agar proses cepat.",
      "Menghapus verifikasi lapangan karena data awal cukup untuk semua kasus.",
      "Mengalihkan semua anggaran ke kegiatan seremonial anti-kemiskinan.",
      "Menggunakan data mikro terpadu untuk memprioritaskan keluarga ekstrem, memastikan paket bantuan lengkap, dan memantau perubahan kesejahteraan.",
      "Mengukur keberhasilan dari jumlah rapat koordinasi kemiskinan.",
    ],
    answer: 3,
    explain: "Kemiskinan ekstrem membutuhkan targeting presisi, konvergensi layanan, dan pemantauan rumah tangga sasaran.",
    version: 1
  },
  {
    id: "G3-S05",
    cluster: "sosial",
    level: "kasus",
    source: "gap3",
    topic: "Remitansi",
    stem: "Banyak keluarga pekerja migran menerima remitansi, tetapi sebagian besar dipakai untuk konsumsi jangka pendek dan biaya sosial. Kebijakan pemberdayaan yang paling sesuai adalah?",
    options: [
      "Membatasi seluruh konsumsi keluarga penerima remitansi.",
      "Menganggap remitansi selalu cukup menggantikan layanan publik.",
      "Memungut biaya tinggi dari remitansi untuk menambah PAD.",
      "Menghapus pendampingan karena uang berasal dari luar negeri.",
      "Literasi keuangan, akses tabungan aman, investasi produktif kecil, dan perlindungan keluarga migran dari biaya informal.",
    ],
    answer: 4,
    explain: "Remitansi dapat memperkuat ketahanan keluarga jika didukung pengelolaan keuangan dan perlindungan yang baik.",
    version: 1
  },
  {
    id: "G3-S06",
    cluster: "sosial",
    level: "panjang",
    source: "gap3",
    topic: "Desa berdaya",
    stem: "Desa disebut berdaya bukan karena banyak menerima proyek, tetapi karena?",
    options: [
      "Warga dan kelembagaan lokal mampu mengenali masalah, mengelola aset, mengambil keputusan inklusif, dan mempertanggungjawabkan hasil.",
      "Semua keputusan pembangunan diambil oleh konsultan luar.",
      "Bantuan datang tanpa proses musyawarah dan pengawasan warga.",
      "Kegiatan desa bergantung pada tokoh tunggal yang menentukan penerima.",
      "Dokumen desa dibuat rapi meski warga tidak memahami isinya.",
    ],
    answer: 0,
    explain: "Pemberdayaan menekankan kapasitas, kontrol, inklusi, dan akuntabilitas lokal.",
    version: 1
  },
  {
    id: "G3-S07",
    cluster: "sosial",
    level: "kasus",
    source: "gap3",
    topic: "Perencanaan berbasis komunitas",
    stem: "Komunitas pesisir menyusun rencana adaptasi abrasi. Agar rencana berbasis komunitas tidak sekadar konsultasi formal, proses yang perlu dijaga adalah?",
    options: [
      "Rencana selesai di kantor konsultan lalu dimintakan tanda tangan warga.",
      "Warga memetakan risiko, memilih prioritas, membagi peran, menyepakati indikator, dan mendapat akses informasi teknis yang mudah dipahami.",
      "Masukan warga dibatasi pada warna desain papan informasi.",
      "Kelompok nelayan kecil dilibatkan setelah keputusan anggaran final.",
      "Data risiko disimpan agar warga tidak khawatir.",
    ],
    answer: 1,
    explain: "Community-based planning menempatkan komunitas sebagai pelaku analisis dan keputusan, dengan dukungan teknis yang dapat diakses.",
    version: 1
  },
  {
    id: "G3-S08",
    cluster: "sosial",
    level: "sedang",
    source: "gap3",
    topic: "UU Perlindungan Disabilitas",
    stem: "Dalam perspektif UU Penyandang Disabilitas, layanan publik inklusif menuntut pemerintah daerah untuk?",
    options: [
      "Menyediakan layanan bila ada sisa anggaran kegiatan sosial.",
      "Memisahkan semua warga difabel dari ruang layanan umum.",
      "Menyediakan aksesibilitas, akomodasi yang layak, data kebutuhan, dan pelibatan penyandang disabilitas dalam perencanaan layanan.",
      "Menyerahkan seluruh dukungan kepada keluarga masing-masing.",
      "Membatasi kanal pengaduan karena penyesuaian layanan sulit.",
    ],
    answer: 2,
    explain: "Hak penyandang disabilitas menuntut akses setara, akomodasi layak, dan partisipasi bermakna.",
    version: 1
  },
  {
    id: "G3-S09",
    cluster: "sosial",
    level: "kasus",
    source: "gap3",
    topic: "Anggaran responsif gender",
    stem: "Program revitalisasi pasar meningkatkan kios, tetapi tidak menyediakan ruang laktasi, toilet aman, dan penerangan bagi pedagang perempuan yang pulang malam. Respons anggaran responsif gender adalah?",
    options: [
      "Menyatakan pasar netral gender karena semua pedagang membayar retribusi.",
      "Mengganti fasilitas dasar dengan seminar pemberdayaan satu hari.",
      "Menghapus data pedagang perempuan agar desain lebih sederhana.",
      "Memasukkan kebutuhan keamanan, fasilitas pendukung, indikator manfaat terpilah, dan alokasi yang menjawab hambatan perempuan.",
      "Menunggu keluhan viral sebelum mengubah desain.",
    ],
    answer: 3,
    explain: "Anggaran responsif gender melihat akses, partisipasi, kontrol, dan manfaat yang berbeda antar kelompok.",
    version: 1
  },
  {
    id: "G3-S10",
    cluster: "sosial",
    level: "panjang",
    source: "gap3",
    topic: "Social mapping",
    stem: "Pemetaan sosial di kawasan kumuh menemukan penyewa kontrakan tidak ikut musyawarah karena dianggap bukan warga tetap, padahal mereka paling rentan banjir. Implikasi perencanaan yang tepat adalah?",
    options: [
      "Penyewa dapat diabaikan karena tidak memiliki sertifikat tanah.",
      "Musyawarah cukup mewakili pemilik bangunan yang hadir.",
      "Program banjir sebaiknya ditunda sampai penyewa pindah.",
      "Data kerentanan tidak perlu membedakan status hunian.",
      "Mekanisme partisipasi dan data sasaran perlu memasukkan penyewa rentan agar manfaat program tidak hanya diterima pemilik rumah.",
    ],
    answer: 4,
    explain: "Pemetaan sosial mengungkap kelompok rentan yang mudah tersisih dari proses formal.",
    version: 1
  },
  {
    id: "G3-S11",
    cluster: "sosial",
    level: "sedang",
    source: "gap3",
    topic: "IPM komponen",
    stem: "Jika IPM naik karena pengeluaran per kapita membaik, tetapi harapan lama sekolah stagnan, catatan kebijakan yang paling tepat adalah?",
    options: [
      "Perbaikan ekonomi belum otomatis memperkuat dimensi pendidikan sehingga intervensi akses dan mutu sekolah tetap diperlukan.",
      "Kenaikan satu dimensi membuat seluruh dimensi IPM tidak perlu diperiksa.",
      "Harapan lama sekolah tidak berhubungan dengan pembangunan manusia.",
      "Pengeluaran per kapita cukup untuk menggantikan layanan pendidikan.",
      "IPM hanya mengukur pendapatan daerah.",
    ],
    answer: 0,
    explain: "IPM perlu dibaca per dimensi agar kebijakan tidak menutup kelemahan pada pendidikan atau kesehatan.",
    version: 1
  },
  {
    id: "G3-S12",
    cluster: "sosial",
    level: "kasus",
    source: "gap3",
    topic: "Kemiskinan ekstrem",
    stem: "Keluarga miskin ekstrem menerima bantuan pangan, tetapi anaknya putus sekolah dan rumah belum memiliki sanitasi. Pendekatan yang paling tepat adalah?",
    options: [
      "Menambah bantuan pangan saja karena satu program lebih mudah dilaporkan.",
      "Konvergensi bantuan sosial, pendidikan, kesehatan, sanitasi, dan pendampingan keluarga berdasarkan profil kebutuhan rumah tangga.",
      "Mengeluarkan keluarga dari sasaran karena masalahnya terlalu banyak.",
      "Menunggu pendapatan naik tanpa intervensi layanan dasar.",
      "Mengganti semua bantuan dengan acara motivasi.",
    ],
    answer: 1,
    explain: "Kemiskinan ekstrem bersifat multidimensi sehingga perlu paket layanan yang saling melengkapi.",
    version: 1
  },
  {
    id: "G3-S13",
    cluster: "sosial",
    level: "panjang",
    source: "gap3",
    topic: "Remitansi",
    stem: "Remitansi meningkatkan konsumsi desa, tetapi harga tanah naik dan keluarga non-migran makin sulit membeli lahan. Analisis sosial yang paling tepat adalah?",
    options: [
      "Remitansi pasti menguntungkan semua warga dengan proporsi sama.",
      "Kenaikan harga tanah tidak terkait struktur sosial desa.",
      "Remitansi membawa manfaat sekaligus risiko ketimpangan lokal sehingga perlu kebijakan akses lahan, usaha produktif, dan perlindungan kelompok non-penerima.",
      "Keluarga non-migran harus dikeluarkan dari program desa.",
      "Perencana cukup mencatat total uang masuk tanpa melihat distribusi.",
    ],
    answer: 2,
    explain: "Dampak remitansi perlu dibaca dari sisi distribusi manfaat, harga aset, dan kerentanan kelompok yang tidak menerima.",
    version: 1
  },
  {
    id: "G3-P01",
    cluster: "spasial",
    level: "kasus",
    source: "gap3",
    topic: "Mitigasi banjir struktur",
    stem: "Kota hilir ingin membangun tanggul tinggi untuk mengurangi banjir, tetapi kapasitas sungai dan drainase lingkungan tetap buruk. Mitigasi struktural yang lebih utuh adalah?",
    options: [
      "Membangun tanggul saja tanpa rencana operasi dan pemeliharaan.",
      "Menutup semua saluran kecil agar air tidak terlihat di permukiman.",
      "Mengandalkan pompa darurat tanpa peta genangan.",
      "Menggabungkan tanggul, kolam retensi, normalisasi selektif, drainase lingkungan, operasi pintu air, dan pemeliharaan berbasis risiko.",
      "Memindahkan banjir ke wilayah tetangga tanpa koordinasi.",
    ],
    answer: 3,
    explain: "Mitigasi struktural banjir perlu dirancang sebagai sistem, bukan satu bangunan terpisah.",
    version: 1
  },
  {
    id: "G3-P02",
    cluster: "spasial",
    level: "panjang",
    source: "gap3",
    topic: "Adaptasi iklim RDTR",
    stem: "RDTR kawasan pesisir disusun tanpa memperhitungkan kenaikan muka laut dan rob yang makin sering. Integrasi adaptasi iklim yang paling tepat adalah?",
    options: [
      "Menetapkan seluruh pesisir sebagai komersial agar nilai lahan naik.",
      "Menggunakan data rob lama tanpa skenario perubahan iklim.",
      "Menghapus zona rawan dari peta agar investasi tidak khawatir.",
      "Membuat aturan sama untuk semua blok meski tingkat bahaya berbeda.",
      "Memasukkan peta bahaya iklim, aturan zonasi adaptif, elevasi bangunan, sempadan aman, ruang retensi, dan jalur evakuasi.",
    ],
    answer: 4,
    explain: "RDTR dapat menjadi instrumen adaptasi melalui zonasi, ketentuan pemanfaatan ruang, dan standar bangunan berbasis risiko.",
    version: 1
  },
  {
    id: "G3-P03",
    cluster: "spasial",
    level: "sedang",
    source: "gap3",
    topic: "Tapak bangunan",
    stem: "Dalam analisis tapak bangunan fasilitas publik, aspek yang paling perlu diperiksa sebelum desain detail adalah?",
    options: [
      "Kemiringan lahan, akses, drainase, orientasi, utilitas, risiko bencana, dan hubungan dengan lingkungan sekitar.",
      "Warna cat gedung dan nama ruang rapat utama.",
      "Jumlah undangan peresmian dan desain spanduk.",
      "Preferensi kontraktor terhadap merek material tertentu.",
      "Panjang sambutan kepala daerah saat peletakan batu pertama.",
    ],
    answer: 0,
    explain: "Analisis tapak memastikan bangunan sesuai kondisi fisik, akses, utilitas, risiko, dan konteks sekitar.",
    version: 1
  },
  {
    id: "G3-P04",
    cluster: "spasial",
    level: "kasus",
    source: "gap3",
    topic: "ROW jalan",
    stem: "Pengembang ingin membangun kios permanen di ruang milik jalan karena lokasi ramai. Pertimbangan ROW jalan yang paling tepat adalah?",
    options: [
      "Kios dapat dibangun jika ramai pembeli meski mengganggu utilitas.",
      "Ruang milik jalan harus menjaga fungsi jalan, keselamatan, utilitas, drainase, pelebaran, dan akses pemeliharaan.",
      "ROW jalan hanya berlaku setelah jalan rusak.",
      "Ruang milik jalan dapat diabaikan jika retribusi tinggi.",
      "Keselamatan pejalan kaki cukup ditangani dengan imbauan.",
    ],
    answer: 1,
    explain: "ROW melindungi fungsi jalan dan ruang pendukungnya dari pemanfaatan yang mengganggu keselamatan serta operasi.",
    version: 1
  },
  {
    id: "G3-P05",
    cluster: "spasial",
    level: "panjang",
    source: "gap3",
    topic: "Kawasan lindung",
    stem: "Usulan vila masuk ke lereng curam yang berfungsi sebagai kawasan lindung resapan air. Sikap perencana tata ruang yang paling tepat adalah?",
    options: [
      "Menyetujui vila karena investasi properti meningkatkan pajak daerah.",
      "Mengubah fungsi lindung melalui notulen rapat teknis.",
      "Menolak atau mengarahkan ulang pemanfaatan ke lokasi sesuai zonasi, sambil menjaga fungsi lindung dan mitigasi risiko longsor.",
      "Membiarkan pembangunan selama desain bangunan terlihat hijau.",
      "Menghapus informasi lereng dari peta kerja.",
    ],
    answer: 2,
    explain: "Kawasan lindung memiliki fungsi ekologis dan risiko yang harus dijaga melalui pengendalian pemanfaatan ruang.",
    version: 1
  },
  {
    id: "G3-P06",
    cluster: "spasial",
    level: "sedang",
    source: "gap3",
    topic: "Citra NDVI",
    stem: "Dalam interpretasi citra, nilai NDVI yang tinggi umumnya menunjukkan?",
    options: [
      "Permukaan kedap air yang sangat panas.",
      "Kedalaman sungai yang lebih besar.",
      "Kepadatan bangunan bertingkat.",
      "Vegetasi lebih rapat atau sehat dibanding area dengan NDVI rendah.",
      "Status kepemilikan lahan.",
    ],
    answer: 3,
    explain: "NDVI memakai perbedaan reflektansi merah dan inframerah dekat untuk membaca kondisi vegetasi.",
    version: 1
  },
  {
    id: "G3-P07",
    cluster: "spasial",
    level: "kasus",
    source: "gap3",
    topic: "Overlay flood",
    stem: "Bappeda ingin mengidentifikasi sekolah yang berada pada zona banjir 25 tahunan dan melayani anak dari keluarga miskin. Analisis SIG yang paling tepat adalah?",
    options: [
      "Mengubah simbol sekolah menjadi warna biru tanpa analisis spasial.",
      "Menghitung rata-rata nilai ujian sebagai pengganti risiko banjir.",
      "Menghapus layer keluarga miskin karena bukan data fisik.",
      "Memilih sekolah terdekat kantor bupati sebagai prioritas.",
      "Overlay zona banjir dengan titik sekolah dan data sosial wilayah layanan untuk menentukan prioritas mitigasi.",
    ],
    answer: 4,
    explain: "Overlay menggabungkan bahaya, lokasi fasilitas, dan kerentanan sosial untuk menentukan prioritas risiko.",
    version: 1
  },
  {
    id: "G3-P08",
    cluster: "spasial",
    level: "panjang",
    source: "gap3",
    topic: "Proyeksi aritmatik vs geometrik",
    stem: "Penduduk kecamatan tumbuh stabil sekitar 1.000 jiwa per tahun selama satu dekade, bukan persentase tetap. Metode proyeksi yang lebih sesuai sebagai baseline sederhana adalah?",
    options: [
      "Aritmatik, karena kenaikan absolut relatif konstan dari tahun ke tahun.",
      "Geometrik, karena semua pertumbuhan penduduk pasti berbunga majemuk.",
      "Eksponensial tinggi tanpa melihat tren historis.",
      "Delphi murni tanpa data penduduk.",
      "Interpolasi spasial tutupan lahan.",
    ],
    answer: 0,
    explain: "Metode aritmatik cocok ketika pertambahan absolut cenderung stabil, sedangkan geometrik cocok untuk laju persentase relatif konstan.",
    version: 1
  },
  {
    id: "G3-P09",
    cluster: "spasial",
    level: "kasus",
    source: "gap3",
    topic: "PSN dampak sosial",
    stem: "PSN jalan tol membuka akses baru, tetapi memutus jalur petani ke sawah dan menaikkan harga sewa di desa sekitar gerbang tol. Mitigasi sosial-spasial yang perlu dimasukkan adalah?",
    options: [
      "Mencatat dampak sosial setelah konstruksi selesai saja.",
      "Akses pengganti lahan usaha, konsultasi warga, perlindungan penyewa rentan, pemulihan mata pencaharian, dan pemantauan dampak harga lahan.",
      "Menganggap akses tol otomatis menguntungkan semua kelompok.",
      "Menutup keluhan warga agar jadwal proyek tidak berubah.",
      "Memindahkan petani tanpa rencana akses produksi.",
    ],
    answer: 1,
    explain: "PSN dapat membawa manfaat dan beban ruang yang berbeda, sehingga mitigasi sosial harus konkret dan terpantau.",
    version: 1
  }
];
