// Bank JFP 2025 (Google Form) — node scripts/build-jfp2025.mjs
const BANK_JFP2025 = [
  {
    id: "JFP-004",
    cluster: "teknis",
    level: "sedang",
    source: "jfp2025",
    formNo: 4,
    stem: "Apa manfaat utama dari dilakukannya evaluasi program dalam proses pembangunan",
    options: [
      "(a) Untuk memastikan proyek dapat selesai tanpa perubahan anggaran",
      "(b) Untuk menilai hasil akhir tanpa melihat proses yang telah dilalui",
      "(c) Untuk mengidentifikasi kekuatan dan kelemahan dalam pelaksanaan proyek dan mengambil langkah perbaikan",
      "(d) Untuk menghindari penggunaan sumber daya yang terlalu berlebih dalam proyek",
      "Untuk hanya mencatat laporan keuangan proyek tanpa evaluasi terhadap kegiatan",
    ],
    answer: 2,
    explain: "Evaluasi program bertujuan menilai pelaksanaan, mengidentifikasi kekuatan dan kelemahan, serta merumuskan perbaikan agar program lebih efektif.",
    fixedOptions: true,
    version: 1
  },
  {
    id: "JFP-005",
    cluster: "sosial",
    level: "sedang",
    source: "jfp2025",
    formNo: 5,
    stem: "Apa tujuan utama dari intervensi sosial dalam pembangunan:",
    options: [
      "Untuk memaksimalkan keuntungan ekonomi tanpa memperhatikan kesejahteraan sosial",
      "Untuk mengatasi ketimpangan sosial dan memastikan bahwa semua kelompok masyarakat dapat merasakan manfaat",
      "Untuk mengabaikan kebutuhan masyarakat dalam perencanaan pembangunan",
      "Untuk menyelaraskan dengan agenda pembangunan pemerintah pusat/negara",
      "Untuk mempercepat pembangunan infrastruktur fisik tanpa memperdulikan dampaknya terhadap masyarakat",
    ],
    answer: 1,
    explain: "Intervensi sosial dirancang mengatasi ketimpangan dan memastikan kelompok rentan ikut merasakan manfaat pembangunan, bukan sekadar pertumbuhan ekonomi.",
    version: 1
  },
  {
    id: "JFP-007",
    cluster: "teknis",
    level: "sedang",
    source: "jfp2025",
    formNo: 7,
    stem: "Dalam pelaksanaan Musrenbang Nasional, usulan prioritas pembangunan daerah dibahas bersama dengan kementerian/lembaga untuk penyesuaian dengan prioritas nasional dan kemampuan pendanaan. Hal ini merupakan bagian dari pendekatan:",
    options: [
      "Politik",
      "Partisipatif",
      "Top-down dan bottom-up",
      "Teknis",
      "Evaluatif",
    ],
    answer: 2,
    explain: "Musrenbang Nasional menggabungkan aspirasi daerah (bottom-up) dengan penyesuaian prioritas dan pendanaan nasional (top-down).",
    version: 1
  },
  {
    id: "JFP-008",
    cluster: "teknis",
    level: "singkat",
    source: "jfp2025",
    formNo: 8,
    stem: "Kinerja pembangunan daerah dapat diukur melalui indikator:",
    options: [
      "(a) Produk Domestik Regional Bruto (PDRB)",
      "(b) Indeks Pembangunan Manusia (IPM)",
      "(c) Tingkat kemiskinan",
      "Hanya (a) dan (b) benar",
      "Semua benar",
    ],
    answer: 4,
    explain: "Kinerja pembangunan daerah lazim diukur lewat PDRB, IPM, dan tingkat kemiskinan — indikator ekonomi, human development, dan sosial.",
    fixedOptions: true,
    version: 1
  },
  {
    id: "JFP-011",
    cluster: "teknis",
    level: "singkat",
    source: "jfp2025",
    formNo: 11,
    stem: "Jenis perencanaan pembangunan yang dilakukan berdasarkan kondisi nyata dan potensi daerah disebut perencanaan:",
    options: [
      "Partisipatif",
      "Top-down",
      "Teknis",
      "Bottom-up",
      "Evaluatif",
    ],
    answer: 3,
    explain: "Perencanaan bottom-up disusun dari kondisi nyata, potensi, dan permasalahan setempat sebagai titik tolak kebijakan daerah.",
    version: 1
  },
  {
    id: "JFP-012",
    cluster: "teknis",
    level: "singkat",
    source: "jfp2025",
    formNo: 12,
    stem: "Efektivitas indikator kinerja diukur dengan membandingkan:",
    options: [
      "Biaya dengan hasil",
      "Waktu dengan target",
      "Target dengan hasil",
      "Input dengan output",
      "Output dengan outcome",
    ],
    answer: 2,
    explain: "Efektivitas indikator kinerja diukur dengan membandingkan target yang ditetapkan dengan hasil/capaian riil.",
    version: 1
  },
  {
    id: "JFP-015",
    cluster: "teknis",
    level: "singkat",
    source: "jfp2025",
    formNo: 15,
    stem: "Konsep pembangunan berkelanjutan menekankan pada keseimbangan antara:",
    options: [
      "Ekonomi, sosial, dan lingkungan",
      "Ekonomi dan industri",
      "Sosial dan budaya",
      "Pembangunan dan pemerintahan",
      "Politik dan ekonomi",
    ],
    answer: 0,
    explain: "Pembangunan berkelanjutan menyeimbangkan aspek ekonomi, sosial, dan lingkungan (triple bottom line).",
    version: 1
  },
  {
    id: "JFP-016",
    cluster: "spasial",
    level: "sedang",
    source: "jfp2025",
    formNo: 16,
    stem: "Gaya sentrifugal menurut teori Charles Colby terdiri dari:",
    options: [
      "Site, situation, spatial",
      "Spatial, status, organization",
      "Social evaluation, organization, occupance, situation",
      "Situation, social evaluation, spatial",
      "Semua benar",
    ],
    answer: 4,
    explain: "Menurut Charles Colby, gaya sentrifugal meliputi spatial, site, situational, social evaluation, status & organization of occupance, serta human equation — opsi A–D masing-masing mencakup sebagian komponen.",
    fixedOptions: true,
    version: 1
  },
  {
    id: "JFP-017",
    cluster: "sosial",
    level: "sedang",
    source: "jfp2025",
    formNo: 17,
    stem: "Apa yang menjadi asumsi dasar dari melakukan fasilitasi:",
    options: [
      "(a) Memiliki keterampilan komunikasi, tidak ada orang yang sama (setiap individu unik), proses pembelajaran seseorang berbeda-beda sesuai dengan keunikan mereka, dan setiap orang akan lebih komit dengan keputusannya sendiri",
      "(b) Proses fasilitasi bertujuan untuk mencapai konsensus dan pemahaman bersama melalui komunikasi terbuka dan kolaborasi",
      "(c) Setiap peserta dihargai dan diberi kesempatan untuk berbicara, tanpa ada pihak yang didominasi atau diabaikan",
      "Fasilitator hanya bertugas untuk mengarahkan diskusi dan bukan untuk berpartisipasi dalam memberikan ide atau pendapat",
      "(d) Semuanya benar",
    ],
    answer: 4,
    explain: "Asumsi fasilitasi: individu unik, proses belajar berbeda, partisipasi setara, fasilitator mengarahkan tanpa mendominasi, dan tujuan konsensus — semua pernyataan relevan.",
    fixedOptions: true,
    version: 1
  },
  {
    id: "JFP-018",
    cluster: "teknis",
    level: "singkat",
    source: "jfp2025",
    formNo: 18,
    stem: "Penjaringan aspirasi masyarakat selain Musrenbang dapat dilakukan melalui:",
    options: [
      "(a) Rapat teknis",
      "(b) Forum konsultasi publik",
      "(c) Seminar dan lokakarya",
      "Hanya (a) dan (c) benar",
      "Semua benar",
    ],
    answer: 4,
    explain: "Penjaringan aspirasi selain Musrenbang dapat melalui rapat teknis, forum konsultasi publik, dan seminar/lokakarya.",
    fixedOptions: true,
    version: 1
  },
  {
    id: "JFP-019",
    cluster: "sosial",
    level: "singkat",
    source: "jfp2025",
    formNo: 19,
    stem: "Unsur pembentuk modal sosial masyarakat antara lain:",
    options: [
      "Kepatuhan terhadap perintah",
      "Keseimbangan hak dan kewajiban",
      "Saling percaya",
      "Penegakan hukum",
      "Penindasan dan anarki",
    ],
    answer: 2,
    explain: "Modal sosial dibangun dari kepercayaan (trust), norma, dan jaringan sosial; saling percaya adalah unsur pembentuk utamanya.",
    version: 1
  },
  {
    id: "JFP-020",
    cluster: "teknis",
    level: "singkat",
    source: "jfp2025",
    formNo: 20,
    stem: "Dalam kerangka perencanaan pembangunan nasional, RPJMD harus selaras dengan:",
    options: [
      "RPJP Nasional",
      "RPJM Nasional",
      "RKP",
      "Renstra K/L",
      "Semua benar",
    ],
    answer: 1,
    explain: "RPJMD daerah harus selaras dengan Rencana Pembangunan Jangka Menengah (RPJM) Nasional agar integrasi pusat–daerah terjaga.",
    fixedOptions: true,
    version: 1
  },
  {
    id: "JFP-021",
    cluster: "teknis",
    level: "singkat",
    source: "jfp2025",
    formNo: 21,
    stem: "Dalam tahapan perencanaan pembangunan, rumusan tujuan dan sasaran pembangunan daerah dituangkan dalam:",
    options: [
      "RPJPD",
      "RPJMD",
      "Renstra OPD",
      "Renja OPD",
      "RKPD",
    ],
    answer: 1,
    explain: "Tujuan dan sasaran pembangunan daerah dijabarkan dalam RPJMD (rencana jangka menengah).",
    version: 1
  },
  {
    id: "JFP-022",
    cluster: "teknis",
    level: "singkat",
    source: "jfp2025",
    formNo: 22,
    stem: "Indikator kinerja harus sejalan dengan tujuan dan program yang diukur, hal ini menunjukkan indikator harus bersifat:",
    options: [
      "Spesifik",
      "Terukur",
      "Relevan",
      "Dapat dicapai",
      "Efektif",
    ],
    answer: 2,
    explain: "Indikator kinerja harus relevan (Relevant) — sejalan dengan tujuan dan program yang diukur (prinsip SMART).",
    version: 1
  },
  {
    id: "JFP-028",
    cluster: "teknis",
    level: "sedang",
    source: "jfp2025",
    formNo: 28,
    stem: "Isu strategis dalam perencanaan pembangunan daerah biasanya diidentifikasi berdasarkan:",
    options: [
      "Kondisi ekonomi daerah",
      "Potensi sumber daya alam",
      "Permasalahan pokok dan tantangan yang dihadapi daerah",
      "Pendapat masyarakat umum",
      "Prioritas kepala daerah",
    ],
    answer: 2,
    explain: "Isu strategis diidentifikasi dari permasalahan pokok dan tantangan substantif daerah, bukan sekadar opini atau agenda personal.",
    version: 1
  },
  {
    id: "JFP-029",
    cluster: "teknis",
    level: "sedang",
    source: "jfp2025",
    formNo: 29,
    stem: "Dalam penyusunan Rencana Pembangunan Daerah, seorang Kepala Daerah terpilih sangat aktif menentukan kegiatan pembangunan di daerahnya sebagai bukti dalam merealisasikan janji-janji kampanyenya. Pendekatan ini dikenal sebagai:",
    options: [
      "Perencanaan partisipatif",
      "Perencanaan bottom-up",
      "Perencanaan top-down",
      "Perencanaan teknokratik",
      "Perencanaan sektoral",
    ],
    answer: 2,
    explain: "Ketika kepala daerah menentukan kegiatan dari janji kampanye, pendekatan perencanaan bersifat top-down/politik — keputusan dari atas.",
    version: 1
  },
  {
    id: "JFP-030",
    cluster: "teknis",
    level: "sedang",
    source: "jfp2025",
    formNo: 30,
    stem: "Penentu baik–buruknya hasil perencanaan adalah:",
    options: [
      "(a) Kesesuaian dengan kondisi yang ada",
      "(b) Pelaksanaan tidak semestinya",
      "(c) Penyusunan tidak tepat",
      "Hanya (a) dan (c) benar",
      "Semua benar",
    ],
    answer: 4,
    explain: "Kualitas perencanaan ditentukan kesesuaian dengan kondisi, ketepatan penyusunan, dan pelaksanaan semestinya.",
    fixedOptions: true,
    version: 1
  },
  {
    id: "JFP-031",
    cluster: "teknis",
    level: "sedang",
    source: "jfp2025",
    formNo: 31,
    stem: "Dalam penyusunan Rencana Pembangunan Jangka Menengah Daerah (RPJMD), tahapan pertama yang harus dilakukan adalah:",
    options: [
      "Analisis situasi dan kondisi daerah",
      "Penentuan indikator kinerja utama",
      "Penyusunan program dan kegiatan prioritas",
      "Penetapan tujuan dan sasaran",
      "Konsultasi publik",
    ],
    answer: 0,
    explain: "Tahap awal penyusunan RPJMD adalah analisis situasi dan kondisi daerah sebagai dasar perumusan strategi.",
    version: 1
  },
  {
    id: "JFP-032",
    cluster: "ekonomi",
    level: "singkat",
    source: "jfp2025",
    formNo: 32,
    stem: "Kebijakan fiskal yang dilakukan pemerintah dalam rangka menstabilkan perekonomian dapat berupa:",
    options: [
      "Penyesuaian tingkat suku bunga",
      "Pengendalian jumlah uang beredar",
      "Penyesuaian pajak dan belanja negara",
      "Pengawasan kegiatan ekspor-impor",
      "Penentuan nilai tukar mata uang",
    ],
    answer: 2,
    explain: "Kebijakan fiskal stabilisasi perekonomian dilakukan melalui penyesuaian pajak dan belanja pemerintah; suku bunga/uang beredar termasuk kebijakan moneter.",
    version: 1
  },
  {
    id: "JFP-033",
    cluster: "ekonomi",
    level: "sedang",
    source: "jfp2025",
    formNo: 33,
    stem: "Istilah “trickle down effect” dalam konteks pembangunan ekonomi berarti:",
    options: [
      "(a) Pertumbuhan ekonomi yang tinggi otomatis akan menetes ke bawah dan meningkatkan kesejahteraan masyarakat miskin",
      "(b) Pengaliran sumber daya dari daerah miskin ke daerah kaya",
      "Penyebaran efek pembangunan hanya pada sektor industri",
      "(c) Dampak negatif pembangunan terhadap masyarakat kecil",
      "(d) Ketergantungan ekonomi antar daerah",
    ],
    answer: 0,
    explain: "Trickle-down effect: manfaat pertumbuhan ekonomi diharapkan menetes ke lapisan bawah meski kritik teori ini menekankan keterbatasan redistribusi otomatis.",
    fixedOptions: true,
    version: 1
  },
  {
    id: "JFP-034",
    cluster: "spasial",
    level: "panjang",
    source: "jfp2025",
    formNo: 34,
    stem: "Berdasarkan data bencana pada tahun 2024, sekitar 93% kejadian bencana yang terjadi di Indonesia merupakan bencana hidrometeorologi seperti banjir, tanah longsor, dan angin puting beliung. Tren ini diperkirakan akan terus meningkat apabila kondisi dasar yang ada tidak diperbaiki. Dalam menginventarisasi masalah bencana, berdasarkan pengamatan saudara, faktor nonalam yang menjadi penyebab terjadinya bencana hidrometeorologi tersebut adalah:",
    options: [
      "(a) Perubahan tata guna lahan yang tidak mengikuti rencana",
      "(b) Intensitas dan curah hujan yang semakin meningkat",
      "(c) Penurunan kemampuan permukaan tanah dalam menginfiltrasi (menyerap) air",
      "Hanya butir (a) dan (c) yang benar",
      "Semua jawaban benar",
    ],
    answer: 3,
    explain: "Faktor non-alam: (a) perubahan tata guna lahan dan (c) penurunan infiltrasi tanah. (b) curah hujan bersifat alamiah. Butir (a) benar tapi tidak lengkap — pilih opsi meta \"Hanya butir (a) dan (c) yang benar\", bukan butir tunggal.",
    fixedOptions: true,
    version: 1
  },
  {
    id: "JFP-036",
    cluster: "ekonomi",
    level: "sedang",
    source: "jfp2025",
    formNo: 36,
    stem: "Pernyataan yang tidak tepat tentang konsep stok dan flow adalah:",
    options: [
      "Kekayaan = stok, pendapatan = flow",
      "Air bak = stok, air keran = flow",
      "Pengangguran = stok, kehilangan pekerjaan = flow",
      "Investasi masuk = stok",
      "Utang = stok, defisit = flow",
    ],
    answer: 3,
    explain: "Investasi adalah flow (aliran selama periode), bukan stock. Pernyataan 'investasi masuk = stok' tidak tepat.",
    version: 1
  },
  {
    id: "JFP-037",
    cluster: "teknis",
    level: "sedang",
    source: "jfp2025",
    formNo: 37,
    stem: "Makna pemilihan presiden secara langsung pasca amandemen UUD 1945 adalah:",
    options: [
      "(a) Bentuk pendidikan politik bagi pemilih",
      "(b) Cerminan faktor emosional dan psikologis pemilih",
      "(c) Penentu arah pembangunan lima tahun ke depan",
      "Hanya (a) dan (c) benar",
      "Semua benar",
    ],
    answer: 4,
    explain: "Pemilu presiden langsung pasca-amandemen UUD 1945 berimplikasi pendidikan politik, dinamika psikologis pemilih, dan penentuan arah pembangunan lima tahun.",
    fixedOptions: true,
    version: 1
  },
  {
    id: "JFP-038",
    cluster: "spasial",
    level: "sedang",
    source: "jfp2025",
    formNo: 38,
    stem: "Langkah yang tidak efektif untuk mengurangi polusi udara di perkotaan adalah:",
    options: [
      "Sosialisasi penggunaan masker",
      "Edukasi bahaya polusi",
      "Pembangunan taman hijau",
      "Pengembangan transportasi ramah lingkungan",
      "Pengendalian emisi pabrik",
    ],
    answer: 0,
    explain: "Sosialisasi masker mengurangi paparan individu, bukan sumber polusi. Langkah efektif mengurangi polusi: hijau, transportasi ramah lingkungan, pengendalian emisi.",
    version: 1
  },
  {
    id: "JFP-039",
    cluster: "sosial",
    level: "singkat",
    source: "jfp2025",
    formNo: 39,
    stem: "Ketika pemerintah daerah mengalokasikan dana lebih banyak untuk pendidikan dan kesehatan, maka kebijakan tersebut mencerminkan orientasi pada:",
    options: [
      "Pembangunan ekonomi",
      "Pembangunan sumber daya manusia",
      "Pembangunan infrastruktur",
      "Pembangunan industri",
      "Pembangunan energi",
    ],
    answer: 1,
    explain: "Alokasi dana pendidikan dan kesehatan orientasi pembangunan sumber daya manusia (human capital).",
    version: 1
  },
  {
    id: "JFP-040",
    cluster: "sosial",
    level: "singkat",
    source: "jfp2025",
    formNo: 40,
    stem: "Konsep perencanaan yang melibatkan berbagai pemangku kepentingan dan masyarakat disebut:",
    options: [
      "Top-down planning",
      "Bottom-up planning",
      "Partisipatory planning",
      "Technocratic planning",
      "Political planning",
    ],
    answer: 2,
    explain: "Perencanaan partisipatory melibatkan pemangku kepentingan dan masyarakat dalam proses perencanaan.",
    version: 1
  },
  {
    id: "JFP-041",
    cluster: "teknis",
    level: "singkat",
    source: "jfp2025",
    formNo: 41,
    stem: "Konsep “musyawarah perencanaan pembangunan” (Musrenbang) merupakan perwujudan dari pendekatan:",
    options: [
      "Top-down",
      "Bottom-up",
      "Partisipatif",
      "Teknis",
      "Evaluatif",
    ],
    answer: 2,
    explain: "Musrenbang adalah wujud pendekatan partisipatif dalam perencanaan pembangunan.",
    version: 1
  },
  {
    id: "JFP-042",
    cluster: "teknis",
    level: "sedang",
    source: "jfp2025",
    formNo: 42,
    stem: "Jika perencanaan pembangunan dilakukan berdasarkan potensi dan permasalahan daerah, maka pendekatan yang digunakan adalah:",
    options: [
      "Politik",
      "Teknis",
      "Partisipatif",
      "Bottom-up",
      "Top-down",
    ],
    answer: 1,
    explain: "Perencanaan berbasis potensi dan permasalahan daerah menggunakan pendekatan teknis/analitis regional.",
    version: 1
  },
  {
    id: "JFP-044",
    cluster: "teknis",
    level: "singkat",
    source: "jfp2025",
    formNo: 44,
    stem: "Jenis indikator kinerja yang menunjukkan masukan sumber daya yang digunakan untuk melaksanakan kegiatan disebut indikator:",
    options: [
      "Input",
      "Output",
      "Outcome",
      "Impact",
      "Proses",
    ],
    answer: 0,
    explain: "Indikator input mengukur sumber daya/masukan yang digunakan (dana, SDM, material).",
    version: 1
  },
  {
    id: "JFP-045",
    cluster: "teknis",
    level: "singkat",
    source: "jfp2025",
    formNo: 45,
    stem: "Indikator yang mengukur hasil langsung dari pelaksanaan program disebut indikator:",
    options: [
      "Input",
      "Output",
      "Outcome",
      "Impact",
      "Proses",
    ],
    answer: 1,
    explain: "Output = hasil langsung pelaksanaan program/kegiatan.",
    version: 1
  },
  {
    id: "JFP-046",
    cluster: "teknis",
    level: "singkat",
    source: "jfp2025",
    formNo: 46,
    stem: "Indikator yang menggambarkan dampak jangka panjang dari pelaksanaan program disebut indikator:",
    options: [
      "Input",
      "Output",
      "Outcome",
      "Impact",
      "Proses",
    ],
    answer: 3,
    explain: "Impact = dampak jangka panjang perubahan kondisi masyarakat/lingkungan akibat program.",
    version: 1
  },
  {
    id: "JFP-051",
    cluster: "sosial",
    level: "panjang",
    source: "jfp2025",
    formNo: 51,
    stem: "Apa yang dimaksud dengan melakukan pendampingan dalam implementasi program pembangunan:",
    options: [
      "(a) Pendampingan adalah proses fasilitasi dalam mengidentifikasi kebutuhan dan memecahkan masalah serta mendorong tumbuhnya inisiatif dalam proses pengambilan keputusan sehingga kemandirian secara berkelanjutan dapat diwujudkan",
      "(b) Merupakan hal yang berfokus pada pembangunan infrastruktur fisik yang melibatkan masyarakat",
      "(c) Merupakan pelibatan pihak eksternal untuk memberi dukungan teknis, sosial dan pembelajaran kepada masyarakat pada tahap proses pembangunan tertentu",
      "(d) Memberikan hibah langsung kepada individu tanpa pelatihan atau pengawasan",
      "Memprioritaskan pembangunan hanya pada sektor ekonomi tanpa memperhatikan dampak sosial",
    ],
    answer: 0,
    explain: "Pendampingan adalah proses fasilitasi identifikasi kebutuhan, pemecahan masalah, dan penguatan kemandirian berkelanjutan — bukan hibah atau intervensi semata.",
    fixedOptions: true,
    version: 1
  },
  {
    id: "JFP-058",
    cluster: "teknis",
    level: "sedang",
    source: "jfp2025",
    formNo: 58,
    stem: "Tujuan dari UU No. 25 Tahun 2004 tentang SPPN adalah untuk:",
    options: [
      "(a) Menjamin koordinasi antar pelaku pembangunan",
      "(b) Meningkatkan partisipasi masyarakat",
      "(c) Menjamin keterkaitan dan konsistensi antar perencanaan",
      "Hanya (a) dan (c) benar",
      "Semua benar",
    ],
    answer: 4,
    explain: "UU 25/2004 SPPN: koordinasi pelaku pembangunan, partisipasi masyarakat, dan keterkaitan antar perencanaan — ketiganya tujuan utama.",
    fixedOptions: true,
    version: 1
  },
  {
    id: "JFP-065",
    cluster: "sosial",
    level: "sedang",
    source: "jfp2025",
    formNo: 65,
    stem: "Tahapan perencanaan sosial dibandingkan dengan perencanaan ekonomi atau spasial bersifat:",
    options: [
      "Berbeda dengan ekonomi",
      "Sama dengan spasial",
      "Lebih sederhana",
      "Berbeda dengan pembangunan bangsa",
      "Lebih sedikit dari spasial",
    ],
    answer: 1,
    explain: "Tahapan perencanaan sosial, ekonomi, dan spasial pada dasarnya sama (identifikasi–analisis–alternatif–implementasi–evaluasi).",
    version: 1
  },
  {
    id: "JFP-066",
    cluster: "sosial",
    level: "singkat",
    source: "jfp2025",
    formNo: 66,
    stem: "Konsep pembangunan manusia berfokus pada peningkatan:",
    options: [
      "Pendapatan per kapita",
      "Investasi fisik",
      "Kualitas hidup masyarakat melalui pendidikan, kesehatan, dan pendapatan",
      "Pembangunan infrastruktur",
      "Produktivitas tenaga kerja",
    ],
    answer: 2,
    explain: "Pembangunan manusia (human development) fokus peningkatan kualitas hidup melalui pendidikan, kesehatan, dan pendapatan — bukan infrastruktur semata.",
    version: 1
  },
  {
    id: "JFP-067",
    cluster: "ekonomi",
    level: "sedang",
    source: "jfp2025",
    formNo: 67,
    stem: "Ketimpangan pembangunan antarwilayah dapat terjadi karena:",
    options: [
      "(a) Perbedaan potensi sumber daya alam",
      "(b) Ketimpangan investasi",
      "(c) Ketimpangan infrastruktur",
      "Hanya (a) dan (b) benar",
      "Semua benar",
    ],
    answer: 4,
    explain: "Ketimpangan antarwilayah disebabkan perbedaan SDA, investasi, dan infrastruktur — semua benar.",
    fixedOptions: true,
    version: 1
  },
  {
    id: "JFP-068",
    cluster: "teknis",
    level: "sedang",
    source: "jfp2025",
    formNo: 68,
    stem: "Yang bukan termasuk permasalahan dalam identifikasi potensi dan masalah daerah adalah:",
    options: [
      "Kemiskinan",
      "Kesenjangan",
      "Ketidaksesuaian",
      "Ketidakpatuhan",
      "Ketidakcukupan",
    ],
    answer: 3,
    explain: "Masalah identifikasi potensi/masalah daerah: kemiskinan, kesenjangan, ketidaksesuaian, ketidakcukupan. Ketidakpatuhan bersifat administratif/perilaku, bukan kategori masalah substantif.",
    version: 1
  },
  {
    id: "JFP-072",
    cluster: "spasial",
    level: "singkat",
    source: "jfp2025",
    formNo: 72,
    stem: "Skala peta dalam perencanaan pembangunan berhubungan dengan:",
    options: [
      "Kewenangan daerah",
      "Kewenangan anggaran",
      "Kerincian informasi",
      "Ketentuan menteri",
      "Ketersediaan peta",
    ],
    answer: 2,
    explain: "Skala peta menentukan kerincian informasi ruang — skala besar = detail tinggi, skala kecil = generalisasi.",
    version: 1
  },
  {
    id: "JFP-075",
    cluster: "ekonomi",
    level: "sedang",
    source: "jfp2025",
    formNo: 75,
    stem: "Pernyataan yang tepat tentang konsep stok dan flow adalah:",
    options: [
      "Investasi = stok, modal = flow",
      "Investasi dan kapital = flow",
      "Kekayaan = stok, pendapatan = flow",
      "Pengangguran dan gaji = stok",
      "Penerimaan dan belanja = stok",
    ],
    answer: 2,
    explain: "Stock diukur pada satu waktu (kekayaan); flow diukur per periode (pendapatan, investasi, pengeluaran).",
    version: 1
  },
  {
    id: "JFP-079",
    cluster: "teknis",
    level: "sedang",
    source: "jfp2025",
    formNo: 79,
    stem: "Kemampuan untuk melakukan pemantauan dan pengendalian atas pelaksanaan rencana tergantung pada:",
    options: [
      "(a) Metode yang tepat",
      "(b) Desain pemantauan",
      "(c) Instrumen pengumpulan data",
      "Hanya (a) dan (c) benar",
      "Semua benar",
    ],
    answer: 4,
    explain: "Pemantauan-pengendalian efektif memerlukan metode tepat, desain pemantauan, dan instrumen pengumpulan data.",
    fixedOptions: true,
    version: 1
  },
  {
    id: "JFP-089",
    cluster: "teknis",
    level: "singkat",
    source: "jfp2025",
    formNo: 89,
    stem: "Jenis evaluasi pembangunan yang dilakukan selama pelaksanaan program berlangsung disebut evaluasi:",
    options: [
      "Ex-ante",
      "On-going",
      "Ex-post",
      "Mid-term",
      "Akhir",
    ],
    answer: 1,
    explain: "Evaluasi on-going dilakukan selama program berlangsung untuk koreksi timely.",
    version: 1
  },
  {
    id: "JFP-091",
    cluster: "teknis",
    level: "singkat",
    source: "jfp2025",
    formNo: 91,
    stem: "Evaluasi yang dilakukan pada tahap awal perencanaan suatu program disebut evaluasi:",
    options: [
      "Ex-ante",
      "On-going",
      "Ex-post",
      "Mid-term",
      "Akhir",
    ],
    answer: 0,
    explain: "Evaluasi ex-ante dilakukan pada tahap perencanaan awal untuk menilai kelayakan sebelum pelaksanaan.",
    version: 1
  },
  {
    id: "JFP-095",
    cluster: "sosial",
    level: "sedang",
    source: "jfp2025",
    formNo: 95,
    stem: "Bagaimana modal sosial dapat mempengaruhi keberhasilan pembangunan yang berkelanjutan:",
    options: [
      "Dengan mengabaikan kepercayaan antar masyarakat dan hanya fokus pada faktor ekonomi",
      "(a) Dengan menciptakan persaingan antar kelompok tanpa memperhatikan kerja sama",
      "(b) Dengan memperkuat jaringan sosial yang mendukung pengambilan keputusan kolektif dan pemecahan masalah secara bersama",
      "(c) Dengan mengurangi peran masyarakat dalam proses perencanaan dan pelaksanaan pembangunan",
      "(d) Dengan meningkatkan ketergantungan pada bantuan internasional",
    ],
    answer: 2,
    explain: "Modal sosial memperkuat jaringan kepercayaan dan kerja sama kolektif — kunci pembangunan berkelanjutan.",
    fixedOptions: true,
    version: 1
  },
  {
    id: "JFP-097",
    cluster: "teknis",
    level: "singkat",
    source: "jfp2025",
    formNo: 97,
    stem: "Data masa lalu yang disusun dalam urutan waktu disebut:",
    options: [
      "Deret ukur",
      "Deret hitung",
      "Data series",
      "Data paralel",
      "Data sequential",
    ],
    answer: 2,
    explain: "Data masa lalu berurutan waktu = time series / data series untuk analisis tren.",
    version: 1
  },
  {
    id: "JFP-098",
    cluster: "teknis",
    level: "singkat",
    source: "jfp2025",
    formNo: 98,
    stem: "Jika data yang dikumpulkan mencerminkan kondisi rata-rata pendapatan penduduk di suatu daerah, maka data tersebut merupakan contoh dari:",
    options: [
      "Data kualitatif",
      "Data sekunder",
      "Data primer",
      "Data kuantitatif",
      "Data spasial",
    ],
    answer: 3,
    explain: "Rata-rata pendapatan penduduk berbentuk angka → data kuantitatif.",
    version: 1
  },
  {
    id: "JFP-099",
    cluster: "teknis",
    level: "singkat",
    source: "jfp2025",
    formNo: 99,
    stem: "Jenis data yang dikumpulkan melalui wawancara langsung dengan masyarakat disebut:",
    options: [
      "Data sekunder",
      "Data primer",
      "Data administratif",
      "Data agregat",
      "Data panel",
    ],
    answer: 1,
    explain: "Data dari wawancara langsung = data primer.",
    version: 1
  },
  {
    id: "JFP-101",
    cluster: "teknis",
    level: "singkat",
    source: "jfp2025",
    formNo: 101,
    stem: "Input dalam analisis perkembangan dan perubahan dapat bersifat:",
    options: [
      "Tunggal",
      "Majemuk",
      "Biner",
      "Serial",
      "Numerik",
    ],
    answer: 3,
    explain: "Analisis perkembangan/perubahan membutuhkan data serial (berurutan waktu) untuk melihat tren.",
    version: 1
  },
  {
    id: "JFP-104",
    cluster: "teknis",
    level: "singkat",
    source: "jfp2025",
    formNo: 104,
    stem: "Indikator efisiensi menunjukkan perbandingan antara:",
    options: [
      "Input dengan output",
      "Target dengan pelaksanaan",
      "Biaya dengan manfaat",
      "Biaya dengan waktu",
      "Biaya dengan hasil",
    ],
    answer: 0,
    explain: "Indikator efisiensi = perbandingan input dengan output (rasio input-output).",
    version: 1
  },
  {
    id: "JFP-105",
    cluster: "teknis",
    level: "singkat",
    source: "jfp2025",
    formNo: 105,
    stem: "Hasil capaian dari RKP(D) disebut",
    options: [
      "Output",
      "Outcome",
      "Benefit",
      "Impact",
      "Semua benar",
    ],
    answer: 0,
    explain: "RKP/RKPD bersifat tahunan-operasional; capaian langsung kegiatan = output.",
    fixedOptions: true,
    version: 1
  },
  {
    id: "JFP-108",
    cluster: "teknis",
    level: "singkat",
    source: "jfp2025",
    formNo: 108,
    stem: "Yang bukan merupakan metode proyeksi dalam perencanaan adalah:",
    options: [
      "Eksponensial",
      "Deret ukur",
      "Algoritma",
      "Aritmatika",
      "Least square",
    ],
    answer: 2,
    explain: "Metode proyeksi: eksponensial, deret ukur, aritmatika, least square. Algoritma = prosedur logis, bukan metode proyeksi.",
    version: 1
  },
  {
    id: "JFP-109",
    cluster: "sosial",
    level: "panjang",
    source: "jfp2025",
    formNo: 109,
    stem: "Apa tujuan utama dari pendampingan yang dilakukan kepada masyarakat atau pemerintah daerah:",
    options: [
      "Agar masyarakat atau pemerintah daerah dapat mengelola anggaran tanpa pengawasan",
      "Untuk memastikan proyek pembangunan dapat berjalan tanpa adanya evaluasi",
      "Agar masyarakat atau pemerintah daerah tidak perlu melibatkan pihak eksternal dalam proses pengambilan keputusan",
      "Untuk membantu masyarakat atau pemerintah daerah meningkatkan kapasitas dan keterampilan dalam merencanakan, melaksanakan, dan evaluasi program pembangunan",
      "Agar masyarakat atau pemerintah daerah tidak perlu membuat laporan kemajuan proyek",
    ],
    answer: 3,
    explain: "Pendampingan bertujuan meningkatkan kapasitas masyarakat/PEMDA merencanakan, melaksanakan, dan mengevaluasi program — bukan menggantikan tanggung jawab mereka.",
    version: 1
  }
];
