// Bank soal Pre Test UKOM — node build-pretest.cjs
const BANK_PRETEST = [
  {
    id: "PT-01",
    cluster: "sosial",
    level: "sedang",
    source: "pretest",
    stem: "Menurut Hirschman, Social Overhead Capital (SOC) dalam pembangunan terutama merujuk pada?",
    options: [
      "Norma gotong royong dan kepercayaan warga sebagai satu-satunya penggerak pertumbuhan",
      "Instrumen penyelesaian konflik formal antarlembaga pemerintah semata",
      "Alat tawar-menawar anggaran belanja pegawai di tingkat pusat",
      "Infrastruktur pendukung produksi seperti jalan, energi, air, dan komunikasi",
      "Portofolio saham perusahaan swasta yang diperdagangkan di pasar modal",
    ],
    answer: 3,
    explain: "Dalam teori Hirschman, SOC (Social Overhead Capital) adalah modal sosial-overhead berupa infrastruktur pendukung (jalan, pelabuhan, listrik, air, komunikasi) yang menopang Directly Productive Activities—bukan sinonim modal sosial (norma/kepercayaan).",
    version: 3
  },
  {
    id: "PT-02",
    cluster: "sosial",
    level: "sedang",
    source: "pretest",
    stem: "Menurut Chambers (1996), perbedaan utama Rapid Rural Appraisal (RRA) dan Participatory Rural Appraisal (PRA) terletak pada aspek mana?",
    options: [
      "Titik berat pada perilaku individu semata",
      "Fokus hasil jangka pendek tanpa proses belajar",
      "Kurun waktu lahirnya metode di dekade yang berbeda",
      "Potensi sumber informasi dan cara melibatkan masyarakat",
      "Kemampuan statistik formal masyarakat setempat",
    ],
    answer: 3,
    explain: "Perbedaan RRA vs PRA: potensi sumber informasi (PRA lebih partisipatif).",
    version: 2
  },
  {
    id: "PT-03",
    cluster: "spasial",
    level: "sedang",
    source: "pretest",
    stem: "Perhitungan statistik, interpretasi data kuantitatif–kualitatif, analisis peta, interpretasi citra, dan pengolahan data spasial dengan SIG termasuk prosedur pada tahapan perencanaan tata ruang yang mana?",
    options: [
      "Perumusan rencana tata ruang wilayah",
      "Penjabaran konsep dan strategi pengembangan wilayah",
      "Pemetaan data sosial kemasyarakatan semata",
      "Kegiatan analisis wilayah secara umum",
      "Pemahaman karakteristik wilayah tanpa rencana",
    ],
    answer: 0,
    explain: "Tahapan perencanaan tata ruang: perumusan rencana (bukan hanya pemetaan sosial).",
    version: 2
  },
  {
    id: "PT-04",
    cluster: "spasial",
    level: "sedang",
    source: "pretest",
    stem: "Zona perumahan dengan kepadatan sedang memiliki kriteria kepadatan bangunan. Manakah ketentuan yang tepat?",
    options: [
      "40–100 rumah/ha (kepadatan padat)",
      "10–40 rumah/ha (kepadatan sedang)",
      "100–1000 rumah/ha (kepadatan tinggi)",
      "Di atas 1000 rumah/ha (kepadatan sangat tinggi)",
      "Di bawah 10 rumah/ha (kepadatan sangat rendah)",
    ],
    answer: 1,
    explain: "Kepadatan sedang menurut Perpres penataan ruang: 10–40 rumah/ha.",
    version: 2
  },
  {
    id: "PT-05",
    cluster: "sosial",
    level: "sedang",
    source: "pretest",
    stem: "Dalam teori perencanaan, apa yang dimaksud perencanaan sebagai mobilisasi sosial?",
    options: [
      "Mengubah kedudukan masyarakat dari objek menjadi subjek pembangunan semata",
      "Menekankan tradisi positivisme tanpa keterlibatan aktor sosial dalam perencanaan",
      "Proses dialogis non-hierarkis dengan eksperimen sosial dan toleransi perbedaan",
      "Menemukan cara paling efektif bagi negara tanpa penekanan emansipasi",
      "Partisipasi masyarakat disertai emansipasi terhadap penindasan sosial",
    ],
    answer: 4,
    explain: "Mobilisasi sosial: penekanan emansipasi dan partisipasi (Friedmann).",
    version: 2
  },
  {
    id: "PT-06",
    cluster: "spasial",
    level: "singkat",
    source: "pretest",
    stem: "Dalam praktik penataan ruang daerah, pemangku kepentingan yang biasanya berperan sebagai inisiator awal proses perencanaan adalah pihak mana?",
    options: [
      "Konsultan perencana swasta",
      "Pemerintah daerah terkait",
      "Kelompok masyarakat adat",
      "Organisasi nonpemerintah",
      "Pelaku usaha properti",
    ],
    answer: 1,
    explain: "Inisiator penataan ruang pada praktik umum: pemerintah daerah.",
    version: 2
  },
  {
    id: "PT-07",
    cluster: "ekonomi",
    level: "singkat",
    source: "pretest",
    stem: "Menurut hukum permintaan, bagaimana hubungan antara harga barang dan jumlah yang diminta, ceteris paribus?",
    options: [
      "Jumlah yang diminta naik ketika harga barang naik",
      "Produsen meningkatkan pasokan saat harga barang meningkat",
      "Semakin tinggi harga, semakin banyak barang yang ditawarkan",
      "Jumlah yang diminta turun ketika harga barang naik",
      "Semakin rendah harga, semakin sedikit barang yang ditawarkan",
    ],
    answer: 3,
    explain: "Hukum permintaan: ceteris paribus, kuantitas diminta turun saat harga naik (hubungan berbanding terbalik).",
    version: 3
  },
  {
    id: "PT-08",
    cluster: "sosial",
    level: "singkat",
    source: "pretest",
    stem: "Manakah yang tidak termasuk teknik Participatory Rural Appraisal (PRA)?",
    options: [
      "Teknik penelusuran alur sejarah desa",
      "Kajian mata pencaharian rumah tangga",
      "Teknik transect atau penampang wilayah",
      "Wawancara informal dan formal berlapis birokrasi",
      "Pembuatan bagan kecenderungan dan perubahan",
    ],
    answer: 3,
    explain: "Bukan teknik PRA: wawancara formal berlebihan (PRA informal/partisipatif).",
    version: 2
  },
  {
    id: "PT-09",
    cluster: "teknis",
    level: "singkat",
    source: "pretest",
    stem: "Proses sistematis mengumpulkan, menganalisis, dan menginterpretasikan informasi untuk menilai keberhasilan program menurut kriteria tertentu bagi pengambilan keputusan disebut apa?",
    options: [
      "Monitoring pelaksanaan",
      "Perencanaan program",
      "Pengawasan administratif",
      "Evaluasi program",
      "Pengukuran fisik output",
    ],
    answer: 3,
    explain: "Evaluasi = penilaian keberhasilan program untuk keputusan.",
    version: 2
  },
  {
    id: "PT-10",
    cluster: "ekonomi",
    level: "sedang",
    source: "pretest",
    stem: "Menurut teori basis ekonomi (economic base theory), faktor apa yang terutama menentukan laju pertumbuhan ekonomi suatu wilayah?",
    options: [
      "Peningkatan ekspor dan impor secara bersamaan dari wilayah tersebut",
      "Keberadaan sektor basis tanpa aktivitas non-basis sama sekali",
      "Penawaran barang dan jasa dari luar daerah sebagai penentu utama",
      "Besarnya peningkatan ekspor sektor basis wilayah tersebut",
      "Besarnya peningkatan impor barang dari luar wilayah tersebut",
    ],
    answer: 3,
    explain: "Economic base: pertumbuhan daerah ditopang ekspor sektor basis.",
    version: 2
  },
  {
    id: "PT-11",
    cluster: "sosial",
    level: "panjang",
    source: "pretest",
    stem: "Manakah ciri kebijakan pembangunan yang bersifat partisipatif?",
    options: [
      "Mengutamakan pertimbangan teknis pemerintah tanpa masukan masyarakat",
      "Membatasi peran masyarakat pada sosialisasi hasil keputusan pusat",
      "Masyarakat memengaruhi perencanaan, pelaksanaan, dan pemantauan kebijakan",
      "Menekankan efisiensi, kuantifikasi, dan produktivitas semata",
      "Mengandalkan pola top-down tanpa ruang dialog dengan warga",
    ],
    answer: 2,
    explain: "Kebijakan partisipatif: masyarakat mempengaruhi perencanaan–pelaksanaan–pemantauan.",
    version: 2
  },
  {
    id: "PT-12",
    cluster: "ekonomi",
    level: "singkat",
    source: "pretest",
    stem: "Manakah yang tidak termasuk variabel utama dalam analisis ekonomi makro?",
    options: [
      "Kesempatan kerja dan pengangguran",
      "Ekspor dan impor agregat",
      "Produk domestik bruto (PDB)",
      "Perilaku konsumtif individu",
      "Tingkat inflasi umum",
    ],
    answer: 3,
    explain: "Variabel makro: perilaku konsumtif bukan variabel utama makro.",
    version: 2
  },
  {
    id: "PT-13",
    cluster: "spasial",
    level: "sedang",
    source: "pretest",
    stem: "Manakah pernyataan yang tepat mengenai RDTR (Rencana Detail Tata Ruang)?",
    options: [
      "RDTR memuat ketentuan teknis rinci tapak/zona pada skala detail",
      "RDTR sama dengan RTRW provinsi",
      "RDTR mencakup seluruh wilayah nasional tanpa batas administratif",
      "RDTR hanya berisi peta administrasi tanpa aturan zonasi",
      "RDTR menggantikan peraturan tata ruang kabupaten/kota",
    ],
    answer: 0,
    explain: "RDTR berskala detail (rincian tapak/zona); RTRW menyusun struktur ruang kabupaten/kota.",
    version: 1
  },
  {
    id: "PT-14",
    cluster: "teknis",
    level: "singkat",
    source: "pretest",
    stem: "Manakah yang tidak termasuk fungsi perencanaan pembangunan?",
    options: [
      "Menjadi pedoman pelaksanaan kegiatan menuju tujuan tertentu",
      "Memilih berbagai alternatif kebijakan yang tersedia",
      "Menganalisis perilaku ekonomi konsumen dan produsen individu",
      "Menyusun skala prioritas program pembangunan",
      "Menjadi acuan untuk melakukan evaluasi kinerja",
    ],
    answer: 2,
    explain: "Fungsi perencanaan: bukan teori mikro konsumen–produsen.",
    version: 2
  },
  {
    id: "PT-15",
    cluster: "ekonomi",
    level: "sedang",
    source: "pretest",
    stem: "Jumlah barang yang diproduksi tahun 2022 sebanyak 500 unit. Harga dasar tahun 2017 adalah Rp300.000 per unit. Berapa PDB tahun 2022 atas harga konstan?",
    options: [
      "Rp60.000.000",
      "Rp300.000.000",
      "Rp30.000.000",
      "Rp15.000.000",
      "Rp150.000.000",
    ],
    answer: 4,
    explain: "PDB konstan = 500 × Rp 300.000 = Rp 150.000.000.",
    version: 2
  },
  {
    id: "PT-16",
    cluster: "spasial",
    level: "singkat",
    source: "pretest",
    stem: "Manakah contoh yang paling tepat untuk formal region?",
    options: [
      "Wilayah administrasi negara",
      "Wilayah abstrak tanpa batas jelas",
      "Wilayah persebaran perkebunan",
      "Wilayah cakupan komuter harian",
      "Wilayah persebaran komoditas pertanian",
    ],
    answer: 0,
    explain: "Formal region = wilayah administrasi negara.",
    version: 2
  },
  {
    id: "PT-17",
    cluster: "teknis",
    level: "sedang",
    source: "pretest",
    stem: "Manakah pernyataan yang paling lengkap mengenai tujuan evaluasi pembangunan?",
    options: [
      "Menjamin ketepatan jadwal, memberi umpan balik, dan akuntabilitas dana publik",
      "Memastikan program on track tanpa ruang umpan balik perbaikan",
      "Memberikan umpan balik tanpa penilaian akuntabilitas publik",
      "Mempertanggungjawabkan dana tanpa pembelajaran pemangku kepentingan",
      "Membantu pembelajaran tanpa kaitannya dengan keputusan program",
    ],
    answer: 0,
    explain: "Tujuan evaluasi: semua benar (akuntabilitas, umpan balik, on track).",
    version: 3
  },
  {
    id: "PT-18",
    cluster: "teknis",
    level: "singkat",
    source: "pretest",
    stem: "Rumusan umum mengenai keadaan yang diinginkan pada akhir periode perencanaan disebut apa?",
    options: [
      "Misi organisasi",
      "Kebijakan operasional",
      "Strategi jangka menengah",
      "Visi pembangunan",
      "Program tahunan",
    ],
    answer: 3,
    explain: "Visi = keadaan masa depan yang ingin dicapai.",
    version: 2
  },
  {
    id: "PT-19",
    cluster: "spasial",
    level: "singkat",
    source: "pretest",
    stem: "Wilayah teritorial dengan batas dan perwatakan berdasarkan wewenang administratif pemerintahan menurut peraturan perundang-undangan disebut apa?",
    options: [
      "Kawasan fungsional",
      "Wilayah geografis umum",
      "Area perencanaan teknis",
      "Komunitas sosial lokal",
      "Daerah administratif",
    ],
    answer: 4,
    explain: "Daerah = wilayah administratif menurut peraturan.",
    version: 2
  },
  {
    id: "PT-20",
    cluster: "ekonomi",
    level: "sedang",
    source: "pretest",
    stem: "Manakah definisi Produk Domestik Bruto (PDB) yang paling tepat?",
    options: [
      "Nilai seluruh barang domestik tanpa jasa dan tanpa produksi residen asing",
      "Nilai seluruh barang yang dihasilkan unit ekonomi tanpa memasukkan jasa",
      "Nilai sebagian barang/jasa domestik termasuk produksi warga negara asing",
      "Nilai sebagian barang yang dihasilkan suatu negara tanpa jasa",
      "Nilai seluruh barang/jasa domestik termasuk produksi residen asing di dalam negeri",
    ],
    answer: 4,
    explain: "PDB/GDP: seluruh barang/jasa domestik termasuk produksi residen asing.",
    version: 2
  },
  {
    id: "PT-21",
    cluster: "teknis",
    level: "sedang",
    source: "pretest",
    stem: "Pendekatan perencanaan pembangunan daerah yang menempatkan rencana sebagai penjabaran visi–misi kepala daerah disebut pendekatan apa?",
    options: [
      "Pendekatan teknokratis murni",
      "Pendekatan politik",
      "Pendekatan top-down dan bottom-up",
      "Pendekatan partisipatif murni",
      "Pendekatan spasial semata",
    ],
    answer: 1,
    explain: "Pendekatan politik: rencana sebagai penjabaran visi–misi kepala daerah.",
    version: 2
  },
  {
    id: "PT-22",
    cluster: "teknis",
    level: "singkat",
    source: "pretest",
    stem: "Berikut ini adalah syarat dokumen perencanaan, kecuali:",
    options: [
      "Relevant",
      "Measureable",
      "Multi years",
      "Spesifik",
      "Achievable",
    ],
    answer: 2,
    explain: "SMART: Multi years bukan komponen SMART (Specific, Measurable, dll.).",
    version: 1
  },
  {
    id: "PT-23",
    cluster: "spasial",
    level: "singkat",
    source: "pretest",
    stem: "Manakah yang merupakan masalah substantif klasik dalam perencanaan spasial?",
    options: [
      "Kemiskinan rumah tangga semata",
      "Tata guna lahan yang tidak optimal",
      "Tingkat pendidikan penduduk",
      "Jangkauan jaringan internet desa",
      "Struktur ruang yang belum selaras",
    ],
    answer: 1,
    explain: "Masalah mutlak perencanaan spasial: tata guna lahan tidak optimal.",
    version: 2
  },
  {
    id: "PT-24",
    cluster: "sosial",
    level: "sedang",
    source: "pretest",
    stem: "Indeks Pembangunan Manusia (IPM) digunakan sebagai indikator pembangunan manusia karena …",
    options: [
      "IPM menerjemahkan konsep kompleks ke dalam tiga dimensi dasar yang terukur",
      "IPM menstimulasi diskusi mengenai pembangunan daerah",
      "IPM membantu pergeseran paradigma pembangunan dari ekonomi semata ke aspek kesejahteraan manusia",
      "IPM berfokus pada kapabilitas yang relevan untuk negara tertinggal",
      "IPM memberikan motivasi kompetisi antarpetani semata",
    ],
    answer: 0,
    explain: "IPM merangkum dimensi kesehatan, pendidikan, pendapatan.",
    version: 1
  },
  {
    id: "PT-25",
    cluster: "sosial",
    level: "sedang",
    source: "pretest",
    stem: "Perencanaan dilihat sebagai proses yang dilakukan oleh dan untuk masyarakat dalam pembangunan merupakan pengertian perencanaan sebagai...",
    options: [
      "Perencanaan sebagai sosial learning",
      "Perencanaan sebagai ekonomi learning",
      "Perencanaan sebagai fisik learning",
      "Perencanaan sebagai mobilisasi learning",
      "Perencanaan sebagai politik learning",
    ],
    answer: 0,
    explain: "Perencanaan sebagai social learning (proses belajar bersama masyarakat).",
    version: 1
  },
  {
    id: "PT-26",
    cluster: "sosial",
    level: "singkat",
    source: "pretest",
    stem: "Ada 4 pilar utama dalam pengentasan kemiskinan dan ketimpangan diantaranya..., kecuali...",
    options: [
      "Melindungi orang miskin dari guncangan dan bencana",
      "Menerapkan kebijakan fiskal yang progresif",
      "Menciptakan pekerjaan yang layak untuk semua",
      "Memberikan peningkatan kepatuhan pajak",
      "Memberikan peluang yang sama di awal kehidupan",
    ],
    answer: 3,
    explain: "Bukan pilar pengentasan kemiskinan: peningkatan patuh pajak semata.",
    version: 1
  },
  {
    id: "PT-27",
    cluster: "spasial",
    level: "singkat",
    source: "pretest",
    stem: "Berdasarkan Undang-Undang Republik Indonesia Nomor 26 Tahun 2007 Tentang Penataan Ruang, Penataan ruang berdasarkan fungsi utama kawasan terdiri atas ....",
    options: [
      "Wilayah nasional, penataan ruang wilayah provinsi, dan penataan ruang wilayah kabupaten/kota",
      "Sistem wilayah dan sistem internal perkotaan.",
      "Kawasan lindung dan kawasan budi daya",
      "Ruang kawasan perkotaan dan penataan ruang kawasan perdesaan.",
      "Ruang kawasan strategis nasional, penataan ruang kawasan strategis provinsi, dan penataan ruang kawasan strategis kabupaten/kota.",
    ],
    answer: 2,
    explain: "UU 26/2007: penataan ruang → kawasan lindung & budi daya.",
    version: 1
  },
  {
    id: "PT-28",
    cluster: "sosial",
    level: "sedang",
    source: "pretest",
    stem: "Berikut pendekatan pembangunan yang menekankan partisipasi dan pemberdayaan masyarakat, kecuali:",
    options: [
      "Pendekatan Trickle down effect",
      "Pendekatan proses top-down dan bottom-up",
      "Pendekatan Partisipatif",
      "Pendekatan politis",
      "Pendekatan proses teknorat",
    ],
    answer: 0,
    explain: "Trickle-down mengandalkan manfaat turun dari elite/pusat ke masyarakat; tidak menekankan partisipasi aktif seperti bottom-up atau partisipatif.",
    version: 2
  },
  {
    id: "PT-29",
    cluster: "spasial",
    level: "sedang",
    source: "pretest",
    stem: "Bagian wilayah kabupaten/kota yang penataan ruangnya diprioritaskan karena pengaruh penting terhadap ekonomi, sosial budaya, dan lingkungan disebut apa?",
    options: [
      "Kawasan budidaya",
      "Kawasan agropolitan",
      "Kawasan lindung",
      "Kawasan strategis",
      "Kawasan metropolitan",
    ],
    answer: 3,
    explain: "Wilayah prioritas penataan ruang kab/kota: kawasan strategis (bukan budidaya).",
    version: 2
  },
  {
    id: "PT-30",
    cluster: "spasial",
    level: "singkat",
    source: "pretest",
    stem: "Pada struktur ruang kota, struktur yang menggambarkan tingkat perhubungan dengan kondisi sosial dalam ruang disebut apa?",
    options: [
      "Struktur sosial",
      "Struktur budaya",
      "Struktur ekonomi",
      "Struktur fisik",
      "Struktur masyarakat",
    ],
    answer: 0,
    explain: "Struktur sosial = pola relasi sosial dalam ruang kota.",
    version: 2
  },
  {
    id: "PT-31",
    cluster: "teknis",
    level: "sedang",
    source: "pretest",
    stem: "Manakah rangkaian tahapan perencanaan pembangunan nasional yang paling lengkap menurut UU Sistem Perencanaan Pembangunan Nasional?",
    options: [
      "Penyusunan rencana tanpa dilanjutkan penetapan resmi",
      "Penetapan rencana tanpa mekanisme pengendalian pelaksanaan",
      "Evaluasi pelaksanaan tanpa tahap penyusunan rencana awal",
      "Pengendalian pelaksanaan tanpa evaluasi capaian hasil",
      "Penyusunan, penetapan, pengendalian, dan evaluasi rencana",
    ],
    answer: 4,
    explain: "Tahapan nasional: penyusunan, penetapan, pengendalian, evaluasi.",
    version: 3
  },
  {
    id: "PT-32",
    cluster: "ekonomi",
    level: "singkat",
    source: "pretest",
    stem: "Manakah definisi inflasi yang paling tepat?",
    options: [
      "Penurunan nilai mata uang tanpa kenaikan harga barang dan jasa umum",
      "Kondisi saat harga barang di dalam negeri mengalami penurunan terus-menerus",
      "Periode penurunan harga umum disertai kenaikan nilai uang secara luas",
      "Kecenderungan penurunan harga umum terus-menerus dalam periode tertentu",
      "Kecenderungan kenaikan harga umum terus-menerus dalam periode tertentu",
    ],
    answer: 4,
    explain: "Inflasi = kenaikan harga umum terus-menerus (±1 tahun).",
    version: 2
  },
  {
    id: "PT-33",
    cluster: "sosial",
    level: "sedang",
    source: "pretest",
    stem: "Faktor alami yang dapat menjadi penyebab ketimpangan sosial adalah faktor mana?",
    options: [
      "Pengaruh globalisasi ekonomi",
      "Kebijakan redistribusi pemerintah",
      "Pengaruh kondisi demografis wilayah",
      "Faktor internal preferensi individu",
      "Perbedaan ketersediaan sumber daya alam",
    ],
    answer: 4,
    explain: "Faktor alami ketimpangan: perbedaan sumber daya alam.",
    version: 2
  },
  {
    id: "PT-34",
    cluster: "teknis",
    level: "singkat",
    source: "pretest",
    stem: "Proses menentukan tindakan masa depan yang tepat melalui urutan pilihan dengan memperhitungkan sumber daya disebut apa?",
    options: [
      "Program operasional",
      "Perencanaan",
      "Visi lembaga",
      "Pembangunan fisik",
      "Kegiatan rutin",
    ],
    answer: 1,
    explain: "Perencanaan = penetapan tindakan masa depan dengan alokasi sumber daya.",
    version: 2
  },
  {
    id: "PT-35",
    cluster: "sosial",
    level: "singkat",
    source: "pretest",
    stem: "Suatu proses yang terjadi ketika satu pihak secara negatif mempengaruhi pihak lain, dengan melakukan kekerasan fisik yang membuat orang lain, perasaan dan fisiknya terganggu. Penjelasan tersebut merupakan pengertian dari ...",
    options: [
      "Stereotype",
      "Etnosentrisme",
      "Konflik",
      "Prasangka",
      "Diskriminasi",
    ],
    answer: 2,
    explain: "Konflik = pihak saling mengganggu (termasuk kekerasan fisik).",
    version: 1
  },
  {
    id: "PT-36",
    cluster: "sosial",
    level: "sedang",
    source: "pretest",
    stem: "PRA merupakan metode pendekatan belajar mengenai kondisi dan kehidupan pedesaan dari, dengan, oleh masyarakat pedesaan sendiri, meliputi kegiatan menganalisis, merencanakan dan bertindak. Prinsip- prinsip PRA diantaranya sebagai berikut, kecuali...",
    options: [
      "Santai dan informal",
      "Triangulasi",
      "Tertutup dan formal",
      "Terbuka",
      "Optimalisasi hasil",
    ],
    answer: 2,
    explain: "PRA: santai, terbuka, triangulasi — bukan tertutup formal.",
    version: 1
  },
  {
    id: "PT-37",
    cluster: "ekonomi",
    level: "sedang",
    source: "pretest",
    stem: "Manakah yang bukan sebab terjadinya perdagangan antarnegara?",
    options: [
      "Memperoleh barang yang tidak diproduksi di dalam negeri",
      "Memperluas pasar bagi produk domestik",
      "Mengimpor teknologi yang lebih modern",
      "Kepemilikan sumber daya yang sama persis antarnegara",
      "Memperoleh keuntungan dari spesialisasi produksi",
    ],
    answer: 3,
    explain: "Perdagangan internasional karena perbedaan SDM/SDA, bukan identik.",
    version: 2
  },
  {
    id: "PT-38",
    cluster: "ekonomi",
    level: "singkat",
    source: "pretest",
    stem: "Manakah yang paling tepat menggambarkan ruang lingkup ekonomi makro?",
    options: [
      "Analisis pasar satu komoditas secara terpisah",
      "Analisis harga suatu barang tertentu saja",
      "Kegiatan ekonomi konsumen dan produsen individu",
      "Analisis tingkah laku satu pelaku ekonomi tertentu",
      "Perilaku ekonomi agregat atau perekonomian secara keseluruhan",
    ],
    answer: 4,
    explain: "Ekonomi makro = agregat perekonomian (PDB, inflasi, pengangguran).",
    version: 2
  },
  {
    id: "PT-39",
    cluster: "teknis",
    level: "singkat",
    source: "pretest",
    stem: "Dalam perencanaan terdapat karakteristik perencanaan. Manakah yang bukan karakteristik proses perencanaan?",
    options: [
      "Mengarah ke perubahan",
      "Memilih alternatif",
      "Hanya mendokumentasikan kondisi eksisting tanpa memilih alternatif tindakan",
      "Mengarah ke pencapaian tujuan",
      "Bertumpu pada rasionalitas",
    ],
    answer: 2,
    explain: "Perencanaan bukan sekadar dokumentasi kondisi saat ini; intinya memilih alternatif tindakan menuju perubahan secara rasional.",
    version: 2
  },
  {
    id: "PT-40",
    cluster: "sosial",
    level: "sedang",
    source: "pretest",
    stem: "Komunikasi pembangunan bertujuan membangkitkan partisipasi masyarakat. Manakah yang bukan makna komunikasi pembangunan yang tepat?",
    options: [
      "Menyalurkan aspirasi tanpa membangun kesadaran berpartisipasi",
      "Menumbuhkan kesadaran masyarakat untuk berpartisipasi",
      "Menginformasikan kesempatan bagi masyarakat untuk berpartisipasi",
      "Menunjukkan dan meningkatkan kemampuan masyarakat berpartisipasi",
      "Menggerakkan kemauan masyarakat untuk berpartisipasi",
    ],
    answer: 0,
    explain: "Komunikasi pembangunan: menumbuhkan kesadaran partisipasi (bukan hanya menyalurkan aspirasi).",
    version: 2
  }
];
