// Bank soal Pre Test UKOM — node build-pretest.cjs
const BANK_PRETEST = [
  {
    id: "PT-01",
    cluster: "sosial",
    level: "sedang",
    source: "pretest",
    stem: "Social Overhead Capital (SOC) memiliki fungsi dan peran antara lain …",
    options: [
      "Menurunkan partisipasi masyarakat",
      "Alat untuk menyelesaikan konflik yang ada di dalam masyarakat",
      "Menjadi alat tawar menawar pemerintah",
      "Memberikan kontribusi tersendiri bagi terjadinya integrasi social",
      "Membentuk solidaritas social masyarakat dengan pilar kesukarelaan",
    ],
    answer: 3,
    explain: "SOC = norma, kepercayaan, jaringan yang mendukung produktivitas sosial (integrasi sosial).",
    version: 1
  },
  {
    id: "PT-02",
    cluster: "sosial",
    level: "sedang",
    source: "pretest",
    stem: "Secara umum terdapat beberapa perbedaan antara RRA dan PRA (Chambers, 1996), yaitu :",
    options: [
      "Titik berat perilaku",
      "Hasil jangka pendek",
      "Kurun waktu perkembangan, RRA akhir 1980an dan PRA akhir 1990an",
      "Potensi sumber informasi",
      "Kemampuan masyarakat setempat",
    ],
    answer: 3,
    explain: "Perbedaan RRA vs PRA: potensi sumber informasi (PRA lebih partisipatif).",
    version: 1
  },
  {
    id: "PT-03",
    cluster: "spasial",
    level: "sedang",
    source: "pretest",
    stem: "Perhitungan statistik, interpretasi data kuantitatif dan kualitatif, analisis peta, interpretasi citra, dan pengolahan data spasial dengan SIG termasuk prosedur pada tahapan perencanaan tata ruang. Tahapan yang dimaksud adalah …",
    options: [
      "Perumusan rencana tata ruang wilayah",
      "Penjabaran konsep dan strategi pengembangan tata ruang wilayah",
      "Pemetaan data sosial kemasyarakatan",
      "Kegiatan analisis wilayah",
      "Kegiatan pemahaman karakteristik wilayah",
    ],
    answer: 0,
    explain: "Tahapan perencanaan tata ruang: perumusan rencana (bukan hanya pemetaan sosial).",
    version: 1
  },
  {
    id: "PT-04",
    cluster: "spasial",
    level: "sedang",
    source: "pretest",
    stem: "Zona perumahan dengan kepadatan sedang memiliki kriteria kepadatan bangunan perumahan. Manakah ketentuan yang tepat?",
    options: [
      "40–100 rumah/ha (kepadatan padat)",
      "10–40 rumah/ha (kepadatan sedang)",
      "100–1000 rumah/ha (kepadatan tinggi)",
      "Di atas 1000 rumah/ha (kepadatan sangat tinggi)",
    ],
    answer: 1,
    explain: "Kepadatan sedang menurut Perpres penataan ruang: 10–40 rumah/ha.",
    version: 1
  },
  {
    id: "PT-05",
    cluster: "sosial",
    level: "sedang",
    source: "pretest",
    stem: "Perencanaan sebagai mobilisasi sosial adalah...",
    options: [
      "Merubah kedudukan masyarakat dari obyek menjadi subyek pembangunan",
      "Perubahan sosial dipengaruhi oleh tradisi pemikiran positivisme dari pada penekanan terhadap keterlibatan aktor sosial dalam proses perencanaan",
      "Proses dialogis, relasi non hirarkis, komitmen pelaksanaan eksperimen sosial, toleransi terhadap perbedaan dan mengutamakan transaksi social",
      "Penekanan pada upaya penemuan cara paling efektif bagi negara dalam perencanaan",
      "Bentuk partisipasi masyarakat dalam perencanaan dan penekanan kepada emansipasi kemanusiaan terhadap penindasan sosial",
    ],
    answer: 4,
    explain: "Mobilisasi sosial: penekanan emansipasi dan partisipasi (Friedmann).",
    version: 1
  },
  {
    id: "PT-06",
    cluster: "spasial",
    level: "singkat",
    source: "pretest",
    stem: "Stakeholder dalam perencanaan tata ruang yang berfungsi sebagai inisiator adalah",
    options: [
      "Perencana",
      "Pemerintah",
      "Masyarakat",
      "LSM",
      "Swasta",
    ],
    answer: 1,
    explain: "Inisiator penataan ruang pada praktik umum: pemerintah daerah.",
    version: 1
  },
  {
    id: "PT-07",
    cluster: "ekonomi",
    level: "singkat",
    source: "pretest",
    stem: "Hukum permintaan dalam ekonomi menyatakan bahwa…",
    options: [
      "Jumlah barang yang diminta akan naik ketika harga barang tersebut turun",
      "Bila harga sesuatu barang meningkat, maka produsen akan meningkatkan jumlah barang yang dijualnya",
      "Semakin tinggi harga, maka semakin banyak pula jumlah barang yang ditawarkan",
      "Jumlah barang yang diminta akan turun ketika harga barang tersebut naik",
      "Semakin rendah harga barang, jumlah yang ditawarkan juga akan semakin sedikit",
    ],
    answer: 3,
    explain: "Hukum permintaan: Qd turun saat harga naik (doc juga menyorot opsi naik saat turun).",
    version: 1
  },
  {
    id: "PT-08",
    cluster: "sosial",
    level: "singkat",
    source: "pretest",
    stem: "Yang tidak termasuk dari teknik – teknik PRA adalah...",
    options: [
      "Teknik penelusuran alur Sejarah",
      "Kajian mata pencaharian",
      "Teknik transect",
      "Wawancara informal dan formal",
      "Teknik pembuatan bagan kecendrungan dan perubahan",
    ],
    answer: 3,
    explain: "Bukan teknik PRA: wawancara formal berlebihan (PRA informal/partisipatif).",
    version: 1
  },
  {
    id: "PT-09",
    cluster: "teknis",
    level: "singkat",
    source: "pretest",
    stem: "Proses sistematis dalam mengumpulkan, menganalisis, dan menginterpretasikan informasi untuk mengetahui tingkat keberhasilan pelaksanaan kegiatan, kebijakan atau program dengan kriteria tertentu untuk keperluan pembuatan keputusan disebut:",
    options: [
      "Monitoring",
      "Perencanaan",
      "Pengawasan",
      "Evaluasi",
      "Pengukuran",
    ],
    answer: 3,
    explain: "Evaluasi = penilaian keberhasilan program untuk keputusan.",
    version: 1
  },
  {
    id: "PT-10",
    cluster: "ekonomi",
    level: "sedang",
    source: "pretest",
    stem: "Teori Basis Ekonomi (Economic Base Theory) menyatakan bahwa …",
    options: [
      "Laju pertumbuhan ekonomi suatu wilayah ditentukan oleh besarnya peningkatan ekspor dan impor dari wilayah tersebut",
      "Teori basis ekonomi hanya terdiri atas sector basis",
      "Faktor penentu utama pertumbuhan ekonomi suatu daerah berhubungan langsung dengan penawaran barang dan jasa dari luar daerah",
      "Laju pertumbuhan ekonomi suatu wilayah ditentukan oleh besarnya peningkatan ekspor wilayah tersebut",
      "Laju pertumbuhan ekonomi suatu wilayah ditentukan oleh besarnya peningkatan impor wilayah tersebut",
    ],
    answer: 3,
    explain: "Economic base: pertumbuhan daerah ditopang ekspor sektor basis.",
    version: 1
  },
  {
    id: "PT-11",
    cluster: "sosial",
    level: "panjang",
    source: "pretest",
    stem: "Terminologi kebijakan pembangunan yang partisipasif adalah:",
    options: [
      "Mengutamakan pertimbangan teknis dan keilmuan dari pemerintah dalam membangun pondasi argumentatif strategi pembangunan",
      "Berhubungan dengan masyarakat",
      "Masyarakat mengambil peran serta ikut mempengaruhi proses perencanaan, pelaksanaan dan pemantauan kebijakan-kebijakan yang langsung mempengaruhi kehidupan mereka menempatkan pemerintah sebagai pihak yang secara mutlak berwenang untuk merencanakan dan melaksanakan pembangunan untuk kepentingan public",
      "Menekankan prinsip-prinsip teknologi, seperti efisiensi, kuantifikasi, dan produktivitas",
      "Model ini biasanya berafiliasi dengan pola pembangunan top-down, pemerintah berwenang mengatur masyarakat dan tingkat pemerintah dibawahnya.",
    ],
    answer: 2,
    explain: "Kebijakan partisipatif: masyarakat mempengaruhi perencanaan–pelaksanaan–pemantauan.",
    version: 1
  },
  {
    id: "PT-12",
    cluster: "ekonomi",
    level: "singkat",
    source: "pretest",
    stem: "Yang tidak termasuk ke dalam variabel-variabel utama ekonomi adalah ….",
    options: [
      "Kesempatan kerja dan pengangguran",
      "Ekspor dan Impor",
      "Produk domestic bruto (PDB)",
      "Perilaku konsumtif",
      "Inflasi",
    ],
    answer: 3,
    explain: "Variabel makro: perilaku konsumtif bukan variabel utama makro.",
    version: 1
  },
  {
    id: "PT-13",
    cluster: "spasial",
    level: "sedang",
    source: "pretest",
    stem: "Manakah pernyataan yang tepat mengenai RDTR (Rencana Detail Tata Ruang)?",
    options: [
      "RDTR memuat ketentuan teknis rinci tapak/zona pada skala detail",
      "RDTR sama dengan RTRW provinsi",
      "RDTR mencakup seluruh wilayah nasional tanpa batas administratif",
      "RDTR hanya berisi peta administrasi tanpa aturan zonasi",
      "RDTR menggantikan peraturan tata ruang kabupaten/kota",
    ],
    answer: 0,
    explain: "RDTR berskala detail (rincian tapak/zona); RTRW menyusun struktur ruang kabupaten/kota.",
    version: 1
  },
  {
    id: "PT-14",
    cluster: "teknis",
    level: "singkat",
    source: "pretest",
    stem: "Yang tidak termasuk fungsi perencanaan diantaranya ….",
    options: [
      "Pedoman pelaksanaan kegiatan yang ditujukan untuk tujuan tertentu",
      "Memilih berbagai macam alternatif",
      "Berkaitan dengan kegiatan ekonomi dari konsumen dan produsen",
      "Penyusunan skala prioritas",
      "Alat ukur/acuan untuk melakukan evaluasi",
    ],
    answer: 2,
    explain: "Fungsi perencanaan: bukan teori mikro konsumen–produsen.",
    version: 1
  },
  {
    id: "PT-15",
    cluster: "ekonomi",
    level: "sedang",
    source: "pretest",
    stem: "Jumlah barang yang diproduksikan tahun 2022 sebanyak 500 unit. Jika harga barang perunit sebesar Rp. 300.000,- tahun 2017 dianggap kondisi yang stabil, maka harga barang tersebut pada tahun tersebut digunakan sebagai harga dasar, sehingga PDB tahun 2022 berdasarkan harga konstan adalah ….",
    options: [
      "Rp. 60.000.000,-",
      "Rp. 300.000.000,-",
      "Rp. 30.000.000-",
      "Rp. 15.000.000,-",
      "Rp. 150.000.000,-",
    ],
    answer: 4,
    explain: "PDB konstan = 500 × Rp 300.000 = Rp 150.000.000.",
    version: 1
  },
  {
    id: "PT-16",
    cluster: "spasial",
    level: "singkat",
    source: "pretest",
    stem: "Yang merupakan contoh \"formal region\" adalah",
    options: [
      "Wilayah administrasi negara",
      "Wilayah abstrak",
      "Wilayah persebaran perkebunan",
      "Wilayah cakupan komuter",
      "Wilayah persebaran komoditas pertanian",
    ],
    answer: 0,
    explain: "Formal region = wilayah administrasi negara.",
    version: 1
  },
  {
    id: "PT-17",
    cluster: "teknis",
    level: "sedang",
    source: "pretest",
    stem: "Tujuan evaluasi pembangunan adalah :",
    options: [
      "Semua benar",
      "Untuk menjamin terlaksananya kebijakan, program dan proyek sesuai dengan target dan rencana yang telah ditetapkan (on Track – on Schedule)",
      "Agar ada umpan balik terhadap kebijakan, program dan proyek, untuk diteruskan dilanjutkan dengan perbaikan atau dihentikan",
      "Agar kebijakan, program dan proyek mampu mempertanggungjawabkan penggunaan dana publik (akuntabilitas)",
      "Untuk membantu pemangku kepentingan belajar lebih banyak mengenai kebijakan, program dan proyek",
    ],
    answer: 0,
    explain: "Tujuan evaluasi: semua benar (akuntabilitas, umpan balik, on track).",
    version: 1
  },
  {
    id: "PT-18",
    cluster: "teknis",
    level: "singkat",
    source: "pretest",
    stem: "Rumusan umum mengenai keadaan yang diinginkan pada akhir periode perencanaan adalah…",
    options: [
      "Misi",
      "Kebijakan",
      "Strategi",
      "Visi",
      "Program",
    ],
    answer: 3,
    explain: "Visi = keadaan masa depan yang ingin dicapai.",
    version: 1
  },
  {
    id: "PT-19",
    cluster: "spasial",
    level: "singkat",
    source: "pretest",
    stem: "Suatu wilayah teritorial dengan pengertian, batasan, dan perwatakannya didasarkan pada wewenang administratif pemerintahan yang ditentukan oleh peraturan perundang-undangan tertentu, disebut...",
    options: [
      "Kawasan",
      "Wilayah",
      "Area",
      "Komunitas",
      "Daerah",
    ],
    answer: 4,
    explain: "Daerah = wilayah administratif menurut peraturan.",
    version: 1
  },
  {
    id: "PT-20",
    cluster: "ekonomi",
    level: "sedang",
    source: "pretest",
    stem: "Yang dimaksud dengan Produk Domestic Bruto (Gross Domestic Product) adalah …",
    options: [
      "Nilai seluruh barang yang dihasilkan oleh semua unit ekonomi dalam suatu negara, termasuk barang yang dihasilkan oleh warga Negara lain yang tinggal di Negara tersebut",
      "Nilai seluruh barang yang dihasilkan oleh semua unit ekonomi dalam suatu Negara",
      "Nilai sebagian barang/jasa yang dihasilkan oleh semua unit ekonomi dalam suatu negara, termasuk barang/jasa yang dihasilkan oleh warga Negara lain yang tinggal di Negara tersebut",
      "Nilai sebagian barang yang dihasilkan oleh suatu Negara",
      "Nilai seluruh barang/jasa yang dihasilkan oleh semua unit ekonomi dalam suatu negara, termasuk barang/jasa yang dihasilkan oleh warga Negara lain yang tinggal di Negara tersebut",
    ],
    answer: 4,
    explain: "PDB/GDP: seluruh barang/jasa domestik termasuk produksi residen asing.",
    version: 1
  },
  {
    id: "PT-21",
    cluster: "teknis",
    level: "sedang",
    source: "pretest",
    stem: "Salah satu pendekatan perencanaan pembangunan daerah yang medefinisikan rencana pembangunan adalah hasil penjabaran visi misi kepala daerah adalah pendekatan yang:",
    options: [
      "Semua jawaban salah",
      "Politik",
      "Teknoratis",
      "Top-down dan bottom-up",
      "Partisipatif",
    ],
    answer: 1,
    explain: "Pendekatan politik: rencana sebagai penjabaran visi–misi kepala daerah.",
    version: 1
  },
  {
    id: "PT-22",
    cluster: "teknis",
    level: "singkat",
    source: "pretest",
    stem: "Berikut ini adalah syarat dokumen perencanaan, kecuali:",
    options: [
      "Relevant",
      "Measureable",
      "Multi years",
      "Spesifik",
      "Achievable",
    ],
    answer: 2,
    explain: "SMART: Multi years bukan komponen SMART (Specific, Measurable, dll.).",
    version: 1
  },
  {
    id: "PT-23",
    cluster: "spasial",
    level: "singkat",
    source: "pretest",
    stem: "Yang merupakan masalah mutlak dalam perencanaan spasial, yaitu",
    options: [
      "Kemiskinan",
      "tata guna lahan tidak optimal",
      "tingkat pendidikan",
      "jangkauan jaringan internet",
      "struktur ruang belum pas",
    ],
    answer: 1,
    explain: "Masalah mutlak perencanaan spasial: tata guna lahan tidak optimal.",
    version: 1
  },
  {
    id: "PT-24",
    cluster: "sosial",
    level: "sedang",
    source: "pretest",
    stem: "Indeks Pembangunan Manusia (IPM) digunakan sebagai indikator pembangunan manusia karena …",
    options: [
      "IPM menerjemahkan konsep kompleks ke dalam tiga dimensi dasar yang terukur",
      "IPM menstimulasi diskusi mengenai pembangunan daerah",
      "IPM membantu pergeseran paradigma pembangunan dari ekonomi semata ke aspek kesejahteraan manusia",
      "IPM berfokus pada kapabilitas yang relevan untuk negara tertinggal",
      "IPM memberikan motivasi kompetisi antarpetani semata",
    ],
    answer: 0,
    explain: "IPM merangkum dimensi kesehatan, pendidikan, pendapatan.",
    version: 1
  },
  {
    id: "PT-25",
    cluster: "sosial",
    level: "sedang",
    source: "pretest",
    stem: "Perencanaan dilihat sebagai proses yang dilakukan oleh dan untuk masyarakat dalam pembangunan merupakan pengertian perencanaan sebagai...",
    options: [
      "Perencanaan sebagai sosial learning",
      "Perencanaan sebagai ekonomi learning",
      "Perencanaan sebagai fisik learning",
      "Perencanaan sebagai mobilisasi learning",
      "Perencanaan sebagai politik learning",
    ],
    answer: 0,
    explain: "Perencanaan sebagai social learning (proses belajar bersama masyarakat).",
    version: 1
  },
  {
    id: "PT-26",
    cluster: "sosial",
    level: "singkat",
    source: "pretest",
    stem: "Ada 4 pilar utama dalam pengentasan kemiskinan dan ketimpangan diantaranya..., kecuali...",
    options: [
      "Melindungi orang miskin dari guncangan dan bencana",
      "Menerapkan kebijakan fiskal yang progresif",
      "Menciptakan pekerjaan yang layak untuk semua",
      "Memberikan peningkatan kepatuhan pajak",
      "Memberikan peluang yang sama di awal kehidupan",
    ],
    answer: 3,
    explain: "Bukan pilar pengentasan kemiskinan: peningkatan patuh pajak semata.",
    version: 1
  },
  {
    id: "PT-27",
    cluster: "spasial",
    level: "singkat",
    source: "pretest",
    stem: "Berdasarkan Undang-Undang Republik Indonesia Nomor 26 Tahun 2007 Tentang Penataan Ruang, Penataan ruang berdasarkan fungsi utama kawasan terdiri atas ....",
    options: [
      "Wilayah nasional, penataan ruang wilayah provinsi, dan penataan ruang wilayah kabupaten/kota",
      "Sistem wilayah dan sistem internal perkotaan.",
      "Kawasan lindung dan kawasan budi daya",
      "Ruang kawasan perkotaan dan penataan ruang kawasan perdesaan.",
      "Ruang kawasan strategis nasional, penataan ruang kawasan strategis provinsi, dan penataan ruang kawasan strategis kabupaten/kota.",
    ],
    answer: 2,
    explain: "UU 26/2007: penataan ruang → kawasan lindung & budi daya.",
    version: 1
  },
  {
    id: "PT-28",
    cluster: "sosial",
    level: "sedang",
    source: "pretest",
    stem: "Proses pembangunan bisa dilakukan dengan pendekatan berikut, kecuali:",
    options: [
      "Pendekatan Trickle down effect",
      "Pendekatan proses top-down dan bottom-up",
      "Pendekatan Partisipatif",
      "Pendekatan politis",
      "Pendekatan proses teknorat",
    ],
    answer: 0,
    explain: "Trickle-down bukan pendekatan partisipatif/pemberdayaan.",
    version: 1
  },
  {
    id: "PT-29",
    cluster: "spasial",
    level: "sedang",
    source: "pretest",
    stem: "Bagian wilayah kabupaten/kota yang penataan ruangnya diprioritaskan karena memiliki pengaruh sangat penting dalam lingkup kabupaten terhadap ekonomi, sosial budaya dan lingkungan adalah",
    options: [
      "Kawasan budidaya",
      "Kawasan agropolitan",
      "Kawasan lindung",
      "Kawasan strategis",
      "Kawasan metropolitan",
    ],
    answer: 3,
    explain: "Wilayah prioritas penataan ruang kab/kota: kawasan strategis (bukan budidaya).",
    version: 1
  },
  {
    id: "PT-30",
    cluster: "spasial",
    level: "singkat",
    source: "pretest",
    stem: "Pada struktur ruang kota, struktur yang menggambarkan adanya tingkat perhubungan dengan kondisi sosial dalam ruang adalah",
    options: [
      "Struktur Social",
      "Struktur Budaya",
      "Struktur Ekonomi",
      "Struktur Fisik",
      "Struktur Masyarakat",
    ],
    answer: 0,
    explain: "Struktur sosial = pola relasi sosial dalam ruang kota.",
    version: 1
  },
  {
    id: "PT-31",
    cluster: "teknis",
    level: "sedang",
    source: "pretest",
    stem: "Tahapan perencanaan pembangunan nasional meliputi…",
    options: [
      "Penyusunan rencana",
      "Penetapan rencana",
      "Evaluasi pelaksanaan rencana",
      "Pengendalian pelaksanaan rencana",
      "Semua benar",
    ],
    answer: 4,
    explain: "Tahapan nasional: penyusunan, penetapan, pengendalian, evaluasi.",
    version: 1
  },
  {
    id: "PT-32",
    cluster: "ekonomi",
    level: "singkat",
    source: "pretest",
    stem: "Definisi inflasi adalah …",
    options: [
      "kecepatan penurunan nilai mata uang yang tidak berdampak pada peningkatan harga barang dan jasa secara umum",
      "suatu kondisi saat harga barang yang ada didalam sebuah Negara mengalami penurunan",
      "suatu periode dimana harga-harga secara umum mengalami penurunan dan nilai uang bertambah",
      "Kecenderungan penurunan harga umum yang terjadi secara terus menerus selama periode tertentu",
      "suatu kecenderungan kenaikan harga umum yang terjadi secara terus menerus selama periode tertentu, biasanya satu tahun",
    ],
    answer: 4,
    explain: "Inflasi = kenaikan harga umum terus-menerus (±1 tahun).",
    version: 1
  },
  {
    id: "PT-33",
    cluster: "sosial",
    level: "sedang",
    source: "pretest",
    stem: "Kesenjangan sosial merupakan ketidakseimbangan yang mencolok dalam masyarakat. Berikut yang termasuk faktor alami penyebab ketimpangan sosial adalah …",
    options: [
      "Pengaruh globalisasi",
      "Kebijakan pemerintah",
      "Pengaruh kondisi demografis",
      "Faktor internal individu",
      "Perbedaan Sumber daya alam",
    ],
    answer: 4,
    explain: "Faktor alami ketimpangan: perbedaan sumber daya alam.",
    version: 1
  },
  {
    id: "PT-34",
    cluster: "teknis",
    level: "singkat",
    source: "pretest",
    stem: "Suatu proses untuk menentukan tindakan masa depan yang tepat melalui urutan pilihan dengan memperhitungkan sumberdaya yang tepat disebut",
    options: [
      "Program",
      "Perencanaan",
      "Visi",
      "Pembangunan",
      "Kegiatan",
    ],
    answer: 1,
    explain: "Perencanaan = penetapan tindakan masa depan dengan alokasi sumber daya.",
    version: 1
  },
  {
    id: "PT-35",
    cluster: "sosial",
    level: "singkat",
    source: "pretest",
    stem: "Suatu proses yang terjadi ketika satu pihak secara negatif mempengaruhi pihak lain, dengan melakukan kekerasan fisik yang membuat orang lain, perasaan dan fisiknya terganggu. Penjelasan tersebut merupakan pengertian dari ...",
    options: [
      "Stereotype",
      "Etnosentrisme",
      "Konflik",
      "Prasangka",
      "Diskriminasi",
    ],
    answer: 2,
    explain: "Konflik = pihak saling mengganggu (termasuk kekerasan fisik).",
    version: 1
  },
  {
    id: "PT-36",
    cluster: "sosial",
    level: "sedang",
    source: "pretest",
    stem: "PRA merupakan metode pendekatan belajar mengenai kondisi dan kehidupan pedesaan dari, dengan, oleh masyarakat pedesaan sendiri, meliputi kegiatan menganalisis, merencanakan dan bertindak. Prinsip- prinsip PRA diantaranya sebagai berikut, kecuali...",
    options: [
      "Santai dan informal",
      "Triangulasi",
      "Tertutup dan formal",
      "Terbuka",
      "Optimalisasi hasil",
    ],
    answer: 2,
    explain: "PRA: santai, terbuka, triangulasi — bukan tertutup formal.",
    version: 1
  },
  {
    id: "PT-37",
    cluster: "ekonomi",
    level: "sedang",
    source: "pretest",
    stem: "Sebab –sebab terjadinya perdagangan antar Negara adalah, kecuali…",
    options: [
      "Memperoleh barang yang diproduksi didalam negeri",
      "Memperluas pasar",
      "Mengimpor teknologi modern",
      "Kepemilikan sumber daya yang sama",
      "Memperoleh keuntungan dari spesialisasi",
    ],
    answer: 3,
    explain: "Perdagangan internasional karena perbedaan SDM/SDA, bukan identik.",
    version: 1
  },
  {
    id: "PT-38",
    cluster: "ekonomi",
    level: "singkat",
    source: "pretest",
    stem: "Ruang lingkup ekonomi makro (macroeconomics) adalah ….",
    options: [
      "Dikenal sebagai pasar atau market",
      "Menganalisis harga suatu barang tertentu saja",
      "Berkaitan dengan kegiatan ekonomi dari konsumen dan produsen",
      "Menganalisis tingkah laku pelaku ekonomi tertentu saja",
      "Berkaitan dengan perilaku ekonomi aggregate atau perekonomian secara keseluruhan",
    ],
    answer: 4,
    explain: "Ekonomi makro = agregat perekonomian (PDB, inflasi, pengangguran).",
    version: 1
  },
  {
    id: "PT-39",
    cluster: "teknis",
    level: "singkat",
    source: "pretest",
    stem: "Dalam perencanaan terdapat karakteristik perencanaan, berikut merupakan karakteristik perencanaan kecuali ….",
    options: [
      "Mengarah ke perubahan",
      "Memilih alternatif",
      "Pernyataan pilihan tindakan",
      "Mengarah ke pencapaian tujuan",
      "Bertumpu pada rasionalitas",
    ],
    answer: 2,
    explain: "Karakteristik perencanaan: memilih alternatif (bukan sekadar 'mengarah perubahan' sebagai pengecualian).",
    version: 1
  },
  {
    id: "PT-40",
    cluster: "sosial",
    level: "sedang",
    source: "pretest",
    stem: "Komunikasi pembangunan adalah cara yang harus ditempuh untuk membangkitkan dan mengembangkan partisipasi masyarakat dalam proses pembangunan, dalam arti di bawah ini, kecuali:",
    options: [
      "Menyalurkan aspirasi masyarakat",
      "Menumbuhkan kesadaran masyarakat untuk berpartisipasi",
      "Menginformasikan tentang adanya kesempatan bagi masyarakat untuk berpartisipasi",
      "Menunjukkan dan meningkatkan kemampuan masyarakat untuk berpartisipasi",
      "Menggerakkan kemauan masyarakat untuk berpartisipasi",
    ],
    answer: 1,
    explain: "Komunikasi pembangunan: menumbuhkan kesadaran partisipasi (bukan hanya menyalurkan aspirasi).",
    version: 1
  }
];

const BANK_PRETEST_VARIAN = [
  {
    id: "PT-V01",
    cluster: "sosial",
    level: "sedang",
    source: "pretest-varian",
    stem: "Social Overhead Capital (SOC) menurut teori pembangunan berperan untuk …",
    options: [
      "Menurunkan partisipasi masyarakat dalam pembangunan",
      "Menjadi alat tawar-menawar semata antara kelompok",
      "Memperkuat integrasi sosial dan kohesi antarkelompok",
      "Mengganti fungsi lembaga pemerintah daerah",
      "Hanya mengatur tata ruang fisik kota",
    ],
    answer: 2,
    explain: "SOC = norma, kepercayaan, jaringan yang mendukung produktivitas sosial (integrasi sosial).",
    version: 1
  },
  {
    id: "PT-V02",
    cluster: "sosial",
    level: "sedang",
    source: "pretest-varian",
    stem: "Perbedaan utama Rapid Rural Appraisal (RRA) dan Participatory Rural Appraisal (PRA) menurut Chambers (1996) terletak pada …",
    options: [
      "Titik berat pada perilaku individu",
      "Fokus hasil jangka pendek semata",
      "Perbedaan kurun waktu lahirnya metode",
      "Sumber informasi dan cara melibatkan masyarakat",
      "Kemampuan statistik masyarakat setempat",
    ],
    answer: 3,
    explain: "Perbedaan RRA vs PRA: potensi sumber informasi (PRA lebih partisipatif).",
    version: 1
  },
  {
    id: "PT-V03",
    cluster: "spasial",
    level: "sedang",
    source: "pretest-varian",
    stem: "Kegiatan perumusan rencana tata ruang wilayah dalam rantai teknis perencanaan setara dengan tahap …",
    options: [
      "Perumusan rencana tata ruang",
      "Penjabaran strategi pengembangan saja",
      "Pemetaan sosial kemasyarakatan saja",
      "Analisis wilayah tanpa rencana",
      "Pemahaman karakteristik tanpa kebijakan ruang",
    ],
    answer: 0,
    explain: "Tahapan perencanaan tata ruang: perumusan rencana (bukan hanya pemetaan sosial).",
    version: 1
  },
  {
    id: "PT-V04",
    cluster: "spasial",
    level: "sedang",
    source: "pretest-varian",
    stem: "Kepadatan bangunan perumahan sedang menurut ketentuan umum penataan ruang setara dengan …",
    options: [
      "Di bawah 10 unit/ha",
      "10–40 unit/ha",
      "40–100 unit/ha",
      "100–1000 unit/ha",
      "Di atas 1000 unit/ha",
    ],
    answer: 1,
    explain: "Kepadatan sedang (Perpres): 10–40 rumah/ha. Highlight doc ke padat (40–100) dikoreksi.",
    version: 1
  },
  {
    id: "PT-V05",
    cluster: "sosial",
    level: "sedang",
    source: "pretest-varian",
    stem: "Perencanaan sebagai mobilisasi sosial menekankan …",
    options: [
      "Masyarakat tetap objek pembangunan",
      "Positivisme teknokrat tanpa aktor sosial",
      "Dialog, relasi non-hierarkis, dan emansipasi",
      "Efisiensi negara tanpa partisipasi",
      "Penemuan cara paling efisien bagi negara semata",
    ],
    answer: 2,
    explain: "Mobilisasi sosial: penekanan emansipasi dan partisipasi (Friedmann).",
    version: 1
  },
  {
    id: "PT-V06",
    cluster: "spasial",
    level: "singkat",
    source: "pretest-varian",
    stem: "Stakeholder yang umumnya memegang peran inisiator awal penataan ruang di tingkat daerah adalah …",
    options: [
      "Perencana konsultan swasta",
      "Pemerintah daerah",
      "Masyarakat adat semata",
      "LSM internasional",
      "Pelaku usaha properti",
    ],
    answer: 1,
    explain: "Inisiator penataan ruang pada praktik umum: pemerintah daerah.",
    version: 1
  },
  {
    id: "PT-V07",
    cluster: "ekonomi",
    level: "singkat",
    source: "pretest-varian",
    stem: "Hukum permintaan (law of demand) menyatakan hubungan antara harga dan kuantitas diminta …",
    options: [
      "Q naik saat P naik",
      "Q naik saat P turun",
      "Q tetap whatever P",
      "Q turun saat P turun",
      "P dan Q tidak berkorelasi",
    ],
    answer: 1,
    explain: "Hukum permintaan: Qd turun saat harga naik (doc juga menyorot opsi naik saat turun).",
    version: 1
  },
  {
    id: "PT-V08",
    cluster: "sosial",
    level: "singkat",
    source: "pretest-varian",
    stem: "Manakah yang BUKAN contoh teknik Participatory Rural Appraisal (PRA)?",
    options: [
      "Transect walk",
      "Kajian mata pencaharian",
      "Penelusuran sejarah",
      "Wawancara formal berlapis birokrasi",
      "Bagan kecenderungan perubahan",
    ],
    answer: 3,
    explain: "Bukan teknik PRA: wawancara formal berlebihan (PRA informal/partisipatif).",
    version: 1
  },
  {
    id: "PT-V09",
    cluster: "teknis",
    level: "singkat",
    source: "pretest-varian",
    stem: "Kegiatan sistematis menilai keberhasilan program terhadap kriteria untuk pengambilan keputusan disebut …",
    options: [
      "Monitoring",
      "Perencanaan",
      "Pengawasan administratif",
      "Evaluasi",
      "Pengukuran fisik",
    ],
    answer: 3,
    explain: "Evaluasi = penilaian keberhasilan program untuk keputusan.",
    version: 1
  },
  {
    id: "PT-V10",
    cluster: "ekonomi",
    level: "sedang",
    source: "pretest-varian",
    stem: "Menurut economic base theory, pertumbuhan ekonomi wilayah sangat dipengaruhi oleh …",
    options: [
      "Impor semata",
      "Ekspor sektor basis",
      "Sektor non-basis saja",
      "Penawaran dari luar tanpa ekspor",
      "Hanya konsumsi rumah tangga",
    ],
    answer: 1,
    explain: "Economic base: pertumbuhan daerah ditopang ekspor sektor basis.",
    version: 1
  },
  {
    id: "PT-V11",
    cluster: "sosial",
    level: "panjang",
    source: "pretest-varian",
    stem: "Ciri kebijakan pembangunan yang bersifat partisipatif adalah …",
    options: [
      "Teknis pusat tanpa masukan lokal",
      "Masyarakat ikut mempengaruhi siklus kebijakan",
      "Top-down tanpa umpan balik",
      "Efisiensi kuantitatif semata",
      "Pemerintah mutlak tanpa dialog",
    ],
    answer: 1,
    explain: "Kebijakan partisipatif: masyarakat mempengaruhi perencanaan–pelaksanaan–pemantauan.",
    version: 1
  },
  {
    id: "PT-V12",
    cluster: "ekonomi",
    level: "singkat",
    source: "pretest-varian",
    stem: "Yang tidak termasuk variabel utama analisis ekonomi makro adalah …",
    options: [
      "Pengangguran",
      "Inflasi",
      "PDB",
      "Perilaku konsumtif individu",
      "Ekspor–impor agregat",
    ],
    answer: 3,
    explain: "Variabel makro: perilaku konsumtif bukan variabel utama makro.",
    version: 1
  },
  {
    id: "PT-V13",
    cluster: "spasial",
    level: "sedang",
    source: "pretest-varian",
    stem: "Perbedaan RDTR dengan RTRW/kawasan yang tepat adalah …",
    options: [
      "RDTR = skala nasional",
      "RDTR = rincian tapak; RTRW = cakupan wilayah terbatas",
      "RDTR tidak punya aturan zonasi",
      "RDTR sama dengan RTRW provinsi",
      "RDTR hanya peta administrasi",
    ],
    answer: 1,
    explain: "RDTR berskala detail; RTRW wilayah terbatas — bukan 'sudah rincian' sebagai kriteria RDTR.",
    version: 1
  },
  {
    id: "PT-V14",
    cluster: "teknis",
    level: "singkat",
    source: "pretest-varian",
    stem: "Yang BUKAN fungsi perencanaan pembangunan adalah …",
    options: [
      "Menyusun alternatif kebijakan",
      "Menetapkan pedoman pelaksanaan",
      "Menganalisis teori elastisitas permintaan individu",
      "Menyusunan skala prioritas",
      "Menjadi acuan evaluasi",
    ],
    answer: 2,
    explain: "Fungsi perencanaan: bukan teori mikro konsumen–produsen.",
    version: 1
  },
  {
    id: "PT-V15",
    cluster: "ekonomi",
    level: "sedang",
    source: "pretest-varian",
    stem: "PDB tahun 2022 harga konstan: 500 unit × Rp 300.000 = …",
    options: [
      "Rp 60.000.000",
      "Rp 150.000.000",
      "Rp 300.000.000",
      "Rp 30.000.000",
      "Rp 15.000.000",
    ],
    answer: 1,
    explain: "PDB konstan = 500 × Rp 300.000 = Rp 150.000.000.",
    version: 1
  },
  {
    id: "PT-V16",
    cluster: "spasial",
    level: "singkat",
    source: "pretest-varian",
    stem: "Contoh wilayah formal region adalah …",
    options: [
      "Wilayah administrasi negara",
      "Wilayah komuter harian",
      "Wilayah sebaran komoditas",
      "Wilayah abstrak perilaku",
      "Daerah aliran sungai saja",
    ],
    answer: 0,
    explain: "Formal region = wilayah administrasi negara.",
    version: 1
  },
  {
    id: "PT-V17",
    cluster: "teknis",
    level: "sedang",
    source: "pretest-varian",
    stem: "Tujuan evaluasi pembangunan yang benar meliputi …",
    options: [
      "Hanya laporan keuangan",
      "Semua: on track, umpan balik, akuntabilitas",
      "Mengganti perencanaan",
      "Menghapus monitoring",
      "Tanpa partisipasi pemangku kepentingan",
    ],
    answer: 1,
    explain: "Tujuan evaluasi: semua benar (akuntabilitas, umpan balik, on track).",
    version: 1
  },
  {
    id: "PT-V18",
    cluster: "teknis",
    level: "singkat",
    source: "pretest-varian",
    stem: "Rumusan keadaan masa depan yang ingin dicapai daerah pada akhir horizon perencanaan adalah …",
    options: [
      "Misi",
      "Kebijakan",
      "Strategi",
      "Visi",
      "Program tahunan",
    ],
    answer: 3,
    explain: "Visi = keadaan masa depan yang ingin dicapai.",
    version: 1
  },
  {
    id: "PT-V19",
    cluster: "spasial",
    level: "singkat",
    source: "pretest-varian",
    stem: "Wilayah teritorial dengan batas administrasi menurut peraturan perundang-undangan disebut …",
    options: [
      "Kawasan",
      "Wilayah",
      "Area",
      "Komunitas",
      "Daerah",
    ],
    answer: 4,
    explain: "Daerah = wilayah administratif menurut peraturan.",
    version: 1
  },
  {
    id: "PT-V20",
    cluster: "ekonomi",
    level: "sedang",
    source: "pretest-varian",
    stem: "Produk Domestik Bruto (PDB) mencakup …",
    options: [
      "Hanya barang domestik",
      "Nilai barang/jasa domestik termasuk residen asing di dalam negeri",
      "Hanya jasa",
      "Hanya ekspor",
      "Pendapatan luar negeri warga di luar negeri",
    ],
    answer: 1,
    explain: "PDB/GDP: seluruh barang/jasa domestik termasuk produksi residen asing.",
    version: 1
  },
  {
    id: "PT-V21",
    cluster: "teknis",
    level: "sedang",
    source: "pretest-varian",
    stem: "Pendekatan yang menempatkan rencana sebagai penjabaran visi–misi kepala daerah adalah pendekatan …",
    options: [
      "Teknoratis murni",
      "Politik",
      "Partisipatif murni",
      "Bottom-up saja",
      "Spasial saja",
    ],
    answer: 1,
    explain: "Pendekatan politik: rencana sebagai penjabaran visi–misi kepala daerah.",
    version: 1
  },
  {
    id: "PT-V22",
    cluster: "teknis",
    level: "singkat",
    source: "pretest-varian",
    stem: "Komponen yang BUKAN bagian kriteria SMART pada indikator program adalah …",
    options: [
      "Specific",
      "Measurable",
      "Multi years",
      "Achievable",
      "Time-bound",
    ],
    answer: 2,
    explain: "SMART: Multi years bukan komponen SMART (Specific, Measurable, dll.).",
    version: 1
  },
  {
    id: "PT-V23",
    cluster: "spasial",
    level: "singkat",
    source: "pretest-varian",
    stem: "Masalah substantif klasik perencanaan tata ruang/wilayah adalah …",
    options: [
      "Kemiskinan semata",
      "Tata guna lahan tidak optimal",
      "Inflasi",
      "ICOR tinggi",
      "Gini coefficient",
    ],
    answer: 1,
    explain: "Masalah mutlak perencanaan spasial: tata guna lahan tidak optimal.",
    version: 1
  },
  {
    id: "PT-V24",
    cluster: "sosial",
    level: "sedang",
    source: "pretest-varian",
    stem: "Alasan IPM dipakai mengukur pembangunan manusia adalah …",
    options: [
      "IPM merangkum dimensi dasar terukur (kesehatan, pendidikan, pendapatan)",
      "IPM hanya PDB per kapita",
      "IPM mengganti RKPD",
      "IPM tanpa data daerah",
      "IPM khusus pertanian",
    ],
    answer: 0,
    explain: "IPM merangkum dimensi kesehatan, pendidikan, pendapatan.",
    version: 1
  },
  {
    id: "PT-V25",
    cluster: "sosial",
    level: "sedang",
    source: "pretest-varian",
    stem: "Perencanaan sebagai proses belajar bersama masyarakat dalam pembangunan disebut …",
    options: [
      "Social learning",
      "Ekonomi learning",
      "Mobilisasi learning",
      "Politik learning",
      "Fisik learning",
    ],
    answer: 0,
    explain: "Perencanaan sebagai social learning (proses belajar bersama masyarakat).",
    version: 1
  },
  {
    id: "PT-V26",
    cluster: "sosial",
    level: "singkat",
    source: "pretest-varian",
    stem: "Bukan pilar pengentasan kemiskinan menurut kerangka umum adalah …",
    options: [
      "Perlindungan sosial",
      "Kebijakan fiskal progresif",
      "Pekerjaan layak",
      "Peningkatan kepatuhan pajak semata",
      "Kesempatan awal kehidupan",
    ],
    answer: 3,
    explain: "Bukan pilar pengentasan kemiskinan: peningkatan patuh pajak semata.",
    version: 1
  },
  {
    id: "PT-V27",
    cluster: "spasial",
    level: "singkat",
    source: "pretest-varian",
    stem: "Menurut UU 26/2007, penataan ruang berdasarkan fungsi utama kawasan adalah …",
    options: [
      "Nasional–provinsi–kabupaten",
      "Lindung dan budi daya",
      "Perkotaan dan perdesaan saja",
      "Strategis nasional saja",
      "Sistem internal perkotaan saja",
    ],
    answer: 1,
    explain: "UU 26/2007: penataan ruang → kawasan lindung & budi daya.",
    version: 1
  },
  {
    id: "PT-V28",
    cluster: "sosial",
    level: "sedang",
    source: "pretest-varian",
    stem: "Pendekatan pembangunan yang dianggap top-down dan kurang partisipatif adalah …",
    options: [
      "Trickle-down effect",
      "Partisipatif",
      "Bottom-up",
      "PRA",
      "Aliansi masyarakat",
    ],
    answer: 0,
    explain: "Trickle-down bukan pendekatan partisipatif/pemberdayaan.",
    version: 1
  },
  {
    id: "PT-V29",
    cluster: "spasial",
    level: "sedang",
    source: "pretest-varian",
    stem: "Bagian kabupaten/kota yang diprioritaskan karena pengaruh strategis terhadap ekonomi–sosial–lingkungan adalah …",
    options: [
      "Kawasan budidaya semata",
      "Kawasan agropolitan",
      "Kawasan lindung",
      "Kawasan strategis",
      "Kawasan metropolitan nasional",
    ],
    answer: 3,
    explain: "Wilayah prioritas penataan ruang kab/kota: kawasan strategis (bukan budidaya).",
    version: 1
  },
  {
    id: "PT-V30",
    cluster: "spasial",
    level: "singkat",
    source: "pretest-varian",
    stem: "Struktur ruang kota yang menggambarkan relasi sosial antar kelompok di ruang adalah …",
    options: [
      "Struktur sosial",
      "Struktur budaya",
      "Struktur ekonomi",
      "Struktur fisik",
      "Struktur ekologis",
    ],
    answer: 0,
    explain: "Struktur sosial = pola relasi sosial dalam ruang kota.",
    version: 1
  },
  {
    id: "PT-V31",
    cluster: "teknis",
    level: "sedang",
    source: "pretest-varian",
    stem: "Tahapan perencanaan pembangunan nasional yang lengkap meliputi …",
    options: [
      "Hanya penyusunan",
      "Penyusunan, penetapan, pengendalian, evaluasi",
      "Hanya evaluasi",
      "Hanya pengendalian",
      "Renstra K/L saja",
    ],
    answer: 1,
    explain: "Tahapan nasional: penyusunan, penetapan, pengendalian, evaluasi.",
    version: 1
  },
  {
    id: "PT-V32",
    cluster: "ekonomi",
    level: "singkat",
    source: "pretest-varian",
    stem: "Inflasi didefinisikan sebagai …",
    options: [
      "Penurunan harga umum terus-menerus",
      "Kenaikan harga umum terus-menerus dalam periode tertentu",
      "Stagnasi harga satu komoditas",
      "Kenaikan nilai tukar rupiah",
      "Penurunan uang beredar",
    ],
    answer: 1,
    explain: "Inflasi = kenaikan harga umum terus-menerus (±1 tahun).",
    version: 1
  },
  {
    id: "PT-V33",
    cluster: "sosial",
    level: "sedang",
    source: "pretest-varian",
    stem: "Faktor alami yang memengaruhi ketimpangan sosial adalah …",
    options: [
      "Kebijakan fiskal",
      "Globalisasi",
      "Perbedaan sumber daya alam",
      "Demografi semata",
      "Perilaku konsumtif",
    ],
    answer: 2,
    explain: "Faktor alami ketimpangan: perbedaan sumber daya alam.",
    version: 1
  },
  {
    id: "PT-V34",
    cluster: "teknis",
    level: "singkat",
    source: "pretest-varian",
    stem: "Proses menentukan tindakan masa depan dengan urutan pilihan dan sumber daya disebut …",
    options: [
      "Program",
      "Perencanaan",
      "Visi",
      "Pembangunan",
      "Kegiatan",
    ],
    answer: 1,
    explain: "Perencanaan = penetapan tindakan masa depan dengan alokasi sumber daya.",
    version: 1
  },
  {
    id: "PT-V35",
    cluster: "sosial",
    level: "singkat",
    source: "pretest-varian",
    stem: "Satu pihak secara negatif memengaruhi pihak lain termasuk gangguan fisik disebut …",
    options: [
      "Stereotype",
      "Etnosentrisme",
      "Konflik",
      "Prasangka",
      "Diskriminasi",
    ],
    answer: 2,
    explain: "Konflik = pihak saling mengganggu (termasuk kekerasan fisik).",
    version: 1
  },
  {
    id: "PT-V36",
    cluster: "sosial",
    level: "sedang",
    source: "pretest-varian",
    stem: "Prinsip PRA yang tidak sesuai adalah …",
    options: [
      "Santai dan informal",
      "Triangulasi",
      "Tertutup dan formal kaku",
      "Terbuka",
      "Optimalisasi hasil",
    ],
    answer: 2,
    explain: "PRA: santai, terbuka, triangulasi — bukan tertutup formal.",
    version: 1
  },
  {
    id: "PT-V37",
    cluster: "ekonomi",
    level: "sedang",
    source: "pretest-varian",
    stem: "Bukan alasan terjadinya perdagangan internasional adalah …",
    options: [
      "Spesialisasi",
      "Perluasan pasar",
      "Impor teknologi",
      "Kepemilikan sumber daya yang sama persis",
      "Perbedaan sumber daya",
    ],
    answer: 3,
    explain: "Perdagangan internasional karena perbedaan SDM/SDA, bukan identik.",
    version: 1
  },
  {
    id: "PT-V38",
    cluster: "ekonomi",
    level: "singkat",
    source: "pretest-varian",
    stem: "Ruang lingkup ekonomi makro berkaitan dengan …",
    options: [
      "Harga satu barang",
      "Satu produsen",
      "Satu konsumen",
      "Perilaku agregat perekonomian",
      "Pasar komoditas lokal saja",
    ],
    answer: 3,
    explain: "Ekonomi makro = agregat perekonomian (PDB, inflasi, pengangguran).",
    version: 1
  },
  {
    id: "PT-V39",
    cluster: "teknis",
    level: "singkat",
    source: "pretest-varian",
    stem: "Bukan karakteristik proses perencanaan adalah …",
    options: [
      "Memilih alternatif",
      "Mengarah ke perubahan kebijakan",
      "Bertumpu rasionalitas",
      "Hanya dokumentasi tanpa pilihan",
      "Mengarah pencapaian tujuan",
    ],
    answer: 3,
    explain: "Karakteristik perencanaan: memilih alternatif (bukan sekadar 'mengarah perubahan' sebagai pengecualian).",
    version: 1
  },
  {
    id: "PT-V40",
    cluster: "sosial",
    level: "sedang",
    source: "pretest-varian",
    stem: "Tujuan komunikasi pembangunan yang tepat adalah …",
    options: [
      "Menyalurkan aspirasi semata",
      "Menumbuhkan kesadaran dan kemampuan partisipasi",
      "Mengganti perencanaan teknis",
      "Menghapus dialog",
      "Hanya media massa",
    ],
    answer: 1,
    explain: "Komunikasi pembangunan: menumbuhkan kesadaran partisipasi (bukan hanya menyalurkan aspirasi).",
    version: 1
  }
];
