// Bank simulasi UKOM (40 soal)
const BANK_SIMULASI = [
  {
    id: "S01",
    cluster: "teknis",
    level: "singkat",
    source: "simulasi",
    stem: "Tahapan penyusunan RKP yang melibatkan musyawarah perencanaan di kabupaten/kota dan provinsi untuk mengumpulkan aspirasi program disebut apa?",
    options: [
      "Penetapan pagu indikatif anggaran",
      "Musrenbang perencanaan pembangunan",
      "Evaluasi kinerja tahunan program",
      "Penetapan Perpres dokumen RKP",
      "Penyusunan RKA final kementerian",
    ],
    answer: 1,
    explain: "Musrenbang (musyawarah perencanaan pembangunan) merupakan forum partisipatif mengumpulkan usulan program sebelum konsolidasi ke RKP.",
    version: 2
  },
  {
    id: "S02",
    cluster: "teknis",
    level: "sedang",
    source: "simulasi",
    stem: "Setelah Musrenbang, K/L menyusun perkiraan alokasi anggaran awal yang belum final dan masih dapat disesuaikan pada harmonisasi RKP. Dokumen/besaran itu disebut apa?",
    options: [
      "Rencana Kerja dan Anggaran (RKA) final",
      "Laporan Pertanggungjawaban (LPJ) tahunan",
      "Pagu indikatif anggaran K/L",
      "Perpres RKP yang telah ditetapkan",
      "Nota keuangan APBN yang final",
    ],
    answer: 2,
    explain: "Pagu indikatif adalah perkiraan plafon anggaran awal K/L dalam penyusunan RKP sebelum penetapan definitif.",
    version: 2
  },
  {
    id: "S03",
    cluster: "teknis",
    level: "sedang",
    source: "simulasi",
    stem: "Pada akhir tahun anggaran, pemerintah menilai capaian target program prioritas, menganalisis hambatan, dan menyusun rekomendasi perbaikan. Tahapan siklus RKP ini disebut apa?",
    options: [
      "Evaluasi kinerja pelaksanaan",
      "Musrenbang tingkat nasional",
      "Penyusunan pagu indikatif",
      "Penetapan Perpres RKP berikutnya",
      "Penyusunan RKA awal kementerian",
    ],
    answer: 0,
    explain: "Evaluasi kinerja dilakukan setelah pelaksanaan untuk menilai capaian, efektivitas, dan kelayakan kebijakan program.",
    version: 2
  },
  {
    id: "S04",
    cluster: "teknis",
    level: "singkat",
    source: "simulasi",
    stem: "Setelah harmonisasi dan persetujuan DPR, RKP ditetapkan secara resmi melalui instrumen hukum apa?",
    options: [
      "Keputusan Menteri Keuangan",
      "Instruksi Presiden operasional",
      "Surat Edaran Bappenas",
      "Peraturan Presiden (Perpres)",
      "Peraturan Daerah tentang APBD",
    ],
    answer: 3,
    explain: "RKP ditetapkan dengan Peraturan Presiden (Perpres) setelah pembahasan dengan DPR sesuai UU 25/2004.",
    version: 2
  },
  {
    id: "S05",
    cluster: "ekonomi",
    level: "sedang",
    source: "simulasi",
    stem: "Untuk memisahkan efek struktur industri dan daya saing regional pada pertumbuhan sektor daerah terhadap nasional, analisis yang tepat adalah apa?",
    options: [
      "Analisis Input-Output antarsektor",
      "Analisis Shift-Share regional",
      "Location Quotient (LQ) sektor",
      "Analisis SWOT kelembagaan",
      "Koefisien Gini ketimpangan",
    ],
    answer: 1,
    explain: "Analisis Shift-Share memecah pertumbuhan sektor menjadi komponen nasional, industri (struktur), dan daya saing regional.",
    version: 2
  },
  {
    id: "S06",
    cluster: "ekonomi",
    level: "sedang",
    source: "simulasi",
    stem: "Perencana daerah ingin mengetahui multiplier investasi infrastruktur terhadap sektor lain melalui rantai pasokan antarsektor. Metode yang tepat adalah apa?",
    options: [
      "Analisis Input-Output",
      "Analisis Shift-Share",
      "Location Quotient (LQ)",
      "Analisis SWOT sektor",
      "Metode Delphi pakar",
    ],
    answer: 0,
    explain: "Tabel Input-Output menunjukkan keterkaitan antarsektor, koefisien teknis, dan dampak multiplier investasi.",
    version: 2
  },
  {
    id: "S07",
    cluster: "ekonomi",
    level: "singkat",
    source: "simulasi",
    stem: "Indeks yang membandingkan proporsi tenaga kerja sektor pariwisata di Kabupaten X dengan proporsi nasional untuk menilai spesialisasi sektor disebut apa?",
    options: [
      "Koefisien Gini ketimpangan",
      "Analisis Shift-Share",
      "Location Quotient (LQ)",
      "Analisis Input-Output",
      "Indeks Pembangunan Manusia",
    ],
    answer: 2,
    explain: "LQ > 1 menunjukkan sektor relatif terspesialisasi (basis) di daerah dibanding rata-rata nasional.",
    version: 2
  },
  {
    id: "S08",
    cluster: "ekonomi",
    level: "singkat",
    source: "simulasi",
    stem: "Identifikasi kekuatan, kelemahan, peluang, dan ancaman dalam pengembangan klaster UMKM daerah termasuk jenis analisis apa?",
    options: [
      "Analisis Shift-Share",
      "Analisis Input-Output",
      "Location Quotient (LQ)",
      "Analisis SWOT",
      "Proyeksi geometrik penduduk",
    ],
    answer: 3,
    explain: "SWOT memetakan faktor internal (S/W) dan eksternal (O/T) sebagai dasar formulasi strategi sektor.",
    version: 2
  },
  {
    id: "S09",
    cluster: "sosial",
    level: "singkat",
    source: "simulasi",
    stem: "Menurut konsep pembangunan berkelanjutan, tiga pilar yang harus seimbang dan saling mendukung adalah pilar mana?",
    options: [
      "Pusat, daerah, dan desa",
      "Ekonomi, sosial, dan lingkungan",
      "Politik, hukum, dan budaya",
      "Pendidikan, kesehatan, dan infrastruktur",
      "Efisiensi, efektivitas, dan relevansi",
    ],
    answer: 1,
    explain: "Pembangunan berkelanjutan berlandaskan keseimbangan pilar ekonomi, sosial, dan lingkungan (triple bottom line).",
    version: 2
  },
  {
    id: "S10",
    cluster: "sosial",
    level: "sedang",
    source: "simulasi",
    stem: "Program prioritas daerah menargetkan penurunan buta huruf, cakupan imunisasi, dan peningkatan daya beli rumah tangga miskin. Kelompok dimensi yang paling relevan adalah apa?",
    options: [
      "Politik, hukum, dan budaya",
      "Pusat, daerah, dan desa",
      "Pendidikan, kesehatan, dan standar hidup/pendapatan",
      "Ekonomi, sosial, dan lingkungan abstrak",
      "Efisiensi, efektivitas, dan keberlanjutan",
    ],
    answer: 2,
    explain: "IPM terdiri atas dimensi pendidikan, kesehatan, dan standar hidup (pendapatan/pengeluaran). Intervensi pada ketiga aspek itu paling selaras.",
    version: 3
  },
  {
    id: "S11",
    cluster: "sosial",
    level: "sedang",
    source: "simulasi",
    stem: "Dalam sistem pemerintahan Indonesia, pembagian kewenangan dan koordinasi pembangunan meliputi tingkat mana?",
    options: [
      "Pusat, daerah, dan desa",
      "Ekonomi, sosial, dan lingkungan",
      "Efisiensi, efektivitas, dan relevansi",
      "Bottom-up, top-down, dan teknokratis",
      "RPJPN, RPJMN, dan Renstra K/L saja",
    ],
    answer: 0,
    explain: "UU 23/2014 dan UU 6/2014 mengatur pembagian urusan pemerintahan pusat, daerah (provinsi/kabupaten/kota), dan desa.",
    version: 2
  },
  {
    id: "S12",
    cluster: "sosial",
    level: "singkat",
    source: "simulasi",
    stem: "Aspek tata kelola pembangunan yang mencakup stabilitas kelembagaan, kepastian hukum, dan penguatan nilai lokal disebut dimensi apa?",
    options: [
      "Pendidikan, kesehatan, dan infrastruktur",
      "Ekonomi, sosial, dan lingkungan",
      "Politik, hukum, dan budaya",
      "Pusat, daerah, dan desa",
      "Efisiensi, efektivitas, dan relevansi",
    ],
    answer: 2,
    explain: "Dimensi politik-hukum-budaya berkaitan dengan tata kelola, legitimasi kebijakan, dan kearifan lokal dalam pembangunan.",
    version: 2
  },
  {
    id: "S13",
    cluster: "teknis",
    level: "singkat",
    source: "simulasi",
    stem: "Evaluasi yang menilai apakah sumber daya (anggaran, tenaga, waktu) digunakan secara hemat relatif terhadap output mengukur aspek apa?",
    options: [
      "Efisiensi penggunaan sumber daya",
      "Efektivitas pencapaian tujuan",
      "Relevansi terhadap kebutuhan",
      "Keberlanjutan manfaat jangka panjang",
      "Akuntabilitas laporan keuangan saja",
    ],
    answer: 0,
    explain: "Efisiensi membandingkan input dengan output (rasio biaya–manfaat atau cost-effectiveness).",
    version: 2
  },
  {
    id: "S14",
    cluster: "teknis",
    level: "singkat",
    source: "simulasi",
    stem: "Program sanitasi desa menurunkan angka stunting dari 28% menjadi 19% dalam dua tahun. Aspek evaluasi yang paling mencerminkan pencapaian tujuan adalah apa?",
    options: [
      "Relevansi terhadap prioritas daerah",
      "Keberlanjutan pasca proyek berakhir",
      "Efektivitas pencapaian sasaran program",
      "Efisiensi anggaran tanpa melihat outcome",
      "Kepatuhan administratif pelaporan saja",
    ],
    answer: 2,
    explain: "Efektivitas menilai sejauh mana output/outcome mencapai tujuan dan sasaran yang ditetapkan.",
    version: 2
  },
  {
    id: "S15",
    cluster: "teknis",
    level: "sedang",
    source: "simulasi",
    stem: "Sebelum digitalisasi layanan publik diluncurkan, Bappeda menilai keselarasan program dengan prioritas RPJMD dan kebutuhan sasaran. Kriteria evaluasi ini disebut apa?",
    options: [
      "Efisiensi biaya pelaksanaan",
      "Efektivitas capaian outcome",
      "Relevansi terhadap kebutuhan dan prioritas",
      "Keberlanjutan manfaat jangka panjang",
      "Akuntabilitas penyerapan anggaran",
    ],
    answer: 2,
    explain: "Relevansi menilai kesesuaian program dengan masalah, prioritas pembangunan, dan kebutuhan pemangku kepentingan.",
    version: 2
  },
  {
    id: "S16",
    cluster: "teknis",
    level: "sedang",
    source: "simulasi",
    stem: "Evaluasi reboisasi menilai apakah penghijauan dapat dipertahankan setelah proyek berakhir, termasuk kelembagaan dan pendanaan lanjutan. Aspek yang dinilai adalah apa?",
    options: [
      "Efisiensi biaya penanaman",
      "Efektivitas jangka pendek semata",
      "Relevansi terhadap RPJMD",
      "Keberlanjutan manfaat dan kelembagaan",
      "Kepatuhan pelaporan keuangan saja",
    ],
    answer: 3,
    explain: "Keberlanjutan (sustainability) menilai kelangsungan manfaat, kelembagaan, dan dampak jangka panjang pasca intervensi.",
    version: 2
  },
  {
    id: "S17",
    cluster: "teknis",
    level: "singkat",
    source: "simulasi",
    stem: "Dokumen rencana pembangunan jangka panjang nasional dengan horizon 20 tahun menurut UU 25/2004 disebut apa?",
    options: [
      "RPJPN",
      "RTRW nasional",
      "Renstra K/L",
      "RKPD tahunan",
      "RPJMD daerah",
    ],
    answer: 0,
    explain: "RPJPN (Rencana Pembangunan Jangka Panjang Nasional) berjangka 20 tahun sebagai payung pembangunan nasional.",
    version: 2
  },
  {
    id: "S18",
    cluster: "spasial",
    level: "singkat",
    source: "simulasi",
    stem: "Dokumen perencanaan tata ruang yang memuat kebijakan struktur ruang, pola ruang, dan arahan zonasi untuk seluruh wilayah kabupaten/kota disebut apa?",
    options: [
      "RKPD tahunan daerah",
      "RPJMD lima tahunan",
      "RTRW kabupaten/kota",
      "Renstra perangkat daerah",
      "RPJPN dua puluh tahun",
    ],
    answer: 2,
    explain: "RTRW (Rencana Tata Ruang Wilayah) mengatur struktur dan pola ruang sesuai UU 26/2007 jo. PP 21/2021.",
    version: 2
  },
  {
    id: "S19",
    cluster: "teknis",
    level: "singkat",
    source: "simulasi",
    stem: "Dokumen perencanaan strategis kementerian/lembaga untuk lima tahun yang memuat tujuan, sasaran, program, dan indikator kinerja disebut apa?",
    options: [
      "RKPD tahunan daerah",
      "RPJPN nasional",
      "Renstra K/L",
      "RTRW wilayah",
      "LPJ keuangan tahunan",
    ],
    answer: 2,
    explain: "Renstra (Rencana Strategis) K/L berjangka 5 tahun, selaras dengan RPJMN dan menjadi dasar RKA.",
    version: 2
  },
  {
    id: "S20",
    cluster: "teknis",
    level: "singkat",
    source: "simulasi",
    stem: "Dokumen perencanaan pemerintah daerah untuk satu tahun yang menjadi dasar penyusunan APBD disebut apa?",
    options: [
      "RPJPD jangka panjang",
      "RKPD tahunan",
      "RPJPN nasional",
      "RTRW kabupaten/kota",
      "Renstra K/L pusat",
    ],
    answer: 1,
    explain: "RKPD (Rencana Kerja Pemerintah Daerah) berjangka 1 tahun, turunan RPJMD dan dasar APBD.",
    version: 2
  },
  {
    id: "S21",
    cluster: "teknis",
    level: "sedang",
    source: "simulasi",
    stem: "Daerah memiliki kekuatan ekowisata (S) dan peluang promosi digital nasional (O). Strategi memaksimalkan keduanya termasuk kuadran SWOT mana?",
    options: [
      "SO — memanfaatkan kekuatan untuk menangkap peluang",
      "ST — menggunakan kekuatan menghadapi ancaman",
      "WT — meminimalkan kelemahan dan menghindari ancaman",
      "WO — memperbaiki kelemahan dengan peluang eksternal",
      "SS — memperkuat kekuatan internal semata tanpa peluang",
    ],
    answer: 0,
    explain: "Strategi SO memanfaatkan kekuatan internal untuk menangkap peluang (growth/agresif).",
    version: 2
  },
  {
    id: "S22",
    cluster: "teknis",
    level: "sedang",
    source: "simulasi",
    stem: "Industri pengolahan lokal unggul (S) tetapi menghadapi ancaman produk impor murah (T). Strategi diversifikasi produk/pasar termasuk kuadran SWOT mana?",
    options: [
      "SO — memanfaatkan kekuatan untuk menangkap peluang",
      "ST — menggunakan kekuatan menghadapi ancaman",
      "WT — meminimalkan kelemahan dan menghindari ancaman",
      "WO — memperbaiki kelemahan dengan peluang eksternal",
      "OO — mengejar peluang tanpa memanfaatkan kekuatan",
    ],
    answer: 1,
    explain: "Strategi ST menggunakan kekuatan untuk menghadapi ancaman, sering melalui diversifikasi produk/pasar.",
    version: 2
  },
  {
    id: "S23",
    cluster: "teknis",
    level: "sedang",
    source: "simulasi",
    stem: "BUMD mengalami defisit (W) dan regulasi sektor semakin ketat (T). Strategi menekan biaya atau reorganisasi termasuk kuadran SWOT mana?",
    options: [
      "SO — memanfaatkan kekuatan untuk menangkap peluang",
      "ST — menggunakan kekuatan menghadapi ancaman",
      "WT — meminimalkan kelemahan dan menghindari ancaman",
      "WO — memperbaiki kelemahan dengan peluang eksternal",
      "WW — memperdalam kelemahan tanpa respons ancaman",
    ],
    answer: 2,
    explain: "Strategi WT meminimalkan kelemahan dan menghindari ancaman (survival/defensive).",
    version: 2
  },
  {
    id: "S24",
    cluster: "teknis",
    level: "sedang",
    source: "simulasi",
    stem: "Infrastruktur irigasi daerah tertinggal (W) namun ada dukungan dana rehabilitasi nasional (O). Strategi perbaikan melalui mitra pendanaan termasuk kuadran SWOT mana?",
    options: [
      "SO — memanfaatkan kekuatan untuk menangkap peluang",
      "ST — menggunakan kekuatan menghadapi ancaman",
      "WT — meminimalkan kelemahan dan menghindari ancaman",
      "WO — memperbaiki kelemahan dengan peluang eksternal",
      "TT — menghadapi ancaman tanpa memperbaiki kelemahan",
    ],
    answer: 3,
    explain: "Strategi WO mengatasi kelemahan dengan memanfaatkan peluang (perbaikan/turnaround).",
    version: 2
  },
  {
    id: "S25",
    cluster: "spasial",
    level: "sedang",
    source: "simulasi",
    stem: "Pengendalian pemanfaatan ruang melalui penetapan kawasan dan persyaratan teknis serta izin sesuai rencana tata ruang dilakukan dengan instrumen apa?",
    options: [
      "Survei kepuasan masyarakat layanan",
      "Musyawarah dusun tanpa dokumen ruang",
      "Zonasi dan perizinan berbasis tata ruang",
      "Penyusunan APBD tahunan daerah",
      "Proyeksi penduduk geometrik semata",
    ],
    answer: 2,
    explain: "Zonasi dalam RTRW/RDTR dan perizinan (KKPR/izin lain) adalah instrumen pengendalian pemanfaatan ruang.",
    version: 2
  },
  {
    id: "S26",
    cluster: "teknis",
    level: "singkat",
    source: "simulasi",
    stem: "Instrumen pengendalian pelaksanaan pembangunan daerah melalui alokasi, revisi, dan pertanggungjawaban belanja pemerintah daerah adalah instrumen apa?",
    options: [
      "RTRW kabupaten/kota",
      "APBD sebagai instrumen fiskal",
      "Musyawarah dusun komunitas",
      "Survei kepuasan layanan publik",
      "Analisis Shift-Share sektor",
    ],
    answer: 1,
    explain: "APBD merupakan instrumen fiskal pengendalian pelaksanaan program melalui pagu dan mekanisme revisi.",
    version: 2
  },
  {
    id: "S27",
    cluster: "sosial",
    level: "sedang",
    source: "simulasi",
    stem: "Penetapan batas penggunaan lahan adat dan kesepakatan pengelolaan sumber daya di tingkat komunitas pedesaan sering diformalisasi melalui mekanisme apa?",
    options: [
      "Penetapan zonasi RDTR semata",
      "Musyawarah dusun atau desa",
      "Pinjaman luar negeri proyek",
      "Regresi linear proyeksi penduduk",
      "Penetapan Perpres RKP nasional",
    ],
    answer: 1,
    explain: "Musyawarah dusun merupakan forum partisipatif desa untuk kesepakatan pembangunan dan pengelolaan sumber daya.",
    version: 2
  },
  {
    id: "S28",
    cluster: "sosial",
    level: "singkat",
    source: "simulasi",
    stem: "Pemerintah daerah mengukur kepuasan terhadap pelayanan perizinan dan menyusun perbaikan proses berdasarkan umpan balik pemohon. Alat pengendalian yang digunakan adalah apa?",
    options: [
      "Survei kepuasan masyarakat",
      "Penetapan pagu indikatif RKP",
      "Analisis Shift-Share regional",
      "Penyusunan RPJPN nasional",
      "Location Quotient sektor unggulan",
    ],
    answer: 0,
    explain: "Survei kepuasan masyarakat merupakan instrumen monitoring dan pengendalian kualitas pelayanan publik.",
    version: 2
  },
  {
    id: "S29",
    cluster: "teknis",
    level: "sedang",
    source: "simulasi",
    stem: "Jika pertumbuhan penduduk konstan sebesar r% per tahun, proyeksi jumlah penduduk tahun ke-n dari tahun dasar menggunakan metode apa?",
    options: [
      "Metode Delphi konsensus pakar",
      "Proyeksi geometrik penduduk",
      "Proyeksi aritmatik penduduk",
      "Regresi linear tren historis",
      "Analisis SWOT kependudukan",
    ],
    answer: 1,
    explain: "Proyeksi geometrik: Pt = P0 × (1 + r)^n, untuk pertumbuhan persentase konstan.",
    version: 2
  },
  {
    id: "S30",
    cluster: "teknis",
    level: "sedang",
    source: "simulasi",
    stem: "Perencana mengumpulkan opini pakar secara berulang hingga tercapai konsensus estimasi penduduk masa depan tanpa rumus matematis tunggal. Metode ini disebut apa?",
    options: [
      "Proyeksi aritmatik penduduk",
      "Regresi linear tren historis",
      "Metode Delphi konsensus pakar",
      "Proyeksi geometrik penduduk",
      "Location Quotient kependudukan",
    ],
    answer: 2,
    explain: "Metode Delphi menggunakan kuesioner berulang kepada pakar untuk meraih konsensus prognosa.",
    version: 2
  },
  {
    id: "S31",
    cluster: "teknis",
    level: "singkat",
    source: "simulasi",
    stem: "Jumlah penduduk bertambah konstan sebesar Δ jiwa per tahun dari tahun dasar. Metode proyeksi yang tepat adalah apa?",
    options: [
      "Proyeksi geometrik penduduk",
      "Proyeksi aritmatik penduduk",
      "Metode Delphi konsensus pakar",
      "Regresi linear tren historis",
      "Analisis Input-Output penduduk",
    ],
    answer: 1,
    explain: "Proyeksi aritmatik: Pt = P0 + n × Δ, untuk penambahan absolut konstan per periode.",
    version: 2
  },
  {
    id: "S32",
    cluster: "ekonomi",
    level: "sedang",
    source: "simulasi",
    stem: "Dengan data penduduk beberapa tahun terakhir, perencana membuat garis tren Pt = a + b×t untuk memperkirakan penduduk mendatang. Metode yang digunakan adalah apa?",
    options: [
      "Proyeksi geometrik penduduk",
      "Metode Delphi konsensus pakar",
      "Proyeksi aritmatik sederhana",
      "Regresi linear tren historis",
      "Analisis SWOT kependudukan",
    ],
    answer: 3,
    explain: "Regresi linear menaksir parameter a dan b dari data historis untuk proyeksi tren penduduk.",
    version: 2
  },
  {
    id: "S33",
    cluster: "sosial",
    level: "sedang",
    source: "simulasi",
    stem: "Penyusunan prioritas pembangunan desa berangkat dari musyawarah warga dan usulan program dari bawah yang dikonsolidasikan ke kabupaten. Pendekatan ini disebut apa?",
    options: [
      "Pendekatan bottom-up",
      "Pendekatan top-down",
      "Pendekatan politik",
      "Pendekatan teknokratis",
      "Pendekatan sektoral semata",
    ],
    answer: 0,
    explain: "Pendekatan bottom-up menempatkan aspirasi dan kebutuhan lokal sebagai titik awal perencanaan.",
    version: 2
  },
  {
    id: "S34",
    cluster: "sosial",
    level: "sedang",
    source: "simulasi",
    stem: "Keputusan alokasi anggaran dipengaruhi koalisi politik, kepentingan kelompok, dan negosiasi kekuasaan dalam perencanaan. Pendekatan yang paling sesuai adalah apa?",
    options: [
      "Pendekatan teknokratis murni",
      "Pendekatan top-down administratif",
      "Pendekatan politik",
      "Pendekatan bottom-up partisipatif murni",
      "Pendekatan proyeksi demografis saja",
    ],
    answer: 2,
    explain: "Political approach menekankan perencanaan sebagai arena negosiasi kepentingan dan kekuasaan (Friedmann, dll.).",
    version: 2
  },
  {
    id: "S35",
    cluster: "teknis",
    level: "singkat",
    source: "simulasi",
    stem: "Kebijakan dan program diturunkan dari target nasional/provinsi ke SKPD dan desa dengan arahan terpusat serta indikator baku. Pendekatan perencanaan ini disebut apa?",
    options: [
      "Pendekatan bottom-up",
      "Pendekatan politik",
      "Pendekatan top-down",
      "Pendekatan teknokratis",
      "Pendekatan SWOT sektoral",
    ],
    answer: 2,
    explain: "Pendekatan top-down menurunkan kebijakan dari tingkat atas ke bawah dengan standar dan target terpusat.",
    version: 2
  },
  {
    id: "S36",
    cluster: "teknis",
    level: "sedang",
    source: "simulasi",
    stem: "Keputusan perencanaan didasarkan pada analisis teknis, model, dan rekomendasi ahli dengan minim keterlibatan politik. Pendekatan ini disebut apa?",
    options: [
      "Pendekatan bottom-up",
      "Pendekatan politik",
      "Pendekatan top-down partisipatif",
      "Pendekatan teknokratis",
      "Pendekatan musyawarah dusun",
    ],
    answer: 3,
    explain: "Technocratic approach mengandalkan keahlian teknis dan rasionalitas ilmiah dalam pengambilan keputusan perencanaan.",
    version: 2
  },
  {
    id: "S37",
    cluster: "teknis",
    level: "singkat",
    source: "simulasi",
    stem: "Indikator Kinerja Utama (IKU) Kementerian X dilaporkan berkala dan dikaitkan dengan Renstra. Fungsi utama IKU tersebut adalah apa?",
    options: [
      "Menggantikan penyusunan RKA tahunan tanpa indikator kinerja",
      "Mengukur dan mengawal capaian kinerja strategis instansi",
      "Menetapkan pagu APBN secara langsung dari angka IKU semata",
      "Mengatur struktur organisasi K/L tanpa kaitannya dengan Renstra",
      "Menggantikan dokumen RPJPN nasional sebagai arah pembangunan",
    ],
    answer: 1,
    explain: "IKU mengukur capaian sasaran strategis K/L dan menjadi dasar akuntabilitas kinerja instansi.",
    version: 3
  },
  {
    id: "S38",
    cluster: "ekonomi",
    level: "sedang",
    source: "simulasi",
    stem: "Realisasi IKU infrastruktur menunjukkan penyerapan pinjaman proyek jalan dari lembaga multilateral mencapai 85% rencana semestral. Aspek indikator yang terukur adalah apa?",
    options: [
      "Laporan pertanggungjawaban keuangan tahunan",
      "Tingkat kepuasan pegawai internal",
      "Realisasi penarikan/penyerapan pinjaman luar negeri",
      "Pembayaran gaji PNS bulanan satuan kerja",
      "Jumlah musyawarah dusun yang diselenggarakan",
    ],
    answer: 2,
    explain: "IKU dapat memuat indikator realisasi pinjaman LN untuk proyek prioritas infrastruktur/sectoral.",
    version: 2
  },
  {
    id: "S39",
    cluster: "teknis",
    level: "singkat",
    source: "simulasi",
    stem: "Pada akhir tahun anggaran, K/L menyusun laporan realisasi belanja dan capaian kinerja sebagai dasar evaluasi. Dokumen ini disebut apa?",
    options: [
      "Renstra lima tahunan",
      "RKA usulan anggaran",
      "LPJ keuangan dan kinerja",
      "RPJMN jangka menengah",
      "RTRW wilayah nasional",
    ],
    answer: 2,
    explain: "LPJ (Laporan Pertanggungjawaban) melaporkan realisasi anggaran dan kinerja kepada pemerintah/DPR.",
    version: 2
  },
  {
    id: "S40",
    cluster: "teknis",
    level: "singkat",
    source: "simulasi",
    stem: "IKU satuan kerja perencanaan daerah mencakup penyelesaian analisis jabatan dan ketepatan waktu penyaluran gaji ASN. Kelompok indikator yang dominan adalah apa?",
    options: [
      "Realisasi pinjaman luar negeri",
      "Pemantauan sasaran strategis RPJPN",
      "Administrasi kepegawaian dan penggajian",
      "Proyeksi penduduk geometrik daerah",
      "Analisis Shift-Share sektor unggulan",
    ],
    answer: 2,
    explain: "IKU administrasi/SDM dapat mencakup aspek kepegawaian, analisis jabatan, dan ketepatan penyaluran gaji.",
    version: 2
  }
];
