const BANK = [
  {
    id: 1,
    cluster: "teknis",
    level: "singkat",
    stem: "Dokumen rencana pembangunan jangka panjang nasional (20 tahun) menurut UU 25/2004 adalah …",
    options: [
      "RPJMD (5 tahun)",
      "RPJPN (20 tahun)",
      "RKPD (1 tahun)",
      "RPJPD (20 tahun daerah)",
      "Renstra K/L (5 tahun)",
    ],
    answer: 1,
    explain: "RPJPN = Rencana Pembangunan Jangka Panjang Nasional (20 tahun). RPJMD adalah daerah; RKPD tahunan daerah.",
    version: 2
  },
  {
    id: 2,
    cluster: "teknis",
    level: "singkat",
    stem: "UU No. 25 Tahun 2004 tentang Sistem Perencanaan Pembangunan Nasional berstatus sebagai …",
    options: [
      "Undang-Undang",
      "Peraturan Pemerintah",
      "Produk hukum / peraturan perundang-undangan",
      "Naskah akademik perencanaan",
      "Panduan teknis internal",
    ],
    answer: 2,
    explain: "UU 25/2004 adalah produk hukum yang mengatur tata cara perencanaan, bukan teori atau konsep akademis semata.",
    version: 2
  },
  {
    id: 3,
    cluster: "teknis",
    level: "singkat",
    stem: "Dokumen perencanaan daerah untuk satu tahun fiskal adalah …",
    options: [
      "RPJPD",
      "RPJMD",
      "RKPD",
      "RPJPN",
      "RKP",
    ],
    answer: 2,
    explain: "RKPD = Rencana Kerja Pemerintah Daerah (1 tahun), turunan RPJMD dan dasar APBD.",
    version: 2
  },
  {
    id: 4,
    cluster: "teknis",
    level: "singkat",
    stem: "Kegiatan memantau realisasi anggaran triwulan I termasuk dalam tahap …",
    options: [
      "Evaluasi akhir periode",
      "Pengendalian saja",
      "Monitoring",
      "Perumusan visi",
      "Penetapan RPJMN",
    ],
    answer: 2,
    explain: "Monitoring dilakukan selama pelaksanaan untuk memantau kemajuan; evaluasi setelah periode tertentu.",
    version: 2
  },
  {
    id: 5,
    cluster: "teknis",
    level: "sedang",
    stem: "Urutan alur dokumen perencanaan daerah yang benar adalah …",
    options: [
      "RKPD → RPJMD → RPJPD → APBD",
      "RPJPD → RPJMD → Renstra PD → RKPD → APBD",
      "RPJPN → RKPD → RPJMD",
      "Renstra PD → RPJPD → RKPD → APBD",
      "APBD → RKPD → RPJMD",
    ],
    answer: 1,
    explain: "Alur: RPJPD (20 th) → RPJMD (5 th) → Renstra PD → RKPD (1 th) → APBD.",
    version: 2
  },
  {
    id: 6,
    cluster: "teknis",
    level: "sedang",
    stem: "Pertumbuhan ekonomi dan pembangunan — pernyataan yang tepat adalah …",
    options: [
      "Keduanya identik dan diukur hanya dengan PDB",
      "Pembangunan hanya fokus pada kenaikan PDB",
      "Pertumbuhan ekonomi adalah salah satu aspek pembangunan yang lebih luas",
      "Pertumbuhan ekonomi selalu menurunkan kemiskinan",
      "Pembangunan tidak memerlukan perencanaan",
    ],
    answer: 2,
    explain: "Pertumbuhan diukur PDB/PDRB; pembangunan multidimensi (ekonomi, sosial, lingkungan, dll.).",
    version: 2
  },
  {
    id: 7,
    cluster: "teknis",
    level: "sedang",
    stem: "Evaluasi program pembangunan bertujuan utama untuk …",
    options: [
      "Mengganti seluruh struktur organisasi",
      "Menilai capaian dan menentukan lanjut/henti/perbaiki",
      "Mengukur capaian indikator program secara berkala",
      "Menetapkan zonasi kawasan tata ruang",
      "Menganalisis elastisitas permintaan",
    ],
    answer: 1,
    explain: "Evaluasi dilakukan setelah periode tertentu untuk menilai efektivitas dan keputusan tindak lanjut.",
    version: 2
  },
  {
    id: 8,
    cluster: "teknis",
    level: "sedang",
    stem: "Dokumen rencana pembangunan jangka menengah nasional (5 tahun) adalah …",
    options: [
      "RPJPN (20 tahun)",
      "RPJMN (5 tahun)",
      "RKPD (1 tahun)",
      "RPJMD (5 tahun daerah)",
      "Renja K/L (1 tahun)",
    ],
    answer: 1,
    explain: "RPJMN = Rencana Pembangunan Jangka Menengah Nasional. Di daerah padanannya RPJMD.",
    version: 2
  },
  {
    id: 9,
    cluster: "teknis",
    level: "sedang",
    stem: "Pengendalian dalam siklus perencanaan berfungsi sebagai tindakan …",
    options: [
      "Tindakan preventif tanpa data capaian",
      "Tindakan korektif berdasarkan temuan monitoring/evaluasi",
      "Tindakan konsultatif tanpa dasar data",
      "Penyusunan RPJPN pertama kali",
      "Partisipasi masyarakat pada tahap perumusan",
    ],
    answer: 1,
    explain: "Pengendalian korektif, misalnya mengalihkan anggaran ke kegiatan yang tertinggal.",
    version: 2
  },
  {
    id: 10,
    cluster: "teknis",
    level: "sedang",
    stem: "Stakeholder yang umumnya berperan sebagai inisiator perencanaan pembangunan daerah adalah …",
    options: [
      "Masyarakat sipil",
      "Media massa",
      "Pemerintah (pemerintah pusat/daerah)",
      "Dunia usaha",
      "Akademisi tanpa mandat resmi",
    ],
    answer: 2,
    explain: "Pemerintah memiliki mandat hukum menyusun dan menetapkan rencana pembangunan.",
    version: 2
  },
  {
    id: 11,
    cluster: "teknis",
    level: "panjang",
    stem: "Dalam rapat tim perencana, anggota A mengatakan RPJMN 2025–2029 harus langsung diturunkan ke RKPD tanpa RPJPN karena jangka 5 tahun sudah cukup. Anggota B menegaskan RPJPN 2025–2045 sebagai payung transformasi digital. Anggota C menyamakan pertumbuhan 6% dengan peningkatan IPM otomatis. Manakah penilaian yang PALING sesuai kerangka SPPN UU 25/2004?",
    options: [
      "A benar; RPJPN boleh dilewati",
      "B benar; RPJPN memberi konsistensi arah jangka panjang sebelum RPJMN/RKPD",
      "C benar; pertumbuhan PDB sama dengan pembangunan manusiawi",
      "A dan C benar",
      "Semua salah karena hanya APBD yang penting",
    ],
    answer: 1,
    explain: "RPJPN (20 th) → RPJMN (5 th) → RKP/RKPD. Pertumbuhan ≠ pembangunan multidimensi otomatis.",
    version: 2
  },
  {
    id: 12,
    cluster: "teknis",
    level: "panjang",
    stem: "Kecuali yang berikut, semuanya termasuk dalam empat tahapan perencanaan pembangunan nasional menurut materi SPPN …",
    options: [
      "Penyusunan rencana",
      "Penetapan rencana",
      "Pengendalian pelaksanaan",
      "Evaluasi",
      "Penetapan tarif pajak daerah",
    ],
    answer: 4,
    explain: "Empat tahap: susun, tetapkan, kendali, evaluasi. Tarif pajak bukan tahap inti SPPN.",
    version: 2
  },
  {
    id: 13,
    cluster: "teknis",
    level: "panjang",
    stem: "Visi dalam dokumen perencanaan daerah pada umumnya menggambarkan …",
    options: [
      "Pernyataan operasional misi untuk mencapai visi",
      "Keadaan/gambaran masa depan daerah yang ingin dicapai",
      "Langkah teknis penyusunan RKPD tahun berjalan",
      "Indikator kinerja tahunan tanpa horizon jangka panjang",
      "Rincian belanja barang per SKPD tahun berjalan",
    ],
    answer: 1,
    explain: "Visi = gambaran keadaan masa depan yang diinginkan; misi/strategi menjabarkan cara mencapainya.",
    version: 2
  },
  {
    id: 14,
    cluster: "teknis",
    level: "panjang",
    stem: "Pada kasus program infrastruktur jalan desa: realisasi fisik 45% di triwulan II, serapan anggaran 70%, keluhan warga soal akses. Tim monitoring mencatat deviasi; tim evaluasi di akhir tahun menilai target 80% tidak tercapai. Langkah pengendalian yang tepat adalah …",
    options: [
      "Menghentikan seluruh program tanpa analisis capaian",
      "Menunggu periode rencana baru tanpa penyesuaian program",
      "Koreksi alokasi, jadwal, atau ruang lingkup berdasarkan temuan monitoring-evaluasi",
      "Mengganti visi daerah tanpa meninjau indikator program",
      "Hanya memperbarui target indikator tanpa tinjauan capaian",
    ],
    answer: 2,
    explain: "Monitoring (selama) + evaluasi (setelah) → pengendalian korektif, bukan mengabaikan temuan.",
    version: 2
  },
  {
    id: 15,
    cluster: "teknis",
    level: "panjang",
    stem: "Manakah pasangan dokumen dan jangka waktu yang SALAH (jebakan arah periode)?",
    options: [
      "RPJPN — 20 tahun",
      "RPJMD — 5 tahun",
      "RKPD — 1 tahun",
      "RPJPD — 5 tahun",
      "RKP — 1 tahun nasional",
    ],
    answer: 3,
    explain: "RPJPD = 20 tahun (bukan 5). RPJMD daerah = 5 tahun. Jebakan: menukar jangka RPJPD/RPJMD.",
    version: 2
  },
  {
    id: 16,
    cluster: "ekonomi",
    level: "singkat",
    stem: "Location Quotient (LQ) > 1 pada suatu sektor di daerah menunjukkan sektor tersebut …",
    options: [
      "Tertinggal dan perlu ditutup",
      "Merupakan sektor basis/unggulan relatif terhadap rujukan",
      "Tidak berkontribusi pada PDB daerah",
      "Selalu elastis terhadap harga",
      "Sama dengan DLQ < 1",
    ],
    answer: 1,
    explain: "LQ > 1 = konsentrasi sektor di daerah lebih besar daripada rujukan (nasional) → basis.",
    version: 2
  },
  {
    id: 17,
    cluster: "ekonomi",
    level: "singkat",
    stem: "Inflasi yang benar secara konsep adalah …",
    options: [
      "Kenaikan harga satu jenis barang sekali",
      "Penurunan harga umum berkelanjutan",
      "Kenaikan harga barang dan jasa secara umum secara terus-menerus",
      "Kenaikan nilai tukar rupiah",
      "Penurunan jumlah uang beredar saja",
    ],
    answer: 2,
    explain: "Inflasi = kenaikan harga umum berkelanjutan; bukan satu komoditas atau deflasi.",
    version: 2
  },
  {
    id: 18,
    cluster: "ekonomi",
    level: "singkat",
    stem: "Hukum permintaan (ceteris paribus) menyatakan bahwa jika harga naik, jumlah yang diminta …",
    options: [
      "Naik",
      "Tetap",
      "Turun",
      "Tidak terkait harga",
      "Menjadi tak terbatas",
    ],
    answer: 2,
    explain: "Harga ↑ → Qd ↓; harga ↓ → Qd ↑ (faktor lain dianggap tetap).",
    version: 2
  },
  {
    id: 19,
    cluster: "ekonomi",
    level: "singkat",
    stem: "Rumus pendekatan pengeluaran untuk PDB adalah …",
    options: [
      "PDB = C + I + G + (X − M)",
      "PDB = Gini × ICOR",
      "PDB = LQ / DLQ",
      "PDB = inflasi + pengangguran",
      "PDB = harga × kuantitas saja tanpa komponen",
    ],
    answer: 0,
    explain: "Pendekatan pengeluaran: Konsumsi + Investasi + Belanja pemerintah + Ekspor neto.",
    version: 2
  },
  {
    id: 20,
    cluster: "ekonomi",
    level: "sedang",
    stem: "Produksi warga negara Indonesia di luar negeri masuk dalam pengukuran …",
    options: [
      "PDB Indonesia",
      "PDRB kabupaten setempat",
      "GNP/GNI Indonesia",
      "PDB riil per kapita tanpa komponen agregat",
      "Nilai ekspor barang dan jasa saja",
    ],
    answer: 2,
    explain: "PDB/PDRB = produksi di dalam wilayah; GNI = pendapatan warga negara di mana pun.",
    version: 2
  },
  {
    id: 21,
    cluster: "ekonomi",
    level: "sedang",
    stem: "PDB konstan: produksi 500 unit dengan harga dasar Rp 300.000 per unit. Nilai PDB konstan adalah …",
    options: [
      "Rp 90.000.000",
      "Rp 150.000.000",
      "Rp 300.000",
      "Rp 1.500.000.000",
      "Rp 15.000.000",
    ],
    answer: 1,
    explain: "500 × 300.000 = Rp 150.000.000. Harga dasar agar tidak bias inflasi.",
    version: 2
  },
  {
    id: 22,
    cluster: "ekonomi",
    level: "sedang",
    stem: "ICOR (Incremental Capital Output Ratio) yang semakin kecil berarti …",
    options: [
      "Modal semakin boros",
      "Investasi kurang efisien menghasilkan output",
      "Modal relatif lebih efisien menghasilkan pertumbuhan output",
      "Inflasi pasti tinggi",
      "Gini coefficient mendekati 1",
    ],
    answer: 2,
    explain: "ICOR = ΔK/ΔY; nilai kecil = butuh modal lebih sedikit per unit pertumbuhan output.",
    version: 2
  },
  {
    id: 23,
    cluster: "ekonomi",
    level: "sedang",
    stem: "Kurva Phillips menggambarkan trade-off jangka pendek antara …",
    options: [
      "Ekspor dan impor",
      "Inflasi dan pengangguran",
      "LQ dan DLQ",
      "Pertanian dan industri saja",
      "Pajak dan subsidi",
    ],
    answer: 1,
    explain: "Phillips: inflasi rendah sering beriringan pengangguran lebih tinggi (dan sebaliknya) jangka pendek.",
    version: 2
  },
  {
    id: 24,
    cluster: "ekonomi",
    level: "sedang",
    stem: "Elastisitas harga permintaan |Ed| > 1 berarti permintaan bersifat …",
    options: [
      "Inelastis",
      "Unitary",
      "Elastis",
      "Nol",
      "Tidak terdefinisi",
    ],
    answer: 2,
    explain: "|Ed| > 1 elastis; < 1 inelastis; = 1 unitary.",
    version: 2
  },
  {
    id: 25,
    cluster: "ekonomi",
    level: "sedang",
    stem: "Koefisien Gini yang meningkat dari 0,32 ke 0,41 menunjukkan …",
    options: [
      "Distribusi pendapatan semakin merata",
      "Distribusi pendapatan semakin tidak merata",
      "Tidak ada perubahan ketimpangan",
      "Inflasi turun",
      "Sektor basis hilang",
    ],
    answer: 1,
    explain: "Gini 0 = sempurna merata; mendekati 1 = sangat tidak merata. Naik = lebih tidak merata.",
    version: 2
  },
  {
    id: 26,
    cluster: "ekonomi",
    level: "sedang",
    stem: "DLQ (Dynamic Location Quotient) > 1 pada umumnya diartikan sektor tersebut …",
    options: [
      "Mengalami pertumbuhan lebih lambat dari nasional",
      "Prospektif (pertumbuhan sektor lokal lebih cepat dari nasional)",
      "Bukan sektor unggulan",
      "Sama persis dengan LQ < 1",
      "Menyebabkan deflasi",
    ],
    answer: 1,
    explain: "DLQ > 1 = dinamika pertumbuhan sektor lokal lebih baik dibanding rujukan nasional.",
    version: 2
  },
  {
    id: 27,
    cluster: "ekonomi",
    level: "panjang",
    stem: "Data: IHK 2021 = 107,66; IHK 2022 = 113,59. Tim ekonomi juga mencatat harga cabai naik 80% karena panen gagal, sementara harga umum lain relatif stabil. Inflasi tahunan yang sesuai definasi makro dan angka materi pelatihan adalah …",
    options: [
      "Inflasi = 80% karena cabai",
      "Tidak ada inflasi karena hanya satu komoditas",
      "Inflasi umum ≈ 5,51% dari perubahan IHK, bukan kenaikan satu barang",
      "Inflasi = 113,59%",
      "Deflasi karena IHK naik",
    ],
    answer: 2,
    explain: "Inflasi dari IHK: ((113,59−107,66)/107,66)×100% ≈ 5,51%. Kenaikan cabai saja bukan inflasi umum.",
    version: 2
  },
  {
    id: 28,
    cluster: "ekonomi",
    level: "panjang",
    stem: "Permintaan Qd = 60 − 10P dan penawaran Qs = 5P + 15 (harga dalam ribuan rupiah). Harga dan kuantitas keseimbangan pasar adalah …",
    options: [
      "P = 2, Q = 40",
      "P = 3, Q = 30",
      "P = 4, Q = 20",
      "P = 5, Q = 10",
      "P = 6, Q = 0",
    ],
    answer: 1,
    explain: "60−10P = 5P+15 → 45 = 15P → P=3; Q = 5(3)+15 = 30.",
    version: 2
  },
  {
    id: 29,
    cluster: "ekonomi",
    level: "panjang",
    stem: "Kecuali yang berikut, semuanya dapat menjadi penyebab perdagangan internasional menurut teori ekonomi klasik/modern …",
    options: [
      "Perbedaan teknologi produksi",
      "Perbedaan kelimpahan sumber daya alam",
      "Efisiensi skala ekonomi",
      "Ketersediaan sumber daya alam yang sama persis antarnegara",
      "Perbedaan preferensi konsumen",
    ],
    answer: 3,
    explain: "SDA sama persis mengurangi motif perdagangan; perbedaan SDA/teknologi mendorong perdagangan.",
    version: 2
  },
  {
    id: 30,
    cluster: "ekonomi",
    level: "panjang",
    stem: "Pemerintah menetapkan harga maksimum (ceiling) di bawah harga keseimbangan pasar beras. Dampak jangka pendek yang paling mungkin dan kebijakan pendamping yang lazim adalah …",
    options: [
      "Surplus besar; pemerintah membeli surplus",
      "Kekurangan pasar; operasi pasar/penambahan supply untuk melindungi konsumen",
      "Harga naik bebas; tidak perlu intervensi",
      "Penawaran melebihi permintaan tanpa batas",
      "Keseimbangan pasar tetap tanpa perubahan",
    ],
    answer: 1,
    explain: "Ceiling < equilibrium → shortage; operasi pasar menambah supply. Floor price kebalikannya (surplus).",
    version: 2
  },
  {
    id: 31,
    cluster: "sosial",
    level: "singkat",
    stem: "Social Overhead Capital (SOC) pada dasarnya mencakup …",
    options: [
      "Infrastruktur fisik jalan dan jembatan semata",
      "Norma, kepercayaan, dan jaringan yang mendukung produktivitas sosial",
      "Kekuatan hukum tanpa norma dan kepercayaan sosial",
      "Modal finansial perusahaan besar saja",
      "Partisipasi masyarakat hanya pada tahap evaluasi akhir",
    ],
    answer: 1,
    explain: "SOC = jalan, listrik, pendidikan, norma, kepercayaan, jaringan sosial produktif.",
    version: 2
  },
  {
    id: 32,
    cluster: "sosial",
    level: "singkat",
    stem: "Indeks Pembangunan Manusia (IPM) secara umum memiliki tiga dimensi …",
    options: [
      "Ekspor, impor, investasi",
      "Umur hidup, pendidikan, pendapatan",
      "Lindung, budi daya, industri",
      "Inflasi, pengangguran, PDB",
      "Gotong royong, pajak, partisipasi",
    ],
    answer: 1,
    explain: "IPM = health (umur hidup), education, income (pendapatan per kapita).",
    version: 2
  },
  {
    id: 33,
    cluster: "sosial",
    level: "singkat",
    stem: "PRA (Participatory Rural Appraisal) pada prinsipnya menempatkan …",
    options: [
      "Tim eksternal sebagai satu-satunya ahli",
      "Masyarakat sebagai pusat proses",
      "Pemerintah tanpa dialog",
      "Analisis tertutup dan formal semata",
      "Hanya data satelit",
    ],
    answer: 1,
    explain: "PRA partisipatif, santai, triangulasi; bukan RRA formal cepat atau tertutup.",
    version: 2
  },
  {
    id: 34,
    cluster: "sosial",
    level: "sedang",
    stem: "Modal sosial tipe bridging menurut Woolcock berfungsi untuk …",
    options: [
      "Memperkuat ikatan dalam kelompok homogen saja",
      "Menjembatani hubungan antarkelompok berbeda",
      "Menghubungkan rakyat langsung ke presiden tanpa perantara",
      "Mengganti peran KKPR",
      "Menghitung ICOR",
    ],
    answer: 1,
    explain: "Bonding = dalam kelompok; bridging = antarkelompok; linking = lintas level kekuasaan.",
    version: 2
  },
  {
    id: 35,
    cluster: "sosial",
    level: "sedang",
    stem: "Mobilisasi sosial dalam pembangunan berarti perubahan posisi masyarakat dari …",
    options: [
      "Subyek menjadi obyek",
      "Obyek menjadi subyek aktif",
      "Pemerintah menjadi swasta",
      "Visi menjadi misi",
      "RPJPN menjadi RKPD",
    ],
    answer: 1,
    explain: "Mobilisasi = pemberdayaan: masyarakat dari penerima pasif menjadi pelaku aktif.",
    version: 2
  },
  {
    id: 36,
    cluster: "sosial",
    level: "sedang",
    stem: "Tiga unsur partisipasi masyarakat dalam perencanaan meliputi kesadaran, kemampuan, dan …",
    options: [
      "Kemauan ditambah kesempatan dan akses sumber daya",
      "Kepatuhan pajak sebagai satu-satunya faktor kemiskinan",
      "Tingkat pendidikan tanpa memperhatikan akses layanan",
      "Partisipasi masyarakat hanya pada tahap perencanaan",
      "Indikator kemiskinan moneter tanpa dimensi multidimensi",
    ],
    answer: 0,
    explain: "Partisipasi efektif butuh kesadaran, kemampuan, kemauan, dan kesempatan (ALLIR melibatkan masyarakat).",
    version: 2
  },
  {
    id: 37,
    cluster: "sosial",
    level: "sedang",
    stem: "Tahapan ALLIR yang benar urutannya adalah …",
    options: [
      "Evaluasi → Penjajakan → Pelaksanaan",
      "Penjajakan kebutuhan → Kajian potensi → Pelaksanaan → Pemantauan → Evaluasi",
      "Pelaksanaan → Penjajakan → Penyusunan APBD",
      "Perumusan visi → Pelaksanaan → Evaluasi tanpa pemantauan",
      "Pemantauan → Penjajakan → Penetapan indikator",
    ],
    answer: 1,
    explain: "ALLIR: penjajagan → kajian potensi → pelaksanaan → pemantauan → evaluasi.",
    version: 2
  },
  {
    id: 38,
    cluster: "sosial",
    level: "sedang",
    stem: "Faktor alami yang dapat memperlebar ketimpangan antardaerah adalah …",
    options: [
      "Kepatuhan pajak yang seragam di semua wilayah",
      "Perbedaan ketersediaan dan pola pemanfaatan sumber daya alam",
      "Visi pembangunan daerah yang identik",
      "Kepadatan penduduk sebagai satu-satunya pembeda",
      "Tingkat inflasi nasional yang sama",
    ],
    answer: 1,
    explain: "Perbedaan SDA geografis/klimat memengaruhi potensi ekonomi antardaerah.",
    version: 2
  },
  {
    id: 39,
    cluster: "sosial",
    level: "panjang",
    stem: "Empat pilar penanggulangan kemiskinan sering disebut: pendidikan, kesehatan, perlindungan sosial, dan ekonomi/produktif. Manakah yang BUKAN pilar tersebut (jebakan kecuali/bukan)?",
    options: [
      "Peningkatan akses pendidikan",
      "Jaminan kesehatan",
      "Kepatuhan pajak sebagai pilar utama kemiskinan",
      "Pemberdayaan ekonomi produktif",
      "Perlindungan sosial",
    ],
    answer: 2,
    explain: "Kepatuhan pajak bukan pilar kemiskinan dalam materi pre-test; jebakan kategori salah.",
    version: 2
  },
  {
    id: 40,
    cluster: "sosial",
    level: "panjang",
    stem: "Kecuali yang berikut, semuanya mencerminkan karakteristik PRA yang benar …",
    options: [
      "Partisipatif dan terbuka",
      "Triangulasi informasi",
      "Santai dan iteratif",
      "Tertutup dan sangat formal seperti audit",
      "Masyarakat sebagai pusat",
    ],
    answer: 3,
    explain: "PRA bukan tertutup & formal; itu kebalikan PRA (lebih ke RRA/audit).",
    version: 2
  },
  {
    id: 41,
    cluster: "sosial",
    level: "panjang",
    stem: "Desa X: gotong royong rutin antarwarga RT (bonding kuat), tetapi kurang jaringan dengan UMKM kota tetangga. Program pembangunan menghubungkan koperasi desa dengan asosiasi pengusaha kabupaten dan forum pemerintah-daerah-swasta. Kombinasi modal sosial yang dibangun adalah …",
    options: [
      "Hanya bonding",
      "Bonding + bridging + linking",
      "Hanya linking tanpa bonding",
      "SOC = hanya jalan tol",
      "PRA tertutup formal",
    ],
    answer: 1,
    explain: "Gotong royong = bonding; asosiasi lintas kelompok = bridging; forum multi-level = linking.",
    version: 2
  },
  {
    id: 42,
    cluster: "sosial",
    level: "panjang",
    stem: "Data kemiskinan turun 2%, tetapi IPM stagnan karena angka melek huruf dan harapan hidup tidak membaik. Kesimpulan untuk perencana ahli muda yang paling tepat adalah …",
    options: [
      "Cukup lihat satu indikator kemiskinan",
      "Perlu analisis multidimensi (pendapatan + IPM + akses layanan)",
      "Ganti RPJPN saja",
      "Hanya hitung LQ",
      "Tingkatkan kepadatan 10–40 rumah/ha",
    ],
    answer: 1,
    explain: "Kemiskinan moneter ≠ kesejahteraan manusiawi lengkap; IPM menangkap dimensi non-pendapatan.",
    version: 2
  },
  {
    id: 43,
    cluster: "spasial",
    level: "singkat",
    stem: "Menurut UU 26/2007, fungsi utama kawasan adalah …",
    options: [
      "Industri dan perdagangan saja",
      "Lindung dan budi daya",
      "Pertanian dan pertambangan saja",
      "Permukiman dan pelabuhan saja",
      "RTH 30% nasional tunggal",
    ],
    answer: 1,
    explain: "UU 26: dua fungsi utama kawasan = lindung + budi daya.",
    version: 2
  },
  {
    id: 44,
    cluster: "spasial",
    level: "singkat",
    stem: "Skala peta RDTR (Rencana Detail Tata Ruang) menurut pedoman umum adalah …",
    options: [
      "1 : 250.000",
      "1 : 100.000",
      "1 : 2.000 – 1 : 5.000",
      "1 : 50.000",
      "1 : 500.000",
    ],
    answer: 2,
    explain: "RDTR untuk zonasi/block plan: skala 1:2.000 hingga 1:5.000.",
    version: 2
  },
  {
    id: 45,
    cluster: "spasial",
    level: "singkat",
    stem: "Maksimal waktu penyusunan RTRW menurut PP 21/2021 adalah …",
    options: [
      "6 bulan",
      "12 bulan",
      "18 bulan",
      "24 bulan",
      "36 bulan",
    ],
    answer: 2,
    explain: "PP 21/2021: penyusunan RTRW paling lama 18 bulan.",
    version: 2
  },
  {
    id: 46,
    cluster: "spasial",
    level: "singkat",
    stem: "KKPR adalah singkatan dari …",
    options: [
      "Kawasan Konservasi Pesisir Rakyat",
      "Kesesuaian Kegiatan Pemanfaatan Ruang",
      "Kredit Kepemilikan Perumahan Rakyat",
      "Kurva Keseimbangan Permintaan Regional",
      "Klasifikasi Kepadatan Perumahan Rendah",
    ],
    answer: 1,
    explain: "KKPR = Kesesuaian Kegiatan Pemanfaatan Ruang (PP 21/2021).",
    version: 2
  },
  {
    id: 47,
    cluster: "spasial",
    level: "singkat",
    stem: "Sempadan pantai minimal menurut Perpres 51/2016 diukur …",
    options: [
      "50 m dari bibir pantai",
      "100 m dari garis pasang tertinggi",
      "200 m dari jalan raya",
      "30 m dari ROW jalan",
      "10 m dari bangunan",
    ],
    answer: 1,
    explain: "Sempadan pantai = 100 m dari garis pasang tertinggi (bukan 50 m atau ROW jalan).",
    version: 2
  },
  {
    id: 48,
    cluster: "spasial",
    level: "singkat",
    stem: "Persentase minimum Ruang Terbuka Hijau (RTH) publik di kota menurut pedoman umum adalah …",
    options: [
      "10%",
      "20%",
      "30%",
      "40%",
      "50%",
    ],
    answer: 1,
    explain: "RTH total kota 30% (20% publik + 10% privat). Jangan tertukar total vs publik.",
    version: 2
  },
  {
    id: 49,
    cluster: "spasial",
    level: "singkat",
    stem: "Kepadatan perumahan kategori sedang menurut materi pre-test adalah …",
    options: [
      "1–5 rumah/ha",
      "10–40 rumah/ha",
      "50–100 rumah/ha",
      "100–200 rumah/ha",
      "Tidak ada standar",
    ],
    answer: 1,
    explain: "Kepadatan sedang = 10–40 rumah/ha (jebakan: 30% RTH atau 30 m ROW).",
    version: 2
  },
  {
    id: 50,
    cluster: "spasial",
    level: "sedang",
    stem: "UU No. 26 Tahun 2007 tentang Penataan Ruang …",
    options: [
      "Menetapkan 30% kawasan lindung nasional tunggal untuk seluruh NKRI",
      "Mengatur tata ruang; kawasan lindung ditetapkan per karakter wilayah",
      "Menggantikan UU 25/2004 tentang SPPN",
      "Hanya berlaku untuk DKI Jakarta",
      "Menghapus kebutuhan RDTR",
    ],
    answer: 1,
    explain: "UU 26 tidak menetapkan satu angka % lindung nasional tunggal; ditetapkan per wilayah.",
    version: 2
  },
  {
    id: 51,
    cluster: "spasial",
    level: "sedang",
    stem: "Jika belum terdapat RDTR, persetujuan kegiatan pemanfaatan ruang dilakukan melalui …",
    options: [
      "Izin Mendirikan Bangunan (IMB) tanpa penilaian kesesuaian ruang",
      "Kesesuaian Kegiatan Pemanfaatan Ruang (KKPR)",
      "Persetujuan Bangunan Gedung (PBG) sebagai pengganti penilaian ruang",
      "Rencana Induk RTRW provinsi",
      "Analisis dampak lalu lintas jalan nasional",
    ],
    answer: 1,
    explain: "PP 21: belum ada RDTR → persetujuan melalui KKPR.",
    version: 2
  },
  {
    id: 52,
    cluster: "spasial",
    level: "sedang",
    stem: "Sempadan sungai kecil menurut pedoman UNSRI umumnya …",
    options: [
      "25 m satu sisi",
      "50 m kiri dan kanan",
      "100 m kiri dan kanan",
      "200 m kiri dan kanan",
      "Tidak perlu sempadan",
    ],
    answer: 1,
    explain: "Sungai kecil ≈ 50 m (kiri+kanan); sungai besar ≈ 100 m. Jangan tertukar dengan pantai 100 m.",
    version: 2
  },
  {
    id: 53,
    cluster: "spasial",
    level: "sedang",
    stem: "Daya dukung lingkungan hidup berbed dari daya tampung karena daya dukung menekankan …",
    options: [
      "Kemampuan menyerap limbah tanpa batas",
      "Kemampuan lingkungan menopang kehidupan secara lestari",
      "Hanya luas lahan industri",
      "Skala peta RTR 1:1.000",
      "Trade-off Phillips",
    ],
    answer: 1,
    explain: "Daya dukung = sustain life; daya tampung = absorb beban/pencemaran.",
    version: 2
  },
  {
    id: 54,
    cluster: "spasial",
    level: "sedang",
    stem: "Evaluasi Rancangan Peraturan Daerah tentang RTRW kabupaten/kota dilakukan oleh …",
    options: [
      "Bupati/Walikota saja",
      "Gubernur",
      "DPRD provinsi",
      "Presiden langsung",
      "LSM internasional",
    ],
    answer: 1,
    explain: "PP 21/2021: evaluasi rancangan perda RTRW kab/kota oleh Gubernur.",
    version: 2
  },
  {
    id: 55,
    cluster: "spasial",
    level: "sedang",
    stem: "Luas minimal satu unit Ruang Terbuka Hijau (RTH) menurut pedoman umum adalah …",
    options: [
      "500 m²",
      "1.000 m²",
      "2.500 m²",
      "5.000 m²",
      "10.000 m²",
    ],
    answer: 2,
    explain: "Satu unit RTH minimal ≥ 2.500 m². Jebakan angka: 2.000 (skala RDTR) atau 2.000 km² pulau.",
    version: 2
  },
  {
    id: 56,
    cluster: "spasial",
    level: "sedang",
    stem: "Pulau kecil menurut Perpres 51/2016 didefinisikan memiliki luas …",
    options: [
      "≤ 500 km²",
      "≤ 2.000 km²",
      "≤ 5.000 km²",
      "≤ 10.000 km²",
      "≤ 100 km²",
    ],
    answer: 1,
    explain: "Pulau kecil ≤ 2.000 km². Jangan tertukar dengan 2.500 m² RTH.",
    version: 2
  },
  {
    id: 57,
    cluster: "spasial",
    level: "panjang",
    stem: "Perencana A menyarankan setiap kabupaten wajib 30% kawasan lindung nasional seragam karena UU 26/2007. Perencana B menegaskan 30% adalah target RTH kota (20 publik + 10 privat). Perencana C meminta KKPR untuk usaha di zona yang belum ada RDTR. Manakah kombinasi pernyataan yang benar?",
    options: [
      "A benar; B dan C salah",
      "B dan C benar; A salah tentang % lindung nasional tunggal",
      "Semua benar",
      "Hanya A benar",
      "B salah karena RTH 30% adalah lindung hutan nasional",
    ],
    answer: 1,
    explain: "UU 26 tidak % lindung tunggal NKRI; 30% = RTH kota. Belum RDTR → KKPR.",
    version: 2
  },
  {
    id: 58,
    cluster: "spasial",
    level: "panjang",
    stem: "Data rencana: RTRWP skala 1:250.000; RTRWK 1:100.000; RDTR 1:3.000; Rencana Teknik tapak 1:1.000. Pemilik lahan ingin detail tapak bangunan per blok. Dokumen dan skala yang tepat adalah …",
    options: [
      "RDTR 1:250.000",
      "RTRWP untuk tapak bangunan",
      "Rencana Teknik (RTR) skala 1:1.000",
      "RPJPN 20 tahun",
      "KKPR mengganti semua peta",
    ],
    answer: 2,
    explain: "RDTR = zonasi (1:2.000–5.000); RTR/Rencana Teknik = tapak per blok (1:1.000).",
    version: 2
  },
  {
    id: 59,
    cluster: "spasial",
    level: "panjang",
    stem: "Kecuali pasangan angka–ketentuan yang benar, manakah yang SALAH (jebakan angka)?",
    options: [
      "Sempadan pantai — 100 m",
      "RTH total kota — 30%",
      "ROW jalan bebas hambatan — 30 m",
      "Sempadan sungai kecil — 100 m kiri-kanan",
      "RTH publik — 20%",
    ],
    answer: 3,
    explain: "Sungai kecil = 50 m (bukan 100 m). 100 m untuk sungai besar atau sempadan pantai.",
    version: 2
  },
  {
    id: 60,
    cluster: "spasial",
    level: "panjang",
    stem: "Kota Y berencana menambah mal besar di tepi sungai kecil dengan jarak bangunan 30 m dari bibir sungai, tanpa RDTR, hanya izin bangunan. Kepadatan rencana 55 rumah/ha di zona perumahan sedang, dan RTH baru 15% total. Pelanggaran/ketidaksesuaian utama adalah …",
    options: [
      "Semua sudah sesuai",
      "Sempadan sungai kecil kurang (min 50 m), KKPR diperlukan tanpa RDTR, kepadatan melebihi sedang (10–40), RTH di bawah 30%",
      "Hanya KKPR yang salah",
      "Hanya Phillips curve",
      "UU 26 mengharuskan 30% lindung nasional tunggal",
    ],
    answer: 1,
    explain: "Multi-pelanggaran: sempadan 50 m, KKPR wajib, kepadatan sedang max 40, RTH kota 30%.",
    version: 2
  }
];
